### ISSUE TITLE
Make width and height pull-downs editable

### ISSUE THREAD

**Issue by iegoshin** [easydiffusion/easydiffusion#1014]
**Is your feature request related to a problem? Please describe.**
It's almost impossible to keep h/w ratio of original image and have resolution close to the max. 

I tried using the plugin:
[More resolutions](https://raw.githubusercontent.com/superskirv/stable-diffusion-ui-plugins/main/Ski-SDUI-MoreRes.plugin.js) by [Super.Skirv](https://github.com/superskirv) and [JeLuF](https://github.com/JeLuF)

but then it doesn't remember previously used resolution on browser startup.

**Describe the solution you'd like**
Would be nice:
a) Override height and/or width in the UI / remember it for the next start
b) In the settings define your own list of resolutions

**Comment by JeLuF** [comment]
This feature has been implemented in EasyDiffusion 3.0, released today.
