### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement stable-diffusion-sdkit==2.1.3 (from sdkit) (from versions: 2.1.0, 2.1.1)

### ISSUE THREAD

**Issue by rogerhanzhao** [easydiffusion/easydiffusion#1021]
run the ./start.sh

has following :

Collecting picklescan
  Using cached https://mirrors.aliyun.com/pypi/packages/17/d5/2221d104d3510961eba4bdbaa57c97ee182ca3bdb32c9ffbf45b58e0c67d/picklescan-0.0.8-py3-none-any.whl (10 kB)
Collecting safetensors
  Using cached https://mirrors.aliyun.com/pypi/packages/4c/82/72effc1f427d511740904f4919a1d69cdcb9b7920ae79dfa2e5f23621f72/safetensors-0.3.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.2 MB)
ERROR: Could not find a version that satisfies the requirement stable-diffusion-sdkit==2.1.3 (from sdkit) (from versions: 2.1.0, 2.1.1)
ERROR: No matching distribution found for stable-diffusion-sdkit==2.1.3
![ddd](https://user-images.githubusercontent.com/23209751/225542864-da546b23-bd3e-40e8-ad3a-829ab5bd4265.jpg)

**Comment by Xsakura1314** [comment]
Perhaps you can change your pip download source. The sdkit package was updated yesterday, your previous download source was not updated in time. 

To open the pip configuration file in the user's home directory.

* For Windows users, the default path is `C:\Users\Username\pip\pip.ini`; 
* For Linux or macOS users, the default path is `~/.pip/pip.conf`. 

If this file does not exist, you can create it manually.

Add the following content to the pip configuration file and replace the source address with the download source address you want to use:
```
[global]
index-url = XXX
```

**Comment by rogerhanzhao** [comment]
thanks i will check.

**Comment by cnscud** [comment]
for the sync issue, update your pip.conf , it will fallback to official source

[global]
index-url = https://mirrors.aliyun.com/pypi/simple/

trusted-host = mirrors.aliyun.com
	       pypi.tuna.tsinghua.edu.cn
               pypi.org

extra-index-url= https://pypi.org/simple

**Comment by JeLuF** [comment]
closed due to inactivity
