### ISSUE TITLE
Browser tab not opening when starting.

### ISSUE THREAD

**Issue by Starconjure** [easydiffusion/easydiffusion#1026]
**Describe the bug**
Stalling in processes when trying to run.
Not sure what is stopping.

**To Reproduce**
1. Start terminal in easy-diffusion folder
2. ./start.sh (even tried sudo)
3. Wait for script do its magic
4. Stalls at end of uploaded txt file. 

**Expected behavior**
Browser tab opening with running program

**Desktop (please complete the following information):**
 - OS: Pop!_OS 22.04
 - Browser: Firefox
 - Version: Easy Diffusion 2.5

[startshrunbuildstall.txt](https://github.com/cmdr2/stable-diffusion-ui/files/11006923/startshrunbuildstall.txt)

**Comment by JeLuF** [comment]
You ran the installation under `sudo` permissions. First of all, **don't do that**. Running EasyDiffusion as root is **not recommended**.
While running as root, the installer can no longer talk to your desktop and therefor it can't start the browser.

**Comment by Starconjure** [comment]
Deleted the directory and files and re-extracted from zip.
Ran without using sudo in txt
Similar result. Not sure what differences are at the moment in error reports.

Perhaps this qt.qpa.plugin "xcb" not being able to load despite it being found?

[startshrunbuildstallnosudo.txt](https://github.com/cmdr2/stable-diffusion-ui/files/11012868/startshrunbuildstallnosudo.txt)

**Comment by JeLuF** [comment]
In a discord chat, a solution for this was found. You can use this command to start EasyDiffusion:
```
QT_QPA_PLATFORM=offscreen ./start.sh
```

**Comment by JeLuF** [comment]
closed due to inactivity
