### ISSUE TITLE
When using a list of prompts, Random doesn't change the seed for each line in the list.

### ISSUE THREAD

**Issue by chuckheron** [easydiffusion/easydiffusion#1039]
Hi,

**Describe the bug**
If I give a list of prompts on multiple lines. the Random switch doesn't give a random seed for each different prompt.
It uses the same prompt specified in the Seed field to start each prompt.

**To Reproduce**
1. Provide a multi-line list of prompts
2. Click on 'Random' to enable it.
3. Click on Make XX images.
4. Each prompt uses the same seed.

**Expected behavior**
I would expect the Random setting to give a random seed for each prompt in the list.
If it is turned off, then I would expect it to start each prompt with the same seed.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Chrome
 - Version: Easy Diffusion v2.5.26

Thanks for your great UI!  
It's the best and easiest I've found!

Thanks
-chuck

**Comment by w0nk0** [comment]
Same issue here, v2.5.36. 

The seed counts down 1 per in-batch image generated, but then is restored to the initial value on the next prompt.

**Comment by JeLuF** [comment]
No update within 4 weeks => closed for inactivity
