### ISSUE TITLE
Control Net support.

### ISSUE THREAD

**Issue by Wordjoy** [easydiffusion/easydiffusion#1040]
Control Net seems to be adding a lot of power to control and managed the design of the output.   
A better Img2Img? 

https://github.com/lllyasviel/ControlNet

https://aituts.com/controlnet/

**Comment by zolrath** [comment]
Would love ControlNet support, its pretty central for a ton of workflows!

**Comment by JeLuF** [comment]
Control Net is on the todo list for the new Diffusers based release

**Comment by JeLuF** [comment]
ControlNet support has been introduced with version 3.0 of EasyDiffusion, released today.

**Comment by YabbaYabbaYabba** [comment]
Getting this error: Error: Sorry, you're trying to use a SD 1 controlnet model with a SDXL Stable Diffusion model. They're not compatible, please use a compatible model!

Will there be support for SDXL in near future?
