### ISSUE TITLE
Ctrl-Z Undo during drawing will undo previous update on prompt as well

### ISSUE THREAD

**Issue by dpalix74** [easydiffusion/easydiffusion#1057]
Ctrl-Z Undo during drawing will undo the latest change on the prompt

**To Reproduce**
Modify the Prompt
Choose Draw (to modify the initial Image)
Do some change in the picture
Undo your change through ctrl-Z
This will undo the change in the picture but at the same time undo the previous prompt change 
_(may affect other fields as well... will in fact undo any change done before entering the drawing mode)_

Desktop (please complete the following information):
OS: Windows
Browser: Chrome
Version: 2.5.x

**Comment by JeLuF** [comment]
We fixed this a while ago. I checked and wasn't able to reproduce the issue in version 3.0 => closing ticket
