### ISSUE TITLE
Can't start the web ui

### ISSUE THREAD

**Issue by kaxuei** [easydiffusion/easydiffusion#1064]
I cant start the web ui it just says 
'eloper' is not recognized as an internal or external command,
operable program or batch file.
The system cannot find the path specified. 
and
'r' is not recognized as an internal or external command,
operable program or batch file.
The system cannot find the path specified.

**Comment by cmdr2** [comment]
Please try the latest version, if you're still interested: https://github.com/easydiffusion/easydiffusion/releases/tag/v3.0.2
