### ISSUE TITLE
model.safetensors.index.json not found

### ISSUE THREAD

**Issue by camelweiming** [easydiffusion/easydiffusion#1071]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser:
 - Version:

**Smartphone (please complete the following information):**
 - Device: 
 - OS: win11
 - Browser chrome
 - Version 2.5

**Additional context**

DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
'HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /openai/clip-vit-large-patch14/resolve/main/model.safetensors.index.json (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))' thrown while requesting HEAD https://huggingface.co/openai/clip-vit-large-patch14/resolve/main/model.safetensors.index.json
16:39:15.619 WARNING cuda:0 'HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded     _http.py:145
with url: /openai/clip-vit-large-patch14/resolve/main/model.safetensors.index.json (Caused by
ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))' thrown while requesting HEAD
https://huggingface.co/openai/clip-vit-large-patch14/resolve/main/model.safetensors.index.json
16:39:15.622 ERROR cuda:0 Error while loading stable-diffusion model:                                model_manager.py:45
D:\diffusion\models\stable-diffusion\sd-v1-4.ckpt
16:39:15.624 ERROR cuda:0 Error: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries   model_manager.py:46
exceeded with url: /openai/clip-vit-large-patch14/resolve/main/model.safetensors.index.json (Caused
by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))
16:39:15.626 ERROR cuda:0 Consider removing the model from the model folder.                         model_manager.py:47
16:39:15.999 INFO cuda:0 Session 1679906319176 starting task 2009298434944 on NVIDIA GeForce GTX     task_manager.py:312
1660 SUPER
16:39:16.002 INFO cuda:0 loading gfpgan model from D:\diffusion\models\gfpgan\GFPGANv1.3.pth to device:   __init__.py:23
cuda:0
D:\diffusion\installer_files\env\lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
D:\diffusion\installer_files\env\lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=None`.
  warnings.warn(msg)
16:39:24.489 INFO cuda:0 loaded gfpgan model from D:\diffusion\models\gfpgan\GFPGANv1.3.pth to device:    __init__.py:27
cuda:0
16:39:24.512 INFO cuda:0 request: {'guidance_scale': 7.5,                                                 renderer.py:51
 'height': 512,
 'hypernetwork_strength': 0,
 'negative_prompt': 'Deformed, blurry, bad anatomy, disfigured, poorly drawn '
                    'face, mutation, mutated, extra limb, ugly, poorly drawn '
                    'hands, missing limb, blurry, floating limbs, disconnected '
                    'limbs, malformed hands, blur, out of focus, long neck, '
                    'long body, ((((mutated hands and fingers)))), (((out of '
                    'frame)))',
 'num_inference_steps': 25,
 'num_outputs': 1,
 'preserve_init_image_color_profile': False,
 'prompt': 'a photograph of an astronaut riding a horse',
 'sampler_name': 'dpmpp_sde',
 'seed': 3521597,
 'width': 512}
16:39:24.516 INFO cuda:0 task data: {'block_nsfw': False,                                                 renderer.py:52
 'metadata_output_format': 'none',
 'output_format': 'jpeg',
 'output_quality': 75,
 'request_id': 2009298434944,
 'save_to_disk_path': None,
 'session_id': '1679906319176',
 'show_only_filtered_image': True,
 'stream_image_progress': False,
 'stream_image_progress_interval': 5,
 'upscale_amount': 4,
 'use_face_correction': 'D:\\diffusion\\models\\gfpgan\\GFPGANv1.3.pth',
 'use_hypernetwork_model': None,
 'use_stable_diffusion_model': 'D:\\diffusion\\models\\stable-diffusion\\sd-v1-4.ckpt',
 'use_upscale': None,
 'use_vae_model': None,
 'vram_usage_level': 'balanced'}
16:39:24.520 INFO cuda:0 Global seed set to 3521597                                                           seed.py:65
16:39:24.632 ERROR cuda:0 Traceback (most recent call last):                                         task_manager.py:346
  File "D:\diffusion\ui\easydiffusion\task_manager.py", line 336, in thread_render
    task.response = renderer.make_images(
  File "D:\diffusion\ui\easydiffusion\renderer.py", line 38, in make_images
    images, seeds = make_images_internal(req, task_data, data_queue, task_temp_images,
step_callback)
  File "D:\diffusion\ui\easydiffusion\renderer.py", line 59, in make_images_internal
    images, user_stopped = generate_images_internal(
  File "D:\diffusion\ui\easydiffusion\renderer.py", line 91, in generate_images_internal
    images = generate_images(context, callback=callback, **req.dict())
  File "D:\diffusion\installer_files\env\lib\site-packages\sdkit\generate\image_generator.py", line
50, in generate_images
    raise RuntimeError(
RuntimeError: The model for Stable Diffusion has not been loaded yet! If you've tried to load it,
please check the logs above this message for errors (while loading the model).

16:39:24.750 INFO cuda:0 Session 1679906319176 task 2009298434944 failed!

**Comment by JeLuF** [comment]
closed due to inactivity
