### ISSUE TITLE
is this portable? where is the win version of zip pack, installer might not be portable.

### ISSUE THREAD

**Issue by bryanray** [easydiffusion/easydiffusion#1072]
is this portable? where is the win version of zip pack, installer might not be portable.

**Comment by JeLuF** [comment]
The installed folder is portable. The installer doesn't need admin privileges. It's not following the definitions of portable applications, but practically, you can handle the program like a portable program.

**Comment by JeLuF** [comment]
The space character problem was caused by micromamba, a tool that we used to install python. It also had problems with non-ASCII characters like á, ä, Æ, α. We finally got rid of it and will lift the ban of space characters in one of the next minor releases, after some more testing.

**Comment by JeLuF** [comment]
closed due to inactivity
