### ISSUE TITLE
ERROR cuda:0 Error: Unable to load weights from pytorch checkpoint file

### ISSUE THREAD

**Issue by micka9fr** [easydiffusion/easydiffusion#1073]
Hi I have another bug
The API easy diffusion is running now, but then I try to make a rendering of a image it crash. I have this log below. Have you an idea where I m wrong please ?

Install dir: E:\EasyDiffusion\
C:\Program Files\Git\cmd\git.exe
git version 2.40.0.windows.1
E:\EasyDiffusion\installer_files\env\Library\bin\conda.bat
E:\EasyDiffusion\installer_files\env\Scripts\conda.exe
conda 22.11.1

"Easy Diffusion - v2"

"Easy Diffusion's git repository was already installed. Updating from main.."
HEAD is now at 696bb88 Merge pull request #1050 from m-hosoi/main
Already on 'main'
Your branch is up to date with 'origin/main'.
Already up to date.
497 fichier(s) copié(s)
        1 fichier(s) copié(s).
        1 fichier(s) copié(s).
        1 fichier(s) copié(s).
        1 fichier(s) copié(s).
        1 fichier(s) copié(s).
        1 fichier(s) copié(s).
        1 fichier(s) copié(s).
Un sous-répertoire ou un fichier tmp existe déjà.

Hotfixed broken JSON file from OpenAI
"torch and torchvision have already been installed."
"sdkit is already installed."
sdkit version: 1.0.48
stable-diffusion version: 2.1.4
"rich has already been installed."
"Packages necessary for Easy Diffusion were already installed"
"Data files (weights) necessary for Stable Diffusion were already downloaded. Using the HuggingFace 4 GB Model."
"Data files (weights) necessary for GFPGAN (Face Correction) were already downloaded"
"Data files (weights) necessary for ESRGAN (Resolution Upscaling) x4plus were already downloaded"
"Data files (weights) necessary for ESRGAN (Resolution Upscaling) x4plus_anime were already downloaded"
"Data files (weights) necessary for the default VAE (sd-vae-ft-mse-original) were already downloaded"

"Easy Diffusion installation complete! Starting the server!"

PYTHONPATH=E:\EasyDiffusion\installer_files\env\lib\site-packages
E:\EasyDiffusion\installer_files\env\python.exe
C:\Users\Meka\AppData\Local\Programs\Python\Python310\python.exe
C:\Users\Meka\AppData\Local\Programs\Python\Python37\python.exe
C:\Users\Meka\AppData\Local\Microsoft\WindowsApps\python.exe
Python 3.8.5
No module 'xformers'. Proceeding without it.
18:58:20.659 INFO MainThread started in E:\EasyDiffusion\stable-diffusion                                   server.py:21
18:58:20.664 INFO MainThread started at 03/27/23 18:58:20                                                   server.py:22
18:58:20.812 INFO MainThread Scanned 4 models. Nothing infected                                     model_manager.py:248
18:58:20.879 INFO MainThread Start new Rendering Thread on device: cuda:0                            task_manager.py:457
18:58:21.288 INFO cuda:0 Setting cuda:0 as active, with precision: half                            device_manager.py:151
18:58:21.290 INFO cuda:0 loading stable-diffusion model from                                              __init__.py:23
E:\EasyDiffusion\models\stable-diffusion\sd-v1-4.ckpt to device: cuda:0
18:58:22.554 INFO cuda:0 using config:                                                                    __init__.py:57
E:\EasyDiffusion\installer_files\env\lib\site-packages\sdkit\models\models_db\configs\v1-inference.yaml
18:58:22.573 INFO cuda:0 using attn_precision: fp16                                                       __init__.py:63
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
18:59:17.518 ERROR cuda:0 Error while loading stable-diffusion model:                                model_manager.py:45
E:\EasyDiffusion\models\stable-diffusion\sd-v1-4.ckpt
18:59:17.520 ERROR cuda:0 Error: Unable to load weights from pytorch checkpoint file for             model_manager.py:46
'E:\EasyDiffusion\profile/.cache\huggingface\hub\models--openai--clip-vit-large-patch14\snapshots\8d
052a0f05efbaefbc9e8786ba291cfdf93e5bff\pytorch_model.bin' at
'E:\EasyDiffusion\profile/.cache\huggingface\hub\models--openai--clip-vit-large-patch14\snapshots\8d
052a0f05efbaefbc9e8786ba291cfdf93e5bff\pytorch_model.bin'. If you tried to load a PyTorch model from
a TF 2.0 checkpoint, please set from_tf=True.
18:59:17.523 ERROR cuda:0 Consider removing the model from the model folder.                         model_manager.py:47
18:59:59.185 INFO cuda:0 Session 1679936302939 starting task 2245901758864 on NVIDIA GeForce RTX     task_manager.py:312
3080
18:59:59.189 INFO cuda:0 request: {'guidance_scale': 7.5,                                                 renderer.py:51
 'height': 512,
 'hypernetwork_strength': 0,
 'negative_prompt': '',
 'num_inference_steps': 25,
 'num_outputs': 1,
 'preserve_init_image_color_profile': False,
 'prompt': 'girl on the beach',
 'prompt_strength': 0.8,
 'sampler_name': 'ddim',
 'seed': 7277140,
 'width': 512}
18:59:59.502 INFO cuda:0 task data: {'block_nsfw': False,                                                 renderer.py:52
 'metadata_output_format': 'none',
 'output_format': 'jpeg',
 'output_quality': 75,
 'request_id': 2245901758864,
 'save_to_disk_path': None,
 'session_id': '1679936302939',
 'show_only_filtered_image': True,
 'stream_image_progress': False,
 'stream_image_progress_interval': 5,
 'upscale_amount': 4,
 'use_face_correction': None,
 'use_hypernetwork_model': None,
 'use_stable_diffusion_model': 'E:\\EasyDiffusion\\models\\stable-diffusion\\sd-v1-4.ckpt',
 'use_upscale': None,
 'use_vae_model': None,
 'vram_usage_level': 'balanced'}
18:59:59.508 INFO cuda:0 Global seed set to 7277140                                                           seed.py:65
18:59:59.514 ERROR cuda:0 Traceback (most recent call last):                                         task_manager.py:346
  File "E:\EasyDiffusion\ui\easydiffusion\task_manager.py", line 336, in thread_render
    task.response = renderer.make_images(
  File "E:\EasyDiffusion\ui\easydiffusion\renderer.py", line 38, in make_images
    images, seeds = make_images_internal(req, task_data, data_queue, task_temp_images,
step_callback)
  File "E:\EasyDiffusion\ui\easydiffusion\renderer.py", line 59, in make_images_internal
    images, user_stopped = generate_images_internal(
  File "E:\EasyDiffusion\ui\easydiffusion\renderer.py", line 91, in generate_images_internal
    images = generate_images(context, callback=callback, **req.dict())
  File "E:\EasyDiffusion\installer_files\env\lib\site-packages\sdkit\generate\image_generator.py",
line 50, in generate_images
    raise RuntimeError(
RuntimeError: The model for Stable Diffusion has not been loaded yet! If you've tried to load it,
please check the logs above this message for errors (while loading the model).

18:59:59.611 INFO cuda:0 Session 1679936302939 task 2245901758864 failed!

**Comment by JeLuF** [comment]
> 18:59:17.520 ERROR cuda:0 Error: Unable to load weights from pytorch checkpoint file for 
> 'E:\EasyDiffusion\profile/.cache\huggingface\hub\models--openai--clip-vit-large-patch14\snapshots\8d052a0f05efbaefbc9e8786ba291cfdf93e5bff\pytorch_model.bin' at
> 'E:\EasyDiffusion\profile/.cache\huggingface\hub\models--openai--clip-vit-large-patch14\snapshots\8d052a0f05efbaefbc9e8786ba291cfdf93e5bff\pytorch_model.bin'. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.

This error is usually being caused by a truncated `pytorch_model.bin` file. Please delete the file `E:\EasyDiffusion\profile\.cache\huggingface\hub\models--openai--clip-vit-large-patch14\snapshots\8d052a0f05efbaefbc9e8786ba291cfdf93e5bff\pytorch_model.bin` and restart EasyDiffusion. It will download a fresh copy of this file.

**Comment by JeLuF** [comment]
closed due to inactivity
