### ISSUE TITLE
The model file present at models/stable-diffusion/sd-v1-4.ckpt is invalid. It is only 0 bytes in size. Re-downloading..Downloading data files (weights) for Stable Diffusion..

### ISSUE THREAD

**Issue by sammo1965** [easydiffusion/easydiffusion#1083]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser:
 - Version:

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

**Comment by cmdr2** [comment]
Please re-run the installer like it suggests. Are you behind a proxy/VPN? Can you please check your firewall?

Which OS are you using?

**Comment by protrading104** [comment]
the same problem
windows 10
without VPN
any ideas ?

![image](https://user-images.githubusercontent.com/71656833/230723312-afa7bdc8-9817-44f2-87e3-1140fac9cecd.png)

**Comment by chinian** [comment]
![image](https://github.com/easydiffusion/easydiffusion/assets/142168434/a89a23da-5d3b-41f8-87d7-6592e5a7d3c1)
![image](https://github.com/easydiffusion/easydiffusion/assets/142168434/9c6a0084-f326-43b2-b077-bcd3ac1a4719)

**Comment by chinian** [comment]
好像是同样的问题

**Comment by chinian** [comment]
用的W10

**Comment by chinian** [comment]
防火墙需要关闭吗

**Comment by chinian** [comment]
没有VPN

**Comment by cmdr2** [comment]
Please check your VPN/Proxy settings, or download it manually from https://github.com/easydiffusion/sdkit-test-data/releases/download/assets/sd-v1-5.safetensors and put it in the `models/stable-diffusion` folder.
