### ISSUE TITLE
getting this error when using the LORA/Diffuser Opt in Feature

### ISSUE THREAD

**Issue by ollobrains** [easydiffusion/easydiffusion#1089]
This error doesnt generate when not opted in to the LORA-Diffuser feature

Using the same model when in normal beta mode is fine

Opt in to LORA and restart - goto generate with none selected in LORA-DIffuser box and get this error 

"Error: list index out of range"

**Comment by JeLuF** [comment]
Please provide the full log of the console window. If you're using Windows 10, you can collect this log like this:
![image](https://user-images.githubusercontent.com/5852422/228753019-f14a2cb6-0fc8-4b4b-a9e5-d4ed212fbabb.png)
Please save the log to a text file and attach it to this ticket.

**Comment by ollobrains** [comment]
Ok attaching the log for when trying to generate an image when working in LORA opt in mode 

[1.txt](https://github.com/cmdr2/stable-diffusion-ui/files/11128991/1.txt)

**Comment by cmdr2** [comment]
This has been fixed in the latest version: https://github.com/easydiffusion/easydiffusion/releases/tag/v3.0.2

Please feel free to reopen if this is still relevant and continues to be a problem. Thanks
