### ISSUE TITLE
Merging a LORA file into a model file gives this error

### ISSUE THREAD

**Issue by ollobrains** [easydiffusion/easydiffusion#1090]
trying to merge a LORA file into a main model safetensor file generates this error ***beta option enabled 2.5.30, LORA feature opted out***

{"detail":"The size of tensor a (32) must match the size of tensor b (64) at non-singleton dimension 0"}

**Comment by JeLuF** [comment]
Please provide the full log of the console window. If you're using Windows 10, you can collect this log like this:
![image](https://user-images.githubusercontent.com/5852422/228753019-f14a2cb6-0fc8-4b4b-a9e5-d4ed212fbabb.png)
Please save the log to a text file and attach it to this ticket.

**Comment by ollobrains** [comment]
posting it has the same txt file name as the last one but i did a different thing with the lora merge and then after thta tried to run an image generation and still getting error out of range message 
[1.txt](https://github.com/cmdr2/stable-diffusion-ui/files/11129001/1.txt)
Hope this helps

**Comment by ollobrains** [comment]
actually a slight tweak, the combined LORA = Main merge actually works, i went to opt out of LORA and it run soff fine, it was within the LORA Opt in beta version that it was still not generating an image, so i think ill test further that LORA models being merged into a main safetensor model actually does work if it doesnt ill file another error log

**Comment by ollobrains** [comment]
there is another case, i have a larger model at 14.9gb, i am attempting to merge a LORA into the larger and not smaller file and im getting this error (it merged into a smaller model but not the bigger one) something about a 16fp not going into a 32fp and the tensor a 32 not going into tensor b 64 heres the error log

[1.txt](https://github.com/cmdr2/stable-diffusion-ui/files/11129086/1.txt)

**Comment by ollobrains** [comment]
expected behaviour would be that any lora file regardless of size would be able to be merged into any main stable diffusion file regardless of size and regardless of fp size (as i merge fp16 and fp32 models togheter at the main safetensor size now)

**Comment by ollobrains** [comment]
the pull request has been closed, so anyone from reddit, or civitai who is frustrated by the lack of response to this please politley dont private message me on reddit, please leave a polite request to any developers here to work on this, i know there is a big community request for this and im starting to think it cant actually be programmed into any stable diffusion models, but im just the messager not the dev so i will leave it to others to respond and work on

**Comment by ollobrains** [comment]
Install dir: C:\stable-diffusion-ui\stable-diffusion-ui\
C:\stable-diffusion-ui\stable-diffusion-ui\installer\Library\bin\git.exe
git version 2.34.1.windows.1
C:\stable-diffusion-ui\stable-diffusion-ui\installer\Library\bin\conda.bat
C:\stable-diffusion-ui\stable-diffusion-ui\installer\Scripts\conda.exe
conda 4.14.0

"Easy Diffusion - v2"

"Easy Diffusion's git repository was already installed. Updating from beta.."
HEAD is now at 69380e3 sdkit 1.0.63 - bug fix - samplers wouldn't get created if an inpainting was the first to load
Already on 'beta'
Your branch is up to date with 'origin/beta'.
Already up to date.
499 File(s) copied
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
A subdirectory or file tmp already exists.

Hotfixed broken JSON file from OpenAI
"torch and torchvision have already been installed."
"sdkit is already installed."
sdkit version: 1.0.63
stable-diffusion version: 2.1.4
"rich has already been installed."
"Packages necessary for Easy Diffusion were already installed"
"Data files (weights) necessary for Stable Diffusion were already downloaded. Using the HuggingFace 4 GB Model."
"Data files (weights) necessary for GFPGAN (Face Correction) were already downloaded"
"Data files (weights) necessary for ESRGAN (Resolution Upscaling) x4plus were already downloaded"
"Data files (weights) necessary for ESRGAN (Resolution Upscaling) x4plus_anime were already downloaded"
"Data files (weights) necessary for the default VAE (sd-vae-ft-mse-original) were already downloaded"

"Easy Diffusion installation complete! Starting the server!"

PYTHONPATH=C:\stable-diffusion-ui\stable-diffusion-ui\stable-diffusion\env\lib\site-packages
C:\stable-diffusion-ui\stable-diffusion-ui\stable-diffusion\env\python.exe
C:\stable-diffusion-ui\stable-diffusion-ui\installer\python.exe
C:\Users\et_pj\AppData\Local\Programs\Python\Python311\python.exe
C:\Users\et_pj\AppData\Local\Microsoft\WindowsApps\python.exe
Python 3.8.5
No module 'xformers'. Proceeding without it.
12:32:15.024 INFO MainThread started in C:\stable-diffusion-ui\stable-diffusion-ui\stable-diffusion        server.py:21
12:32:15.030 INFO MainThread started at 04/04/23 12:32:15                                                  server.py:22
12:32:15.346 INFO MainThread Scanned 12 models. Nothing infected                                   model_manager.py:254
12:32:15.425 INFO MainThread Start new Rendering Thread on device: cuda:0                           task_manager.py:457
12:32:15.818 INFO cuda:0 Setting cuda:0 as active, with precision: half                           device_manager.py:151
12:32:15.821 INFO cuda:0 loading stable-diffusion model from                                             __init__.py:24
C:\stable-diffusion-ui\stable-diffusion-ui\models\stable-diffusion\MM20.safetensors to device: cuda:0
12:32:15.826 INFO cuda:0 loading on diffusers                                                           __init__.py:118
12:32:15.827 INFO cuda:0 using config:                                                                  __init__.py:120
C:\stable-diffusion-ui\stable-diffusion-ui\models\stable-diffusion\MM20.yaml
12:32:15.842 INFO cuda:0 using attn_precision: fp16                                                     __init__.py:126
global_step key not found in model
In this conversion only the non-EMA weights are extracted. If you want to instead extract the EMA weights (usually better for inference), please make sure to add the `--extract_ema` flag.
C:\stable-diffusion-ui\stable-diffusion-ui\stable-diffusion\env\lib\site-packages\transformers\models\clip\feature_extraction_clip.py:28: FutureWarning: The class CLIPFeatureExtractor is deprecated and will be removed in version 5 of Transformers. Please use CLIPImageProcessor instead.
  warnings.warn(
12:32:37.711 INFO cuda:0 Loaded on diffusers                                                            __init__.py:187
12:32:37.721 INFO cuda:0 loaded stable-diffusion model from                                              __init__.py:28
C:\stable-diffusion-ui\stable-diffusion-ui\models\stable-diffusion\MM20.safetensors to device: cuda:0
{'model0': 'joonYorigami_charJoon', 'model1': 'MM20', 'use_fp16': False, 'out_path': 'test-0.00500.safetensors', 'ratio': 0.005}
12:33:50.211 INFO AnyIO worker thread Merge models: Merging                                          merge_models.py:15
C:\stable-diffusion-ui\stable-diffusion-ui\models\stable-diffusion\joonYorigami_charJoon.safetensors
and C:\stable-diffusion-ui\stable-diffusion-ui\models\stable-diffusion\MM20.safetensors, ratio 0.005
12:33:50.786 ERROR AnyIO worker thread Traceback (most recent call last):                                 server.py:259
  File "C:\stable-diffusion-ui\stable-diffusion-ui\ui\easydiffusion\server.py", line 250, in
model_merge_internal
    merge_models(
  File
"C:\stable-diffusion-ui\stable-diffusion-ui\stable-diffusion\env\lib\site-packages\sdkit\train\merge_mode
ls.py", line 16, in merge_models
    merged = merge_two_models(model0_path, model1_path, ratio, use_fp16)
  File
"C:\stable-diffusion-ui\stable-diffusion-ui\stable-diffusion\env\lib\site-packages\sdkit\train\merge_mode
ls.py", line 51, in merge_two_models
    model0 = (1 - alpha) * model0 + alpha * model1
RuntimeError: The size of tensor a (48) must match the size of tensor b (64) at non-singleton dimension 0


Ok the above is the latest bug report from the latest beta + LORA turned on when attempting to merge LORA into mainstream model (both safe tensors)

**Comment by JeLuF** [comment]
Merging of LORA and checkpoint files is not supported, and there are currently no plans to add this support.
