### ISSUE TITLE
black images when using some models

### ISSUE THREAD

**Issue by panema19** [easydiffusion/easydiffusion#1092]
Images are fully black when using models such as chikmix_V2, chikmix_V1. Models such as chilloutmix_NiPrunedFp32Fix or deliberate_v2 work well.

<html>
<body>
<h3 style="font-family: &quot;Work Sans&quot;, Verdana, Geneva, sans-serif; box-sizing: border-box; transition: background 0.5s ease 0s, color 0.5s ease 0s, background-color 0.5s ease 0s; color: rgb(238, 238, 238); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: center; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(32, 33, 34); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><i class="fa fa-microchip icon" style="font-family: var(--fa-style-family,&quot;Font Awesome 6 Free&quot;); box-sizing: border-box; transition: background 0.5s ease 0s, color 0.5s ease 0s, background-color 0.5s ease 0s; font-weight: var(--fa-style,900); -webkit-font-smoothing: antialiased; display: var(--fa-display,inline-block); font-style: normal; font-variant: normal; line-height: 1; text-rendering: auto;"></i><span> </span>System Info</h3><div id="system-info" style="font-family: &quot;Work Sans&quot;, Verdana, Geneva, sans-serif; box-sizing: border-box; transition: background 0.5s ease 0s, color 0.5s ease 0s, background-color 0.5s ease 0s; max-width: 800px; font-size: 10pt; color: rgb(238, 238, 238); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: center; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(32, 33, 34); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

Processor: | Intel64 Family 6 Model 165 Stepping 2, GenuineIntel
-- | --
Compatible Graphics Cards (all): | NVIDIA GeForce GTX 1650 Ti (cuda:0) (2.2Gb free / 4.3 Gb total)
  |  
Used for rendering 🔥: | NVIDIA GeForce GTX 1650 Ti (cuda:0) (2.2Gb free / 4.3 Gb total)

</div>
</body>
</html>

**Screenshots**
![image](https://user-images.githubusercontent.com/129353471/228720375-b124f972-3da3-4cb2-8bd7-185a3a5f695f.png)
![image](https://user-images.githubusercontent.com/129353471/228720739-f4aa677c-b634-4677-a221-1868deaf3625.png)

**Comment by JeLuF** [comment]
Automatic black image prevention has been recently added. Can you please test whether these models work for you now?

**Comment by JeLuF** [comment]
closed due to inactivity
