### ISSUE TITLE
ERROR: torch install failed

### ISSUE THREAD

**Issue by ulist** [easydiffusion/easydiffusion#1093]
![Screenshot_٢٠٢٣٠٣٣٠-١٨٣٢٠٠_Termux](https://user-images.githubusercontent.com/39057208/228887916-d54c89fa-8e13-46a6-aad4-53304ed83150.png)

Is this version od torch not available for aarch64?
```
ERROR: Could not find a version that satisfies the requirement torch==1.13.1+cu116 (from versions: 1.8.0, 1.8.1, 1.9.0, 1.10.0, 1.10.1, 1.10.2, 1.11.0, 1.12.0, 1.12.1, 1.13.0, 1.13.1, 2.0.0)
ERROR: No matching distribution found for torch==1.13.1+cu116
```

**Comment by JeLuF** [comment]
No, I think aarch64 is currently not supported by CUDA-Torch. Do you have an Nvidia GPU in that system?

Please do not install Easy Diffusion as root. It's not designed to be run as root.

**Comment by JeLuF** [comment]
If you're not using a GPU, you can use the standard torch libraries, torch==1.13.1

**Comment by JeLuF** [comment]
closed due to inactivity
