### ISSUE TITLE
M1 is too slow to generate images, which takes 2-3 minutes

### ISSUE THREAD

**Issue by honstat** [easydiffusion/easydiffusion#1096]
Macbookpro M1 16G is too slow to generate images for 2-3 minutes, which is unbearable. Is there any setting that can be made faster
<img width="719" alt="image" src="https://user-images.githubusercontent.com/13939052/229014495-755c3244-1401-421d-897c-681e5c684c33.png">

**Comment by JeLuF** [comment]
In the `Settings` tab, in the `System Info` section, what does it say in the `Used for rendering` section?

**Comment by madatr** [comment]
I'm on M1 Pro, 16 GB ram. takes around 5 minutes for 512x512, what am I doing wrong?

<img width="685" alt="Screenshot 2023-07-04 at 18 24 47" src="https://github.com/easydiffusion/easydiffusion/assets/45605051/5593d83d-bd8d-41b8-a087-7dc929376d24">

**Comment by JeLuF** [comment]
In the `Settings` tab, in the `System Info` section, what does it say in the `Used for rendering` section?
Did you try the "Balanced" memory profile as well? What are your image settings? Was this only for the first image generated, or also for consecutive images?

**Comment by JeLuF** [comment]
closed due to inactivity
