### ISSUE TITLE
uvicorn crashes when using different models

### ISSUE THREAD

**Issue by lutzseverino** [easydiffusion/easydiffusion#1100]
**Describe the bug**
When trying different stable-diffusion models such as `768-v-ema` or `v2-1_768-ema-pruned`, uvicorn takes up the whole memory storage and swap, then (most times) causes the computer to crash.

When the OS actually gets to kill the process, this is what I see.
```
18:39:20.426 INFO cuda:0 Loading ViT-H-14 model config.                    factory.py:89
/home/lutzseverino/Documents/Tools/easy-diffusion/scripts/on_sd_start.sh: line 321:  5519 Killed                  uvicorn main:server_api --app-dir "$SD_UI_PATH" --port ${SD_UI_BIND_PORT:-9000} --host ${SD_UI_BIND_IP:-0.0.0.0} --log-level error
Press any key to continue
```

This is rather unusual to me, the models are larger, yes, but one of them isn't even a gig larger than the default one.

**To Reproduce**
1. Download different (bigger?) models
2. Add them to the folder
3. Reload and generate image / restart software

**Expected behavior**
uvicron doesn't crash

**Screenshots**
My computer was unresponsive, so I had to take pictures with a camera, excuse me for that.
![image](https://user-images.githubusercontent.com/28309837/229201559-793de777-aee5-4602-a97c-a2e79e29a392.png)
![image](https://user-images.githubusercontent.com/28309837/229201699-5e6222e3-b4fc-4e18-8e90-b1c36ba4b1a0.png)

**Desktop (please complete the following information):**
 - OS: Fedora Linux Workstation 37 
 - Browser: Firefox
 - Version: 2.5.24 (stable)

**Additional context**
Related to #630, #759 and some other OOM issues with uvicorn at https://github.com/tiangolo/uvicorn-gunicorn-docker/issues/98, https://github.com/encode/uvicorn/issues/1583 and https://github.com/encode/uvicorn/issues/1226

The computer has 16gb or ram, 8gb more as swap.

**Comment by JeLuF** [comment]
Is the swap real swap, or just zram based swap? zram uses memory as swap space, but compresses the swapped out pages. The model data that EasyDiffusion is loading to the GPU isn't working well with zram.

**Comment by Regnsloja** [comment]
I get this problem (also on Linux) when trying to use this CC0 set: https://huggingface.co/Mitsua/mitsua-diffusion-one , which is more than a gb smaller then the default sd-v1-4 (which works without problem).
Granted, my hardware is pretty bad. Just weird that the bigger set works. Are the other sets doing something different?

**Comment by JeLuF** [comment]
@victoria-n-w What exactly is your problem? I don't see any errors in the log file provided.

**Comment by JeLuF** [comment]
closed due to inactivity
