### ISSUE TITLE
With LoRA enabled it's super slow

### ISSUE THREAD

**Issue by iegoshin** [easydiffusion/easydiffusion#1101]
**Describe the bug**
When you enable Test Diffusers, everything becomes very slow: either if you use LoRA or you don't. Like it waits 2-3 minutes before it starts to generate next image. Also max resolution will drop to something like 512x640.

**To Reproduce**
Enable Test Diffusers
Restart server
Try to generate something

**Expected behavior**
Keep max resoltion high, work without such a huge delay

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by JeLuF** [comment]
The "Test Diffusers" tech preview is in a very early development stage. No memory- or performance-tuning has been done yet.

**Comment by RenaKunisaki** [comment]
I've noticed it's much slower but also does seem to give better results, especially when turning one thing into another (eg a photo of a person -> a drawing of a character). But it's strange because I don't actually have any items listed (except None) in the LoRA dropdown.

**Comment by JeLuF** [comment]
@RenaKunisaki 
The img2img and inpainting code used in the tech preview is a different one than in the stable version, even when no LORA is being used.

**Comment by noodles1860** [comment]
is multi LoRA supported?

**Comment by cmdr2** [comment]
Yes, the latest version of Easy Diffusion supports that, and has a lot of VRAM and performance optimizations
