### ISSUE TITLE
Service crashes or produces unfinished pictures at large resolution

### ISSUE THREAD

**Issue by KaliPhobos** [easydiffusion/easydiffusion#1110]
If a large resolution has been selected, the service will crash as soon as image generatin is attempted.
If only a slightly too large setting is chosen, the image generation will stop after the first step.

**To Reproduce**
Steps to reproduce the full crash:
1. Set width to 1024
2. Set height to 1792
3. Click "Enqueue Next Image"

Steps to reproduce the broken image:
1. Set width to 768
2. Set height to 1024
3. Click "Enqueue Next Image"

**Desktop:**
 - Device: Apple Macbook Pro M1 Max
 - OS: MacOS Monterey 12.5.1
 - Browser Firefox 111.0.1
 - Version 2.5.26

If the resolution was slightly too large, the image generation finishes but produces an unfinished image. Everything appears normal, the image is even saved to the designatedd output folder.
![broken_image](https://user-images.githubusercontent.com/21200998/229344967-febb7c7e-14f4-46f1-b730-cb8b0c6a5a04.jpeg)

If the resolution was way too big, the following error message is being pasted:
```
/Users/ANON/Downloads/easy-diffusion/installer_files/env/lib/python3.8/site-packages/k_diffusion/external.py:82: UserWarning: The operator 'aten::frac.out' is not currently supported on the MPS backend and will fall back to run on the CPU. This may have performance implications. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/mps/MPSFallback.mm:11.)
  low_idx, high_idx, w = t.floor().long(), t.ceil().long(), t.frac()
                                                                                                                                             /AppleInternal/Library/BuildRoots/20d6c351-ee94-11ec-bcaf-7247572f23b4/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShaders/MPSCore/Types/MPSNDArray.mm:705: failed assertion `[MPSNDArray initWithDevice:descriptor:] Error: product of dimension sizes > 2**31'
/Users/ANON/Downloads/easy-diffusion/scripts/on_sd_start.sh: line 321: 56087 Abort trap: 6           uvicorn main:server_api --app-dir "$SD_UI_PATH" --port ${SD_UI_BIND_PORT:-9000} --host ${SD_UI_BIND_IP:-0.0.0.0} --log-level error
Press any key to continue/Users/ANON/Downloads/easy-diffusion/installer_files/env/lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

**Comment by KaliPhobos** [comment]
Resolution of 512*756 works perfectly fine on the device

**Comment by cmdr2** [comment]
Please try the latest version, since users are routinely creating images larger than the resolution you've mentioned. https://github.com/easydiffusion/easydiffusion/releases/tag/v3.0.2

Please feel free to reopen if this is still an issue.
