### ISSUE TITLE
cannot import name

### ISSUE THREAD

**Issue by borkolay** [easydiffusion/easydiffusion#1125]
**Des                                                                                                 │
│ E:\Easy-Diffusion\installer_files\env\lib\site-packages\diffusers\pipelines\dance_diffusion\pipe │
│ line_dance_diffusion.py:21 in <module>                                                           │
│                                                                                                  │
│    18 import torch                                                                               │
│    19                                                                                            │
│    20 from ...utils import logging, randn_tensor                                                 │
│ ❱  21 from ..pipeline_utils import AudioPipelineOutput, DiffusionPipeline                        │
│    22                                                                                            │
│    23                                                                                            │
│    24 logger = logging.get_logger(__name__)  # pylint: disable=invalid-name                      │
│                                                                                                  │
│ E:\Easy-Diffusion\installer_files\env\lib\site-packages\diffusers\pipelines\pipeline_utils.py:63 │
│ in <module>                                                                                      │
│                                                                                                  │
│     60 │   import transformers                                                                   │
│     61 │   from transformers import PreTrainedModel                                              │
│     62 │   from transformers.utils import FLAX_WEIGHTS_NAME as TRANSFORMERS_FLAX_WEIGHTS_NAME    │
│ ❱   63 │   from transformers.utils import SAFE_WEIGHTS_NAME as TRANSFORMERS_SAFE_WEIGHTS_NAME    │
│     64 │   from transformers.utils import WEIGHTS_NAME as TRANSFORMERS_WEIGHTS_NAME              │
│     65                                                                                           │
│     66 from ..utils import FLAX_WEIGHTS_NAME, ONNX_WEIGHTS_NAME                                  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ImportError: cannot import name 'SAFE_WEIGHTS_NAME' from 'transformers.utils'
(E:\Easy-Diffusion\installer_files\env\lib\site-packages\transformers\utils\__init__.py)
Press any key to continue . . .
cribe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser:
 - Version:

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

**Comment by cmdr2** [comment]
`dance_diffusion`?

@borkolay Can you please describe how you tried to run this? Did you run the program by double-clicking on `Start Stable Diffusion UI.cmd`?

**Comment by borkolay** [comment]
right

**Comment by borkolay** [comment]
Do I need a Python for installation?

**Comment by cmdr2** [comment]
No it comes with Python inbuilt. Closing, please reopen if this is still relevant to you.
