### ISSUE TITLE
fatal: unable to access

### ISSUE THREAD

**Issue by protrading104** [easydiffusion/easydiffusion#1139]
windows 10
without vpn
any ideas on how to solve this ?

![image](https://user-images.githubusercontent.com/71656833/230757388-36e4b3ea-cddb-4d62-a811-6fe284d5b98b.png)

**Comment by cmdr2** [comment]
Hi, it looks like a networking issue on your PC. Please check if you're running a VPN/Firewall/Proxy that's preventing the connection (or DNS lookup, in this case)
