### ISSUE TITLE
Unable to complete installation, console message

### ISSUE THREAD

**Issue by Civisisa** [easydiffusion/easydiffusion#1153]
"The GFPGAN model file present at models\gfpgan\GFPGANv1.3.pth is invalid. It is only 0 bytes in size. Re-downloading.."

curl: (28) Failed to connect to github.com port 443 after 21040 ms: Timed out

"Error: The downloaded GFPGAN model file was invalid! Bytes downloaded: 0"

**Comment by JeLuF** [comment]
You can download the file manualy from:
https://github.com/TencentARC/GFPGAN/releases/download/v1.3.0/GFPGANv1.3.pth
Please save it to the `models\gfpgan\` folder in the installation directory.

**Comment by JeLuF** [comment]
closed due to inactivity
