### ISSUE TITLE
Running in Windows as a service

### ISSUE THREAD

**Issue by mikesimone** [easydiffusion/easydiffusion#1154]
**Is your feature request related to a problem? Please describe.**
I'm not always at the machine with the beefy graphics cards. I'd like to be able to hit it from my tablet, laptop, etc., but, to do that, I have to RDP to that machine, start it with a batch file, and then go back to the machine I'm working from. 

**Describe the solution you'd like**
Instead of having to start it with a batch file, it'd be great if it could be installed as a service on Windows. That way, it's always running, if it crashes, it'll automatically restart itself, and I can just hit it from other machines around my house. 

**Describe alternatives you've considered**
Standing up a server with the graphics cards and installing Linux on it, but, ultimately, that would be a lot of extra money for very little benefit.

**Comment by JeLuF** [comment]
Microsoft provides a set of small tools to create a service from a `.cmd` file:
https://learn.microsoft.com/en-us/troubleshoot/windows-client/deployment/create-user-defined-service
