### ISSUE TITLE
.ignore files for features supporting subdirectories

### ISSUE THREAD

**Issue by spiralofhope** [easydiffusion/easydiffusion#1160]
At the moment there are subdirectories supported.  For example, with `\EasyDiffusion\models\stable-diffusion`

I would like a feature similar to a `.gitignore` file, where if it exists that directory is not included.

This would make it easy for me to, for example, maintain repositories with other versions of files.

**Comment by cmdr2** [comment]
Sorry, I won't be able to get to this right now. Please feel free to contribute the code for this. Thanks!
