### ISSUE TITLE
Error: The downloaded GFPGAN model file was invalid! Bytes downloaded: 0 bug

### ISSUE THREAD

**Issue by Iliasoli** [easydiffusion/easydiffusion#1161]
**Describe the bug**
hello i have a bug about Error: The downloaded GFPGAN model file was invalid! Bytes downloaded: 0 error message m.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: google chrome
 - Version: build 21h2
![cmd_jI2fZL9QW1](https://user-images.githubusercontent.com/105164394/232232027-549ec92d-11e1-4825-a337-3be9488b79ad.png)
full log:https://pastebin.com/er6prGMb

**Comment by JeLuF** [comment]
"Could not resolve host" indicates problems with your network setup. If these problems are intermittent, rerunning `Start Stable Diffusion UI.cmd` from the installation directory. If that doesn't fix it, you can download the file from https://github.com/TencentARC/GFPGAN/releases/download/v1.3.0/GFPGANv1.3.pth and save it to the `models\gfpgan` folder in the installation directory.
