### ISSUE TITLE
How may I use LoRA in easy diffusion? Is it necessary to use LoRA?

### ISSUE THREAD

**Issue by AlexLashield** [easydiffusion/easydiffusion#1170]
I found that it doesn`t support LoRA. I wonder whether there are some technical problem which refusing LoRA or LoRA is just out of time.
And if it is possible to use LoRA in easy diffusion? Or I need to download a plugin, or make one by myself?

**Comment by JeLuF** [comment]
LORA support is currently experimental. In the "Settings" tab, you can first enable the Beta channel, and after restarting, you can enable Diffusers support. After restarting again, LORA support is available. This is an early tech preview and not all features are supported so far.

**Comment by AlexLashield** [comment]
> LORA support is currently experimental. In the "Settings" tab, you can first enable the Beta channel, and after restarting, you can enable Diffusers support. After restarting again, LORA support is available. This is an early tech preview and not all features are supported so far.
Thanks, it helps a lot.

**Comment by JohnClaw** [comment]
> LORA support is currently experimental. In the "Settings" tab, you can first enable the Beta channel, and after restarting, you can enable Diffusers support. After restarting again, LORA support is available. This is an early tech preview and not all features are supported so far.

Hello. I enabled the Beta channel but after restarting didn't find enabling of Diffusers support in the "Settings" tab. What am i doing wrong? Help me, please.

**Comment by JeLuF** [comment]
> Hello. I enabled the Beta channel but after restarting didn't find enabling of Diffusers support in the "Settings" tab. What am i doing wrong? Help me, please.

Did you restart both the EasyDiffusion program and reload the web page?
Does the version number in the top left corner have a `beta` tag?

**Comment by morfie78** [comment]
I followed the above directions and successfully enabled LoRA support.  Thank you!

**Comment by JohnClaw** [comment]
Yes, Yeluf, i restarted the EasyDiffusion and reloaded the web page. And the version number in the top left corner has a beta tag. Still there is no enabling of Diffusers support in the "Settings" tab.

**Comment by JeLuF** [comment]
> Yes, JeLuF, i restarted the EasyDiffusion and reloaded the web page. And the version number in the top left corner has a beta tag. Still there is no enabling of Diffusers support in the "Settings" tab.

And what is the version number that you see next to the beta tag?

**Comment by teonatty** [comment]
I am experiencing the same issue. Running v2.5.22 (beta)

**Comment by JeLuF** [comment]
@teonatty 
> v2.5.22 (beta)

The current beta version is 2.5.37.  Please share a log from the console window. There's something broken in the auto-update.

**Comment by DeMoN100** [comment]
I am on the latest version with the beta enabled I have restarted SD it says in the corner Easy Diffusion (Beta) v2.5.41 I still do not see loras on the UI.

**Comment by Galaxia-mk** [comment]
> > LORA support is currently experimental. In the "Settings" tab, you can first enable the Beta channel, and after restarting, you can enable Diffusers support. After restarting again, LORA support is available. This is an early tech preview and not all features are supported so far.
> 
> Hello. I enabled the Beta channel but after restarting didn't find enabling of Diffusers support in the "Settings" tab. What am i doing wrong? Help me, please.

After you restarted you have to go back into settings and there you can enable "Test Diffusers", then after restarting again you can use the LoRa feature

**Comment by JeLuF** [comment]
LORA support has been introduced in version 3.0 of EasyDiffusion, which has been released today.

**Comment by lztz0022** [comment]
Congratulations on the new feature! This is a feat moment!
from #914
