### ISSUE TITLE
Merging Models say it's done but didn't export

### ISSUE THREAD

**Issue by gh-doot** [easydiffusion/easydiffusion#1174]
**Describe the bug**
When merging 2 models (even with the same extension) it says it's done but is nowhere to be found in the stable-diffusion folder.

**To Reproduce**
1. Go to 'Merged Models'
2. Merge anything
3. Done. The models have been saved to your models/stable-diffusion folder.
4. No merged model

**Expected behavior**
Expected the model to be exported and merged in the folder, found nothing.

**Screenshots**
![image](https://user-images.githubusercontent.com/48828036/232755927-4d3f0e27-0953-4b8b-b446-e813e6a50ca4.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Google Chrome
 - Version: Latest (as of now)

**Comment by JeLuF** [comment]
The "DefaultCPUAllocator: not enough memory" error message means that your system went out of RAM while merging the models. Please add more paging space. (https://www.ibm.com/docs/en/opw/8.2.0?topic=tuning-optional-increasing-paging-file-size-windows-computers)

**Comment by JeLuF** [comment]
Closed ticket due to inactivity.
