### ISSUE TITLE
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/Users/xxx/downloads/easy-diffusion/installer_files/env/bin/f2py'

### ISSUE THREAD

**Issue by deeduckme** [easydiffusion/easydiffusion#1176]
Impossible to find the file in the installer.

 No such file or directory: '/Users/xxx/downloads/easy-diffusion/installer_files/env/bin/f2py'

package is here :  https://stable-diffusion-ui.github.io/

**Comment by shenija** [comment]
it is necessary to unpack the neural network to the root of the disk, and not to the user directory

**Comment by JeLuF** [comment]
> Impossible to find the file in the installer.
> 
> No such file or directory: '/Users/xxx/downloads/easy-diffusion/installer_files/env/bin/f2py'
> 
> package is here : https://stable-diffusion-ui.github.io/

Please share the entire output of the `./start.sh` script. Without context, it's hard to understand what's going on.

**Comment by JeLuF** [comment]
Closed ticket due to inactivity.
