### ISSUE TITLE
Easy Diffusion, GPU GTX 1080 Ti not supported.

### ISSUE THREAD

**Issue by Cyberbutt** [easydiffusion/easydiffusion#1179]
I have GTX 1080 TI and windows 7. But no compatible GPU found. I can't switch "Use CPU (not GPU)" button. The rest of the app works just perfect. This is the only problem. Is there any way to fix this issue?

Graphics cards compatible with Stable Diffusion
    Pascal: GeForce GTX 1070, 1070 Ti, 1080 and 1080 Ti; GeForce Titan X and Titan XP
    Volta: GeForce Titan V
    Turing: GeForce RTX 2060 Super, 2070, 2070 Super and 2080; GeForce RTX Titan
    Ampere: GeForce RTX 3060 Ti and LHR; GeForce RTX3070 and LHR; GeForce RTX3080 and LHR; GeForce RTX3090
    Ada Lovelace : All 40 Series Graphics Cards

The 4000 series is obviously the most compatible, but also the one that costs the skin of your buttocks and that of your family :
    GeForce RTX 4090: the most powerful graphics card on the market, with 18,432 CUDA cores and 24 GB of GDDR6X memory
    GeForce RTX 4080 Ti: A high-end graphics card, with 15,360 CUDA cores and 16 GB of GDDR6X memory
    GeForce RTX 4070 Ti: an upper mid-range graphics card, with 9,216 CUDA cores and 10 GB or more of GDDR6X memory

**Comment by JeLuF** [comment]
You probably need to update the Nvidia driver to a newer version. Anything newer than October 2022 should work. Older Nvidia drivers aren't supported.

Please note that Windows 7 is not supported any more. Please update your operating system.

**Comment by JeLuF** [comment]
Closed ticket due to inactivity.
