### ISSUE TITLE
Capture client IP address in logs

### ISSUE THREAD

**Issue by elbowdonkey** [easydiffusion/easydiffusion#1199]
**Is your feature request related to a problem? Please describe.**
As far as I can tell, there's no way to know what the IP address of any given client accessing EasyDiffusion.

**Describe the solution you'd like**
For each log entry, in addition to showing things like time stamps, show the IP address of the client interacting with the Easy Diffusion web interface.

**Describe alternatives you've considered**
I can set up logging at the router to accomplish this, but it's tedious, and it's not something everyone can easily do. I'd likely be trivial to do in the code for EasyDiffusion.

**Comment by ollobrains** [comment]
Sounds like a bit of a security risk tbh

**Comment by elbowdonkey** [comment]
How is knowing the IP address of clients accessing a service on my machine a security risk? Are you saying it's a security risk for me, or the clients? Are you aware that every web site you visit knows your IP address, and more?

Not collecting IP addresses is a security risk. Say you have your EasyDiffusion web app open to the Internet (you shouldn't), or more likely, open to your local network, and say your local network has a few hundred clients. Can you tell me which of those clients is submitting prompts?

**Comment by elbowdonkey** [comment]
I'm not suggesting a full separate access log. I'm suggesting adding the client IP address to requests made to the server. Clearly, having logging output to STDOUT is functional. I don't know much about `uvicorn`, but surely it has the ability to access a `request` object or similar, along with things like request headers, and the client associated with the request. Adding the client IP should be trivial.

I'm not suggesting that I want to *not* practice proper security measures. The scenario I'm describing is one where the network *is* trusted, and one out of maybe 20 users is abusing the server. It'd be nice to have some idea of what client is abusing the server so I can have a conversation with them without having to setup a reverse proxy first.

Honestly, it's bizarre that I'd see any push back on such a simple idea. If you spin up a server, you log IP addresses. That's normal. Not logging access isn't.

**Comment by cmdr2** [comment]
If this is still relevant, please feel free to create a pull request.
