### ISSUE TITLE
Allow me to define where logs are saved

### ISSUE THREAD

**Issue by elbowdonkey** [easydiffusion/easydiffusion#1200]
**Is your feature request related to a problem? Please describe.**
As far as I can tell, when running EasyDiffusion on Windows, the logs that one sees in the `cmd` prompt don't save anywhere. I'd like those logs written to disk, and I'd like to define where those logs are saved.

**Describe the solution you'd like**
In the `Settings` add two form elements:
* A toggle that determines whether or not to save logs to disk
* A text input that allows the default log file location to be defined

**Comment by cmdr2** [comment]
Hi, please feel free to create a pull request with the code for this, if you're interested in adding this feature. It's not something that I can get to right now. Thanks!
