### ISSUE TITLE
Cannot install on OSX

### ISSUE THREAD

**Issue by bullshite1** [easydiffusion/easydiffusion#1205]
**Describe the bug**
When attempting to install in Terminal on OSX, after it tries downloading micromamba, the error "url: (60) SSL certificate problem: Invalid certificate chain" appears, and shortly after "ERROR: micromamba download failed" and "Error downloading Stable Diffusion UI. Sorry about that, please try to:"

easy-diffusion user$ ./start.sh
/usr/bin/curl
/usr/bin/tar
/usr/bin/bzip2
Downloading micromamba from https://micro.mamba.pm/api/micromamba/osx-64/latest to /Users/user/easy-diffusion/installer_files/mamba/micromamba
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (60) SSL certificate problem: Invalid certificate chain
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
tar: bin/micromamba: Not found in archive
tar: Error exit delayed from previous errors.

EE micromamba download failed
EE If the lines above contain 'bzip2: Cannot exec', your system doesn't have bzip2 installed
EE If there are network errors, please check your internet setup

EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE

ERROR: micromamba download failed

Error downloading Stable Diffusion UI. Sorry about that, please try to:
 1. Run this installer again.
 2. If that doesn't fix it, please try the common troubleshooting steps at https://github.com/cmdr2/stable-diffusion-ui/wiki/Troubleshooting
 3. If those steps don't help, please copy *all* the error messages in this window, and ask the community at https://discord.com/invite/u9yhsFmEkB
 4. If that doesn't solve the problem, please file an issue at https://github.com/cmdr2/stable-diffusion-ui/issues

Thanks!

Press any key to continue

**Comment by cmdr2** [comment]
Are you behind a VPN/Firewall/Proxy? It looks like something's altering the SSL certificates during the download, and the downloader is refusing to trust the modified certificate. This often happens on proxy or VPN networks.

**Comment by JeLuF** [comment]
What's your version of MacOS? Older versions don't receive certificate store updates any more and thus fail to verify new certificates.

**Comment by bullshite1** [comment]
@cmdr2 I am not behind a VPN, firewall, or proxy.

@JeLuF I am on OS X 10.10.5. My machine failed when attempting to update to a newer version. I'm guessing this is the reason and that it is considered too old? Disappointing if so, yet another project thwarted by my deprecated OS. Thank you for the information though!

**Comment by JeLuF** [comment]
You can try to update your certificate store manually. I'm not a Mac user, but others had success with this guide: https://logi.wiki/index.php/Update_Certificates_in_Older_macOS

**Comment by cmdr2** [comment]
@bullshite1 In that case you can try to download micromamba manually, and run the installer again. It'll skip the micromamba step and proceed.

Download micromamba from https://micro.mamba.pm/api/micromamba/osx-64/latest to `/Users/user/easy-diffusion/installer_files/mamba/micromamba`

Let's try it, but it might fail again in steps after this because of SSL errors.

**Comment by bullshite1** [comment]
> You can try to update your certificate store manually. I'm not a Mac user, but others had success with this guide: https://logi.wiki/index.php/Update_Certificates_in_Older_macOS

Sorry for the late reply - I gave this a shot and now receive this error when attempting install:

/usr/bin/curl
/usr/bin/tar
/usr/bin/bzip2
Packages to install: conda python=3.8.5

                                           __
          __  ______ ___  ____ _____ ___  / /_  ____ _
         / / / / __ `__ \/ __ `/ __ `__ \/ __ \/ __ `/
        / /_/ / / / / / / /_/ / / / / / / /_/ / /_/ /
       / .___/_/ /_/ /_/\__,_/_/ /_/ /_/_.___/\__,_/
      /_/

dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /Users/lwagner/easy-diffusion/installer_files/mamba/micromamba
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _clock_gettime
  Referenced from: /Users/lwagner/easy-diffusion/installer_files/mamba/micromamba
  Expected in: /usr/lib/libSystem.B.dylib

scripts/bootstrap.sh: line 93:  3322 Trace/BPT trap: 5       "$MAMBA_ROOT_PREFIX/micromamba" install -y --prefix "$INSTALL_ENV_DIR" -c conda-forge $PACKAGES_TO_INSTALL

EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE

ERROR: Installation of the packages ' conda python=3.8.5' failed.

Error downloading Stable Diffusion UI. Sorry about that, please try to:
 1. Run this installer again.
 2. If that doesn't fix it, please try the common troubleshooting steps at https://github.com/cmdr2/stable-diffusion-ui/wiki/Troubleshooting
 3. If those steps don't help, please copy *all* the error messages in this window, and ask the community at https://discord.com/invite/u9yhsFmEkB
 4. If that doesn't solve the problem, please file an issue at https://github.com/cmdr2/stable-diffusion-ui/issues

Thanks!


Press any key to continue

**Comment by JeLuF** [comment]
Version 10.10.5 is SIX years old!

`dyld: lazy symbol binding failed: Symbol not found: _clock_gettime` means that your operating system is too old. Without an OS update, EasyDiffusion can't run on your system.

**Comment by JeLuF** [comment]
closed due to inactivity
