### ISSUE TITLE
Test diffusers is not working again

### ISSUE THREAD

**Issue by van1027** [easydiffusion/easydiffusion#1213]
**Describe the bug**
Test Diffusers mode stopped working again. You request something, it says rendering but nothing is going on. It can hang for hours before you kill the server. Stop task doesn't work either.

**To Reproduce**
Request anything with LoRA

**Expected behavior**
Return some image

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
Here is the log:

Install dir: C:\stable-diffusion-ui\
C:\Program Files\Git\cmd\git.exe
git version 2.39.2.windows.1
C:\stable-diffusion-ui\installer_files\env\Library\bin\conda.bat
C:\stable-diffusion-ui\installer_files\env\Scripts\conda.exe
conda 23.1.0

"Easy Diffusion - v2"

"Easy Diffusion's git repository was already installed. Updating from beta.."
HEAD is now at 8174f94 Merge pull request #1207 from cmdr2/main
Already on 'beta'
Your branch is up to date with 'origin/beta'.
Already up to date.
498 File(s) copied
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
A subdirectory or file tmp already exists.
torch: 1.13.1+cu116
torchvision: 0.14.1+cu116
sdkit: 1.0.81
stable-diffusion-sdkit: 2.1.4
rich: 12.6.0
uvicorn: 0.19.0
fastapi: 0.85.1
15:30:03.005 WARNING MainThread A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
stable-diffusion model(s) found.
gfpgan model(s) found.
realesrgan model(s) found.
vae model(s) found.

"Easy Diffusion installation complete! Starting the server!"

PYTHONPATH=C:\stable-diffusion-ui\installer_files\env\lib\site-packages
C:\stable-diffusion-ui\installer_files\env\python.exe
C:\Users\vanda\AppData\Local\Microsoft\WindowsApps\python.exe
Python 3.8.5
15:30:09.184 WARNING MainThread A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
15:30:10.997 INFO MainThread started in C:\stable-diffusion-ui\stable-diffusion                                                                                                                                                server.py:21
15:30:11.012 INFO MainThread started at 04/26/23 15:30:11                                                                                                                                                                      server.py:22
15:30:11.012 INFO MainThread Scanning all model folders for models...                                                                                                                                                  model_manager.py:249
15:30:12.168 INFO MainThread Scanned 39 models. Nothing infected                                                                                                                                                       model_manager.py:258
15:30:12.278 INFO MainThread Start new Rendering Thread on device: cuda:0                                                                                                                                               task_manager.py:460
15:30:13.075 INFO cuda:0 Setting cuda:0 as active, with precision: half                                                                                                                                               device_manager.py:151
15:30:13.075 INFO cuda:0 loading stable-diffusion model from C:\stable-diffusion-ui\models\stable-diffusion\babes_11.safetensors to device: cuda:0                                                                           __init__.py:24
15:30:13.090 INFO cuda:0 loading on diffusers                                                                                                                                                                               __init__.py:125
15:30:13.090 INFO cuda:0 using config: C:\stable-diffusion-ui\installer_files\env\lib\site-packages\sdkit\models\models_db\configs\v1-inference.yaml                                                                        __init__.py:127
15:30:13.122 INFO cuda:0 using attn_precision: fp16                                                                                                                                                                         __init__.py:133
global_step key not found in model
In this conversion only the non-EMA weights are extracted. If you want to instead extract the EMA weights (usually better for inference), please make sure to add the `--extract_ema` flag.
C:\stable-diffusion-ui\installer_files\env\lib\site-packages\transformers\models\clip\feature_extraction_clip.py:28: FutureWarning: The class CLIPFeatureExtractor is deprecated and will be removed in version 5 of Transformers. Please use CLIPImageProcessor instead.
  warnings.warn(
15:30:32.809 INFO cuda:0 Loaded on diffusers                                                                                                                                                                                __init__.py:203
15:30:32.824 INFO cuda:0 loaded stable-diffusion model from C:\stable-diffusion-ui\models\stable-diffusion\babes_11.safetensors to device: cuda:0                                                                            __init__.py:28
15:30:32.824 INFO cuda:0 loading vae model from C:\stable-diffusion-ui\models\vae\vae-ft-mse-840000-ema-pruned.ckpt to device: cuda:0                                                                                        __init__.py:24
C:\stable-diffusion-ui\installer_files\env\lib\site-packages\sdkit\models\model_loader\vae.py:38: FutureWarning: Accessing config attribute `sample_size` directly via 'AutoencoderKL' object attribute is deprecated. Please access 'sample_size' over 'AutoencoderKL's config object instead, e.g. 'unet.config.sample_size'.
  image_size = m.vae.sample_size
15:30:32.996 INFO cuda:0 Loading diffusers vae                                                                                                                                                                                    vae.py:44
15:30:33.340 INFO cuda:0 loaded vae model from C:\stable-diffusion-ui\models\vae\vae-ft-mse-840000-ema-pruned.ckpt to device: cuda:0                                                                                         __init__.py:28
15:30:33.340 INFO cuda:0 Session 1682547916879 starting task 2497576196896 on NVIDIA GeForce RTX 3070 Ti                                                                                                                task_manager.py:312
15:30:33.512 INFO cuda:0 unloaded stable-diffusion model from device: cuda:0                                                                                                                                                 __init__.py:52
15:30:33.512 INFO cuda:0 loading stable-diffusion model from C:\stable-diffusion-ui\models\stable-diffusion\experience_70.safetensors to device: cuda:0                                                                      __init__.py:24
15:30:33.528 INFO cuda:0 loading on diffusers                                                                                                                                                                               __init__.py:125
15:30:33.528 INFO cuda:0 using config: C:\stable-diffusion-ui\installer_files\env\lib\site-packages\sdkit\models\models_db\configs\v1-inference.yaml                                                                        __init__.py:127
15:30:33.559 INFO cuda:0 using attn_precision: fp16                                                                                                                                                                         __init__.py:133
global_step key not found in model
15:31:16.491 INFO cuda:0 Loaded on diffusers                                                                                                                                                                                __init__.py:203
15:31:16.491 INFO cuda:0 loaded stable-diffusion model from C:\stable-diffusion-ui\models\stable-diffusion\experience_70.safetensors to device: cuda:0                                                                       __init__.py:28
15:31:16.881 INFO cuda:0 unloaded vae model from device: cuda:0                                                                                                                                                              __init__.py:52
15:31:16.881 INFO cuda:0 loading vae model from C:\stable-diffusion-ui\models\vae\vae-ft-mse-840000-ema-pruned.ckpt to device: cuda:0                                                                                        __init__.py:24
15:31:17.694 INFO cuda:0 Loading diffusers vae                                                                                                                                                                                    vae.py:44
15:31:18.038 INFO cuda:0 loaded vae model from C:\stable-diffusion-ui\models\vae\vae-ft-mse-840000-ema-pruned.ckpt to device: cuda:0                                                                                         __init__.py:28
15:31:18.038 INFO cuda:0 loading lora model from C:\stable-diffusion-ui\models\lora\hyperpregnant_hyperpregV2.safetensors to device: cuda:0                                                                                  __init__.py:24
15:31:18.303 INFO cuda:0 loaded lora model from C:\stable-diffusion-ui\models\lora\hyperpregnant_hyperpregV2.safetensors to device: cuda:0                                                                                   __init__.py:28
15:31:18.319 INFO cuda:0 request: {'guidance_scale': 7.5,                                                                                                                                                                    renderer.py:64
 'height': 640,
 'hypernetwork_strength': 0,
 'lora_alpha': 0.5,
 'negative_prompt': '***',
 'num_inference_steps': 30,
 'num_outputs': 1,
 'preserve_init_image_color_profile': False,
 'prompt': '***',
 'sampler_name': 'dpmpp_2m',
 'seed': 2563801804,
 'width': 960}
15:31:18.350 INFO cuda:0 task data: {'block_nsfw': False,                                                                                                                                                                    renderer.py:65
 'metadata_output_format': 'txt',
 'output_format': 'png',
 'output_lossless': False,
 'output_quality': 95,
 'request_id': 2497576196896,
 'save_to_disk_path': 'C:\\stable-diffusion-ui\\outputs',
 'session_id': '1682547916879',
 'show_only_filtered_image': True,
 'stream_image_progress': True,
 'stream_image_progress_interval': 5,
 'upscale_amount': 4,
 'use_face_correction': None,
 'use_hypernetwork_model': None,
 'use_lora_model': 'C:\\stable-diffusion-ui\\models\\lora\\hyperpregnant_hyperpregV2.safetensors',
 'use_stable_diffusion_model': 'C:\\stable-diffusion-ui\\models\\stable-diffusion\\experience_70.safetensors',
 'use_upscale': None,
 'use_vae_model': 'C:\\stable-diffusion-ui\\models\\vae\\vae-ft-mse-840000-ema-pruned.ckpt',
 'vram_usage_level': 'balanced'}
15:31:18.366 INFO cuda:0 Global seed set to 2563801804                                                                                                                                                                           seed.py:65
15:31:18.438 INFO cuda:0 Using sampler: DPMSolverMultistepScheduler {                                                                                                                                                image_generator.py:237
  "_class_name": "DPMSolverMultistepScheduler",
  "_diffusers_version": "0.15.1",
  "algorithm_type": "dpmsolver++",
  "beta_end": 0.012,
  "beta_schedule": "scaled_linear",
  "beta_start": 0.00085,
  "clip_sample": false,
  "clip_sample_range": 1.0,
  "dynamic_thresholding_ratio": 0.995,
  "lower_order_final": true,
  "num_train_timesteps": 1000,
  "prediction_type": "epsilon",
  "sample_max_value": 1.0,
  "set_alpha_to_one": false,
  "solver_order": 2,
  "solver_type": "midpoint",
  "steps_offset": 1,
  "thresholding": false,
  "trained_betas": null,
  "use_karras_sigmas": false
}
 because of dpmpp_2m
15:31:18.470 INFO cuda:0 Applying LoRA..                                                                                                                                                                             image_generator.py:251
Applying lora 0.5
15:31:22.016 INFO cuda:0 Parsing the prompt..                                                                                                                                                                        image_generator.py:258
15:31:22.016 INFO cuda:0 compel is ready

**Comment by ollobrains** [comment]
confirming the bug reported

**Comment by cmdr2** [comment]
@ollobrains and @van1027 Can you please try with the `sd-v1-4` model as well, and let us know if that hangs too? Thanks

**Comment by van1027** [comment]
> @ollobrains and @van1027 Can you please try with the `sd-v1-4` model as well, and let us know if that hangs too? Thanks

Yes, it hangs as well.

**Comment by van1027** [comment]
Is it going to ever work again?

**Comment by spiralofhope** [comment]
Welp, this is a showstopper for me.  Is there a way to roll back to a working build from a few weeks ago?  Do I poke around the cmd file(s) and disable the updating, and then roll back the git repo?

**Comment by cmdr2** [comment]
@spiralofhope Do you have "Test Diffusers" enabled in the Settings tab? You can always opt-out by disabling "Test Diffusers" and "beta" and pressing Save, and restarting Easy Diffusion.

**Comment by spiralofhope** [comment]
@cmdr2 

On a fresh restart, I see there was an update to 2.5.38.  I notice that CPU use is disabled (it used to be enabled and force-enabled).  I set it to enabled and after this update it re-disabled it (to use the GPU).  I see it is attempting to use my quaint 1030.  If that works, then that's awesome! (and hilarious)

> What's the error?

I do not get an error with this:

```
Seed: 822594218, Dimensions: 256x512, Sampler: dpm_fast, Inference Steps: 30, Guidance Scale: 7.5, Model: general/Stable Diffusion/sd-v1-4-full-ema, VAE: vae-ft-mse-840000-ema-pruned, Fix Faces: GFPGANv1.4, Upscale: RealESRGAN_x4plus (4x)
```

I was indeed able to reproduce the error with my earlier settings.  As I have that test case where it does work, and another where it does not, I will try to figure out what specifically is causing a problem and report on those settings.

> Do you have "Test Diffusers" enabled in the Settings tab?

I see no such setting in either the top "Settings" tab, or the left side of the "Generate" tab.

Thanks for your response, I'll work to get something more concrete.

**Comment by spiralofhope** [comment]
So far I can reproduce the following error:

```
Error: Could not load the gfpgan model! Reason: 'params'
Error: Could not load the gfpgan model! Reason: 'params'. Task ended after 7 seconds
```

... using LyonHrt's "Lollypop" ESRGAN.  Maybe this has been deprecated?

https://upscale.wiki/wiki/Model_Database
https://drive.google.com/u/1/uc?id=10h8YXKKOQ61ANnwLjjHqXJdn4SbBuUku&export=download

The messages I get in the console are:

<details>
 <summary>Click to expand</summary>

```

08:02:12.325 INFO cuda:0 Session 1685024661320 starting task 2216491993504 on NVIDIA GeForce GT 1030                                                                                          task_manager.py:314
08:02:12.446 INFO cuda:0 unloaded gfpgan model from device: cuda:0                                                                                                                                 __init__.py:62
08:02:12.448 INFO cuda:0 loading gfpgan model from PATH\models\gfpgan\Lollypop.pth to device: cuda:0                                                               __init__.py:34
08:02:14.192 ERROR cuda:0 'params'                                                                                                                                                           model_manager.py:146
Traceback (most recent call last):
  File "PATH\easydiffusion\model_manager.py", line 142, in reload_models_if_necessary
    action_fn(context, model_type, scan_model=False)  # we've scanned them already
  File "PATH\env\lib\site-packages\sdkit\models\model_loader\__init__.py", line 36, in load_model
    context.models = models.load_model(context, **kwargs)
  File "PATH\env\lib\site-packages\sdkit\models\model_loader\gfpgan.py", line 15, in load_model
    return GFPGANer(
  File "PATH\env\lib\site-packages\gfpgan\utils.py", line 97, in __init__
    self.gfpgan.load_state_dict(loadnet, strict=True)
KeyError: 'params'
08:02:14.221 ERROR cuda:0 Traceback (most recent call last):                                                                                                                                  task_manager.py:356
  File "PATH\ui\easydiffusion\task_manager.py", line 339, in thread_render
    model_manager.fail_if_models_did_not_load(renderer.context)
  File "PATH\ui\easydiffusion\model_manager.py", line 169, in fail_if_models_did_not_load
    raise Exception(f"Could not load the {model_type} model! Reason: " + e)
Exception: Could not load the gfpgan model! Reason: 'params'

08:02:14.332 INFO cuda:0 Session 1685024661320 task 2216491993504 failed!                                                                                                                     task_manager.py:365
```

(replace `PATH` with whatever)
</details>

**Comment by JeLuF** [comment]
@spiralofhope 
ESRGAN models are used for upscaling
GFPGAN models are used for face correction
You can't use an upscaling mode as face correction model.
