### ISSUE TITLE
ModuleNotFoundError: No module named 'sdkit'

### ISSUE THREAD

**Issue by fengxueguang** [easydiffusion/easydiffusion#1221]
centos 7.9, Latest updates caused this error not seen before:
`
./start.sh
...
 Using cached http://mirrors.cloud.aliyuncs.com/pypi/packages/e1/1e/bf736f9576a8979752b826b75cbd83663ff86634ea3055a766e2d8ad3ee5/ftfy-6.1.1-py3-none-any.whl (53 kB)
Collecting future>=0.17.1 (from pytorch-lightning==1.4.2->stable-diffusion-sdkit==2.1.4->sdkit==1.0.81)
  Using cached future-0.18.3-py3-none-any.whl
Collecting fsspec[http]!=2021.06.0,>=2021.05.0 (from pytorch-lightning==1.4.2->stable-diffusion-sdkit==2.1.4->sdkit==1.0.81)
  Using cached http://mirrors.cloud.aliyuncs.com/pypi/packages/d6/30/db3078afe553e9a07c87534cbfb87a8c8ebb083fa0a8847ca5bdc86b51a7/fsspec-2023.4.0-py3-none-any.whl (153 kB)
Collecting tensorboard>=2.2.0 (from pytorch-lightning==1.4.2->stable-diffusion-sdkit==2.1.4->sdkit==1.0.81)
  Using cached http://mirrors.cloud.aliyuncs.com/pypi/packages/aa/80/f7233129f75d0d1b35e67df3a48010fffd21ccde124847e3c33d503fef01/tensorboard-2.12.2-py3-none-any.whl (5.6 MB)
Collecting pyDeprecate==0.3.1 (from pytorch-lightning==1.4.2->stable-diffusion-sdkit==2.1.4->sdkit==1.0.81)
  Using cached http://mirrors.cloud.aliyuncs.com/pypi/packages/a2/17/ff7ec2752f53ea245499b23ee64e76d12f45fcde7a5b1b445f9c58cd1ec0/pyDeprecate-0.3.1-py3-none-any.whl (10 kB)
Requirement already satisfied: typing-extensions in /data/easy-diffusion/installer_files/env/lib/python3.8/site-packages (from pytorch-lightning==1.4.2->stable-diffusion-sdkit==2.1.4->sdkit==1.0.81) (4.5.0)
Collecting tokenizers!=0.11.3,<0.14,>=0.11.1 (from transformers~=4.25->compel==1.0.5->sdkit==1.0.81)
  Using cached http://mirrors.cloud.aliyuncs.com/pypi/packages/4e/f2/017bf57106b845e31ef6179bf204042720a53629cf599ef9464da990e0e5/tokenizers-0.13.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (7.8 MB)
Collecting basicsr>=1.4.2 (from gfpgan->sdkit==1.0.81)
  Using cached http://mirrors.cloud.aliyuncs.com/pypi/packages/86/41/00a6b000f222f0fa4c6d9e1d6dcc9811a374cabb8abb9d408b77de39648c/basicsr-1.4.2.tar.gz (172 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [63 lines of output]
      WARNING: The repository located at mirrors.cloud.aliyuncs.com is not a trusted or secure host and is being ignored. If this repository is available via HTTPS we recommend you use HTTPS instead, otherwise you may silence this warning and allow it anyway with '--trusted-host mirrors.cloud.aliyuncs.com'.
      ERROR: Could not find a version that satisfies the requirement cython (from versions: none)
      ERROR: No matching distribution found for cython
      /data/easy-diffusion/installer_files/env/lib/python3.8/site-packages/setuptools/dist.py:755: SetuptoolsDeprecationWarning: Invalid dash-separated options
      !!
 Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-cvgjk_s2/basicsr_a847b1558e634616b77e5397de95ff19/setup.py", line 147, in <module>
          setup(
        File "/data/easy-diffusion/installer_files/env/lib/python3.8/site-packages/setuptools/__init__.py", line 106, in setup
          _install_setup_requires(attrs)
        File "/data/easy-diffusion/installer_files/env/lib/python3.8/site-packages/setuptools/__init__.py", line 79, in _install_setup_requires
          _fetch_build_eggs(dist)
        File "/data/easy-diffusion/installer_files/env/lib/python3.8/site-packages/setuptools/__init__.py", line 84, in _fetch_build_eggs
          dist.fetch_build_eggs(dist.setup_requires)
        File "/data/easy-diffusion/installer_files/env/lib/python3.8/site-packages/setuptools/dist.py", line 917, in fetch_build_eggs
          return _fetch_build_eggs(self, requires)
        File "/data/easy-diffusion/installer_files/env/lib/python3.8/site-packages/setuptools/installer.py", line 38, in _fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "/data/easy-diffusion/installer_files/env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 827, in resolve
          dist = self._resolve_dist(
        File "/data/easy-diffusion/installer_files/env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 863, in _resolve_dist
          dist = best[req.key] = env.best_match(
        File "/data/easy-diffusion/installer_files/env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1133, in best_match
          return self.obtain(req, installer)
        File "/data/easy-diffusion/installer_files/env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1145, in obtain
          return installer(requirement)
        File "/data/easy-diffusion/installer_files/env/lib/python3.8/site-packages/setuptools/installer.py", line 98, in _fetch_build_egg_no_warn
          raise DistutilsError(str(e)) from e
      distutils.errors.DistutilsError: Command '['/data/easy-diffusion/installer_files/env/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpo8frp4b0', '--quiet', '--index-url', 'http://mirrors.cloud.aliyuncs.com/pypi/simple/', 'cython']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.
> python -m pip install --upgrade fastapi==0.85.1
Looking in indexes: http://mirrors.cloud.aliyuncs.com/pypi/simple/
Collecting fastapi==0.85.1
  Using cached http://mirrors.cloud.aliyuncs.com/pypi/packages/bf/54/6eb1882b5cb29e6647df92ee74d0a93dab149234ec914563cab955fa667f/fastapi-0.85.1-py3-none-any.whl (55 kB)
Collecting pydantic!=1.7,!=1.7.1,!=1.7.2,!=1.7.3,!=1.8,!=1.8.1,<2.0.0,>=1.6.2 (from fastapi==0.85.1)
  Using cached http://mirrors.cloud.aliyuncs.com/pypi/packages/f1/bd/0dad4908e5f693b7951b68f435139ec583f5eebb3d75505e1efa0f2284fe/pydantic-1.10.7-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.2 MB)
Collecting starlette==0.20.4 (from fastapi==0.85.1)
  Using cached http://mirrors.cloud.aliyuncs.com/pypi/packages/51/37/8ac52116984d6a0d8502ec2c7e4a4a78f862b76410cdb1a4bcb384c91cb3/starlette-0.20.4-py3-none-any.whl (63 kB)
Collecting anyio<5,>=3.4.0 (from starlette==0.20.4->fastapi==0.85.1)
  Using cached http://mirrors.cloud.aliyuncs.com/pypi/packages/77/2b/b4c0b7a3f3d61adb1a1e0b78f90a94e2b6162a043880704b7437ef297cad/anyio-3.6.2-py3-none-any.whl (80 kB)
Requirement already satisfied: typing-extensions>=3.10.0 in /data/easy-diffusion/installer_files/env/lib/python3.8/site-packages (from starlette==0.20.4->fastapi==0.85.1) (4.5.0)
Requirement already satisfied: idna>=2.8 in /data/easy-diffusion/installer_files/env/lib/python3.8/site-packages (from anyio<5,>=3.4.0->starlette==0.20.4->fastapi==0.85.1) (3.4)
Collecting sniffio>=1.1 (from anyio<5,>=3.4.0->starlette==0.20.4->fastapi==0.85.1)
  Using cached http://mirrors.cloud.aliyuncs.com/pypi/packages/c3/a0/5dba8ed157b0136607c7f2151db695885606968d1fae123dc3391e0cfdbf/sniffio-1.3.0-py3-none-any.whl (10 kB)
Installing collected packages: sniffio, pydantic, anyio, starlette, fastapi
Successfully installed anyio-3.6.2 fastapi-0.85.1 pydantic-1.10.7 sniffio-1.3.0 starlette-0.20.4
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
fastapi: 0.85.1
Traceback (most recent call last):
  File "../scripts/check_models.py", line 3, in <module>
    from sdkit.models import download_model, get_model_info_from_db
ModuleNotFoundError: No module named 'sdkit'
Press any key to continueclient_loop: send disconnect: Broken pipe
`

**Comment by JeLuF** [comment]
First of all, please don't run EasyDiffusion as root. It doesn't need root privs and it's best practice not to use elevated privs if you don't need them.

Your system seems to have a pypi mirror configured. This is probably due to some settings in the base image of your cloud VM. Please check your pip configuration and change the address of the mirror to https, as suggested in the error message.
