### ISSUE TITLE
Timeout when downloading

### ISSUE THREAD

**Issue by ootraktoroo** [easydiffusion/easydiffusion#1225]
I try to use sd 2.1 chkpt, ip_pytorch_model.bin starts to download and at ~ 750 mb fails. File is pretty big for my limited mobile data connection. As far as I understand, i just need to increase timeout and retries parameters. Please help me find the lines and scripts that i should modify to do this!

**Comment by JeLuF** [comment]
You can try to download it from here: https://huggingface.co/openai/clip-vit-large-patch14/resolve/8d052a0f05efbaefbc9e8786ba291cfdf93e5bff/pytorch_model.bin

**Comment by ootraktoroo** [comment]
> You can try to download it from here: https://huggingface.co/openai/clip-vit-large-patch14/resolve/8d052a0f05efbaefbc9e8786ba291cfdf93e5bff/pytorch_model.bin

Thanks, but the file that downloads through the console is around 4 gb, while this is 1,6 gb. Also, where shall i put it so the script picks it up instead of the one it tries to get?

**Comment by cmdr2** [comment]
If this is still relevant, the .ckpt file needs to be put in `models/stable-diffusion`
