### ISSUE TITLE
Test Diffusers consume a lot more VRAM

### ISSUE THREAD

**Issue by ex479** [easydiffusion/easydiffusion#1227]
When the **test_diffusers** option is enabled, the amount of consumed video memory increases dramatically.

Moreover, with Test Diffusers ON VRAM consumption isn't affected by **GPU Memory Usage** setting, you can select Low, Balanced or High - the memory consumption is always the same (very high).

The screenshots show that without test diffusers about 7GB of VRAM is used, but with them is more than 10GB. All additional settings such as upscaling, face refinement etc are disabled.

Full precision (FP32) is used in both cases (without full precision VRAM is consumed less by about 1-2GB, but the ratio between two cases is about the same, it can just be 5GB vs 9GB instead of 7GB vs 10GB).

Image size is 512x960
--------------------------------------------
**Screenshots**
![Test_Diffusers_OFF_512x960_FP32_MemUse-HIGH](https://user-images.githubusercontent.com/132173201/235327312-049144ee-ae52-4505-8fd2-11422a3cf366.png)
![Test_Diffusers_ON_512x960_FP32_MemUse-LOW](https://user-images.githubusercontent.com/132173201/235327315-8827acb8-175f-4c29-85da-a0f8be32f6fb.png)

--------------------------------------------
 - OS: Windows 7x64
 - Browser: Chrome 109.0.5414.120 64bit
 - Version: 2.5.31(beta)

**Comment by ex479** [comment]
I don't know if it matters or not, but I use **xformers** module.
Here is the **xformers info** inside the local easy-diffusion enviroment (**D:\EDiffusion\installer_files\env\python.exe -m xformers.info**)
[log.txt](https://github.com/cmdr2/stable-diffusion-ui/files/11360230/log.txt)

**Comment by ex479** [comment]
I noticed that the lack of memory optimization is somehow connected with the ldm module (shapes, dimensions, attentions - something like that). Without test_diffusers those operations are shown in console as well as the xformers stuff (when xformers is active)

**Comment by cmdr2** [comment]
Yes, this is being worked upon, and an update is coming in a few days.

**Comment by JohnClaw** [comment]
How did you enable Test Diffusers? There is no such option in the "Settings" tab. Screenshot: https://i.yapx.ru/V9Nn4.png

**Comment by ex479** [comment]
> How did you enable Test Diffusers? There is no such option in the "Settings" tab. Screenshot: https://i.yapx.ru/V9Nn4.png

Maybe it's because of version you have (2.5.22), my version is 2.5.31

**Comment by cmdr2** [comment]
@JohnClaw That's strange, your version is pretty old. Easy Diffusion auto-updates when you restart the program, have you disabled that by any chance? Thanks

**Comment by Nourepide** [comment]
I confirm that on Test Diffusers my maximum is 448x448, when on a regular one I can render 512x1024.

---
Standart Diffusers 512x1024
![image](https://user-images.githubusercontent.com/22074527/235466445-d81c8890-a9fc-4858-941e-e394046d7bea.png)

Test Diffusers 448x448
![image](https://user-images.githubusercontent.com/22074527/235467889-2977f422-fb44-4881-b25d-19f05446bef6.png)

Test Diffusers 448x512
![image](https://user-images.githubusercontent.com/22074527/235468027-c4126375-ee12-4708-9cc1-e5c197f2fc21.png)


GPU Memory usage not working.

3050 Mobile. 4GB VRAM

**Comment by JeLuF** [comment]
> How can i download the latest version of Easy Diffusion (2.5.31)?

Please restart Easy Diffusion. If the version number in the top left of the web page does not say 2.5.31, please share the _full_ content of the console window so that we can have a look.

**Comment by ex479** [comment]
@JeLuF By the way, is it ok to see such messages in the console?
```
"Easy Diffusion's git repository was already installed. Updating from update branch.."
Fatal: Not A Git Repository” (Or Any Of The Parent Directories): .git
Fatal: Not A Git Repository” (Or Any Of The Parent Directories): .git
Fatal: Not A Git Repository” (Or Any Of The Parent Directories): .git
```
Does this mean my version cannot be upgraded anymore because of that? I saw 2.5.34 in the beta branch today, but my version is still 2.5.31

**Comment by cmdr2** [comment]
@ex479 Yeah, it looks like the git repository has been corrupted. Please try these steps:
1. Delete the `sd-ui-files` folder inside Easy Diffusion.
2. Open `scripts\install_status.txt` in a text editor (like Notepad) and remove the line that says `sd_ui_git_cloned`. Save the file.
3. Run Easy Diffusion again, as usual. It'll repair itself.

Please let us know if that doesn't work. Thanks!

**Comment by cmdr2** [comment]
We released a few improvements to the VRAM usage yesterday. It's still not as good as the non-diffusers version, but it's better than before.

A few more optimizations are coming up, and the goal is to be equal to the non-diffusers branch in terms of VRAM usage.

**Comment by ex479** [comment]
@cmdr2 Thanks a lot! It worked, now the version is 2.5.35 and VRAM is really consumed much less.

By the way, in the .git folder I have new files and for some reason they contain the path to the folder of my email client `<C:\Program Files (x86)\The Bat!\SAVEDATA>`
I hope it's ok and there is no reason to worry about it

**Comment by ex479** [comment]
There is something else that I noticed at the transition from 2.5.31 to 2.5.35.
On version 2.5.31, test diffusers generated different img2img results for DDIM and Heun samplers. Now, on 2.5.35 they generate almost identical pictures. Then I tried to use DPM2 Ancestral to see more difference. The difference really appeared, but it is much less difference that DPM2 Ancestral gave at 2.5.31.
I don’t know whether it became more correct as it happens now or it was more correct before, but decided to report this change just in case.

**Comment by cmdr2** [comment]
@ex479 Thanks for reporting. Will check the two samplers, we didn't change anything between .31 and .35 related to samplers.

Regarding the email files, what are the names of the new files in the .git folder?

**Comment by ex479** [comment]
> @ex479 Thanks for reporting. Will check the two samplers, we didn't change anything between .31 and .35 related to samplers.
Maybe it's because of xformers module. I used xformers 0.0.16 on 2.5.31, and now I use 0.0.19 (for pytorch 2.0.0+cuda118) on 2.5.35
My Guidance scale was 50, Prompt strength 0.31, 250 steps
> Regarding the new files, what are the names of the new files in the .git folder?
All the files are in \sd-ui-files\.git\logs called HEAD and beta

It's strange but I got a new error while restarting (seems it somehow connected with updating of sdkit)
![error](https://user-images.githubusercontent.com/132173201/236248072-d0a65b89-9763-4152-b796-da58b414b128.png)

**Comment by JohnClaw** [comment]
> If the version number in the top left of the web page does not say 2.5.31, please share the _full_ content of the console window so that we can have a look.

Install dir: C:\EasyDiffusion\
"Packages to install: git"

                                           __
          __  ______ ___  ____ _____ ___  / /_  ____ _
         / / / / __ `__ \/ __ `/ __ `__ \/ __ \/ __ `/
        / /_/ / / / / / / /_/ / / / / / / /_/ / /_/ /
       / .___/_/ /_/ /_/\__,_/_/ /_/ /_/_.___/\__,_/
      /_/

conda-forge/noarch                                  12.2MB @   4.0MB/s  4.2s
conda-forge/win-64                                  20.2MB @   2.3MB/s 11.0s
critical libmamba ������ ������� �� ����� ������������� � �������� ������������� ������� ��������.
INFO: Could not find files for the given pattern(s).
'git' is not recognized as an internal or external command,
operable program or batch file.
C:\EasyDiffusion\installer_files\env\Library\bin\conda.bat
C:\EasyDiffusion\installer_files\env\Scripts\conda.exe
conda 22.11.1

"Easy Diffusion - v2"

"Easy Diffusion's git repository was already installed. Updating from beta.."
'git' is not recognized as an internal or external command,
operable program or batch file.
'git' is not recognized as an internal or external command,
operable program or batch file.
'git' is not recognized as an internal or external command,
operable program or batch file.
493 File(s) copied
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
A subdirectory or file tmp already exists.

Hotfixed broken JSON file from OpenAI
"torch and torchvision have already been installed."
"sdkit is already installed."
sdkit version: 1.0.43
stable-diffusion version: 2.1.3
"rich has already been installed."
"Packages necessary for Easy Diffusion were already installed"
"Data files (weights) necessary for Stable Diffusion were already downloaded. Using the HuggingFace 4 GB Model."
"Data files (weights) necessary for GFPGAN (Face Correction) were already downloaded"
"Data files (weights) necessary for ESRGAN (Resolution Upscaling) x4plus were already downloaded"
"Data files (weights) necessary for ESRGAN (Resolution Upscaling) x4plus_anime were already downloaded"
"Data files (weights) necessary for the default VAE (sd-vae-ft-mse-original) were already downloaded"

"Easy Diffusion installation complete! Starting the server!"

PYTHONPATH=C:\EasyDiffusion\installer_files\env\lib\site-packages
C:\EasyDiffusion\installer_files\env\python.exe
Python 3.8.5
No module 'xformers'. Proceeding without it.

**Comment by cmdr2** [comment]
@JohnClaw If this is still relevant, please try the latest installer which fixes this problem: https://github.com/easydiffusion/easydiffusion/releases/tag/v3.0.2

Closing this issue since the original problem has been solved.
