### ISSUE TITLE
Can EasyDiffusion run offline?

### ISSUE THREAD

**Issue by JohnClaw** [easydiffusion/easydiffusion#1231]
Everytime when i start EasyDiffusion it downloads some files from the web. So it will not work on a PC without internet connection, right?

**Comment by JeLuF** [comment]
Easy Diffusion automatically updates when it has an internet connection. If this update fails (e.g. if there's no internet connection), it will start using the version on your computer.

**Comment by fdwr** [comment]
Yep, it works fine without Internet, after the first time. Actually I found this pretty annoying to automatically update every time without asking me, as it wastes extra startup time and changes behaviors (granted, sometimes those changes are *good* changes like bug fixes, but other times those changes *break* things :/). So I just unplug my network cable when launching it, and then plug it back in later after it's launched. 😅

**Comment by cmdr2** [comment]
@fdwr Please let us know if the updates break changes. If you're on the stable branch, the updates go through quite a lot of testing in the beta branch before they're released to the stable branch.

In recent history we haven't released updates that broke the stable branch, but it may also be because nobody complained :)

**Comment by cmdr2** [comment]
Reopening because I agree with @fdwr about it wasting time during startup (especially when offline). Keeping this issue open until it checks for network connectivity before attempting an update.

**Comment by JeLuF** [comment]
If there is no network connectivity, any outgoing connection will fail instantly.
Only if there is a network connected _and_ a default route configured, it will go into a timeout trying to connect to the remote site. I'd call this setup a user error.

**Comment by JeLuF** [comment]
I'd like to suggest to close the issue. EasyDiffusion calls git, git fails to resolve `github.com`, and EasyDiffusion just skips this error and starts up using the local version. This only takes a few milliseconds.
