### ISSUE TITLE
Faster backend

### ISSUE THREAD

**Issue by laurentopia** [easydiffusion/easydiffusion#1235]
Compared to A1111 this is 50% slower
Maybe change the backend?
This is supposed to be 4x faster than pytorch  https://github.com/Oneflow-Inc/oneflow/

**Comment by Nourepide** [comment]
Settings -> Beta -> Save -> Restart
Settings -> Test Diffusers -> Save -> Restart

On 3050M 4Gb, DDIM, 20 Samples, 448x448
Default - 33s.
Test - 16s.

**Comment by laurentopia** [comment]
done! now i see the sampler choser
tested on a 4-parallel of the default astronaut on horse prompt
3.8it/s vs 6.4it/s on automatic's
gpu is a 2060rtx 6gb

**Comment by cmdr2** [comment]
@laurentopia Are you using xFormers with auto1111? You can try to enable xFormers with Easy Diffusion and see if that speeds things up for you - https://github.com/cmdr2/stable-diffusion-ui/wiki/xFormers

**Comment by JeLuF** [comment]
Ticket closed for inactivity
