### ISSUE TITLE
Seamless tiles repeating as selectable options

### ISSUE THREAD

**Issue by redregar** [easydiffusion/easydiffusion#1255]
Hi I really enjoy working with Easy Diffusion and would love if you could add a function for seamless tiles that can be repeated be integrate.

This could be by Ui option or by prompt( depends whats possible)

Here is an example that where someone has done it with stable diffusion: https://replicate.com/tommoore515/material_stable_diffusion

I have only a designer background so im not sure how or if it can be integrated. Midjourney has this function also already integrated. If there are some other easy ways to use it. I would love to hear.
Best redregar

**Comment by JeLuF** [comment]
Seamless tiles are available in the "Beta/Test Diffusers" branch and will become available once this branch is rolled out.

**Comment by JeLuF** [comment]
The option is now available as a regular feature of EasyDiffusion 3.0
