### ISSUE TITLE
Support Textual Inversions

### ISSUE THREAD

**Issue by Dexus** [easydiffusion/easydiffusion#1258]
**Is your feature request related to a problem? Please describe.**
Support for Textual Inversions (embeddings)

**Describe the solution you'd like**
In Stable Diffusion Automatic 1111 it is supported.

**Describe alternatives you've considered**
Automatic 1111

**Comment by Blueblizard** [comment]
Yes, i requested it too in february. It would be very useful.

**Comment by JeLuF** [comment]
Duplicate of #590 => Closed.

There is PR #1362 that implements embedding support.
