### ISSUE TITLE
CLIP FIX option

### ISSUE THREAD

**Issue by ollobrains** [easydiffusion/easydiffusion#1259]
A lot of models when merged get broken CLIP locations, there are scripts out there that can fix these broken clips, but none of them are compatible with easy diffusion UI, given we already have a model merge capability how hard would it be to introduce an option to Fix Broken CLIP Locations on a model

**Comment by JeLuF** [comment]
Clip Fix is available in the "Beta/Test Diffusers" branch and will become available once this branch is rolled out.

**Comment by JeLuF** [comment]
Clip Skip has been released as part of EasyDiffusion 3.0
