### ISSUE TITLE
Output is grey regardless of prompt or settings

### ISSUE THREAD

**Issue by DavisStanko** [easydiffusion/easydiffusion#1261]
**Describe the bug**
Whenever I hit "Make Image" it takes a few seconds to render but outputs a 512x512 picture of just the color grey. #807B78 to be specific. I'm running a 5700xt.

**To Reproduce**
1. run start.sh
2. click on make image
3. output is just grey

**Expected behavior**
I expect an image to be generated that is relevant to the prompt and isn't just grey.

**Screenshots**
![a_photograph_of_an_astronaut_riding_a_horse_S3377104915_St25_G7 5](https://github.com/cmdr2/stable-diffusion-ui/assets/65086944/45e8e001-b4ed-4113-a0bd-25c5e18460db)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser: Firefox
 - Version: 112.0.2
![image](https://github.com/cmdr2/stable-diffusion-ui/assets/65086944/b1915496-2cc7-4029-8eed-4dba24bebf79)

**Additional context**
The exact same image is produced regardless of prompt.

**Comment by JeLuF** [comment]
Can you try whether starting it via `FORCE_FULL_PRECISION=1 ./start.sh` fixes this?

**Comment by lostbow** [comment]
That fixed it for me, slows it down a bit but still faster than the CPU and it not working at all

**Comment by JeLuF** [comment]
Closed ticket due to inactivity.
