### ISSUE TITLE
Ошибка: Не удается загрузить веса из файла контрольной точки pytorch для 'D:\ED\profile\.cache\huggingface\hub\models--openai--clip-vit-large-patch14\snapshots\8d052a0f05efbaefbc9e8786ba291cfdf93e5bff\pytorch_model.bin ' на 'D:\ED\profile\.cache\huggingface\hub\models--openai--clip-vit-large-patch14\snapshots\8d052a0f05efbaefbc9e8786ba291cfdf93e5bff\pytorch_model.bin'. Если вы пытались загрузить модель PyTorch с контрольной точки TF 2.0, пожалуйста, установите from_tf=True.

### ISSUE THREAD

**Issue by threebackups** [easydiffusion/easydiffusion#1268]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser:
 - Version:

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

**Comment by threebackups** [comment]
Здравствуйте. Easy Diffusion выдает данную ошибку.
Ошибка: Не удается загрузить веса из файла контрольной точки pytorch для 'D:\ED\profile\.cache\huggingface\hub\models--openai--clip-vit-large-patch14\snapshots\8d052a0f05efbaefbc9e8786ba291cfdf93e5bff\pytorch_model.bin ' на 'D:\ED\profile\.cache\huggingface\hub\models--openai--clip-vit-large-patch14\snapshots\8d052a0f05efbaefbc9e8786ba291cfdf93e5bff\pytorch_model.bin'. Если вы пытались загрузить модель PyTorch с контрольной точки TF 2.0, пожалуйста, установите from_tf=True.

подскажите пожалуйста как решить?

**Comment by JeLuF** [comment]
Видаліть D:\ED\profile.cache\huggingface\hub\models--openai--clip-vit-large-patch14\snapshots\8d052a0f05efbaefbc9e8786ba291cfdf93e5bff\pytorch_model.bin і перезапустіть

**Comment by JeLuF** [comment]
No update within 4 weeks => closed for inactivity
