### ISSUE TITLE
Ubuntu WSL2 no detecting AMD GPU 6600

### ISSUE THREAD

**Issue by LiveRock** [easydiffusion/easydiffusion#1269]
**Describe the bug**
Ubuntu WSL2 no detecting AMD GPU 6600

**To Reproduce**
1. run ./start.sh

**Expected behavior**
Should be able to use "AMD GPU out of the box"

**Screenshots**
![image](https://github.com/cmdr2/stable-diffusion-ui/assets/211891/1dba8bce-c51a-4282-958c-53dd3e13d59a)

**Desktop (please complete the following information):**
 - OS: Ubuntu on WSL2
 - Browser: Edge
 - Version: 11

**Smartphone (please complete the following information):**
 Not tested

**Additional context**
AMD RX 6600 GPU

**Comment by JeLuF** [comment]
There is no AMD GPU support on Windows, this includes WSL. AMD GPU are only supported on native Linux.

**Comment by LiveRock** [comment]
ok, got it.
If I would to do a dual-boot, windows and Linux, which Linux distro has the least issues for Easy Diffusion 1-click install? Ubuntu, Mint, Fedora?

**Comment by JeLuF** [comment]
Closed ticket due to inactivity.
