### ISSUE TITLE
"Invalid value for '--port':"

### ISSUE THREAD

**Issue by XOVG** [easydiffusion/easydiffusion#1271]
After unexpected restet of the system (program was working) i have tried to start it again and in the console i get error: "Invalid value for '--port': 'Expecting' is not a valid integer."

- OS: Win11
 - Browser: Firefox 113.0.1

![error](https://github.com/cmdr2/stable-diffusion-ui/assets/133699127/03a6b68d-1d8b-4ce9-8c19-2cf662a0333a)

**Comment by JeLuF** [comment]
Can you please try to remove `C:\EasyDiffusion\scripts\config.json`?

**Comment by XOVG** [comment]
thank, now works!
