### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: '/proc/bus/pci/devices'

### ISSUE THREAD

**Issue by SamohtSirrom1** [easydiffusion/easydiffusion#1277]
**Describe the bug**
I am unable to finish installing the program do the fact that I do not have access to proc/bus/pci/devices, despite using root@localhost for the install chown username +wrx returns a don't have permission 

**To Reproduce**
All I did to get that error is run start.sh from the stable diffusion UI program

**Expected behavior**
I expected it to complete and then to be able to run stable diffusion.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Unbuntu canonical
 - Browser: LXDE
 - Version:22.04

**Smartphone (please complete the following information):**
 - Device: motorola_one_5G_ace
 - OS: Android 11
 - Browser Chrome
 - Version 7.1-rc1-release

**Additional context**
All I'm trying to do is get this thing installed, if I've managed to get this far surely there is a way to finish it.

**Comment by JeLuF** [comment]
What is the output of:
```sh
ls -ald / /proc /proc/bus /proc/bus/pci /proc/bus/pci/devices
echo ---
mount | grep proc
```

**Comment by JeLuF** [comment]
According to our discord discussion, the user is running Linux on their smartphone, which apparently doesn't have a PCI bus.

**Comment by JeLuF** [comment]
No update within 4 weeks => closed for inactivity

**Comment by SamohtSirrom1** [comment]
Honestly I thought my job was only to report to issue and then leave it to the experts to look over the information provided see if other people had the issue and work on a solution I didn't know I was required to continue troubleshooting with them but whatever close means close
