### ISSUE TITLE
Bad line ending characters in scripts under linux

### ISSUE THREAD

**Issue by devingfx** [easydiffusion/easydiffusion#1280]
**Describe the bug**
Bad line ending characters in scripts under linux, bash produces a `./start.sh: scripts/bootstrap.sh : /bin/bash^M : bad interpreter: ...`

**To Reproduce**
1. Download linux installer and follow instruction
2. Get the error
3. Comment in `scripts/on_env_start.sh` the lines that copies the fresh checkouted scripts
4. Correct line endings to be `LF`
5. The UI starts correctly
6. Shutdown and relaunch
7. Got to 2.

**Expected behavior**
Git EOL override for target OS, and/or correct pushed bash files EOL to LF

**Screenshots**
Not applicable

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Browser: Didn't get to the browser! :)
 - Version: Last

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

**Comment by JeLuF** [comment]
I wasn't able to reproduce this. 
Do you have any custom settings in your users's git config?

**Comment by devingfx** [comment]
I didn't at the time of writting issue, then I added `core.autocrlf=input` to get rid of the issue (as suggested on stackoverflow)...
I'm sorry for this lack of details but it was 2month ago and I can't remember exactly what I tested before that and I'm using A1111 now :/
