### ISSUE TITLE
No matching distribution found for sdkit==1.0.93

### ISSUE THREAD

**Issue by johnny710vip** [easydiffusion/easydiffusion#1282]
run bash start.sh

/usr/bin/curl
/bin/tar
/home/caros/WorkSpace1/wangyuan/SD/enter/envs/webui/bin/bzip2
/usr/bin/git
git version 2.17.1
/home/caros/WorkSpace1/wangyuan/tools/easy-diffusion/installer_files/env/bin/conda
conda 23.3.1

Easy Diffusion

Easy Diffusion's git repository was already installed. Updating from main..
HEAD is now at 4313166 Merge pull request #1275 from cmdr2/beta
Already on 'main'
Your branch is up to date with 'origin/main'.
Already up to date.
torch: 2.0.0
torchvision: 0.15.1
> python -m pip install --upgrade sdkit==1.0.93
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
ERROR: Could not find a version that satisfies the requirement sdkit==1.0.93 (from versions: 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.0.8, 1.0.9, 1.0.11, 1.0.12, 1.0.13, 1.0.14, 1.0.15, 1.0.16, 1.0.17, 1.0.18, 1.0.19, 1.0.20, 1.0.21, 1.0.22, 1.0.23, 1.0.24, 1.0.26, 1.0.27, 1.0.28, 1.0.29, 1.0.30, 1.0.31, 1.0.32, 1.0.33, 1.0.34, 1.0.35, 1.0.36, 1.0.37, 1.0.38, 1.0.39, 1.0.40, 1.0.41, 1.0.42, 1.0.43, 1.0.44, 1.0.45, 1.0.46, 1.0.47, 1.0.48, 1.0.49, 1.0.50, 1.0.51, 1.0.52, 1.0.53, 1.0.54, 1.0.55, 1.0.56, 1.0.57, 1.0.58, 1.0.59, 1.0.60, 1.0.61, 1.0.62, 1.0.63, 1.0.64, 1.0.65, 1.0.67, 1.0.68, 1.0.69, 1.0.70, 1.0.71, 1.0.72, 1.0.73, 1.0.74, 1.0.75, 1.0.76, 1.0.77, 1.0.78, 1.0.79, 1.0.80, 1.0.81, 1.0.82, 1.0.83, 1.0.84, 1.0.85, 1.0.86, 1.0.87, 1.0.88, 1.0.89, 1.0.90, 1.0.91)
ERROR: No matching distribution found for sdkit==1.0.93
sdkit: None
stable-diffusion-sdkit: 2.1.4
rich: 12.6.0
uvicorn: 0.19.0
fastapi: 0.85.1
Traceback (most recent call last):
  File "../scripts/check_models.py", line 3, in <module>
    from sdkit.models import download_model, get_model_info_from_db
ModuleNotFoundError: No module named 'sdkit'
Press any key to continue

**Comment by JeLuF** [comment]
You're using a PyPi mirror, https://pypi.tuna.tsinghua.edu.cn/simple.
Please contact them to check how often they update their mirror.
