### ISSUE TITLE
“> python -m pip install --upgrade sdkit==1.0.96 -q” doesn't work

### ISSUE THREAD

**Issue by ZZjm666** [easydiffusion/easydiffusion#1295]
> python -m pip install --upgrade sdkit==1.0.96 -q
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1106: The handshake operation timed out'))': /simple/sdkit/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1106: The handshake operation timed out'))': /simple/sdkit/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))': /simple/sdkit/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x00000201E5E008B0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))': /simple/sdkit/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x00000201E5E0FA60>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))': /simple/sdkit/
ERROR: Could not find a version that satisfies the requirement sdkit==1.0.96 (from versions: none)
ERROR: No matching distribution found for sdkit==1.0.96
sdkit: 1.0.35
stable-diffusion-sdkit: 2.1.4
rich: 12.6.0
uvicorn: 0.19.0
fastapi: 0.85.1
No module 'xformers'. Proceeding without it.
stable-diffusion model(s) found.
gfpgan model(s) found.
realesrgan model(s) found.
Traceback (most recent call last):
  File "..\scripts\check_models.py", line 57, in init
    download_if_necessary(model_type, model["file_name"], model["model_id"])
  File "..\scripts\check_models.py", line 40, in download_if_necessary
    expected_hash = get_model_info_from_db(model_type=model_type, model_id=model_id)["quick_hash"]
TypeError: 'NoneType' object is not subscriptable
Error downloading the vae model. Sorry about that, please try to:
1. Run this installer again.
2. If that doesn't fix it, please try to download the file manually. The address to download from, and the destination to save to are printed above this message.
3. If those steps don't help, please copy *all* the error messages in this window, and ask the community at https://discord.com/invite/u9yhsFmEkB
4. If that doesn't solve the problem, please file an issue at https://github.com/cmdr2/stable-diffusion-ui/issues
Thanks!

**Comment by JeLuF** [comment]
`ProxyError('Cannot connect to proxy.'`
There is a proxy configured on your system that Python wasn't able to connect to. Please check your proxy settings, including the http_proxy and https_proxy environment variables.
