### ISSUE TITLE
Special characters in file names prevent img2img from working

### ISSUE THREAD

**Issue by Salvatos** [easydiffusion/easydiffusion#1297]
**Describe the bug**
When a reference image has special characters in its file <strike>name</strike> extension (tested with parentheses), the interface shows the correct settings for img2img generation, but the jobs run in a different sampler than ddim (DPM_Fast in my case, which is the one I had been using previously) and disregard the reference image.

**To Reproduce**
1. Create a reference image with special characters in its <strike>name</strike> extension (tested with <strike>1 (copy).png</strike> `1.png (copy)`).
2. Attempt to run an img2img generation at a low prompt strength.
3. The corresponding job shows a different sampler than ddim and the resulting image doesn’t look anything like the reference.

**Expected behavior**
The job should run ddim by default.

**Desktop (please complete the following information):**
 - OS: Linux Mint 21.1
 - Browser: Firefox 113.0.1
 - Version: 2.5.38 (beta)

**Comment by JeLuF** [comment]
Are you using the Diffusers Tech Preview?
![image](https://github.com/cmdr2/stable-diffusion-ui/assets/5852422/fd2e2941-11ab-4697-abe2-3d41c32500f2)

**Comment by Salvatos** [comment]
Beta is on, Diffusers is off, but I have tested it before so it might have left something behind.

**Comment by JeLuF** [comment]
If you're not using the Diffusers test, the backend enforces DDIM. It's a display error. The actual scheduler used is always DDIM.

**Comment by Salvatos** [comment]
But if I use the same settings and the same source image with a different name, it makes a different image when the name contains parentheses, but consistently remakes the same image when it doesn’t.

Ah, I made a mistake in the above repro steps. The parentheses are actually _after_ the file extension. With parentheses before it, the error does not occur.

**Comment by cmdr2** [comment]
This was fixed a few versions ago, it was a reporting error. Please try the latest version and feel free to reopen if this continues to be a problem.
