### ISSUE TITLE
UI Freeze Upon Pasting Prompt

### ISSUE THREAD

**Issue by XenoTheStrange** [easydiffusion/easydiffusion#1324]
**Describe the bug**
Easy-Diffusion UI Freezes when this text is pasted into the prompt field:
"hyperrealistic full length portrait of gorgeous goddess | standing in field full of flowers | detailed gorgeous face!! | full body!! | skimpy armor | god rays | intricate | elegant | realistic | hyperrealistic | cinematic | character design | concept art | highly detailed | illustration | digital art | digital painting | depth of field"

Pasting part of the prompt and manually typing the rest also results in a freeze. I suspect the "|" has something to do with it.

**To Reproduce**
Paste the above prompt into the prompt field

**Expected behavior**
No immediate effects

**Desktop (please complete the following information):**
 - OS: KDE Neon (5.19.0-43-generic)
 - Browser: Librewolf
 - Version: Firefox 113.0.2-1

**Recording**
https://github.com/cmdr2/stable-diffusion-ui/assets/48196283/a0e7cc34-a018-4d1d-98c5-2255767cdaed

**Comment by ManInDark** [comment]
I believe the reason for the (temporary) UI freeze is that upon pasting the prompt (the number of) images that would be generated by it is calculated, which is in this case 131072 (if you generate one of every option). That's why I think that it's not a bug, but sort of intended behavior.

**Comment by JeLuF** [comment]
@XenoTheStrange In the EasyDiffusion browser tab, go to the "Help & Community" tab. Look for the "Writing prompts" link. The behaviour of the `|` character is described in the "Testing variations of prompts" section.

**Comment by cmdr2** [comment]
Maybe the code that calculates this should stop at 10000, and show "Generate 10000+ images".

I can't think of a good reason why someone would want to know that they're generating exactly 131072 images. The intent of this calculation is to warn a user if the prompt is going to make a LOT of images.

Showing the count as 10000+ should be enough to make someone think twice, and will avoid this hanging behavior.

**Comment by ManInDark** [comment]
I looked into the code a bit to try to figure out if I could implement that, and as with how it is currently built you could either stop the creation of all the prompts [here](https://github.com/easydiffusion/easydiffusion/blob/main/ui/media/js/utils.js#L135) by returning if `n_permutations` is larger than 10k or adding another option like [this](https://github.com/easydiffusion/easydiffusion/blob/main/ui/media/js/main.js#L1542-L1544) with `totalImages > 10000` which would probably not resolve the UI-Freezing problem.
The problem with the first solution is that it would prevent people who actually want to generate that many images (for whatever reason) from doing so.

> Maybe the code that calculates this should stop at 10000, and show "Generate 10000+ images"

This could be another option, to just pass another parameter that is false for calculating the amount of images that would be created and true if you actually click on create.

The underlying issue appears to be that at the moment, it is not possible to calculate the amount of images created without creating the prompts.

**Comment by cmdr2** [comment]
The number of prompts is probably a factor of the number of permutations, as well as the set operators (`{foo, bar}`).

**Comment by JeLuF** [comment]
> 2**(number of `"|"` characters) * Product( "number of commas + 1" for each pair of `"{}"`) * "number of images per batch"

That should provide a rough estimate (it's not exact since it makes a difference where the pairs of {} are placed), and is basically O(n) for n= _number of characters in the prompt_

If this is <10'000, compute the exact number of prompts. If it's bigger than 10'000, set the button text to "Make thousands of images"

```
prompt.match(/{[^}]*}/g).map((e) => e.match(/,/g).length+1).reduce( (p,a) => p*a, 1 ) * 2**prompt.match(/\|/g).length
```

**Comment by XenoTheStrange** [comment]
Thanks for the heads up, I didn't know exactly what the || operator did. I'll be more (precise) with prompts in the future and read up on the specifics in the mentioned area.

**Comment by cmdr2** [comment]
Thanks!
