### ISSUE TITLE
bug only cpu load

### ISSUE THREAD

**Issue by xalteropsx** [easydiffusion/easydiffusion#1327]
rtx 7900 xtx not found inside linux machine always use cpu load

**Comment by ManInDark** [comment]
Take a look at #115, the default installation does not – as far as I know – yet support AMD GPU's, but the modified one does.

**Comment by Nephiaust** [comment]
It does partially support it. but there is bad doco from AMD about what cards are supported and what not

**Comment by JeLuF** [comment]
> rtx 7900 xtx not found inside linux machine always use cpu load

@xalteropsx Please check whether your user is in the `video` and `renderer` groups.

**Comment by xalteropsx** [comment]
will check soon thnx for helping >.<

**Comment by Nephiaust** [comment]
> @JeLuF where is this video and renderer groups menu are?

What Linux flavour are you running?

You should be able to run `groups` to see what groups you are a member of.

**Comment by JeLuF** [comment]
For gfx1100 support (e.g. for the 7900), you need to replace the torch library with a newer version.
- Start `developer_console.sh`
- Run `python -m pip install --pre --upgrade torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/rocm5.5`
- If you have multiple GPUs (e.g. an embedded GPU in your APU), you may need to add `export HIP_VISIBLE_DEVICES=0`

**Comment by presentformyfriends** [comment]
Linux Mint 21.1 with rx6750XT not recognizing GPU at all and when trying to use CPU I get:

`on_sd_start.sh: line 82: 3234656 Killed                  uvicorn main:server_api --app-dir "$SD_UI_PATH" --port "$ED_BIND_PORT" --host "$ED_BIND_IP" --log-level error              | 0/25 [00:00<?, ?it/s]`

**Comment by JeLuF** [comment]
Closed due to OP inactivity
