### ISSUE TITLE
LoRA not loading from file

### ISSUE THREAD

**Issue by ManInDark** [easydiffusion/easydiffusion#1330]
**Describe the bug**
In case you are on the beta channel and have LoRA's enabled they are already written to the file created alongside the image file, but if you try to load them back in the LoRA field(s) are not set according to what is written in the loaded file.

**To Reproduce**
1. Create an image with an LoRA.
2. Try to load the .txt from the file created alongside the image from 1.
3. See error

**Expected behavior**
The LoRA field(s) should be set too.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Brave
 - Version: Beta Channel, Test Diffusers

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ManInDark** [comment]
I tried to find why it might not be working and found that the file is being read in in this [function](https://github.com/cmdr2/stable-diffusion-ui/blob/3045f5211f7aa9ea93b45ce08f4a6acb36e073ca/ui/media/js/dnd.js#L403) (I think at least) which should properly change it with this [bit](https://github.com/cmdr2/stable-diffusion-ui/blob/3045f5211f7aa9ea93b45ce08f4a6acb36e073ca/ui/media/js/dnd.js#L292C22-L309) of code, but that doesn't work as intended for some reason.

Although I'm not sure, I suspect there might be a problem with path escaping, as when manually inputting what was written to the file the \ were lost in translation. However, this still does not explain why the loraModelField.value is '', even after supposedly being set.

Another possible problem could be that [this function](https://github.com/cmdr2/stable-diffusion-ui/blob/3045f5211f7aa9ea93b45ce08f4a6acb36e073ca/ui/media/js/dnd.js#L485) removes the extension, which could lead to errors down the line, but wouldn't really explain why it's not shown in the UI.

Well anyway I did some digging but could not find a definite solution / problem at the moment.
Nothing happens either when calling the TASK_MAPPING['use_lora_model'].setUI function manually.

**Comment by DublinBen** [comment]
I can confirm that LoRAs are broken for me as well. In my terminal I can see these errors when trying to generate an image using a LoRA:

`18:03:09.684 ERROR cuda:0 Traceback (most recent call last):                                       lora.py:35
  File                                                                                                       
"/home/username/Downloads/easy-diffusion/installer_files/env/lib/python3.8/site-packages/sdkit/mo           
dels/model_loader/lora.py", line 33, in apply_lora_model                                                     
    _apply_lora(context, default_pipe, alpha)                                                                
  File                                                                                                       
"/home/username/Downloads/easy-diffusion/installer_files/env/lib/python3.8/site-packages/sdkit/mo           
dels/model_loader/lora.py", line 105, in _apply_lora                                                         
    weight.data += alpha * torch.mm(weight_up, weight_down).unsqueeze(2).unsqueeze(3)                        
RuntimeError: mat2 must be a matrix                                                                          
                                                                                                             
18:03:09.685 ERROR cuda:0 Could not apply LoRA!                                                    lora.py:36
18:03:09.760 INFO cuda:0 unloaded lora model from device: cuda:0                               __init__.py:64
`

**Comment by cmdr2** [comment]
Hi @DublinBen Can you please give me a link to where you downloaded that LoRA file from? And can you please try another LoRA file as well? Thanks

**Comment by DublinBen** [comment]
Here's the link to download the LoRA that is broken for me: https://civitai.com/models/98086?modelVersionId=104888

Switching to a different LoRA sometimes works, like this one: https://civitai.com/models/83402?modelVersionId=100306

**Comment by JeLuF** [comment]
With the release of EasyDiffusion 3.0, a lot of Lora issues have been fixed. Please update to the latest version and re-test these LORAs

**Comment by cmdr2** [comment]
Please reopen if this continues to be a problem.
