### ISSUE TITLE
windows installer exe file does not work

### ISSUE THREAD

**Issue by F-16Aircraft** [easydiffusion/easydiffusion#1334]
windows exe installer not starting or running on windows 11

**Comment by JeLuF** [comment]
Some versions of Windows 11 have restrictions which software can be installed: https://pureinfotech.com/enable-developer-mode-windows-11/

Please check whether the installer works in developer mode.

**Comment by F-16Aircraft** [comment]
i enabled developer mode and the program does not start on windows11, there are no errors that pop up.

**Comment by F-16Aircraft** [comment]
> Some versions of Windows 11 have restrictions which software can be installed: https://pureinfotech.com/enable-developer-mode-windows-11/
> 
> Please check whether the installer works in developer mode.

i tried this, it does not start,when i click on the the program, it asks for admin privelages, i click 'ok', a blue loading circle pops up for a few seconds, i am unable to click on anything for a few seconds(clicks become unresponsive) then it goes back to normal, no installer pops up. dont know what to do.

**Comment by JeLuF** [comment]
The installer does not need admin privileges, and doesn't ask for them. That's weird. Can you provide a screenshot of that popup?

**Comment by F-16Aircraft** [comment]
> The installer does not need admin privileges, and doesn't ask for them. That's weird. Can you provide a screenshot of that popup?

it stopped asking for admin privelages but now it just does nothing. not sure if its an issue specific with windows 11, but i cant get it to work unfortunately

**Comment by F-16Aircraft** [comment]
i just tried older versions of the installer and none of them appear to do anything on windows 11, gonna assume this is a windows11 issue. i guess ill wait til theres a fix.

**Comment by F-16Aircraft** [comment]
i never got it to work, but i was finally able to install easydiffusion successfully with AUTOMATIC1111.
