### ISSUE TITLE
Add an "Allow Auto-Update" button to let the user be in control of automatic updates

### ISSUE THREAD

**Issue by LxeC** [easydiffusion/easydiffusion#1340]
I was using the beta version because I really needed to use LoRAs, but a couple days ago it just stopped working altogether and had to wait for the issue to be resolved. 

Could there be an option in the settings that turns off auto-updates? Sometimes updates just break previously stable things. I do like receiving updates automatically, but I'd like to have more control over it without having to turn off my entire internet. So an option for that, that affects both stable and beta channel, would be ideal.

**Comment by cmdr2** [comment]
Hi @LxeC If you're using the beta version, it's going to be unstable by definition. I understand that LoRA is very useful, and we're working as fast as possible to get the new engine released to the main branch (i.e. to everyone). But at the moment, it's still got a few bugs and we're working on them.

I understand the desire for disabling auto-updates, but we're a very tiny team of developers working in our spare time, and it's just not possible for us to support all the various versions of Easy Diffusion in the wild (that will happen if people stop receiving updates). Especially in beta.

Lots of bugs are fixed and improvements are released several times a week, often several times a day. The whole field of Stable Diffusion is very new, and things are always changing rapidly.

If you want stability, I'd advise staying on the stable version, and just waiting a bit longer please for LoRA. We try to keep the "main" branch really stable, after testing changes in the "beta" branch as thoroughly as we can.

So at the moment, as much as I understand the desire for more control, this isn't something we can turn off for now. We don't have the resources as volunteers. Please stay on the main branch, as it's always kept stable and non-breaking (to our best efforts). Sorry about that.

Once things stabilize in the field of Stable Diffusion and the project becomes more mature, giving an option to disable auto-updates would make sense. Not yet.
