### ISSUE TITLE
 API mode

### ISSUE THREAD

**Issue by pilot138** [easydiffusion/easydiffusion#1346]
Good afternoon Please tell me how to run the program in API mode and is it possible to use Photoshope? Thanks in advance!

**Comment by JeLuF** [comment]
EasyDiffusion does not support Photoshop integration.

**Comment by cmdr2** [comment]
Hi @pilot138 We don't have a public-facing API. One option is to use sdkit directly (our engine) using Python - https://github.com/easydiffusion/sdkit
