### ISSUE TITLE
HTTPSConnectionPool(host='cdn-lfs.huggingface.co', port=443)

### ISSUE THREAD

**Issue by LilBtr** [easydiffusion/easydiffusion#1347]
HTTPSConnectionPool(host='cdn-lfs.huggingface.co', port=443): Max retries exceeded with url: /openai/clip-vit-large-patch14/f1a17cdbe0f36fec524f5cafb1c261ea3bbbc13e346e0f74fc9eb0460dedd0d3?response-content-disposition=attachment%3B+filename*%3DUTF-8%27%27pytorch_model.bin%3B+filename%3D%22pytorch_model.bin%22%3B&response-content-type=application%2Foctet-stream&Expires=1687022495&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9jZG4tbGZzLmh1Z2dpbmdmYWNlLmNvL29wZW5haS9jbGlwLXZpdC1sYXJnZS1wYXRjaDE0L2YxYTE3Y2RiZTBmMzZmZWM1MjRmNWNhZmIxYzI2MWVhM2JiYmMxM2UzNDZlMGY3NGZjOWViMDQ2MGRlZGQwZDM~cmVzcG9uc2UtY29udGVudC1kaXNwb3NpdGlvbj0qJnJlc3BvbnNlLWNvbnRlbnQtdHlwZT0qIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjg3MDIyNDk1fX19XX0_&Signature=0WMchIYC7KofA-Xscz8TRKQpgV-IbpaNubfA5kSQkNmAVF40kCjOKCWMYiKscIONIq3iDy6HsrGjE2UTw4elsqzLV9wm8eJv56M-fB~--JJ7RAmxZJSRHKE~VufLlC1r6VzJUp~sj3Y0gwtEZ9UjQ1xq6Iu-OKci3bbpKUMVwDcxu~RuGKv0maqV6~dgbavHVfe8FiN~ElBgdGaZl~QUOGin8vJp1u1S0hRNKmtLxB1463zM~WpPROXuEijheuk0TDS5OHXOM37LNdHH~~RfyQmWa-EhYb4T5vocQxtDmC9M7pO~Vhtcbo7QB6z8qKmJ2WirsWDAR6Oa~0u2Z8bMYQ__&Key-Pair-Id=KVTP0A1DKRTAX (Caused by NewConnectionError(': Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))

how to solve this ?

**Comment by JeLuF** [comment]
Please check your network settings. Something is preventing your system from connecting to `cdn-lfs.huggingface.co`. This could be the Windows firewall, anti-malware, VPN providers, etc.
