### ISSUE TITLE
Web UI not accessible via LAN

### ISSUE THREAD

**Issue by felixmc** [easydiffusion/easydiffusion#1350]
I'm running EasyDiffusion on my desktop PC computer running Windows 11 Home edition.
Things work great, I access the web UI via localhost:9000.

However, I would love it if I could access the web UI from my laptop on my home network.
In EasyDiffusion settings, I have "Make Stable Diffusion available on your network" turned on, and at the bottom it shows that I should be able to access it via the LAN address 192.168.1.200:9000, which matches my desktop PC's IP address.

However, when I try to go to that URL, either from my PC or another computer on my LAN, it is not accessible (get connection refused error, essentially saying nothing is listening on that port).

Here's some things I tried:
1. confirmed I can ping my desktop PC from my other laptops, so they can see each other
2. Went into Windows Firewall turned on inbound TCP port 9000
3. Tried turning off Windows Firewall completely, and restarted the PC, which had no effect, which leads me to believe it's not an issue with Windows blocking the port
4. Restarted both computers several times between trying different things

I run another webserver on my LAN (raspberrypi media center), and that is accessible from both the PC and the Macbook, so I don't think it's some LAN fuckery.

If I run `netstat -aon` in PowerShell on my Windows computer, I can see TCP 127.0.0.1:9000 listed as LISTENING, but not 192.168.1.200:9000, which makes me think that maybe EasyDiffusion is only listening on localhost and not the LAN address as well?  But not sure if I'm misinterpreting that, my Windows-foo is a little rusty.

This all makes me think it's either something specific with my Windows machine or a bug in the EasyDiffusion web server (whether a windows bug or a general one).

I would appreciate any help resolving this issue.  I'm a software engineer, I've run webservers on Windows in the past (though admittedly not in a long time), so feel free to be as technical as necessary or send any technical documentation my way.
I would also be happy to try to solve this bug myself if it is a bug, if someone could point me in the general direction of the relevant code in the repo.

**Comment by felixmc** [comment]
So I digged around the code a little bit and eventually found that the settings the web server uses are stored in a `config.json`  in the `scripts/` directory.  I was able to add `"net": {"listen_to_network": true}` in the config file, restart EasyDiffusion and now the web server is properly listening on the LAN address.

This workaround fixes my issue, but I believe that this is still a bug with EasyDiffusion, likely the UI is not saving the setting correctly or something along those lines?  So I will keep the issue open for that to be resolved.

I tried to see if I could find the UI/config bug myself, but couldn't quite figure it out.

**Comment by JeLuF** [comment]
You're right, there's a bug. It will be fixed by PR #1357

**Comment by exander77** [comment]
I restarted the app today and stopped listening on network.

**Comment by cmdr2** [comment]
This change has been released to the main branch, can you please try again? Thanks

**Comment by JeLuF** [comment]
Closed due to inactivity
