### ISSUE TITLE
easy diffusion keeps downloading large files in every request, why?

### ISSUE THREAD

**Issue by alfabill** [easydiffusion/easydiffusion#1351]
With every single request the amount of time with cpu device reaches the 30 minutes or above

**To Reproduce**
any operation gives this behavior, text prompt, img2img, etc

**Screenshots**

**Desktop (please complete the following information):**
 - OS:  Centos 7
 - Browser: Chrome
 - Version: 101

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

**Comment by cmdr2** [comment]
Hi @alfabill We'll need the logs to investigate, to understand which file it's trying to download.

Can you please share the full logs from the black-and-white command prompt window? Please start Easy Diffusion, generate an image, and share the logs from the time Easy Diffusion starts till the time it starts generating the image.

BTW, the CPU mode is very slow. It's common for the CPU to take about 20 minutes to generate a single image, on regular PCs. It doesn't need to download anything, the CPU mode is just very slow.

Stable Diffusion is designed for graphics cards (which can generate an image in 5 to 10 seconds), and the CPU mode is just an alternative for users without graphics cards.

Thanks!
