### ISSUE TITLE
The model for Stable Diffusion has not been loaded yet! How to fix?

### ISSUE THREAD

**Issue by changle-li** [easydiffusion/easydiffusion#1352]
Install dir: C:\EasyDiffusion\
C:\Program Files\Git\cmd\git.exe
git version 2.40.0.windows.1
C:\EasyDiffusion\installer_files\env\Library\bin\conda.bat
C:\EasyDiffusion\installer_files\env\Scripts\conda.exe
conda 22.11.1

"Easy Diffusion - v2"

"Easy Diffusion's git repository was already installed. Updating from main.."
HEAD is now at 6158f49 Workaround to fix the broken Rabbit Hole plugin
Already on 'main'
Your branch is up to date with 'origin/main'.
fatal: unable to access 'https://github.com/cmdr2/stable-diffusion-ui.git/': Recv failure: Connection was reset
493 File(s) copied
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
A subdirectory or file tmp already exists.

Hotfixed broken JSON file from OpenAI
"torch and torchvision have already been installed."
"sdkit is already installed."
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /simple/sdkit/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /simple/sdkit/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /simple/sdkit/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /simple/sdkit/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /simple/sdkit/
ERROR: Could not find a version that satisfies the requirement sdkit==1.0.43 (from versions: none)
ERROR: No matching distribution found for sdkit==1.0.43
"Error updating sdkit"
sdkit version: 1.0.35
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /simple/stable-diffusion-sdkit/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /simple/stable-diffusion-sdkit/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /simple/stable-diffusion-sdkit/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /simple/stable-diffusion-sdkit/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /simple/stable-diffusion-sdkit/
ERROR: Could not find a version that satisfies the requirement stable-diffusion-sdkit==2.1.3 (from versions: none)
ERROR: No matching distribution found for stable-diffusion-sdkit==2.1.3
"Error updating stable-diffusion-sdkit"
stable-diffusion version: 2.1.1
"rich has already been installed."
"Packages necessary for Easy Diffusion were already installed"
"Data files (weights) necessary for Stable Diffusion were already downloaded. Using the HuggingFace 4 GB Model."
"Data files (weights) necessary for GFPGAN (Face Correction) were already downloaded"
"Data files (weights) necessary for ESRGAN (Resolution Upscaling) x4plus were already downloaded"
"Data files (weights) necessary for ESRGAN (Resolution Upscaling) x4plus_anime were already downloaded"
"Data files (weights) necessary for the default VAE (sd-vae-ft-mse-original) were already downloaded"

"Easy Diffusion installation complete! Starting the server!"

PYTHONPATH=C:\EasyDiffusion\installer_files\env\lib\site-packages
C:\EasyDiffusion\installer_files\env\python.exe
C:\Users\chang\AppData\Local\Programs\Python\Python310\python.exe
C:\Users\chang\AppData\Local\Microsoft\WindowsApps\python.exe
Python 3.8.5
No module 'xformers'. Proceeding without it.
23:41:43.699 INFO MainThread started in C:\EasyDiffusion\stable-diffusion                                   server.py:19
23:41:43.704 INFO MainThread started at 06/16/23 23:41:43                                                   server.py:20
23:41:43.883 INFO MainThread Scanned 3 models. Nothing infected                                     model_manager.py:248
23:41:43.976 INFO MainThread Start new Rendering Thread on device: cuda:0                            task_manager.py:454
23:41:45.480 INFO cuda:0 Setting cuda:0 as active, with precision: half                            device_manager.py:134
23:41:45.483 INFO cuda:0 loading stable-diffusion model from                                              __init__.py:22
C:\EasyDiffusion\models\stable-diffusion\sd-v1-4.ckpt to device: cuda:0
23:41:46.719 INFO cuda:0 using config:                                                                    __init__.py:45
C:\EasyDiffusion\installer_files\env\lib\site-packages\sdkit\models\models_db\configs\v1-inference.yaml
23:41:46.739 INFO cuda:0 using attn_precision: fp16                                                       __init__.py:51
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
23:41:51.351 ERROR cuda:0 Error while loading stable-diffusion model:                                model_manager.py:45
C:\EasyDiffusion\models\stable-diffusion\sd-v1-4.ckpt
23:41:51.352 ERROR cuda:0 Error: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries   model_manager.py:46
exceeded with url: /openai/clip-vit-large-patch14/resolve/main/vocab.json (Caused by
ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))
23:41:51.354 ERROR cuda:0 Consider removing the model from the model folder.                         model_manager.py:47
23:42:05.549 INFO cuda:0 Session 1686930106876 starting task 2603783822640 on NVIDIA GeForce RTX     task_manager.py:312
3060
23:42:05.553 INFO cuda:0 request: {'guidance_scale': 7.5,                                                 renderer.py:51
 'height': 512,
 'hypernetwork_strength': 0,
 'negative_prompt': '',
 'num_inference_steps': 25,
 'num_outputs': 1,
 'preserve_init_image_color_profile': False,
 'prompt': 'a photograph of an astronaut riding a horse',
 'sampler_name': 'euler_a',
 'seed': 6876273,
 'width': 512}
23:42:05.555 INFO cuda:0 task data: {'block_nsfw': False,                                                 renderer.py:52
 'metadata_output_format': 'none',
 'output_format': 'jpeg',
 'output_quality': 75,
 'request_id': 2603783822640,
 'save_to_disk_path': 'C:\\Users\\chang\\Pictures\\StableDiffusion',
 'session_id': '1686930106876',
 'show_only_filtered_image': True,
 'stream_image_progress': False,
 'stream_image_progress_interval': 5,
 'upscale_amount': 4,
 'use_face_correction': None,
 'use_hypernetwork_model': None,
 'use_stable_diffusion_model': 'C:\\EasyDiffusion\\models\\stable-diffusion\\sd-v1-4.ckpt',
 'use_upscale': None,
 'use_vae_model': None,
 'vram_usage_level': 'balanced'}
23:42:05.558 INFO cuda:0 Global seed set to 6876273                                                           seed.py:65
23:42:05.569 ERROR cuda:0 Traceback (most recent call last):                                         task_manager.py:346
  File "C:\EasyDiffusion\ui\easydiffusion\task_manager.py", line 336, in thread_render
    task.response = renderer.make_images(
  File "C:\EasyDiffusion\ui\easydiffusion\renderer.py", line 38, in make_images
    images, seeds = make_images_internal(req, task_data, data_queue, task_temp_images,
step_callback)
  File "C:\EasyDiffusion\ui\easydiffusion\renderer.py", line 59, in make_images_internal
    images, user_stopped = generate_images_internal(
  File "C:\EasyDiffusion\ui\easydiffusion\renderer.py", line 91, in generate_images_internal
    images = generate_images(context, callback=callback, **req.dict())
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\sdkit\generate\image_generator.py",
line 47, in generate_images
    raise RuntimeError("The model for Stable Diffusion has not been loaded yet! If you've tried to
load it, please check the logs above this message for errors (while loading the model).")
RuntimeError: The model for Stable Diffusion has not been loaded yet! If you've tried to load it,
please check the logs above this message for errors (while loading the model).

23:42:05.676 INFO cuda:0 Session 1686930106876 task 2603783822640 failed!                            task_manager.py:355

**Comment by JeLuF** [comment]
> WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /simple/sdkit/

You have a network proxy configured on your system that is not reachable any more. Please remove this proxy configuration or ensure that the proxy is reachable.
