### ISSUE TITLE
Error: CUDA out of memory..

### ISSUE THREAD

**Issue by 19woody63** [easydiffusion/easydiffusion#1353]
Hi all. Can anyone here tell me why when I switch from GPU to CPU, I still get an error "Error: CUDA out of memory.." As far as I understand, if the CPU is enabled, then the video card no longer matters. The picture is generated through the CPU very slowly, but still generated. And what about CUDA? This happens when the image 768X512 is upscaled by Latent Upscaler 2x, Upscaling Steps 20
video card GPU 4.00 GiB.  Can anyone provide an explanation? Thanks in advance.

**Comment by JeLuF** [comment]
The switch to enable CPU mode is in the Settings tab of the Easy Diffusion web interface.

CUDA is the programming interface of your GPU. If you disable GPU support, you will not use CUDA any more.

The latent upscaler is using stable diffusion for upscaling, which requires a lot of GPU memory for a resolution of 1536*1024. The RealESRGAN upscalers are using less GPU memory and should be preferred with a 4GB GPU.

**Comment by JeLuF** [comment]
Closed due to inactivity
