### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Zhi2609** [easydiffusion/easydiffusion#1356]
Suggestions to improve things a bit, seen from my point of view as a user.

- Add something similar to what A1111 uses with the models (Checkpoints, Lora) a list where you can put preview images of all the models you have.

- To be able to use multiple Lora: considering that there are Loras that are for characters, clothes, poses, places, etc. It would be better to add that you can use multiple Lora to improve your work, maybe using something like the Lora tags (<lora:subaru_shuba-06:1>).

- Support for LyCORIS

Just suggestions, I don't know if you are already doing it or have it planned for the future, but I still put it.
Thank you very much for your work.

**Comment by Innomen** [comment]
Seconded. Came looking for how to use poses. I guess I can't yet?

**Comment by JeLuF** [comment]
Multiple LORA support and Poses have been added in EasyDiffusion 3.0

**Comment by Innomen** [comment]
Holy crap! Downloading! Thank you!

**Comment by cmdr2** [comment]
Tracking lycoris in this issue https://github.com/easydiffusion/easydiffusion/issues/1434
