### ISSUE TITLE
Get rid of the unnecessary safety checker, occupying over 1Gb on system drive

### ISSUE THREAD

**Issue by Seedmanc** [easydiffusion/easydiffusion#1358]
**Is your feature request related to a problem? Please describe.**
 _I'm always frustrated when_ I have to deal with censorship and compulsory safety filters when generating online, so the last thing I expected is having to pay in free space for the functionality I don't need.

**Describe the solution you'd like**
Do not redownload the "CompVis--stable-diffusion-safety-checker" if it was disabled in settings or at the very least don't make its absence fatal for generation. A mere warning would be enough.

**Describe alternatives you've considered**
EasyDiffusion already writes plenty of huge files to user profile, I'd expect the "one-click installer" it claims to be, to be self-contained within its own folder. It can be fixed manually through junctions though.

**Comment by cmdr2** [comment]
Hi @Seedmanc The safety checker model is only downloaded the first time it is actually used, it isn't downloaded automatically.

I just looked through the code again to confirm. So I think your installation has enabled the "Block NSFW" setting at some point, for which it'll have to download the model.

If you don't need NSFW filtering, please feel free to delete the `CompVis--stable-diffusion-safety-checker` model folder.
