### ISSUE TITLE
After the latest update - The server is not available

### ISSUE THREAD

**Issue by KingAlMoore** [easydiffusion/easydiffusion#1359]
**Describe the bug**

**To Reproduce**
1. Run the Start Stable Diffusion UI.cmd file
2. Wait for the ui to load
3. Look at the message in the upper right corner of the ui, yellow text (Stable Diffusion is starting.)
4. Waited for 30 mins, this never goes to Stable Diffusion is running... Green text

**Expected behavior**
Prior to the last update, the message would turn green...

**Screenshots**

**Desktop (pleas
![Screenshot 2023-06-20 094250](https://github.com/easydiffusion/easydiffusion/assets/62607196/0c9a97dd-65d7-4822-8586-ddc289cedaa4)
e complete the following information):**
 - OS: Windows 11 Pro - 22621.1848
 - Browser: Google
 - Version: 114.0.5735.134 (Official Build) (64-bit)

**Additional context**
This only started after I got the last update... Usually start it offline, but this time I started while connected to the internet, it downloaded the updates successfully, then when it started, I got a message stating it could not login to the server in a red div tag at the top of the UI.

**Comment by JeLuF** [comment]
> I got a message stating it could not login to the server in a red div tag at the top of the UI.

Can you please show a screenshot of this message? It's not visible in the provided screenshot.

Additionally, can you please attach the content of the Easy Diffusion command window? On Windows 10, you can copy the content of this window with these 6 clicks:
![image](https://github.com/easydiffusion/easydiffusion/assets/5852422/5865119e-dec5-4d1f-b2bf-74a7fd2e7c86)

**Comment by naweka** [comment]
same problem. After run it try run PLMS and crash after a minute (no errors)
windows 10 21h2 x64

**Comment by yonker3445** [comment]
Same issue, works when a fresh install is used.  After close and restart it waits on the yellow "Stable Diffusion is starting." message without turning green.

Here is my command window:

Install dir: C:\EasyDiffusion\
C:\EasyDiffusion\installer_files\env\Library\bin\git.exe
git version 2.41.0.windows.1
C:\EasyDiffusion\installer_files\env\Library\bin\conda.bat
C:\EasyDiffusion\installer_files\env\Scripts\conda.exe
conda 22.11.1

"Easy Diffusion - v2"

"Easy Diffusion's git repository was already installed. Updating from main.."
HEAD is now at 8ced5b71 Merge pull request #1344 from easydiffusion/beta
Already on 'main'
Your branch is up to date with 'origin/main'.
Already up to date.
499 File(s) copied
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
A subdirectory or file tmp already exists.
torch: 1.13.1+cu116
torchvision: 0.14.1+cu116
sdkit: 1.0.106
stable-diffusion-sdkit: 2.1.4

"Easy Diffusion installation complete! Starting the server!"

PYTHONPATH=C:\EasyDiffusion\installer_files\env\lib\site-packages
C:\EasyDiffusion\installer_files\env\python.exe
C:\Python311\python.exe
C:\Users\daryn\AppData\Local\Microsoft\WindowsApps\python.exe
Python 3.8.5
No module 'xformers'. Proceeding without it.
20:51:08.723 INFO MainThread started in C:\EasyDiffusion\stable-diffusion                                   server.py:20
20:51:08.731 INFO MainThread started at 06/25/23 20:51:08                                                   server.py:21
stable-diffusion model(s) found.
gfpgan model(s) found.
realesrgan model(s) found.
vae model(s) found.
20:51:08.747 INFO MainThread Scanning all model folders for models...                               model_manager.py:370
20:51:08.895 INFO MainThread Scanned 8 models. Nothing infected                                     model_manager.py:379
20:51:08.968 INFO MainThread Start new Rendering Thread on device: cuda:0                            task_manager.py:467
20:51:09.683 INFO cuda:0 Device usage during initialization:                                              renderer.py:48
20:51:09.690 INFO cuda:0 CPU utilization: 20.5%, System RAM used: 7.6 of 32.0 GiB, GPU RAM used       memory_utils.py:44
(cuda:0): 1.0 of 6.0 GiB (peak: 0.0 GiB)
20:51:09.693 WARNING cuda:0 forcing full precision on this GPU, to avoid green images. GPU         device_manager.py:150
detected: NVIDIA GeForce GTX 1660
20:51:09.696 INFO cuda:0 Setting cuda:0 as active, with precision: full                            device_manager.py:154
20:51:09.698 INFO cuda:0 loading stable-diffusion model from                                              __init__.py:36
C:\EasyDiffusion\models\stable-diffusion\sd-v1-4.ckpt to device: cuda:0
╭────────────────────────────────────────────── Easy Diffusion is ready ───────────────────────────────────────────────╮
│                                                                                                                      │
│ Easy Diffusion is ready to serve requests.                                                                           │
│                                                                                                                      │
│ A new browser tab should have been opened by now.                                                                    │
│ If not, please open your web browser and navigate to http://localhost:9000/                                          │
│                                                                                                                      │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
20:51:11.347 INFO cuda:0 using config:                                                                    __init__.py:75
C:\EasyDiffusion\installer_files\env\lib\site-packages\sdkit\models\models_db\configs\v1-inference.yaml
20:51:11.377 INFO cuda:0 using attn_precision: fp32                                                       __init__.py:81
20:51:11.396 INFO AnyIO worker thread Scanning all model folders for models...                      model_manager.py:370
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
20:51:19.660 INFO cuda:0 VRAM Optimizations: {'KEEP_FS_AND_CS_IN_CPU', 'SET_ATTENTION_STEP_TO_16'}   optimizations.py:26
20:51:20.674 INFO cuda:0 Global seed set to 42                                                                seed.py:65
Sampling:   0%|                                                                                  | 0/1 [00:00<?, ?it/s]20:51:22.637 INFO cuda:0 seeds used = [42]                                                            sampler_main.py:64
Data shape for PLMS sampling is (1, 4, 8, 8)
Running PLMS Sampling with 1 timesteps
PLMS Sampler: 100%|██████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.12s/it]
Sampling: 100%|██████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.41s/it]
20:51:24.311 INFO cuda:0 loaded stable-diffusion model from                                               __init__.py:40
C:\EasyDiffusion\models\stable-diffusion\sd-v1-4.ckpt to device: cuda:0

**Comment by yonker3445** [comment]
Found work-around:

In the browser navigate to the "Settings" tab
Set the network port to something else (For Example: 9200)
Click "Save"
Close the browser AND the Command window
Re-open using "Start Stable Diffusion UI.cmd" in the Easy Diffusion main folder
The browser will re-open and attempt to go to "http://localhost:9000/"
Change this to the port you chose "http://localhost:9200/"
The yellow "Stable Diffusion is starting" will turn to "Stable Diffusion is ready"

**Comment by CodeMaster2012** [comment]
Control shift R does the trick. Thank you :-)

**Comment by JeLuF** [comment]
Closed due to OP inactivity
