### ISSUE TITLE
Seems the latest update broke something

### ISSUE THREAD

**Issue by ex479** [easydiffusion/easydiffusion#1360]
**Describe the bug**
After changing models, sometimes even changing loras, a blue crappy image is generated (sometimes it's yellow or gray). Switching the memory setting (to low or high) seems to fix this weird behavior, but only until the next model change. 

**To Reproduce**
I'm not sure if this bug is always reproduced, but you can try to enable clip skip, change the current model and lora model with balanced or high memory settings. All other options such as codeformer, upscaling, preview etc are disabled. VAE: None

**Expected behavior**
Generating images with the same parameters should give the same result regardless of memory settings.

**Desktop (please complete the following information):**
 - OS: Windows 7 x64 
 - Browser: Chrome 109.0.5414.120 64 bit
 - Version: Test Diffusers 2.5.41 (beta) - 20 Jun 2023

**Additional context**
1080Ti 11Gb RAM (1 GPU cuda:0), xformers module is enabled (cuda: 11.8), fp32: enabled
I can assume that something from previous models remains in memory and is not released

**Comment by JeLuF** [comment]
Neither Windows 7 nor xformers are supported environments.

What do you mean by "fp32: enabled"?

**Comment by ex479** [comment]
> Neither Windows 7 nor xformers are supported environments.
> 
> What do you mean by "fp32: enabled"?
I mean @set FORCE_FULL_PRECISION=T

Does it mean that if xformers are suddenly no longer supported with test diffusers, I can turn them off and not lose anything in terms of memory optimization? On the same version 2.5.41, but a day earlier, everything worked perfectly with the same configuration and I didn't have to switch the memory mode in the settings to reset something.

**Comment by ex479** [comment]
It looks like this bug only appears when lora is applied. loRA settings are applied only for the first time, but on subsequent attempts, loRA is in fact not applied at all. Later, if you remove the loRA, the model may not be generated correctly, as if that loRA is subtracted or something like that (just my guess). Changing memory settings resets everything, so it allows you to make the program work as expected.

**Comment by ex479** [comment]
I came up with the idea that if the loRA does not cease to be applied, but simply subtracted at a size of 1. I compared the images at values less than 1, and then when the loRA broke again (by changing the clip setting or the memory setting), I tried to apply the same value, but 1 more (eg 1.54 instead of 0.54). The result at 1.54 with a broken loRA turned out exactly the same as it was at 0.54

**Comment by DublinBen** [comment]
I can also confirm that a recent update broke LORAs somehow. I am experiencing the same garbage single color output when trying to generate images. After startup, my terminal output mentions `sdkit: 1.0.112`. I can confirm this was working on earlier versions like `1.0.106`.

**Desktop (please complete the following information):**

-     OS: Ubuntu 22.04.02 LTS
-     Browser: Firefox 114.0.2
-     Version: Test Diffusers 2.5.41 (beta) - 20 Jun 2023 
-     GPU: AMD Radeon RX 6700 XT

**Comment by JeLuF** [comment]
> I came up with the idea that if the loRA does not cease to be applied, but simply subtracted at a size of 1. I compared the images at values less than 1, and then when the loRA broke again (by changing the clip setting or the memory setting), I tried to apply the same value, but 1 more (eg 1.54 instead of 0.54). The result at 1.54 with a broken loRA turned out exactly the same as it was at 0.54

A fix for "not applying LORA files correctly after model changes" has been deployed. Can you please test whether it works as expected again.

**Comment by ex479** [comment]
> A fix for "not applying LORA files correctly after model changes" has been deployed. Can you please test whether it works as expected again.

Looks like the bug has been fixed. I don't notice problems with lora anymore.

However, I accidentally noticed a small issue while testing - switching from img2img to txt2img (when deleting the original image), does not reset some settings (perhaps the number of steps, or maybe the method itself), which causes the generation of an incorrect picture for the first time after that.

**Comment by DublinBen** [comment]
Running the latest version (2dfa482b) I no longer get the single color broken image problem. 

Now, after trying different combinations of models and LoRAs, it seems that they are just not being applied at all. Enabling, disabling, any strength level have no effect on image generation.

**Comment by DublinBen** [comment]
I can clearly see in the terminal logs now that running a generation with a LoRA is incorrectly applying the LoRA strength of run 1 as a negative value for run 2, which really messes things up.

```
10:29:50.894 INFO cuda:0 Applying LoRA..                  image_generator.py:255
Applying lora -0.0
Applying lora 0.5
```

**Comment by JeLuF** [comment]
It needs to do this. Let's assume you have a model ℳ and a lora ℒ. When the Lora get's applied to the model with strength 𝛼 for the first image generation, it gets added to the model:
ℳ := ℳ + 𝛼 ℒ
If you want to use strength 𝛽 for the second image generation, you only need to apply (𝛽-𝛼)ℒ. To avoid rounding issues with floating point numbers, it makes sense to subtract 𝛼 ℒ before applying 𝛽ℒ:
ℳ := ℳ - 𝛼 ℒ + 𝛽ℒ

**Comment by ex479** [comment]
> It needs to do this. Let's assume you have a model ℳ and a lora ℒ. When the Lora get's applied to the model with strength 𝛼 for the first image generation, it gets added to the model:
> ℳ := ℳ + 𝛼 ℒ
> If you want to use strength 𝛽 for the second image generation, you only need to apply (𝛽-𝛼)ℒ. To avoid rounding issues with floating point numbers, it makes sense to subtract 𝛼 ℒ before applying 𝛽ℒ:
> ℳ := ℳ - 𝛼 ℒ + 𝛽ℒ

What if I have doubts that the model will not lose anything by subtracting, for example, 2𝛼, before 0.5𝛽 is applied to it? How can I force an entire model to be reloaded?

**Comment by JeLuF** [comment]
Closed due to inactivity
