### ISSUE TITLE
Plugins tab missing after updating EasyDiffusion

### ISSUE THREAD

**Issue by cmdrgrunt** [easydiffusion/easydiffusion#1367]
**Describe the bug**
Easy Diffusion updated this morning and made quite a few changes, now the plugins tab has disappeared and my UI plugins have unloaded. I am on the beta branch.

**To Reproduce**
1. Be on the beta branch
2. Launch Easy Diffusion and allow it to update
3. A new splash screen describing upcoming features about diffusers tech preview appears in the web-ui.
4. Notice the UI plugins tab has disappeared and plugins have been unloaded.

**Expected behavior**
Expected to see the Plugins tab and continue using plugins. There are no notes about plugins being disabled.

**Screenshots**
![easydiffusion_missing_plugin](https://github.com/easydiffusion/easydiffusion/assets/137791079/dc19d681-5e8e-4ede-a3b9-3c4967039799)

**Desktop (please complete the following information):**
 - OS: Windows 10 22H2
 - Browser: Edge  114.0.1823.43

**Additional context**
I'm usually checking for updates fairly often, my last check was sometime the day before, and I just checked again which is when the update happened and I lost the plugins tab.

Thanks!

**Comment by cmdr2** [comment]
Hi @cmdrgrunt The plugins tab should be back (as of 16 hours ago), it was a bug. Thanks for the report!
