### ISSUE TITLE
ai qr 

### ISSUE THREAD

**Issue by zartan9** [easydiffusion/easydiffusion#1371]
hi im new to this- but im following qr code tutorials for stable diffusion but its not working in easydiffusion, is there something special i have to do to your knowledge?  this qr/ai world is exciting!

**Comment by cmdr2** [comment]
Hi @zartan9 Unfortunately that isn't supported in Easy Diffusion yet.

**Comment by zartan9** [comment]
ahh thank you!!! I was thinking maybe i followed the tutorials wrong. ok keep me posted thanks.
