### ISSUE TITLE
Disable Pull-To-Refresh for mobile browsers via css function

### ISSUE THREAD

**Issue by cmdrgrunt** [easydiffusion/easydiffusion#1372]
**Is your feature request related to a problem? Please describe.**
I want to compliment the contributors on how friendly the UX is on mobile devices in addition to the desktop experience. For the most part out of box the tool is very usable.

The most destructive issue I run in to is by scrolling and pinch-zooming in and out of the queue, outputs, etc I very often trigger the "pull-to-refresh" action which wipes out the queue and work I've been doing. Even pinching to reset the size of the page width can set it off especially on the mobile Firefox browser.

**Describe the solution you'd like**
I understand there may be a way to override overscroll and pull-to-refresh behavior via css.

**Describe alternatives you've considered**
I've looked for ways to disable the pull-to-scroll behavior on a browser level and for example, on iOS Firefox does not expose the toggle! Alternatively I've been trying to be very careful with my finger movements and religiously checking that easydiffusion's remember settings have "stuck"

**Additional context**
Here is a resource from google that talks about the css "overscroll-behavior" function. Take a look at the "Disabling pull-to-refresh" code which could be placed at the body or html section.

[https://developer.chrome.com/blog/overscroll-behavior/](https://developer.chrome.com/blog/overscroll-behavior/)

**Comment by cmdr2** [comment]
Thanks, this has been added to the latest beta, and will make its way to the main branch soon.

Thanks for the link to overscroll-behavior, I learnt something new today :)

**Comment by cmdrgrunt** [comment]
Hi @cmdr2 
I tested this and didn't see any change on iOS, but as I follow the rabbit hole, I find that this method seems to work with some browsers and not others, and people have been trying to figure out additional workarounds. In the case of WebKit engine which drives every single 1st and 3rd party browser on iOS by apple's decree, it doesn't seem to affect it and pull to refresh still functions.

HOWEVER

I had been doing some offline testing and I found that moving the main.css line:

overscroll-behavior-y: contain;

from the body section to the html section directly above, and changing the code to:

overscroll-behavior-y: none;

Seems to absolutely do the trick on iOS! I don't have android to check on it's permutations, so you may want to leave on beta branch temporarily to make sure all elements seem good, or possibly create a hi preference to enable or disable for mobile use cases, but from my quick testing I had no show stoppers. I can update this post if I do find anything.
