### ISSUE TITLE
Web UI Does not give image results if render models used in queue vary

### ISSUE THREAD

**Issue by scorpiomaj27** [easydiffusion/easydiffusion#1373]
**Describe the bug**
The WebUI fails to refresh the Processing item after a prior item is completed if NEW MODEL is used in subsequent items.  For example, 1 or 2 items in the queue will process and display results, but subsequent items continue "Waiting" even though the application processes them completely.

If we could grab the results directly from a folder, that may be a workaround, but I'm unable to locate the resulting images.

**To Reproduce**
1. Use ED in CPU only mode (Ryzen 2500u for example)
2. Queue several images using img2img mode with various models/checkpoints.
3. Wait for completion of 2 or 3 items with different **models**, at some point waiting items will visually continue waiting, despite the application continuing to render.

**Expected behavior**
UI would refresh more reliably relative to render results.

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - Browser: Chrome
 - Version: ED 7th March 2023 release.

**Additional context**
This seems to work correctly if only a single model is used for all items in queue.

**Comment by cmdrgrunt** [comment]
I have found that if I keep focus on the current stack of tasks and keep them visible in the browser, it will update and complete them, but occasionally if I change to a different window or scroll the remaining queue offscreen (this especially happens on mobile browser) it will forget what it's doing. It seems like it won't poll the server or continue to submit jobs until you're actively looking at that spot in the queue again. A sort of reverse "watched pot never boils" issue?

**Comment by scorpiomaj27** [comment]
> I have found that if I keep focus on the current stack of tasks and keep them visible in the browser, it will update and complete them, but occasionally if I change to a different window or scroll the remaining queue offscreen (this especially happens on mobile browser) it will forget what it's doing. It seems like it won't poll the server or continue to submit jobs until you're actively looking at that spot in the queue again. A sort of reverse "watched pot never boils" issue?

Yes, this seems to help most (95%) of the time, thanks!

**Comment by cmdr2** [comment]
Hi @scorpiomaj27 I agree, but this isn't something we can fix right now, because the browser decides to put the tab to sleep.

I will keep this in mind, and watch for any solutions in the future (e.g. I heard that playing a silent audio in the tab endlessly can keep the tab alive, not sure).

For now, unfortunately there isn't much we can do about this. Sorry.
