### ISSUE TITLE
Latent Upscaler doesn't work

### ISSUE THREAD

**Issue by ufuksarp** [easydiffusion/easydiffusion#1374]
Pick Latent Upscaler as upscaling option in image settings. Click "Make Image". Image generation finishes, but throws an error "Error: 'latent_upscaler'" at the end.

![image](https://github.com/easydiffusion/easydiffusion/assets/18383194/f5004345-c175-48ce-a21a-cff7e719c1de)

**Log:** [Easy Diffusion.txt](https://github.com/easydiffusion/easydiffusion/files/11894368/Easy.Diffusion.txt)

**Edit:** Forgot to mention that same thing happens after clicking the "Upscale" button on images if Latent Upscaler is selected in image settings.

Beta channel with test diffusers
RTX 3060
Windows 11

**Comment by JeLuF** [comment]
This error usually occurs if the backend isn't running the Diffusers test version any more. Under unknown circumstances, the "beta" and "test" settings get lost. If you're sure that the backend is running the diffusers test version, please upload the log output from the console window.

**Comment by ufuksarp** [comment]
I already sent the console log as a txt file.

**Comment by JeLuF** [comment]
```
15:52:11.265 ERROR cuda:0 Error no file named config.json found in directory 
C:\EasyDiffusion\profile\.cache\huggingface\hub\models--stabilityai--sd-x2-latent-upscaler\snapshot
s\1f2883b22f62cfb29323770ba9cfdcf601757bd3\unet.
```
Parts of the latent upscaler model were not installed correctly. This can happen if there are issues with the internet connectivity during the initial download.

Please delete the folder `C:\EasyDiffusion\profile\.cache\huggingface\hub\models--stabilityai--sd-x2-latent-upscaler\` and restart EasyDiffusion.

**Comment by ufuksarp** [comment]
I was suspecting that was the case, but didn't know which files to delete to trigger a redownload of the files. Thanks, works as it should now.
