### ISSUE TITLE
Replication failed

### ISSUE THREAD

**Issue by goodglitch** [easydiffusion/easydiffusion#1384]
**Describe the bug**
I tried to replicate this example https://civitai.com/images/1357543?period=AllTime&periodMode=published&sort=Newest&view=categories&modelVersionId=11745&modelId=6424&postId=350048 (NSFW) and I spent like two hours reformatting prompt, changing parameters and sampling methods. Nothing worked. Results didn't have anything in common with the example. When I was about to give up, I decided to try the prompt in A1111 and magically it worked! I understand that most probably the user was using A1111 to generate samples, but I think there should be at least some consistency of results between web UIs. Moreover, EasyDiffusion was given me results that had very little in common with the prompt.

Just in case you can't retrieve parameters, here they are:

girl,((naked)),
19th century,paris,on the bed,
(masterpiece:1. 0), (best quality:1. 4), (ultra highres:1. 2), (photorealistic:1. 4), (8k, RAW photo:1. 2), (soft focus:1. 4),  (sharp focus:1. 4),
Negative prompt: paintings, sketches, (worst quality:2), (low quality:2), (normal quality:2), lowres, normal quality, ((monochrome)), ((grayscale)),logo,watermark,text,
((Belly button piercing)),Body Button Piercing,((navel piercing)),Piercing,Piercings,Nipple piercing,Tattoos,earrings,pinns,pinning,
((badhandsv5-neg)), Asian-Less-Neg
Eiffel Tower,
Steps: 24, Size: 512x768, Seed: 2347612059, Model: chilloutmix_NiPrunedFp32Fix, Sampler: DPM++ 2M Karras, CFG scale: 6.5, Model hash: fc2511737a

The prompt have enters, so I had to remove them. I think treatment of enters might be responsible for that behavior, but I have no idea how do they translate into processed prompt by A1111.

**To Reproduce**
Use parameters from the example.

**Expected behavior**
At least some degree of consistency of results between web UIs.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Chrome
 - Version:

**Smartphone (please complete the following information):**
 - Device:
 - OS: 
 - Browser 
 - Version 

**Additional context**

**Comment by JeLuF** [comment]
The negative uses embeddings ("badhandsv5-neg", "Asian-Less-Neg"), which Easy Diffusion does not yet support (There's a PR to implement embeddings support). Furthermore, most a1111 installations use xformers, a library that accelerates the generation of images, but one of the side effects is that the image generation is no longer deterministic. Factors like GPU model or driver version impact the image generation process.
