### ISSUE TITLE
Could not load the stable-diffusion model

### ISSUE THREAD

**Issue by pingachan** [easydiffusion/easydiffusion#1385]
Error: Could not load the stable-diffusion model! Reason: Unable to load weights from pytorch checkpoint file for 'D:\EasyDiffusion\profile.cache\huggingface\hub\models--openai--clip-vit-large-patch14\snapshots\8d052a0f05efbaefbc9e8786ba291cfdf93e5bff\pytorch_model.bin' at 'D:\EasyDiffusion\profile.cache\huggingface\hub\models--openai--clip-vit-large-patch14\snapshots\8d052a0f05efbaefbc9e8786ba291cfdf93e5bff\pytorch_model.bin'. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.

There was suggestion to delete this file, so it would reinstall itself, but for me it didnt work

**Comment by JeLuF** [comment]
Please delete the folder `D:\EasyDiffusion\profile.cache\huggingface\hub\models--openai--clip-vit-large-patch14\snapshots\` and restart easy diffusion. It will download a new copy of the file
