### ISSUE TITLE
Hypernetworks not working with test diffusers on

### ISSUE THREAD

**Issue by sentimoor** [easydiffusion/easydiffusion#1388]
In beta with test diffusers on. Hypernetworks do not appear to have any effect on outputs, regardless of strength. When disabling "test diffusers" they work fine.

**To Reproduce**
Steps to reproduce the behavior: enable test diffusers, generate image, select a hypernetwork, generate second image with same seed/parameters, compare. 

**Expected behavior**
For hypernetworks to work/apply.

 - OS: Windows
 - Browser: Firefox
 - Version:

**Additional context**
I am using many plugins from patrices plugin manager, some of which are not functioning properly. But given the fact it works with diffusers off, that would seem inconsequential.

Thank you for continuing to support this project.

**Comment by JeLuF** [comment]
This is a known and documented limitation of the test diffusers environment. It's mentioned in the splash screen that was shown when you activated the diffusers test version. You can display it again by clicking on the EasyDiffusion logo in the top left corner.

**Comment by sentimoor** [comment]
My apologies. I had never seen such screen, but i can see it now. Thanks for clarification.

**Comment by Seedmanc** [comment]
Where do you "select" a hypernetwork? I don't see it anywhere in the UI. Did they give up and abandon the whole support altogether?

**Comment by JeLuF** [comment]
Hypernetworks are not supported in the V3 engine. You need to disable the V3 engine in the "Settings" tab and restart to use Hypernetworks. Please not that the old engine does not support features like LORAs, SDXL, etc.
