### ISSUE TITLE
Password for Cloudflare tunnel

### ISSUE THREAD

**Issue by QazCetelic** [easydiffusion/easydiffusion#1389]
**Is your feature request related to a problem? Please describe.**
I would like to allow connections from another network to my computer running easydiffusion.

**Describe the solution you'd like**
A password I can choose or a randomly generated PIN.

**Describe alternatives you've considered**
Not using Cloudflare tunnel.

**Comment by JeLuF** [comment]
You could use ngrok instead of cloudflare. They offer password protection for the tunnel address, but require users to register an account. Check ngrok.com for details

**Comment by cmdr2** [comment]
Sorry, this isn't currently planned because our server isn't really meant for untrusted usage. A lot of the internals have been written with the assumption of trusted usage, so re-architecting them would be quite a task, and isn't the focus of this software. Thanks!

**Comment by QazCetelic** [comment]
For anyone that wants to set up something similar like I wanted you can:

1. Install ngrok as @JeLuF mentioned
2. Start easy diffusion
3. Run `ngrok http 9000 --basic-auth USERNAME:PASSWORD`
4. Login on other device with chosen login credentials

**Comment by PeterHindes** [comment]
Would love to have this feature
