### ISSUE TITLE
The server is not avaiable

### ISSUE THREAD

**Issue by odvigajlo** [easydiffusion/easydiffusion#1390]
**Describe the bug**
When i press button "Make Image" i get error message from browser: "The server is not avaiable"

**To Reproduce**
1. Open Easy Diffusion
2. Click on "Make Image"
3. See error

**Expected behavior**
Image should generate

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Browser Version: 114.0.5735.199 (latest)

**Comment by JeLuF** [comment]
Please provide the log output from the EasyDiffusion console window.

**Comment by JeLuF** [comment]
Closed due to inactivity
