### ISSUE TITLE
How do I use other upscalers?

### ISSUE THREAD

**Issue by ufuksarp** [easydiffusion/easydiffusion#1394]
I wanted to try other upscalers, so I downloaded couple of them like "8x_NMKD-Superscale_150000_G.pth" and put them in _models > realesrgan_ folder, but they won't show up.

**Comment by scorpiomaj27** [comment]
I'm not sure about that method, but "Upscayl" is a free application and you can first see how your image looks from ED than before deciding if you want to spend time upscaling.

**Comment by JeLuF** [comment]
Custom Upscalers are currently not supported.

Closed as duplicate of #939
