### ISSUE TITLE
Does it support sdxl 0.9

### ISSUE THREAD

**Issue by selimyalcin** [easydiffusion/easydiffusion#1395]
i have sdxl 0.9, easy does it support this?

**Comment by selimyalcin** [comment]
> Easy Diffusion currently does not support SDXL 0.9.

i know, but ill work for support. just need create a branch

**Comment by NostalgicStone** [comment]
Do you plan on adding support?

**Comment by cmdr2** [comment]
SDXL is fully supported in the latest release
