### ISSUE TITLE
Diffusers beta 2.5.43 img2img workflows stall with "Error: Input for postprocessing is in incorrect format: . We only support pytorch tensor"

### ISSUE THREAD

**Issue by cmdrgrunt** [easydiffusion/easydiffusion#1399]
**Describe the bug**
Load an initial image or use existing image as input to trigger img2img processing. Process fails with "Error: Input for postprocessing is in incorrect format: . We only support pytorch tensor"

**To Reproduce**
1. Install latest v2.5.43 beta, using nvidia gpu on Windows.
2. Make sure experimental diffusers are enabled
3. Generate an image and then select "use as input" or alternatively, import an image for img2img.

**Expected behavior**
A new image should be generated using the influence from img2img at the resolution you set.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 22H2
 - Browser: Microsoft Edge
 - Version: Version 114.0.1823.67 (Official build) (64-bit)

**Additional context**
Some other folks have been experiencing this issue as well, discussing on the Discord. img2img is completely broken for me. I'm attaching the log from start to finish including the traceback. Please look at line 478 of my  log. Perhaps it's expecting a previous routine to have converted the numpy.ndarray pil to torch.tensor? I'm out of my depth.
[cmdrgrunt_beta_console_log_2.5.43_jul9_img2img_tensor_error.txt](https://github.com/easydiffusion/easydiffusion/files/11997279/cmdrgrunt_beta_console_log_2.5.43_jul9_img2img_tensor_error.txt)

**Comment by cmdr2** [comment]
Thanks, pushed a fix for this
