### ISSUE TITLE
hipErrorNoBinaryForGpu: Unable to find code object for all current devices!

### ISSUE THREAD

**Issue by RashiqAzhan** [easydiffusion/easydiffusion#1400]
**Describe the bug**
Unable to get the server to start.

**To Reproduce**
1. Download zip and extract files
2. `./start.sh`
3. This error appears at the bottom
```
"hipErrorNoBinaryForGpu: Unable to find code object for all current devices!"
.../easy-diffusion/scripts/on_sd_start.sh: line 82: 65171 Aborted                 uvicorn main:server_api --app-dir "$SD_UI_PATH" --port "$ED_BIND_PORT" --host "$ED_BIND_IP" --log-level error
Press any key to continue
```

**Expected behavior**
Web ui should appear.

**Desktop (please complete the following information):**
 - OS: CachyOS
 - Browser: Vivaldi
 - Version: Easy Diffusion v2.5.24

**Comment by JeLuF** [comment]
Which GPU do you use?

**Comment by JeLuF** [comment]
You can replace the ROCm libraries with CUDA libraries, which have a working fallback to CPU-mode. Start `./developer_console.sh` to enter the EasyDiffusion python environment, then run:

```
python -m pip install --upgrade torch==1.13.1+cu116 torchvision==0.14.1+cu116 --extra-index-url https://download.pytorch.org/whl/cu116
```

**Comment by cmdr2** [comment]
Closing, please reopen if this continues to be an issue. Thanks
