### ISSUE TITLE
"Error activating conda for Easy Diffusion. Sorry about that, please try to:" "  1. Run this installer again." "  2. If that doesn't fix it, please try the common troubleshooting steps at https://github.com/cmdr2/stable-diffusion-ui/wiki/Troubleshooting" "  3. If those steps don't help, please copy *all* the error messages in this window, and ask the community at https://discord.com/invite/u9yhsFmEkB" "  4. If that doesn't solve the problem, please file an issue at https://github.com/cmdr2/stable-diffusion-ui/issues" "Thanks!"

### ISSUE THREAD

**Issue by davidke460** [easydiffusion/easydiffusion#1407]
"Error activating conda for Easy Diffusion. Sorry about that, please try to:"
"  1. Run this installer again."
"  2. If that doesn't fix it, please try the common troubleshooting steps at https://github.com/cmdr2/stable-diffusion-ui/wiki/Troubleshooting"
"  3. If those steps don't help, please copy *all* the error messages in this window, and ask the community at https://discord.com/invite/u9yhsFmEkB"
"  4. If that doesn't solve the problem, please file an issue at https://github.com/cmdr2/stable-diffusion-ui/issues"
"Thanks!"

**Comment by davidke460** [comment]
I tried to use the installer, but it does not want to be installed, does not react at all, does not open and does not start

**Comment by JeLuF** [comment]
Did we already discuss this on Discord? 
https://discord.com/channels/1014774730907209781/1128658678606729236

**Comment by JeLuF** [comment]
Closed ticket due to inactivity.
