### ISSUE TITLE
Error message: Expected all tensors to be on the same device...

### ISSUE THREAD

**Issue by compactmicrowave** [easydiffusion/easydiffusion#1408]
Error message: Expected all tensors to be on the same device, but found at least two devices, meta and cuda:0! 

v2.5.43 (beta)

This message is shown after selecting a .pt textual inversion file from the embeddings folder C:\EasyDiffusion\models\embeddings

(via the 'add the embedding to the prompt' Ui in Beta (under the hypernetwork dropdown)

No image is produced as the message is generated within a few seconds.

OS: W10, 

Nvidia G  Force GTX 1650 TI allocated to Easy Diffusion

AMD Ryzen 5 4600HS

**Comment by JeLuF** [comment]
Embeddings currently don't work with the "Low" GPU memory profile, they only work on "Balanced".

**Comment by compactmicrowave** [comment]
Thank you - they seem to be working now since recent update.
