### ISSUE TITLE
"Error: Could not load the stable-diffusion model! ..."

### ISSUE THREAD

**Issue by SipoFrost** [easydiffusion/easydiffusion#1411]
**Describe the bug**
Any attempt of generating pictures using easy diffusion is not viable.

**To Reproduce**
Download and start easy diffusion.

**Expected behavior**
Any picture as an outcome.

Hello! I encountered this issue when I tried to operate my easy diffusion for the first time. The screenshot and its output log are attached below. Please let me know if I should provide any other info, thanks in advance! 

<img width="1270" alt="9bf3c5261c4be238fa2af8771ccd928" src="https://github.com/easydiffusion/easydiffusion/assets/139483219/f9a26c41-cc54-4433-a43b-49d7b1c400e6">

Install dir: C:\Users\yilin\Downloads\
C:\Users\yilin\Downloads\installer_files\env\Library\bin\git.exe
git version 2.41.0.windows.1
C:\Users\yilin\Downloads\installer_files\env\Library\bin\conda.bat
C:\Users\yilin\Downloads\installer_files\env\Scripts\conda.exe
conda 22.11.1

"Easy Diffusion - v2"

"Easy Diffusion's git repository was already installed. Updating from main.."
HEAD is now at 788404f6 Update README.md
Already on 'main'
Your branch is up to date with 'origin/main'.
Already up to date.
499 File(s) copied
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
A subdirectory or file tmp already exists.
torch: 1.13.1+cu116
torchvision: 0.14.1+cu116
sdkit: 1.0.112
stable-diffusion-sdkit: 2.1.4

"Easy Diffusion installation complete! Starting the server!"

PYTHONPATH=C:\Users\yilin\Downloads\installer_files\env\lib\site-packages
C:\Users\yilin\Downloads\installer_files\env\python.exe
C:\Users\yilin\AppData\Local\Microsoft\WindowsApps\python.exe
Python 3.8.5
No module 'xformers'. Proceeding without it.
08:31:40.215 INFO MainThread started in C:\Users\yilin\Downloads\stable-diffusion                           server.py:20
08:31:40.215 INFO MainThread started at 07/13/23 08:31:40                                                   server.py:21
stable-diffusion model(s) found.
gfpgan model(s) found.
realesrgan model(s) found.
vae model(s) found.
08:31:40.225 INFO MainThread Scanning all model folders for models...                               model_manager.py:370
08:31:40.309 INFO MainThread Scanned 3 models. Nothing infected                                     model_manager.py:379
08:31:40.356 INFO MainThread Start new Rendering Thread on device: cuda:0                            task_manager.py:467
08:31:40.919 INFO cuda:0 Device usage during initialization:                                              renderer.py:48
08:31:40.919 INFO cuda:0 CPU utilization: 1.5%, System RAM used: 7.4 of 15.7 GiB, GPU RAM used        memory_utils.py:44
(cuda:0): 1.0 of 6.0 GiB (peak: 0.0 GiB)
08:31:40.919 INFO cuda:0 Setting cuda:0 as active, with precision: half                            device_manager.py:154
08:31:40.936 INFO cuda:0 loading stable-diffusion model from                                              __init__.py:36
C:\Users\yilin\Downloads\models\stable-diffusion\sd-v1-4.ckpt to device: cuda:0
╭────────────────────────────────────────────── Easy Diffusion is ready ───────────────────────────────────────────────╮
│                                                                                                                      │
│ Easy Diffusion is ready to serve requests.                                                                           │
│                                                                                                                      │
│ A new browser tab should have been opened by now.                                                                    │
│ If not, please open your web browser and navigate to http://localhost:9000/                                          │
│                                                                                                                      │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
08:31:42.183 INFO AnyIO worker thread Scanning all model folders for models...                      model_manager.py:370
08:31:43.041 INFO cuda:0 using config:                                                                    __init__.py:75
C:\Users\yilin\Downloads\installer_files\env\lib\site-packages\sdkit\models\models_db\configs\v1-inferenc
e.yaml
08:31:43.053 INFO cuda:0 using attn_precision: fp16                                                       __init__.py:81
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
08:31:48.178 ERROR cuda:0 Error while loading stable-diffusion model:                                model_manager.py:74
C:\Users\yilin\Downloads\models\stable-diffusion\sd-v1-4.ckpt
08:31:48.178 ERROR cuda:0 Unable to load weights from pytorch checkpoint file for                    model_manager.py:80
'C:\Users\yilin\Downloads\profile\.cache\huggingface\hub\models--openai--clip-vit-large-patch14\snap
shots\8d052a0f05efbaefbc9e8786ba291cfdf93e5bff\pytorch_model.bin' at
'C:\Users\yilin\Downloads\profile\.cache\huggingface\hub\models--openai--clip-vit-large-patch14\snap
shots\8d052a0f05efbaefbc9e8786ba291cfdf93e5bff\pytorch_model.bin'. If you tried to load a PyTorch
model from a TF 2.0 checkpoint, please set from_tf=True.
Traceback (most recent call last):
  File
"C:\Users\yilin\Downloads\installer_files\env\lib\site-packages\transformers\modeling_utils.py",
line 415, in load_state_dict
    return torch.load(checkpoint_file, map_location="cpu")
  File "C:\Users\yilin\Downloads\installer_files\env\lib\site-packages\torch\serialization.py", line
795, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\yilin\Downloads\installer_files\env\lib\site-packages\torch\serialization.py", line
1002, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
EOFError: Ran out of input

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File
"C:\Users\yilin\Downloads\installer_files\env\lib\site-packages\transformers\modeling_utils.py",
line 426, in load_state_dict
    raise ValueError(
ValueError: Unable to locate the file
C:\Users\yilin\Downloads\profile\.cache\huggingface\hub\models--openai--clip-vit-large-patch14\snaps
hots\8d052a0f05efbaefbc9e8786ba291cfdf93e5bff\pytorch_model.bin which is necessary to load this
pretrained model. Make sure you have saved the model properly.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\yilin\Downloads\ui\easydiffusion\model_manager.py", line 65, in load_default_models
    load_model(
  File
"C:\Users\yilin\Downloads\installer_files\env\lib\site-packages\sdkit\models\model_loader\__init__.p
y", line 38, in load_model
    context.models = models.load_model(context, **kwargs)
  File
"C:\Users\yilin\Downloads\installer_files\env\lib\site-packages\sdkit\models\model_loader\stable_dif
fusion\__init__.py", line 84, in load_model
    model = instantiate_from_config(config.model)
  File "C:\Users\yilin\Downloads\installer_files\env\lib\site-packages\ldm\util.py", line 79, in
instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File
"C:\Users\yilin\Downloads\installer_files\env\lib\site-packages\ldm\models\diffusion\ddpm.py", line
563, in __init__
    self.instantiate_cond_stage(cond_stage_config)
  File
"C:\Users\yilin\Downloads\installer_files\env\lib\site-packages\ldm\models\diffusion\ddpm.py", line
630, in instantiate_cond_stage
    model = instantiate_from_config(config)
  File "C:\Users\yilin\Downloads\installer_files\env\lib\site-packages\ldm\util.py", line 79, in
instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File
"C:\Users\yilin\Downloads\installer_files\env\lib\site-packages\ldm\modules\encoders\modules.py",
line 100, in __init__
    self.transformer = CLIPTextModel.from_pretrained(version)
  File
"C:\Users\yilin\Downloads\installer_files\env\lib\site-packages\transformers\modeling_utils.py",
line 2301, in from_pretrained
    state_dict = load_state_dict(resolved_archive_file)
  File
"C:\Users\yilin\Downloads\installer_files\env\lib\site-packages\transformers\modeling_utils.py",
line 431, in load_state_dict
    raise OSError(
OSError: Unable to load weights from pytorch checkpoint file for
'C:\Users\yilin\Downloads\profile\.cache\huggingface\hub\models--openai--clip-vit-large-patch14\snap
shots\8d052a0f05efbaefbc9e8786ba291cfdf93e5bff\pytorch_model.bin' at
'C:\Users\yilin\Downloads\profile\.cache\huggingface\hub\models--openai--clip-vit-large-patch14\snap
shots\8d052a0f05efbaefbc9e8786ba291cfdf93e5bff\pytorch_model.bin'. If you tried to load a PyTorch
model from a TF 2.0 checkpoint, please set from_tf=True.
08:31:49.123 INFO cuda:0 Session 1689262302096 starting task 2070143068912 on NVIDIA GeForce RTX     task_manager.py:314
3060 Laptop GPU
08:31:49.125 INFO cuda:0 loading stable-diffusion model from                                              __init__.py:36
C:\Users\yilin\Downloads\models\stable-diffusion\sd-v1-4.ckpt to device: cuda:0
08:31:51.414 INFO cuda:0 using config:                                                                    __init__.py:75
C:\Users\yilin\Downloads\installer_files\env\lib\site-packages\sdkit\models\models_db\configs\v1-inferenc
e.yaml
08:31:51.426 INFO cuda:0 using attn_precision: fp16                                                       __init__.py:81
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
08:31:56.948 ERROR cuda:0 Unable to load weights from pytorch checkpoint file for                   model_manager.py:170
'C:\Users\yilin\Downloads\profile\.cache\huggingface\hub\models--openai--clip-vit-large-patch14\sna
pshots\8d052a0f05efbaefbc9e8786ba291cfdf93e5bff\pytorch_model.bin' at
'C:\Users\yilin\Downloads\profile\.cache\huggingface\hub\models--openai--clip-vit-large-patch14\sna
pshots\8d052a0f05efbaefbc9e8786ba291cfdf93e5bff\pytorch_model.bin'. If you tried to load a PyTorch
model from a TF 2.0 checkpoint, please set from_tf=True.
Traceback (most recent call last):
  File
"C:\Users\yilin\Downloads\installer_files\env\lib\site-packages\transformers\modeling_utils.py",
line 415, in load_state_dict
    return torch.load(checkpoint_file, map_location="cpu")
  File "C:\Users\yilin\Downloads\installer_files\env\lib\site-packages\torch\serialization.py",
line 795, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\yilin\Downloads\installer_files\env\lib\site-packages\torch\serialization.py",
line 1002, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
EOFError: Ran out of input

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File
"C:\Users\yilin\Downloads\installer_files\env\lib\site-packages\transformers\modeling_utils.py",
line 426, in load_state_dict
    raise ValueError(
ValueError: Unable to locate the file
C:\Users\yilin\Downloads\profile\.cache\huggingface\hub\models--openai--clip-vit-large-patch14\snap
shots\8d052a0f05efbaefbc9e8786ba291cfdf93e5bff\pytorch_model.bin which is necessary to load this
pretrained model. Make sure you have saved the model properly.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\yilin\Downloads\ui\easydiffusion\model_manager.py", line 166, in
reload_models_if_necessary
    action_fn(context, model_type, scan_model=False)  # we've scanned them already
  File
"C:\Users\yilin\Downloads\installer_files\env\lib\site-packages\sdkit\models\model_loader\__init__.
py", line 38, in load_model
    context.models = models.load_model(context, **kwargs)
  File
"C:\Users\yilin\Downloads\installer_files\env\lib\site-packages\sdkit\models\model_loader\stable_di
ffusion\__init__.py", line 84, in load_model
    model = instantiate_from_config(config.model)
  File "C:\Users\yilin\Downloads\installer_files\env\lib\site-packages\ldm\util.py", line 79, in
instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File
"C:\Users\yilin\Downloads\installer_files\env\lib\site-packages\ldm\models\diffusion\ddpm.py", line
563, in __init__
    self.instantiate_cond_stage(cond_stage_config)
  File
"C:\Users\yilin\Downloads\installer_files\env\lib\site-packages\ldm\models\diffusion\ddpm.py", line
630, in instantiate_cond_stage
    model = instantiate_from_config(config)
  File "C:\Users\yilin\Downloads\installer_files\env\lib\site-packages\ldm\util.py", line 79, in
instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File
"C:\Users\yilin\Downloads\installer_files\env\lib\site-packages\ldm\modules\encoders\modules.py",
line 100, in __init__
    self.transformer = CLIPTextModel.from_pretrained(version)
  File
"C:\Users\yilin\Downloads\installer_files\env\lib\site-packages\transformers\modeling_utils.py",
line 2301, in from_pretrained
    state_dict = load_state_dict(resolved_archive_file)
  File
"C:\Users\yilin\Downloads\installer_files\env\lib\site-packages\transformers\modeling_utils.py",
line 431, in load_state_dict
    raise OSError(
OSError: Unable to load weights from pytorch checkpoint file for
'C:\Users\yilin\Downloads\profile\.cache\huggingface\hub\models--openai--clip-vit-large-patch14\sna
pshots\8d052a0f05efbaefbc9e8786ba291cfdf93e5bff\pytorch_model.bin' at
'C:\Users\yilin\Downloads\profile\.cache\huggingface\hub\models--openai--clip-vit-large-patch14\sna
pshots\8d052a0f05efbaefbc9e8786ba291cfdf93e5bff\pytorch_model.bin'. If you tried to load a PyTorch
model from a TF 2.0 checkpoint, please set from_tf=True.
08:31:57.445 ERROR cuda:0 Traceback (most recent call last):                                         task_manager.py:356
  File "C:\Users\yilin\Downloads\ui\easydiffusion\task_manager.py", line 339, in thread_render
    model_manager.fail_if_models_did_not_load(renderer.context)
  File "C:\Users\yilin\Downloads\ui\easydiffusion\model_manager.py", line 199, in
fail_if_models_did_not_load
    raise Exception(f"Could not load the {model_type} model! Reason: " + e)
Exception: Could not load the stable-diffusion model! Reason: Unable to load weights from pytorch
checkpoint file for
'C:\Users\yilin\Downloads\profile\.cache\huggingface\hub\models--openai--clip-vit-large-patch14\snap
shots\8d052a0f05efbaefbc9e8786ba291cfdf93e5bff\pytorch_model.bin' at
'C:\Users\yilin\Downloads\profile\.cache\huggingface\hub\models--openai--clip-vit-large-patch14\snap
shots\8d052a0f05efbaefbc9e8786ba291cfdf93e5bff\pytorch_model.bin'. If you tried to load a PyTorch
model from a TF 2.0 checkpoint, please set from_tf=True.

08:31:57.534 INFO cuda:0 Session 1689262302096 task 2070143068912 failed!                            task_manager.py:365

**Comment by JeLuF** [comment]
Please delete the folder `C:\Users\yilin\Downloads\profile\.cache\huggingface\hub\models--openai--clip-vit-large-patch14\snap
shots\8d052a0f05efbaefbc9e8786ba291cfdf93e5bff\` and restart Easy Diffusion, so that it will be downloaded again.
