### ISSUE TITLE
Could not load the stable-diffusion model

### ISSUE THREAD

**Issue by Edriel3** [easydiffusion/easydiffusion#1415]
![Снимок экрана (643)](https://github.com/easydiffusion/easydiffusion/assets/139574370/f5a8ec8d-9077-4bbc-b442-890fbdc90b39)
Here is such a mistake. I have already tried deleting both pytorch_model.bin and 8d052a0f05efbaefbc9e8786ba291cfdf93e5bff. Nothing helped.

**Comment by JeLuF** [comment]
The download of the OpenAI language model has apparently failed. Please delete the file mentioned in the error message and the folder containing it. After restarting EasyDiffusion, it should download the model from scratch.
