### ISSUE TITLE
Error: Could not load the lora model! Reason: pop from empty list

### ISSUE THREAD

**Issue by agentsimon** [easydiffusion/easydiffusion#1417]
![Screenshot from 2023-07-17 07-44-24](https://github.com/easydiffusion/easydiffusion/assets/31639346/1250a543-106e-441b-815d-084e4ac73238)
`Exception: Could not load the lora model! Reason: pop from                      
empty list                                                                      
                                                                                
07:52:05.586 INFO cuda:0 Session 1689554215510 task          task_manager.py:365
139673210679648 failed!                                                         
07:52:06.588 INFO cuda:0 Session 1689554215510 starting task task_manager.py:314
139673933854848 on NVIDIA GeForce RTX 3050 Ti Laptop GPU                        
07:52:06.643 ERROR cuda:0 Traceback (most recent call last): task_manager.py:356
  File                                                                          
"/home/simon/Documents/stable-diffusion-ui/ui/easydiffusion/                    
task_manager.py", line 339, in thread_render                                    
    model_manager.fail_if_models_did_not_load(renderer.conte                    
xt)                                                                             
  File                                                                          
"/home/simon/Documents/stable-diffusion-ui/ui/easydiffusion/                    
model_manager.py", line 210, in fail_if_models_did_not_load                     
    raise Exception(f"Could not load the {model_type} model!                    
Reason: " + e)                                                                  
Exception: Could not load the lora model! Reason: pop from                      
empty list                                                                      
                                                                                
07:52:06.760 INFO cuda:0 Session 1689554215510 task          task_manager.py:365
139673933854848 failed!   `

**Comment by compactmicrowave** [comment]
I have this same issue also.

**Comment by cmdr2** [comment]
Just pushed a fix to beta for this, can you please restart Easy Diffusion and try again? Thanks

**Comment by agentsimon** [comment]
Fabulous..that's fixed it. Thank you

**Comment by Musepozos** [comment]
coming late to this conversation. Does Easy Diffusion support lora models. If so, how do you import them. thanks.

**Comment by compactmicrowave** [comment]
Thank you for the quick fix. That's great.

**Comment by compactmicrowave** [comment]
Musepozos -- enable beta and drop the files into the lora folder

C:\EasyDiffusion\models\lora

**Comment by cmdr2** [comment]
@Musepozos Please enable beta in the settings tab of the UI, press Save. Then refresh the page. Then enable "Test Diffusers" in the Settings tab, press Save and restart Easy Diffusion.

Sorry for the lengthy steps, we're close to getting LoRA into regular beta.

Closing this issue, since it appears to have been resolved. Thanks!
