### ISSUE TITLE
Easy Diffusion doesn't start - No error message

### ISSUE THREAD

**Issue by Kyllom** [easydiffusion/easydiffusion#1424]
After a clean (first) installation, launching "Start Stable Diffusion UI.cmd" the program doesn't start and doesn't show any error message:

```
S:\AI\EasyDiffusion>"Start Stable Diffusion UI.cmd"
Install dir: S:\AI\EasyDiffusion\
C:\Program Files\Git\cmd\git.exe
git version 2.41.0.windows.1
S:\AI\EasyDiffusion\installer_files\env\Library\bin\conda.bat
S:\AI\EasyDiffusion\installer_files\env\Scripts\conda.exe
conda 22.11.1
Presione una tecla para continuar . . . (<= Press any key to continue)
```

After this, it stops.

No way to get more information about what's happening.

--
Stable Diffusion: 2.5
SO: Windows 10 (22H2)
RAM: 32GB DDR4
GPU: NVIDIA GeForce GTX 1660
CPU: AMD Ryzen 7 2700X
--

Regards

**Comment by JeLuF** [comment]
Please check your system event log and your anti-malware logs for any error messages.

**Comment by Kyllom** [comment]
Hello JeLuF,

I have just checked everything, there are no error logs or any kind in the system, antivirus, etc.

The process starts and finishes, without any effect.

Is there any other way to launch the program?

Regards

**Comment by Kyllom** [comment]
Hi again.

I found the problem: 'on_env_start.cmd' file was corrupted.

You can close this ticket.

Regards
