### ISSUE TITLE
Error: only one element tensors can be converted to Python scalars. (beta)

### ISSUE THREAD

**Issue by osem598** [easydiffusion/easydiffusion#1425]
v2.5.45
after switching to the beta channel (through the gui) if I set the inference steps to >43 I get the following error (on the non-beta version I had no problems with high inference steps):

(parent of install directory)/easy-diffusion/installer_files/env/lib/py                    
thon3.8/site-packages/diffusers/schedulers/scheduling_dpmsolver_si                    
nglestep.py", line 670, in step                                                       
    step_index = step_index.item()                                                    
ValueError: only one element tensors can be converted to Python                       
scalars

Gpu: AMD 6900xt
OS: fedora linux 38
Browser: Firefox

My apologies if this is not a detailed enough report. I am not much of a github user.

**Comment by catronomix** [comment]
I have the same issue today, never had this before.

**Comment by cmdr2** [comment]
Pushed a fix to beta for this error, can you please try again?

**Comment by osem598** [comment]
> Pushed a fix to beta for this error, can you please try again?

Fixed!!! thank you! 
tested working up to 2048 samples for the lols

**Comment by cmdr2** [comment]
Nice, glad it works! :)
