### ISSUE TITLE
Easy diffusion Core Dump?

### ISSUE THREAD

**Issue by ArchKaine** [easydiffusion/easydiffusion#1426]
Any idea what's going on here? Other than the core dump? OpenSuse Tumbleweed, latest release. Fresh install. 

System Specs:
ryzen 5800x
32gb RAM
rx 5700 xt

PYTHONPATH=/home/brian/Downloads/easy-diffusion/installer_files/env/lib/python3.8/site-packages
/home/brian/Downloads/easy-diffusion/installer_files/env/bin/python
Python 3.8.5
/home/brian/Downloads/easy-diffusion/scripts/on_sd_start.sh: line 82: 31452 Bus error               (core dumped) uvicorn main:server_api --app-dir "$SD_UI_PATH" --port "$ED_BIND_PORT" --host "$ED_BIND_IP" --log-level error

**Comment by JeLuF** [comment]
Can you please try to start using this command:
```
HSA_OVERRIDE_GFX_VERSION=10.3.0 ./start.sh
```

**Comment by ArchKaine** [comment]
Tried it, failed with the following: PYTHONPATH=/home/brian/Downloads/easy-diffusion/installer_files/env/lib/python3.8/site-packages
/home/brian/Downloads/easy-diffusion/installer_files/env/bin/python
Python 3.8.5
/home/brian/Downloads/easy-diffusion/scripts/on_sd_start.sh: line 82: 17604 Bus error               (core dumped) uvicorn main:server_api --app-dir "$SD_UI_PATH" --port "$ED_BIND_PORT" --host "$ED_BIND_IP" --log-level error

**Comment by JeLuF** [comment]
Please include the shell prompt and the exact command executed in error reports.

I'm not sure whether SuSE has `video` and `renderer` groups to allow access to the GPU. If these groups do exist, is your user a member of them?

**Comment by tokenwizard** [comment]
I'm having the exact same issue on Arch Linux. 
I've tried running as my normal user and with sudo and get the same core dump error:

```
sudo ./start.sh
[sudo] password for tokenwizard:              
/usr/bin/curl
/usr/bin/tar
/usr/bin/bzip2
/usr/bin/git
git version 2.41.0
/home/tokenwizard/Downloads/easy-diffusion/installer_files/env/bin/conda
conda 23.5.2


Easy Diffusion

Easy Diffusion's git repository was already installed. Updating from main..
HEAD is now at 710208f3 Update README.md
Already on 'main'
Your branch is up to date with 'origin/main'.
Already up to date.
torch: 1.13.1+rocm5.2
torchvision: 0.14.1+rocm5.2
sdkit: 1.0.112
stable-diffusion-sdkit: 2.1.4


Easy Diffusion installation complete, starting the server!

PYTHONPATH=/home/tokenwizard/Downloads/easy-diffusion/installer_files/env/lib/python3.8/site-packages
/home/tokenwizard/Downloads/easy-diffusion/installer_files/env/bin/python
Python 3.8.5
"hipErrorNoBinaryForGpu: Unable to find code object for all current devices!"
/home/tokenwizard/Downloads/easy-diffusion/scripts/on_sd_start.sh: line 82: 844984 Aborted                 (core dumped) uvicorn main:server_api --app-dir "$SD_UI_PATH" --port "$ED_BIND_PORT" --host "$ED_BIND_IP" --log-level error
Press any key to continue```

**Comment by JeLuF** [comment]
@tokenwizard You have a completely different error message. The OP has a bus error, which you don't have.

First of all: **Do not run EasyDiffusion as root**. Running as root is not supported.

For the 5600, I think you will need these environment variables set:
```
HSA_OVERRIDE_GFX_VERSION=10.3.0 FORCE_FULL_PRECISION=y ./start.sh
```
If this doesn't help, please open a new bug report.

**Comment by tokenwizard** [comment]
> @tokenwizard You have a completely different error message. The OP has a bus error, which you don't have.
> 
> First of all: **Do not run EasyDiffusion as root**. Running as root is not supported.
> 
> For the 5600, I think you will need these environment variables set:
> 
> ```
> HSA_OVERRIDE_GFX_VERSION=10.3.0 FORCE_FULL_PRECISION=y ./start.sh
> ```
> 
> If this doesn't help, please open a new bug report.

Ok, I tried with those command line arguments and I'm still getting stuck at CPU/No GPU Available. I'll open a separate Issue: 
![image](https://github.com/easydiffusion/easydiffusion/assets/24832561/f4b450c5-ef93-4d17-82c6-7b1a93d0ece6)

At least it isn't giving me a SegFault/Core Dump anymore.

**Comment by JeLuF** [comment]
Closed due to inactivity.
