### ISSUE TITLE
I can´t clone the repo!

### ISSUE THREAD

**Issue by callmehanu** [easydiffusion/easydiffusion#1427]
**Describe the bug**
I can´t clone the repo!

**To Reproduce**
1. Open a terminal in easy-diffusion directory
2. Run ./start.sh

**Expected behavior**

**Screenshots**
![image](https://github.com/easydiffusion/easydiffusion/assets/13230502/a0dbe468-d563-4d69-b659-daf87cf37a02)

**Desktop (please complete the following information):**
 - OS: Fedora 38
 - Browser: Firefox
 - Version: Linux 6.3.12-200.fc38.x86_64

**Additional context**

**Comment by JeLuF** [comment]
Please check your git config setting and your proxy settings. git tries to access a web proxy at http://localhost:1087/ for some reason.

**Comment by JeLuF** [comment]
Closed due to inactivity.
