### ISSUE TITLE
Getting an error on install

### ISSUE THREAD

**Issue by fulcrumrebel** [easydiffusion/easydiffusion#1431]
ImportError: cannot import name 'SAFE_WEIGHTS_NAME' from 'transformers.utils'
(C:\EasyDiffusion\installer_files\env\lib\site-packages\transformers\utils\__init__.py)
Press any key to continue . . .

This is the error im getting and nothing that I have found has explained what to actually do to resolve the issue. Can someone walk me through how to fix it? It was working fine on my other laptop but not on my current one.

**Comment by JeLuF** [comment]
Please provide the full log output of the console window. Usually, this error is a follow up error of an earlier problem.

**Comment by fulcrumrebel** [comment]
I got it fixed!
