### ISSUE TITLE
lora tag parsing

### ISSUE THREAD

**Issue by ChevronTango** [easydiffusion/easydiffusion#1435]
**Is your feature request related to a problem? Please describe.**
when you paste in config from a system like civitai, the lora tags appear in the prompt text amonsts all the other tags.

```
1girl, blond hair, <lora:add_detail:0.3>
```

when it would be more useful for those lora tags to be pulled out and added to the correct section in the easy diffusion UI:

![image](https://github.com/easydiffusion/easydiffusion/assets/1690260/7428e44d-9be6-4b03-9edb-87caaf8fa744)

**Describe the solution you'd like**

Lora tags from the prompts when pasted in, both positive and negative, to be parsed and added to the UI, and give the appropriate weight so that its clear what is being used.

**Comment by JeLuF** [comment]
civitai mostly uses a1111 syntax in its examples. EasyDiffusion does not only handle LORAs differently then a1111 does, it also uses a different way to express weights. An approach could be to detect this kind of syntax when text gets pasted and to offer to convert it, replacing weight tags by compel compatible ones and by extracting the LORAs from the prompt.

**Comment by cmdr2** [comment]
Yeah, I think we should just merge the lora plugin (that parses <lora:> tags) and make it part of the core. The plugin is broken currently, and once fixed, it's just more pragmatic to include it in the core.

**Comment by JeLuF** [comment]
EasyDiffusion 3.0 automatically converts any `<lora:model:weight>` it finds in the prompt to a LORA-line in the Image Settings.
