### ISSUE TITLE
SD-XL models cannot be loaded with @set FORCE_FULL_PRECISION=T

### ISSUE THREAD

**Issue by ex479** [easydiffusion/easydiffusion#1436]
**Describe the bug**
Seems that SDXL models have memory problems during loading. When I use @set FORCE_FULL_PRECISION=T line in the config.bat file I get a memory error.

**To Reproduce**
Download the SDXL model from civitai (https://civitai.com/models/101055). You can download VAE too.
Add the @set FORCE_FULL_PRECISION=T line to \scripts\config.bat
Try generating some pics.

**Desktop (please complete the following information):**
 - OS: Win7x64 
 - Browser: Chrome 109.0.5414.120 64-bit
 - Version: Easy Diffusion v2.5.46 (beta)

**Additional context**
I use the latest xformers module, my GPU is 1080Ti 11Gb.

**Comment by cmdr2** [comment]
SDXL consumes a LOT of VRAM. For e.g. a simple 512x512 image with "low" VRAM usage setting consumes over 5 GB on my GPU. With full precision, it can exceed the capacity of the GPU, especially if you haven't set your "VRAM Usage Level" setting to "low" (in the Settings tab).

Closing since there isn't much we can do for the size of SDXL, it's a big model :)

Please try the "low" VRAM mode (in the Settings tab), and avoid full-precision unless you really need it.

**Comment by ex479** [comment]
> SDXL consumes a LOT of VRAM. For e.g. a simple 512x512 image with "low" VRAM usage setting consumes over 5 GB on my GPU. With full precision, it can exceed the capacity of the GPU, especially if you haven't set your "VRAM Usage Level" setting to "low" (in the Settings tab).
> 
> Closing since there isn't much we can do for the size of SDXL, it's a big model :)
> 
> Please try the "low" VRAM mode (in the Settings tab), and avoid full-precision unless you really need it.

I tried 128x128 with low VRAM settings, and it didn't work, then I tried 512x512 on balanced settings without FORCE_FULL_PRECISION - it worked. So it looks like the model itself with full precision doesn't fit in memory no matter how big is the picture size. If that's how it's supposed to work, then that's fine. It seemed strange to me and I thought it better to warn just in case.

**Comment by cmdr2** [comment]
Thanks, will investigate why the model doesn't load with "low" VRAM mode. Reopening.

**Comment by ex479** [comment]
> Thanks, will investigate why the model doesn't load with "low" VRAM mode. Reopening.

I don't know why it didn't work before, but now it works. 512x512 consumes 11GB at low settings with full precision.

**Comment by check-m4te** [comment]
I mean, I can generate 1024*1024 images in my 8gb card with SDXL

**Comment by ex479** [comment]
> I mean, I can generate 1024*1024 images in my 8gb card with SDXL

Is it with full precision or fp 16 (as by default)?
