### ISSUE TITLE
Stable Diffusion (Easy diffusion) models problem

### ISSUE THREAD

**Issue by CosmicDreamer9653** [easydiffusion/easydiffusion#1437]
Good day to all, I ran into such a problem in Stable Diffusion. I'm trying to use default models, but a message pops up that they are not installed. I tried to install other models, but the message is the same. However, I should have enough RAM

I run the program, enter a request and get this error message

Instead of an error, I expected to see art from a neural network

![ubW7WYgCL38](https://github.com/easydiffusion/easydiffusion/assets/140807009/a093c52b-09ef-4b25-966b-4a6042032014)
![bpX6zqECLIg](https://github.com/easydiffusion/easydiffusion/assets/140807009/f8610976-bfb1-4591-9dad-423fbca8442f)

 - OS: Windows 7 
 - Browser: Yandex
 - Version: Current version
 
 ..............................................................................................................................................................................................................................
 Install dir: C:\EasyDiffusion
C:\EasyDiffusion\installer_files\env\Library\bin\git.exe
git version 2.41.0.windows.1
C:\EasyDiffusion\installer_files\env\Library\bin\conda.bat
C:\EasyDiffusion\installer_files\env\Scripts\conda.exe
conda 22.11.1

"Easy Diffusion - v2"

"Easy Diffusion's git repository was already installed. Updating from main.."
fatal: Unable to create 'C:/EasyDiffusion/sd-ui-files/.git/index.lock': File exi
sts.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
fatal: Unable to create 'C:/EasyDiffusion/sd-ui-files/.git/index.lock': File exi
sts.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
error: Unable to create 'C:/EasyDiffusion/sd-ui-files/.git/index.lock': File exi
sts.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
Updating https://github.com/easydiffusion/easydiffusion/commit/6158f494001a099252fc89fa2a502745ec3db9cc..https://github.com/easydiffusion/easydiffusion/commit/710208f3768077aabccbeaaee9d93356a91573fa
493 File(s) copied
1 file(s) copied.
1 file(s) copied.
1 file(s) copied.
1 file(s) copied.
1 file(s) copied.
1 file(s) copied.
1 file(s) copied.
1 file(s) copied.
A subdirectory or file tmp already exists.

Hotfixed broken JSON file from OpenAI
"torch and torchvision have already been installed."
"sdkit is already installed."
sdkit version: 1.0.35
stable-diffusion version: 2.1.1
"rich has already been installed."
"Packages necessary for Easy Diffusion were already installed"
"Data files (weights) necessary for Stable Diffusion were already downloaded. Us
ing the HuggingFace 4 GB Model."
"Data files (weights) necessary for GFPGAN (Face Correction) were already downlo
aded"
"Data files (weights) necessary for ESRGAN (Resolution Upscaling) x4plus were al
ready downloaded"
"Data files (weights) necessary for ESRGAN (Resolution Upscaling) x4plus_anime w
ere already downloaded"
"Data files (weights) necessary for the default VAE (sd-vae-ft-mse-original) wer
e already downloaded"

"Easy Diffusion installation complete! Starting the server!"

PYTHONPATH=C:\EasyDiffusion\installer_files\env\lib\site-packages
C:\EasyDiffusion\installer_files\env\python.exe
Python 3.8.5
No module 'xformers'. Proceeding without it.
C:\EasyDiffusion\installer_files\env\lib\site-packages\torch\cuda_init_.py:88
: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old
(found version 10010). Please update your GPU driver by downloading and installi
ng a new version from the URL: http://www.nvidia.com/Download/index.aspx Alterna
tively, go to: https://pytorch.org/ to install a PyTorch version that has been co
mpiled with your version of the CUDA driver. (Triggered internally at C:\actions
-runner_work\pytorch\pytorch\builder\windows\pytorch\c10\cuda\CUDAFunctions.cpp
:109.)
return torch._C._cuda_getDeviceCount() > 0
17:36:53.415 INFO MainThread started in server.py:19
C:\EasyDiffusion\stable-diffusion
17:36:53.435 INFO MainThread started at 07/28/23 17:36:53 server.py:20
17:36:54.267 INFO MainThread Scanned 4 models. Nothing model_manager.py:248
infected
17:36:54.277 WARNING MainThread WARNING: Could not find a device_manager.py:55
compatible GPU. Using the CPU, but this will be very slow!
17:36:54.283 INFO MainThread Start new Rendering Thread on task_manager.py:454
device: cpu
17:37:17.619 INFO cpu forcing full precision for device: cpu init.py:50
17:37:17.629 INFO cpu loading stable-diffusion model from init.py:22
C:\EasyDiffusion\models\stable-diffusion\sd-v1-4.ckpt to device:
cpu
17:39:06.723 ERROR cpu Error while loading stable-diffusion model_manager.py:45
model:
C:\EasyDiffusion\models\stable-diffusion\sd-v1-4.ckpt
17:39:06.732 ERROR cpu Error: data. DefaultCPUAllocator: model_manager.py:46
not enough memory: you tried to allocate 9437184 bytes.
17:39:06.741 ERROR cpu Consider removing the model from the model_manager.py:47
model folder.
17:39:07.612 INFO cpu Session 1690540644024 starting task task_manager.py:312
2049252080 on AMD64 Family 21 Model 16 Stepping 1,
AuthenticAMD
17:39:07.664 INFO cpu request: {'guidance_scale': 7.5, renderer.py:51
'height': 512,
'hypernetwork_strength': 0,
'negative_prompt': '',
'num_inference_steps': 25,
'num_outputs': 1,
'preserve_init_image_color_profile': False,
'prompt': 'Dragon',
'sampler_name': 'euler_a',
'seed': 3161840,
'width': 512}
17:39:07.699 INFO cpu task data: {'block_nsfw': False, renderer.py:52
'metadata_output_format': 'none',
'output_format': 'jpeg',
'output_quality': 75,
'request_id': 2049252080,
'save_to_disk_path': None,
'session_id': '1690540644024',
'show_only_filtered_image': True,
'stream_image_progress': False,
'stream_image_progress_interval': 5,
'upscale_amount': 4,
'use_face_correction': None,
'use_hypernetwork_model': None,
'use_stable_diffusion_model':
'C:\EasyDiffusion\models\stable-diffusion\sd-v1-4.ckpt',
'use_upscale': None,
'use_vae_model': None,
'vram_usage_level': 'balanced'}
17:39:07.754 INFO cpu Global seed set to 3161840 seed.py:65
17:39:07.911 ERROR cpu Traceback (most recent call last): task_manager.py:346
File "C:\EasyDiffusion\ui\easydiffusion\task_manager.py",
line 336, in thread_render
task.response = renderer.make_images(
File "C:\EasyDiffusion\ui\easydiffusion\renderer.py",
line 38, in make_images
images, seeds = make_images_internal(req, task_data,
data_queue, task_temp_images, step_callback)
File "C:\EasyDiffusion\ui\easydiffusion\renderer.py",
line 59, in make_images_internal
images, user_stopped = generate_images_internal(
File "C:\EasyDiffusion\ui\easydiffusion\renderer.py",
line 91, in generate_images_internal
images = generate_images(context, callback=callback,
**req.dict())
File
"C:\EasyDiffusion\installer_files\env\lib\site-packages\sdk
it\generate\image_generator.py", line 47, in
generate_images
raise RuntimeError("The model for Stable Diffusion has
not been loaded yet! If you've tried to load it, please
check the logs above this message for errors (while loading
the model).")
RuntimeError: The model for Stable Diffusion has not been
loaded yet! If you've tried to load it, please check the
logs above this message for errors (while loading the
model).

17:39:08.169 INFO cpu Session 1690540644024 task 2049252080 task_manager.py:355
failed!

**Comment by cmdr2** [comment]
Hi @CosmicDreamer9653 The log shows this warning: `The NVIDIA driver on your system is too old (found version 10010). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx`

Please update your NVIDIA driver (if possible), and try again.

And your PC is running out of system RAM, it prints this error: `DefaultCPUAllocator: not enough memory`.

Please add more virtual memory by following these instructions: https://www.ibm.com/docs/en/bpm/8.5.6?topic=environment-tuning-your-windows-virtual-memory-settings

Please feel free to reopen this issue if it doesn't get solved after that.

**Comment by CosmicDreamer9653** [comment]
Good day to everyone again. I updated the drivers and tried to start the neural network again. The model no longer swears, but now this error pops up (In red it says here "The device connected to the system does not work"): 
![image](https://github.com/easydiffusion/easydiffusion/assets/140807009/0c23fc6c-e336-4cae-bca2-78550b087a37)

It seems that the problem is in the drivers, so I'll experiment with installing others. However, I really hope for your help with such an error
...............................................................................................................................................................................................

Install dir: C:\EasyDiffusion\
C:\EasyDiffusion\installer_files\env\Library\bin\git.exe
git version 2.41.0.windows.1
C:\EasyDiffusion\installer_files\env\Library\bin\conda.bat
C:\EasyDiffusion\installer_files\env\Scripts\conda.exe
conda 22.11.1

"Easy Diffusion - v2"

"Easy Diffusion's git repository was already installed. Updating from main.."
fatal: Unable to create 'C:/EasyDiffusion/sd-ui-files/.git/index.lock': File exi
sts.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
fatal: Unable to create 'C:/EasyDiffusion/sd-ui-files/.git/index.lock': File exi
sts.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
remote: Enumerating objects: 233, done.
remote: Counting objects: 100% (233/233), done.
remote: Compressing objects: 100% (114/114), done.
remote: Total 233 (delta 152), reused 194 (delta 118), pack-reused 0Receiving ob


Resolving deltas: 100% (152/152), completed with 13 local objects.
From https://github.com/cmdr2/stable-diffusion-ui
   b93c624e..4e444b41  beta       -> origin/beta
error: Unable to create 'C:/EasyDiffusion/sd-ui-files/.git/index.lock': File exi
sts.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
Updating 6158f494..710208f3
493 File(s) copied
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
A subdirectory or file tmp already exists.

Hotfixed broken JSON file from OpenAI
"torch and torchvision have already been installed."
"sdkit is already installed."
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status
=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.con
nection.HTTPSConnection object at 0x0000000004CBB970>: Failed to establish a new
 connection: [Errno 11004] getaddrinfo failed')': /simple/sdkit/
sdkit version: 1.0.35
stable-diffusion version: 2.1.1
"rich has already been installed."
"Packages necessary for Easy Diffusion were already installed"
"Data files (weights) necessary for Stable Diffusion were already downloaded. Us
ing the HuggingFace 4 GB Model."
"Data files (weights) necessary for GFPGAN (Face Correction) were already downlo
aded"
"Data files (weights) necessary for ESRGAN (Resolution Upscaling) x4plus were al
ready downloaded"
"Data files (weights) necessary for ESRGAN (Resolution Upscaling) x4plus_anime w
ere already downloaded"
"Data files (weights) necessary for the default VAE (sd-vae-ft-mse-original) wer
e already downloaded"

"Easy Diffusion installation complete! Starting the server!"

PYTHONPATH=C:\EasyDiffusion\installer_files\env\lib\site-packages
C:\EasyDiffusion\installer_files\env\python.exe
Python 3.8.5
No module 'xformers'. Proceeding without it.
C:\EasyDiffusion\installer_files\env\lib\site-packages\torch\cuda\__init__.py:88
: UserWarning: CUDA initialization: CUDA unknown error - this may be due to an i
ncorrectly set up environment, e.g. changing env variable CUDA_VISIBLE_DEVICES a
fter program start. Setting the available devices to be zero. (Triggered interna
lly at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\c10\cuda\
CUDAFunctions.cpp:109.)
  return torch._C._cuda_getDeviceCount() > 0
22:26:57.316 INFO MainThread started in                            server.py:19
C:\EasyDiffusion\stable-diffusion
22:26:57.394 INFO MainThread started at 08/01/23 22:26:57          server.py:20
22:26:58.236 INFO MainThread Scanned 4 models. Nothing     model_manager.py:248
infected
22:26:58.252 WARNING MainThread WARNING: Could not find a  device_manager.py:55
compatible GPU. Using the CPU, but this will be very slow!
22:26:58.268 INFO MainThread Start new Rendering Thread on  task_manager.py:454
device: cpu
22:27:37.783 INFO cpu forcing full precision for device: cpu     __init__.py:50
22:27:37.783 INFO cpu loading stable-diffusion model from        __init__.py:22
C:\EasyDiffusion\models\stable-diffusion\postapocalypse_v1.ckpt
to device: cpu
22:28:29.199 INFO cpu using config:                              __init__.py:45
C:\EasyDiffusion\installer_files\env\lib\site-packages\sdkit\mod
els\models_db\configs\v1-inference.yaml
22:28:29.309 INFO cpu using attn_precision: fp32                 __init__.py:51
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
Downloading:   0%|                                  | 0.00/939k [00:00<?, ?B/s]2
2:29:08.319 ERROR cpu Error while loading stable-diffusion model_manager.py:45
model:
C:\EasyDiffusion\models\stable-diffusion\postapocalypse_v1.
ckpt
22:29:08.330 ERROR cpu Error: [WinError 31]

**Comment by Harfang-svg** [comment]
у тебя в системе видеокарта отображается ?

**Comment by Harfang-svg** [comment]
вкладка "Экран" должна быть твоя видеокарта показана,или в диспетчере устройств

**Comment by CosmicDreamer9653** [comment]
> У тебя в системе видеокарта отображается ? вкладка "Экран" должна быть твоя видеокарта показана или в диспетчере устройств

Да, отображается в диспетчере устройств

**Comment by Harfang-svg** [comment]
Если проблема не решилась,тогда попробуй еще вот эту штуку поставить https://pytorch.org/

**Comment by Harfang-svg** [comment]
вот еще инфа по твоей теме
https://makesomecode.me/2021/07/cuda-cudnn-tf-pytorch-windows-installation/
