### ISSUE TITLE
SDXL "Error: Could not load the stable-diffusion model! Reason: 'ModuleList' object has no attribute '1'"

### ISSUE THREAD

**Issue by ufuksarp** [easydiffusion/easydiffusion#1438]
Tried to use DreamShaper XL1.0 Alpha2 SDXL model from Civit.ai, gives this error regardless of sampler.

Console log: [Easy Diffusion.txt](https://github.com/easydiffusion/easydiffusion/files/12193926/Easy.Diffusion.txt)

**Comment by dredshep** [comment]
i got a different error

![image](https://github.com/easydiffusion/easydiffusion/assets/78047001/6fc00578-f0ec-4db8-8493-bea4faff87d3)

**Comment by PVZ82** [comment]
Same error for me. I run on CPU... SDXL does not load

**Comment by check-m4te** [comment]
Same error

**Comment by DeeBeeDouble** [comment]
Same for me as well. Linux and AMD.

**Comment by CHJ85** [comment]
Same here. Any update?

**Comment by zephyo** [comment]
Same here u_u

**Comment by bugsebe** [comment]
I'm on the GPU and this fucking pile of shit won't load it there either.

**Comment by ufuksarp** [comment]
Maybe it’s time to jump ship for now. Latest updates made it basically unusable for me, and the quality is not good (blurry faces and others). I’ll try Automatic1111 and ComfyUI in the meantime.

**Comment by CHJ85** [comment]
I have A1111 installed just in case things like this happen.
I don't like using it though. Because even though it's a powerhouse, it's also ugly as sin and a bit unorganized. Whereas Easy Diffusion has some of the cleanest and most organized UI's.

**Comment by osem598** [comment]
same issue, Linux +AMD

**Comment by grilder** [comment]
Тоже не работает, ошибка Error: Could not load the stable-diffusion model! Reason: 'ModuleList' object has no attribute '1'

**Comment by JeLuF** [comment]
SDXL files need a yaml config file. This file needs to have the same name as the model file, with the suffix replaced by `.yaml`

So if your model file is called `dreamshaperXL10_alpha2Xl10.safetensors`, 
your config file must be called `dreamshaperXL10_alpha2Xl10.yaml`.

You can use this [yaml config file](https://gist.githubusercontent.com/JeLuF/5dc56e7a3a6988265c423f464d3cbdd3/raw/4ba4c39b1c7329877ad7a39c8c8a077ea4b53d11/dreamshaperXL10_alpha2Xl10.yaml) and rename it as needed.

**Comment by CHJ85** [comment]
@JeLuF Can I use this file for every SDXL based model? Most of them do not come with a yaml file. I.e this one: https://civitai.com/models/84040?modelVersionId=133118

**Comment by grilder** [comment]
> SDXL files need a yaml config file. This file needs to have the same name as the model file, with the suffix replaced by `.yaml`
> 
> So if your model file is called `dreamshaperXL10_alpha2Xl10.safetensors`, your config file must be called `dreamshaperXL10_alpha2Xl10.yaml`.
> 
> You can use this [yaml config file](https://gist.githubusercontent.com/JeLuF/5dc56e7a3a6988265c423f464d3cbdd3/raw/4ba4c39b1c7329877ad7a39c8c8a077ea4b53d11/dreamshaperXL10_alpha2Xl10.yaml) and rename it as needed.

Лучший! Всё работает чётко!

**Comment by JeLuF** [comment]
The yaml file is no longer required in the newest version of the beta.

**Comment by CHJ85** [comment]
Thanks @JeLuF 
That's great! 👍
