### ISSUE TITLE
If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.

### ISSUE THREAD

**Issue by Rosiko** [easydiffusion/easydiffusion#1440]
**Describe the bug**
First RUN on Windows 11. No error during the installation.
Web server started successfully and after typing the prompt, I click on "make image". After a few seconds it fails:

`Error: Could not load the stable-diffusion model! Reason: Unable to load weights from pytorch checkpoint file for 'C:\EasyDiffusion\profile\.cache\huggingface\hub\models--openai--clip-vit-large-patch14\snapshots\8d052a0f05efbaefbc9e8786ba291cfdf93e5bff\pytorch_model.bin' at 'C:\EasyDiffusion\profile\.cache\huggingface\hub\models--openai--clip-vit-large-patch14\snapshots\8d052a0f05efbaefbc9e8786ba291cfdf93e5bff\pytorch_model.bin'. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.`

Already tried to reboot and reinstall by deleting all the content in the installation folder (in my case C:\EasyDiffusion)

Below extract ENV
`"Environment Info:"
C:\Program Files\Git\cmd\git.exe
git version 2.39.0.windows.2
C:\EasyDiffusion\installer_files\env\Library\bin\conda.bat
C:\EasyDiffusion\installer_files\env\Scripts\conda.exe
C:\EasyDiffusion\installer_files\env\condabin\conda.bat
conda 22.11.1

C:\EasyDiffusion\installer_files\env\python.exe
C:\Users\UserID\AppData\Local\Programs\Python\Python310\python.exe
C:\Users\UserID\AppData\Local\Microsoft\WindowsApps\python.exe
Python 3.8.5
PYTHONPATH=C:\EasyDiffusion\installer_files\env\lib\site-packages`

**Screenshots**
![image](https://github.com/easydiffusion/easydiffusion/assets/96115536/2d49f3ae-8788-4403-a8f1-5955d3792ac8)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome

**Comment by Rosiko** [comment]
Apparently same issue as https://github.com/easydiffusion/easydiffusion/issues/1411

The suggested operation does not solve.
Also attempted complete deletion and complete reinstallation of the package, but the outcome does not change

**Comment by JeLuF** [comment]
Please delete the folder, as suggested in #1411, then restart EasyDiffusion and trigger the generation of an image. Then, copy all the text from the EasyDiffusion console window and upload it to this ticket. On Windows 10, you can use these 6 clicks to copy the entire text:
![image](https://github.com/easydiffusion/easydiffusion/assets/5852422/d05d6b2d-e485-4343-9214-cf7c20e5d6b3)

**Comment by Rosiko** [comment]
Thank you so much for the almost immediate response.

Below is the required output (only note, I use Windows 11)

`
Install dir: C:\EasyDiffusion\
C:\Program Files\Git\cmd\git.exe
git version 2.39.0.windows.2
C:\EasyDiffusion\installer_files\env\Library\bin\conda.bat
C:\EasyDiffusion\installer_files\env\Scripts\conda.exe
conda 22.11.1

"Easy Diffusion - v2"

"Easy Diffusion's git repository was already installed. Updating from main.."
HEAD is now at 710208f3 Update README.md
Already on 'main'
Your branch is up to date with 'origin/main'.
Already up to date.
499 File copiati
        1 file copiati.
        1 file copiati.
        1 file copiati.
        1 file copiati.
        1 file copiati.
        1 file copiati.
        1 file copiati.
        1 file copiati.
Sottodirectory o file tmp già esistente.
torch: 1.13.1+cu116
torchvision: 0.14.1+cu116
sdkit: 1.0.112
stable-diffusion-sdkit: 2.1.4

"Easy Diffusion installation complete! Starting the server!"

PYTHONPATH=C:\EasyDiffusion\installer_files\env\lib\site-packages
C:\EasyDiffusion\installer_files\env\python.exe
C:\Users\feder\AppData\Local\Programs\Python\Python310\python.exe
C:\Users\feder\AppData\Local\Microsoft\WindowsApps\python.exe
Python 3.8.5
No module 'xformers'. Proceeding without it.
16:09:32.818 INFO MainThread started in C:\EasyDiffusion\stable-diffusion                                   server.py:20
16:09:32.822 INFO MainThread started at 07/29/23 16:09:32                                                   server.py:21
stable-diffusion model(s) found.
gfpgan model(s) found.
realesrgan model(s) found.
vae model(s) found.
16:09:32.830 INFO MainThread Scanning all model folders for models...                               model_manager.py:370
16:09:32.934 INFO MainThread Scanned 3 models. Nothing infected                                     model_manager.py:379
16:09:33.019 INFO MainThread Start new Rendering Thread on device: cuda:0                            task_manager.py:467
16:09:33.507 INFO cuda:0 Device usage during initialization:                                              renderer.py:48
16:09:33.515 INFO cuda:0 CPU utilization: 2.9%, System RAM used: 8.4 of 15.9 GiB, GPU RAM used        memory_utils.py:44
(cuda:0): 1.1 of 8.0 GiB (peak: 0.0 GiB)
16:09:33.516 INFO cuda:0 Setting cuda:0 as active, with precision: half                            device_manager.py:154
16:09:33.518 INFO cuda:0 loading stable-diffusion model from                                              __init__.py:36
C:\EasyDiffusion\models\stable-diffusion\sd-v1-4.ckpt to device: cuda:0
╭────────────────────────────────────────────── Easy Diffusion is ready ───────────────────────────────────────────────╮
│                                                                                                                      │
│ Easy Diffusion is ready to serve requests.                                                                           │
│                                                                                                                      │
│ A new browser tab should have been opened by now.                                                                    │
│ If not, please open your web browser and navigate to http://localhost:9000/                                          │
│                                                                                                                      │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
16:09:35.060 INFO AnyIO worker thread Scanning all model folders for models...                      model_manager.py:370
16:09:36.346 INFO cuda:0 using config:                                                                    __init__.py:75
C:\EasyDiffusion\installer_files\env\lib\site-packages\sdkit\models\models_db\configs\v1-inference.yaml
16:09:36.359 INFO cuda:0 using attn_precision: fp16                                                       __init__.py:81
LatentDiffusion: Running in eps-prediction mode
16:09:39.504 ERROR cuda:0 Error while loading stable-diffusion model:                                model_manager.py:74
C:\EasyDiffusion\models\stable-diffusion\sd-v1-4.ckpt
16:09:39.506 ERROR cuda:0 Your PC is low on system RAM. Please add some virtual memory (or swap      model_manager.py:76
space) by following the instructions at this link:
https://www.ibm.com/docs/en/opw/8.2.0?topic=tuning-optional-increasing-paging-file-size-windows-comp
uters
16:09:39.822 INFO cuda:0 loading vae model from                                                           __init__.py:36
C:\EasyDiffusion\models\vae\vae-ft-mse-840000-ema-pruned.ckpt to device: cuda:0
16:09:40.081 INFO cuda:0 loaded vae model from                                                            __init__.py:40
C:\EasyDiffusion\models\vae\vae-ft-mse-840000-ema-pruned.ckpt to device: cuda:0
16:11:22.961 INFO cuda:0 Session 1690639774975 starting task 2031436810224 on NVIDIA GeForce RTX     task_manager.py:314
3070 Ti
16:11:22.967 INFO cuda:0 loading stable-diffusion model from                                              __init__.py:36
C:\EasyDiffusion\models\stable-diffusion\sd-v1-4.ckpt to device: cuda:0
16:11:25.550 INFO cuda:0 using config:                                                                    __init__.py:75
C:\EasyDiffusion\installer_files\env\lib\site-packages\sdkit\models\models_db\configs\v1-inference.yaml
16:11:25.563 INFO cuda:0 using attn_precision: fp16                                                       __init__.py:81
LatentDiffusion: Running in eps-prediction mode
16:11:28.753 ERROR cuda:0  data. DefaultCPUAllocator: not enough memory: you tried to allocate      model_manager.py:170
3932160 bytes.
Traceback (most recent call last):
  File "C:\EasyDiffusion\ui\easydiffusion\model_manager.py", line 166, in
reload_models_if_necessary
    action_fn(context, model_type, scan_model=False)  # we've scanned them already
  File
"C:\EasyDiffusion\installer_files\env\lib\site-packages\sdkit\models\model_loader\__init__.py",
line 38, in load_model
    context.models = models.load_model(context, **kwargs)
  File
"C:\EasyDiffusion\installer_files\env\lib\site-packages\sdkit\models\model_loader\stable_diffusion\
__init__.py", line 84, in load_model
    model = instantiate_from_config(config.model)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\ldm\util.py", line 79, in
instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\ldm\models\diffusion\ddpm.py", line
550, in __init__
    super().__init__(conditioning_key=conditioning_key, *args, **kwargs)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\ldm\models\diffusion\ddpm.py", line
92, in __init__
    self.model = DiffusionWrapper(unet_config, conditioning_key)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\ldm\models\diffusion\ddpm.py", line
1314, in __init__
    self.diffusion_model = instantiate_from_config(diff_model_config)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\ldm\util.py", line 79, in
instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File
"C:\EasyDiffusion\installer_files\env\lib\site-packages\ldm\modules\diffusionmodules\openaimodel.py
", line 700, in __init__
    ) if not use_spatial_transformer else SpatialTransformer(
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\ldm\modules\attention.py", line 307,
in __init__
    [BasicTransformerBlock(inner_dim, n_heads, d_head, dropout=dropout, context_dim=context_dim,
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\ldm\modules\attention.py", line 307,
in <listcomp>
    [BasicTransformerBlock(inner_dim, n_heads, d_head, dropout=dropout, context_dim=context_dim,
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\ldm\modules\attention.py", line 261,
in __init__
    self.attn2 = attn_cls(query_dim=dim, context_dim=context_dim,
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\ldm\modules\attention.py", line 155,
in __init__
    self.to_k = nn.Linear(context_dim, inner_dim, bias=False)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\torch\nn\modules\linear.py", line
96, in __init__
    self.weight = Parameter(torch.empty((out_features, in_features), **factory_kwargs))
RuntimeError:  data. DefaultCPUAllocator: not enough memory: you tried to allocate 3932160 bytes.
16:11:29.031 ERROR cuda:0 Traceback (most recent call last):                                         task_manager.py:356
  File "C:\EasyDiffusion\ui\easydiffusion\task_manager.py", line 339, in thread_render
    model_manager.fail_if_models_did_not_load(renderer.context)
  File "C:\EasyDiffusion\ui\easydiffusion\model_manager.py", line 199, in
fail_if_models_did_not_load
    raise Exception(f"Could not load the {model_type} model! Reason: " + e)
Exception: Could not load the stable-diffusion model! Reason:  data. DefaultCPUAllocator: not enough
memory: you tried to allocate 3932160 bytes.

16:11:29.116 INFO cuda:0 Session 1690639774975 task 2031436810224 failed!                            task_manager.py:365`

while I was performing the requested operation, I noticed the "low memory" error
It seems to try to allocate almost 4MB (3932160 bytes) of Memory, and it fails.

Below you can find the current status on memory usage

![image](https://github.com/easydiffusion/easydiffusion/assets/96115536/a1a27e45-98fa-4199-8fa3-ec29635d1357)

**Comment by Rosiko** [comment]
After posting what you asked, saw the message about the memory and tried to restart the pc.
When I restarted the folder hadn't been re-downloaded yet so I tried to start EasyDiffusion.
He then re-downloaded the folder and now it works flawlessly.

Perhaps despite deleting the folder, something written remains somewhere?

Merging solution #1411 with restart actually fixed it.

However, now the free memory is slightly less than before .. it leaves me doubtful about the memory value indicated and which it would seem I can't use

**Comment by JeLuF** [comment]
> DefaultCPUAllocator: not enough memory: you tried to allocate 3932160 bytes.

Your system went out of paging space. Please increase your paging space, as described for example in this guide: https://www.ibm.com/docs/en/opw/8.2.0?topic=tuning-optional-increasing-paging-file-size-windows-computers

**Comment by Rosiko** [comment]
Thanks for the info, 
I sincerely thought you were talking about RAM and not pagefiles. But in this regard, even if I don't want to keep the thread open for anything else, is there a way to inhibit easydiffusion's use of the paging file? Honestly, having an M.2 SSD, I would like to minimize its usage and not increase it
