### ISSUE TITLE
where to put 'text_encoder' , and whether these files are needed

### ISSUE THREAD

**Issue by Harfang-svg** [easydiffusion/easydiffusion#1443]
https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/tree/main/text_encoder
where to put text_encoder ? and these files are needed for correct operation?

**Comment by cmdr2** [comment]
@Harfang-svg You only need to download this file: https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/resolve/main/sd_xl_base_1.0.safetensors

And save it to the `models/stable-diffusion` folder.

**Comment by cmdr2** [comment]
Added instructions to https://github.com/easydiffusion/easydiffusion/wiki/SDXL

**Comment by Harfang-svg** [comment]
Thanks you
