### ISSUE TITLE
Even though control net Poses support was added in v2.5.48 (beta) It does not appear in image settings

### ISSUE THREAD

**Issue by yaronelh** [easydiffusion/easydiffusion#1456]
**Describe the bug**
Control Image he is missing in the image settings of the latest beta

**To Reproduce**
Activate the beta and the diffusers restart the easy diffusion and get this
https://i.imgur.com/m9tfUfN.png

**Expected behavior**
According to documentation there should be a field called Control Image
https://github.com/easydiffusion/easydiffusion/wiki/ControlNet

**Desktop (please complete the following information):**
 - OS: WIN11
 - Browser: Chrome
 - Version: latest

**Comment by ex479** [comment]
It is on your screenshot and is called ControlNet Image. Click "Choose File" to load your image-file (or any special-type file if you have one)

**Comment by yaronelh** [comment]
👍
