### ISSUE TITLE
Win.Virus.Expiro-10004389-0

### ISSUE THREAD

**Issue by gnibz** [easydiffusion/easydiffusion#1461]
I was having a routine AV run with ClamWin and it detected Win.Virus.Expiro from files in the Easy Diffusion folders.

The results are the following:
EasyDiffusion\installer_files\env\Lib\site-packages\conda\shell\cli-32.exe: Win.Virus.Expiro-10004389-0 FOUND
EasyDiffusion\installer_files\env\Lib\site-packages\conda\shell\cli-64.exe: Win.Virus.Expiro-10004389-0 FOUND
EasyDiffusion\installer_files\env\pkgs\uvicorn-0.20.0-py38haa244fe_1\Scripts\uvicorn.exe: Win.Virus.Expiro-10004389-0 FOUND
EasyDiffusion\installer_files\env\Scripts\2to3.exe: Win.Virus.Expiro-10004389-0 FOUND
EasyDiffusion\installer_files\env\Scripts\conda-env.exe: Win.Virus.Expiro-10004389-0 FOUND
EasyDiffusion\installer_files\env\Scripts\conda.exe: Win.Virus.Expiro-10004389-0 FOUND
EasyDiffusion\installer_files\env\Scripts\idle.exe: Win.Virus.Expiro-10004389-0 FOUND
EasyDiffusion\installer_files\env\Scripts\menuinst.exe: Win.Virus.Expiro-10004389-0 FOUND
EasyDiffusion\installer_files\env\Scripts\pydoc.exe: Win.Virus.Expiro-10004389-0 FOUND
EasyDiffusion\installer_files\mamba\pkgs\conda-22.11.1-py38haa244fe_1\Lib\site-packages\conda\shell\cli-32.exe: Win.Virus.Expiro-10004389-0 FOUND
EasyDiffusion\installer_files\mamba\pkgs\conda-22.11.1-py38haa244fe_1\Lib\site-packages\conda\shell\cli-64.exe: Win.Virus.Expiro-10004389-0 FOUND
EasyDiffusion\installer_files\mamba\pkgs\conda-22.11.1-py38haa244fe_1\Scripts\conda-env.exe: Win.Virus.Expiro-10004389-0 FOUND
EasyDiffusion\installer_files\mamba\pkgs\conda-22.11.1-py38haa244fe_1\Scripts\conda.exe: Win.Virus.Expiro-10004389-0 FOUND
EasyDiffusion\installer_files\mamba\pkgs\menuinst-1.4.19-py38haa244fe_1\Scripts\menuinst.exe: Win.Virus.Expiro-10004389-0 FOUND
EasyDiffusion\installer_files\mamba\pkgs\menuinst-1.4.19-py38haa244fe_1.tar.bz2: Win.Virus.Expiro-10004389-0 FOUND
EasyDiffusion\installer_files\mamba\pkgs\python-3.8.5-h60c2a47_9_cpython\Scripts\2to3.exe: Win.Virus.Expiro-10004389-0 FOUND
EasyDiffusion\installer_files\mamba\pkgs\python-3.8.5-h60c2a47_9_cpython\Scripts\idle.exe: Win.Virus.Expiro-10004389-0 FOUND
EasyDiffusion\installer_files\mamba\pkgs\python-3.8.5-h60c2a47_9_cpython\Scripts\pydoc.exe: Win.Virus.Expiro-10004389-0 FOUND
EasyDiffusion\installer_files\mamba\pkgs\python-3.8.5-h60c2a47_9_cpython.tar.bz2: Win.Virus.Expiro-10004389-0 FOUND

I'm running on Windows 10. Is this a false positive?

**Comment by cmdr2** [comment]
Hi @gnibz The version we distribute is free from viruses. It's scanned before release, and has been running on everyone's PCs without issues.

I can't say whether it's a false positive in your case, since your PC might have an infection separately. If no other files on your PC show up as Win.Virus.Expiro, then yeah it's probably a false positive.In either case, it might be better to delete the Easy D
