### ISSUE TITLE
Slow on MacBook Pro M1, 16 GB

### ISSUE THREAD

**Issue by alexgol55** [easydiffusion/easydiffusion#1468]
How i can improve rendering speed? Its take about 8 min to make pictures with that settings, is it ok?

<img width="444" alt="Снимок экрана 2023-08-04 в 10 10 24" src="https://github.com/easydiffusion/easydiffusion/assets/141376990/2f3d4a21-25af-4b57-966d-2c48f980530c">

<img width="492" alt="Снимок экрана 2023-08-04 в 10 10 35" src="https://github.com/easydiffusion/easydiffusion/assets/141376990/bf62dd25-e299-4517-955f-38781fc77dca">

<img width="605" alt="Снимок экрана 2023-08-04 в 10 10 50" src="https://github.com/easydiffusion/easydiffusion/assets/141376990/4235c09f-4bd6-468a-9b40-d0dd4d8ffa11">

**Comment by bZichett** [comment]
You should definitely not expect to render images with that resolution any faster than minutes (8 seems reasonable)

Try rendering 512 x 512 or less.  You should see exponentially faster speeds, possibly bearable.  You'll need a GPU with a dedicated power supply to render at that resolution in a reasonable time frame.  

Final note: laptops are not built for this.  I suggest buying a desktop with a reasonable GPU (customizable)
