### ISSUE TITLE
UnsupportedOperatorError: Exporting 'aten::scaled_dot_product_attention' to ONNX opset version 17

### ISSUE THREAD

**Issue by iamhumanipromise** [easydiffusion/easydiffusion#1470]
### This Bug Report has been filed on the PyTorch GitHub Repo as [Linked Here](https://github.com/pytorch/pytorch/issues/106612)

Please see above for contents of bug. 

### Reason for Requesting a Solution: 

With prior versions of Easy Diffusion using a 2070 Max Q with TensorRT +ONNX, 1024x1024 images generated at roughly 2.4it/s on an RTX 2070 Max Q. I now have a laptop with RTX 4090 and get approximately 2.7-2.99 it/s. There is something wrong with the power:performance ratio. 

**EasyDiffusion-Specific:** For easy diffusion specific items I have the onnx, tensorrt, nvidia-tensorrt and pytorch-tensorrt plugings installed. I checked the box in the WebUI to enable tensorrt for faster/adjacent processing along with CUDA cores. 

## AdditionalInfo

(Unknown to me right now is if parallel processing occurs using CUDA/Tensor/Ray Tracing cores; hence trying the option linked above. Was hoping ultimately for it to use onnx to process on CUDA, Tensor, RTX cores and CPU cores with AVX512-NNI and other modern neural-net focused CPU extensions. (Just blast out generation)

**Comment by cmdr2** [comment]
Hi @iamhumanipromise This has been fixed in the latest version of Easy Diffusion. Please restart and try again. Thanks
