### ISSUE TITLE
Seamless Tiling seems to never work

### ISSUE THREAD

**Issue by Bacaliu** [easydiffusion/easydiffusion#1479]
**Describe the bug**
The settings for seamless tiling don't change the image at all.

**To Reproduce**
1. make similar images
2. select different options in *seamless tiling*

**Expected behavior**
The resulting images should be tileable most of the time.

**Screenshots**
Here I produced the same image with all the 4 possible tiling-settings.:
![grafik](https://github.com/easydiffusion/easydiffusion/assets/83137280/5b7dc919-9d9a-411a-b918-3b0e60ad1cdd)

Here I tried to make x-tiling images with different stable-diffusion-models:
![grafik](https://github.com/easydiffusion/easydiffusion/assets/83137280/1becbac3-5132-4bfa-9cfe-889a46e37846)

**Desktop (please complete the following information):**
 - OS: Arch Linux 6.4.8
 - Browser: Firefox 116.0.1
 - Version: Easy Diffusion v3.0.0 (beta)

**Additional context**
I tried diffrent prompts, samplers, etc. Since the [help-page](https://github.com/easydiffusion/easydiffusion/wiki/Seamless-Tiling) does not show any suggestions or restrictions regarding the settings, I have to conclude that this is a bug.

**Comment by Vadimluck** [comment]
It stopped working for me too, but it was working before the update. (I didn't make any changes myself)

**Comment by JeLuF** [comment]
It was still working in sdkit 1.0.137 from July24.

https://github.com/easydiffusion/sdkit/pull/55

This test works in sdkit 1.0.137 (the last pre-controlnet version), but fails in recent versions of sdkit.

**Comment by cmdr2** [comment]
Thanks, taking a look

**Comment by JeLuF** [comment]
The new EasyDiffusion 3.0 release contains a fix to the tiling code. Please restart EasyDiffusion to update it.
