### ISSUE TITLE
inpaint dont work in 3.0.0 beta with new v3 enabled

### ISSUE THREAD

**Issue by LachundSach** [easydiffusion/easydiffusion#1484]
I make a pic  768x512
prompt wild west
inpaint the lower half
prompt ocean
 without v3 enabled all fine
v3 enabled give me this error

Error: index 1 is out of bounds for dimension 0 with size 1

 - OS: windows 10 pro 64
 - Browser: chrome 
 - Version: Version 115.0.5790.171 (Offizieller Build) (64-Bit)

cheers

**Comment by LachundSach** [comment]
Ok with DDIM it is working, in v3 but seems the only one
thx anyway

**Comment by ex479** [comment]
> Ok with DDIM it is working, in v3 i did a small batch with samplers and seems all working exept heun, dpm2, dpm2_a, dpmpp_sde

Do you have karras samplers (dpm++) interrupted in the middle, giving out unfinished img2img results too?

**Comment by LachundSach** [comment]
I got no interrupt but with karras often nothing added to the picture tho

**Comment by JeLuF** [comment]
The new 3.0 version of EasyDiffusion now supports any inpainting model. Please restart EasyDiffusion to update it.
