### ISSUE TITLE
Error: [WinError 233] No hay ningún proceso en el otro extremo de la canalización

### ISSUE THREAD

**Issue by WITRRA** [easydiffusion/easydiffusion#1487]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser:
 - Version:

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

**Comment by WITRRA** [comment]
Quiero usar easy diffusion pero al poner el promp y generar la imagen me sale el error del titulo,
Estoy trabajando en una laptop con procesador Intel I7 decima gen, con una targeta grafica nvidia 3060 6gb y 32 gb RAM

**Comment by cmdr2** [comment]
Duplicate of https://github.com/easydiffusion/easydiffusion/issues/1488
