### ISSUE TITLE
Error: Could not load the lora model! Reason: 'StableDiffusionXLPipeline' object has no attribute 'lora'

### ISSUE THREAD

**Issue by CHJ85** [easydiffusion/easydiffusion#1489]
I'm trying to use an XL 1.0 trained lora on SDXL base 1.0, but I'm getting this error message: Error: Could not load the lora model! Reason: 'StableDiffusionXLPipeline' object has no attribute 'lora'.
Idk if this is a bug or what. I doubt it's related to the lora itself, because I've tried a few different ones from 
I've tried a few loras. Like this one https://civitai.com/models/122660?modelVersionId=133627 and this one https://civitai.com/models/119416?modelVersionId=129732
Oh, and I also tried the example lora that comes with SD XL just to be sure.

**Comment by JeLuF** [comment]
SDXL Lora support has been added. Please restart EasyDiffusion to update to the latest version.

**Comment by CHJ85** [comment]
I saw that. I forgot to close this one.
Thank you @JeLuF 👍
