### ISSUE TITLE
Is it any way to install without conda?

### ISSUE THREAD

**Issue by ke1ne** [easydiffusion/easydiffusion#1492]
Hi, I would like to install and run the project via ancient way using `python -m venv venv`, and with no conda stuff. Is it possible?
Thank you, guys!

**Comment by JeLuF** [comment]
It's probably possible, but not supported. EasyDiffusion provides its own python environment, independent from other environments on your computer. To activate it, it uses conda.

**Comment by ke1ne** [comment]
@JeLuF Yea, I use a separate Python venv for each project. I just didn't want to use Conda/Mamba for this to avoid billions of files separated. It does this too much, on my opinion. Thanks
