### ISSUE TITLE
Help me pls. I have problem with EasyDiffusion

### ISSUE THREAD

**Issue by FLA1tes** [easydiffusion/easydiffusion#1495]
hello everyone. 
![Снимок экрана (138)](https://github.com/easydiffusion/easydiffusion/assets/142105792/22437d0f-0f4b-4953-bd60-052592848a25)
 I downloaded LoRA and copied along the way EasyDiffusion/models/lora. But it still gives me the same error. What I need to do?

**Comment by ex479** [comment]
Your LoRA is SDXL type. It works only with SD-XL models. There are many types (versions) of models - 1.4, 1.5, 2.0, 2.1, sdxl etc. Make sure you use the exact type of lora and basic models together.

**Comment by FLA1tes** [comment]
> Ваш LoRA относится к типу SDXL. Работает только с моделями SD-XL. Есть много типов (версий) моделей - 1.4, 1.5, 2.0, 2.1, sdxl и т. д. Убедитесь, что вы используете точный тип лора и базовых моделей вместе.

Thanks, i understood
