### ISSUE TITLE
PIXEL ART SUPPORT

### ISSUE THREAD

**Issue by wisamidris7** [easydiffusion/easydiffusion#1497]
There Are Many Arts But I Want PEXEL Art For My PEXEL Game Or To Learn From Ai Drawing

So Can You Support Pixel Art I Also Downloaded Pixel Art Model 4.1GB

https://huggingface.co/kohbanye/pixel-art-style

So Can I Use It To Pixel Art
Or I Can Use It With Offical Stable Diffusion Model

**Comment by bZichett** [comment]
What happens when you add the model checkpoint file to the stable diffusion model folder and try using it?

**Comment by wisamidris7** [comment]
and this not issue this feature request

**Comment by JeLuF** [comment]
- Download the file https://huggingface.co/kohbanye/pixel-art-style/resolve/main/pixel-art-style.ckpt from the model page
- In your EasyDiffusion installation directory, save the file into the `models/stable-diffusion` folder
- Click the small "refresh" icon next to the models dropdown in the "Image Settings" section
- Select the model from the dropdown
- Make an image
