### ISSUE TITLE
LyCORIS support (maybe w/ KohakuBlueleaf)

### ISSUE THREAD

**Issue by 71cj34** [easydiffusion/easydiffusion#1508]
**Is your feature request related to a problem? Please describe.**
Since LyCORIS has been out for a while now, it makes sense to establish a way to use LyCORIS files, especially considering how many external modules now use LyCORIS instead of Lora. As more and more LyCORIS files become available, it will be even more frustrating to not be able to use them on probably the number one most accessible webui, especially to those without a good understanding of computers.

**Describe the solution you'd like**
An implementation of LyCORIS support, whether custom made or imported from another source.

**Describe alternatives you've considered**
Since Automatic1111 has support for [KohakuBlueleaf's LyCORIS plugin](https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris), we could always just shove support for the extension into EasyDiffusion as well. 

**Additional context**
The only reason why I think KohakuBlueleaf doesn't work is because of its three methods of installation:

> There are some options you can choose to install this extension
>  
> - Open the extension tab and go to "available" tab, search "lycoris" to find this extension and then install it.
> - Open the extension tab and go to "from url" tab, copy-paste the url of this repo (https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris) and click install.
> - Manually clone this repo to the extension folder or download the zip.

The first two, as far as I can tell, are unique to the original Automatic1111 webui, and as to the third one, I can't find an "extension folder" to clone the repo to, unless I'm stupid and just didn't find it. Anyways, at minimum, you should link the method on how to install KohakuBlueleaf inside EasyDiffusion's Help menu (assuming that it is possible to install KohakuBlueleaf with EasyDiffusion, again, it should be possible because it probably works on all Automatic1111 webuis, but idk).

**Comment by cmdr2** [comment]
Hi @71cj34 I agree. Tracking lycoris in this issue https://github.com/easydiffusion/easydiffusion/issues/1508
