### ISSUE TITLE
ControlNet OpenPose

### ISSUE THREAD

**Issue by mynamemeansdog** [easydiffusion/easydiffusion#1515]
**Describe the bug**
when using an open pose png (full, or *), instead of having it generate one from an image, it erases the lines and uses a full black image as it's control net.

**To Reproduce**
1. select any open pose image
2. enqueue image
3. look at controlnet image preview to see a full black image with no open pose skeleton.
4. see that the image generated does not reflect the openpose image you selected as an input

**Expected behavior**
An open pose skeleton should be visible as the control net input
The image should resemble the input.

**Desktop (please complete the following information):**c
 - OS: Windows 10 pro
 - Browser: firefox
 - Version:  v3.0.1 (beta)

**Comment by cmdrgrunt** [comment]
It sounds like you may be selecting the pre processor (filter) for openpose when it isn't needed. It tries to extract a pose from the stick image and ends up generating a black void. 

If you have an existing openpose stick image you would like to use, place it in controlnet as usual, but set the "filter" to none, and model to "Openpose". It will skip the extraction and use your existing "stickman" pose for the image.

![image](https://github.com/easydiffusion/easydiffusion/assets/137791079/21e34967-bd1a-4e4e-9306-694c2f51c34b)

![image](https://github.com/easydiffusion/easydiffusion/assets/137791079/da292ad9-174a-462f-90d5-336cd99a4d56)

**Comment by mynamemeansdog** [comment]
> It sounds like you may be selecting the pre processor (filter) for openpose when it isn't needed. It tries to extract a pose from the stick image and ends up generating a black void.
> 
> If you have an existing openpose stick image you would like to use, place it in controlnet as usual, but set the "filter" to none, and model to "Openpose". It will skip the extraction and use your existing "stickman" pose for the image.
> 
> ![image](https://user-images.githubusercontent.com/137791079/262136300-21e34967-bd1a-4e4e-9306-694c2f51c34b.jpeg)
> 
> ![image](https://user-images.githubusercontent.com/137791079/262148511-0f7db3f8-cdb8-426a-981a-4c513be7ba77.jpeg)

That was it!  Thank you very much. Not bug then, User error 100%.
