### ISSUE TITLE
how to run safetensor file?

### ISSUE THREAD

**Issue by hiqsociety** [easydiffusion/easydiffusion#1520]
i've put the safetensor file inside models/stable diffusion directory and removed the original one. how to choose and run the safetensor file?

**Comment by cmdrgrunt** [comment]
Can you elaborate a little more about what you mean? Is this a model file? Are  you swapping out a checkpoint (.ckpt) for a .safetensors model?

Easy Diffusion should detect all valid models and present them to you in the models dropdown menu. If you don't see the one you want yet, click the little pink recycle button to refresh the model list, or restart Easy Diffusion. 
![image](https://github.com/easydiffusion/easydiffusion/assets/137791079/83042bac-b16d-45b4-bff1-533949604b57)

The model list doesn't display the file extension, so if you see your model in the list, it found it.

**Comment by cmdrgrunt** [comment]
I'm going to assume this question was sufficiently answered, and can be closed?
