### ISSUE TITLE
badhandv4 - embedded: 'LatentDiffusion' object is not subscriptable

### ISSUE THREAD

**Issue by Tremeres** [easydiffusion/easydiffusion#1537]
Hi there, 
I have a new bug?

**Describe the bug**
badhandv4 - embedded produces the following error: 'LatentDiffusion' object is not subscriptable

11:28:19.745 INFO cuda:0 loading embeddings model from                                                    __init__.py:44
\EasyDiffusion\models\embeddings\badhandv4.pt to device: cuda:0
11:28:19.749 ERROR cuda:0 'LatentDiffusion' object is not subscriptable                             model_manager.py:185
Traceback (most recent call last):
  File "\EasyDiffusion\ui\easydiffusion\model_manager.py", line 181, in
reload_models_if_necessary
    action_fn(context, model_type, scan_model=False, **extra_params)  # we've scanned them already
  File
"\EasyDiffusion\installer_files\env\lib\site-packages\sdkit\models\model_loader\__init__.p
y", line 46, in load_model
    context.models = get_loader_module(model_type).load_model(context, **kwargs)
  File
"\EasyDiffusion\installer_files\env\lib\site-packages\sdkit\models\model_loader\embeddings
.py", line 16, in load_model
    pipe = model["default"]
TypeError: 'LatentDiffusion' object is not subscriptable
11:28:19.763 ERROR cuda:0 Traceback (most recent call last):                                         task_manager.py:292
  File "\EasyDiffusion\ui\easydiffusion\task_manager.py", line 284, in thread_render
    task.run()
  File "\EasyDiffusion\ui\easydiffusion\tasks\render_images.py", line 74, in run
    model_manager.fail_if_models_did_not_load(context)
  File "\EasyDiffusion\ui\easydiffusion\model_manager.py", line 212, in
fail_if_models_did_not_load
    raise Exception(f"Could not load the {model_type} model! Reason: " + e)
Exception: Could not load the embeddings model! Reason: 'LatentDiffusion' object is not
subscriptable

**To Reproduce**
1.) copy embedded to \EasyDiffusion\models\embeddings\badhandv4.pt
2.) use (badhandv4) in negative prompts

**Expected behavior**
loaded without errors

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Version: Win 10

**Additional context**
The model: https://civitai.com/models/16993?modelVersionId=20068

Best regards, Tremeres

**Comment by JeLuF** [comment]
Which model are you trying to use the embedding with?

**Comment by Tremeres** [comment]
I used the default one "sd 1.4" and also this one majicmixSombre_v20. Both have the same error

**Comment by Tremeres** [comment]
Nevermind, I found the problem: I missed the option "Use the new v3 engine (diffusers)". I enabled this option and it does work now.

**Comment by cmdr2** [comment]
Thanks, resolving.
