### ISSUE TITLE
Error: Could not load the stable-diffusion model! Reason: Ran out of input

### ISSUE THREAD

**Issue by BogdanRos** [easydiffusion/easydiffusion#1540]
Help me please!
The first prompt immediately after installation gives an error: Error: Could not load the stable-diffusion model! Reason: Ran out of input

Windows 10 Pro - OS: 
Chrome - Browser:

Install dir: E:\stabl\
E:\stabl\installer_files\env\Library\bin\git.exe
git version 2.40.1.windows.1
E:\stabl\installer_files\env\Library\bin\conda.bat
E:\stabl\installer_files\env\Scripts\conda.exe
conda 23.7.3
.
COMSPEC=C:\Windows\system32\cmd.exe

"Easy Diffusion - v3"

"Easy Diffusion's git repository was already installed. Updating from main.."
No local changes to save
HEAD is now at fc9941ab Merge pull request #1539 from easydiffusion/beta
Already on 'main'
Your branch is up to date with 'origin/main'.
Already up to date.
Скопировано файлов: 519.
Скопировано файлов:         1.
Скопировано файлов:         1.
Скопировано файлов:         1.
Скопировано файлов:         1.
Скопировано файлов:         1.
Скопировано файлов:         1.
Скопировано файлов:         1.
Скопировано файлов:         1.
Скопировано файлов:         1.
Скопировано файлов:         1.
Подпапка или файл tmp уже существует.
torch: 2.0.0+cu117
torchvision: 0.15.1+cu117
sdkit: 2.0.5
stable-diffusion-sdkit: 2.1.4

"Easy Diffusion installation complete! Starting the server!"

PYTHONPATH=E:\stabl\installer_files\env\lib\site-packages
E:\stabl\installer_files\env\python.exe
Python 3.8.5
23:25:39.622 INFO MainThread started in E:\stabl\stable-diffusion                                           server.py:29
23:25:39.638 INFO MainThread started at 08/30/23 23:25:39                                                   server.py:30
stable-diffusion model(s) found.
gfpgan model(s) found.
realesrgan model(s) found.
vae model(s) found.
23:25:40.517 INFO MainThread Start new Rendering Thread on device: cuda:0                            task_manager.py:408
23:25:40.517 INFO cuda:0 Device usage during initialization:                                               runtime.py:35
23:25:40.532 INFO cuda:0 CPU utilization: 12.9%, System RAM used: 5.3 of 7.8 GiB, GPU RAM used        memory_utils.py:47
(cuda:0): 0.8 of 4.0 GiB (peak: 0.0 GiB)
23:25:40.532 WARNING cuda:0 forcing full precision on this GPU, to avoid green images. GPU         device_manager.py:150
detected: NVIDIA GeForce GTX 1650 Ti
23:25:40.532 INFO cuda:0 Setting cuda:0 as active, with precision: full                            device_manager.py:154
23:25:41.016 INFO cuda:0 loading stable-diffusion model from                                              __init__.py:44
E:\stabl\models\stable-diffusion\sd-v1-4.ckpt to device: cuda:0
No module 'xformers'. Proceeding without it.
23:25:41.016 ERROR cuda:0 Error while loading stable-diffusion model:                                model_manager.py:82
E:\stabl\models\stable-diffusion\sd-v1-4.ckpt
23:25:41.016 ERROR cuda:0 pickle exhausted before seeing STOP                                        model_manager.py:88
Traceback (most recent call last):
  File "E:\stabl\ui\easydiffusion\model_manager.py", line 73, in load_default_models
    load_model(
  File "E:\stabl\installer_files\env\lib\site-packages\sdkit\models\model_loader\__init__.py", line
46, in load_model
    context.models = get_loader_module(model_type).load_model(context, **kwargs)
  File
"E:\stabl\installer_files\env\lib\site-packages\sdkit\models\model_loader\stable_diffusion\__init__.
py", line 48, in load_model
    scan_result = scan_model_fn(model_path)
  File "E:\stabl\installer_files\env\lib\site-packages\sdkit\models\scan_models.py", line 8, in
scan_model
    return picklescan.scanner.scan_file_path(file_path)
  File "E:\stabl\installer_files\env\lib\site-packages\picklescan\scanner.py", line 377, in
scan_file_path
    return scan_bytes(file, path, file_ext)
  File "E:\stabl\installer_files\env\lib\site-packages\picklescan\scanner.py", line 311, in
scan_bytes
    return scan_pytorch(data, file_id)
  File "E:\stabl\installer_files\env\lib\site-packages\picklescan\scanner.py", line 299, in
scan_pytorch
    magic = get_magic_number(data)
  File "E:\stabl\installer_files\env\lib\site-packages\picklescan\torch.py", line 77, in
get_magic_number
    for opcode, args, _pos in genops(data):
  File "E:\stabl\installer_files\env\lib\pickletools.py", line 2283, in _genops
    raise ValueError("pickle exhausted before seeing STOP")
ValueError: pickle exhausted before seeing STOP
23:25:41.517 INFO MainThread Opening browser..                                                                app.py:305
╭────────────────────────────────────────────── Easy Diffusion is ready ───────────────────────────────────────────────╮
│                                                                                                                      │
│ Easy Diffusion is ready to serve requests.                                                                           │
│                                                                                                                      │
│ A new browser tab should have been opened by now.                                                                    │
│ If not, please open your web browser and navigate to http://localhost:9000/                                          │
│                                                                                                                      │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
23:25:42.673 INFO AnyIO worker thread Scanning all model folders for models...                      model_manager.py:397
23:25:42.675 ERROR AnyIO worker thread error while scanning:                                        model_manager.py:301
E:\stabl\models\stable-diffusion\sd-v1-4.ckpt, error: pickle exhausted before seeing STOP
23:25:42.819 INFO AnyIO worker thread Scanned 3 models. Nothing infected                            model_manager.py:408
23:26:03.995 INFO cuda:0 Session 1693427142323 starting task 3023918804224 on NVIDIA GeForce GTX     task_manager.py:280
1650 Ti
23:26:04.045 INFO cuda:0 loading stable-diffusion model from                                              __init__.py:44
E:\stabl\models\stable-diffusion\sd-v1-4.ckpt to device: cuda:0
23:26:04.062 ERROR cuda:0 Ran out of input                                                          model_manager.py:185
Traceback (most recent call last):
  File "E:\stabl\ui\easydiffusion\model_manager.py", line 181, in reload_models_if_necessary
    action_fn(context, model_type, scan_model=False, **extra_params)  # we've scanned them already
  File "E:\stabl\installer_files\env\lib\site-packages\sdkit\models\model_loader\__init__.py", line
46, in load_model
    context.models = get_loader_module(model_type).load_model(context, **kwargs)
  File
"E:\stabl\installer_files\env\lib\site-packages\sdkit\models\model_loader\stable_diffusion\__init__
.py", line 55, in load_model
    sd = load_tensor_file(model_path)
  File "E:\stabl\installer_files\env\lib\site-packages\sdkit\utils\file_utils.py", line 15, in
load_tensor_file
    return torch.load(path, map_location="cpu")
  File "E:\stabl\installer_files\env\lib\site-packages\torch\serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "E:\stabl\installer_files\env\lib\site-packages\torch\serialization.py", line 1033, in
_legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
EOFError: Ran out of input
23:26:04.096 ERROR cuda:0 Traceback (most recent call last):                                         task_manager.py:292
  File "E:\stabl\ui\easydiffusion\task_manager.py", line 284, in thread_render
    task.run()
  File "E:\stabl\ui\easydiffusion\tasks\render_images.py", line 81, in run
    model_manager.fail_if_models_did_not_load(context)
  File "E:\stabl\ui\easydiffusion\model_manager.py", line 212, in fail_if_models_did_not_load
    raise Exception(f"Could not load the {model_type} model! Reason: " + e)
Exception: Could not load the stable-diffusion model! Reason: Ran out of input

23:26:04.195 INFO cuda:0 Session 1693427142323 task 3023918804224 failed!                            task_manager.py:302
23:26:50.477 INFO AnyIO worker thread Scanning all model folders for models...                      model_manager.py:397
23:26:54.014 INFO cuda:0 Session 1693427209656 starting task 3023918375264 on NVIDIA GeForce GTX     task_manager.py:280
1650 Ti
23:26:54.067 INFO cuda:0 loading stable-diffusion model from                                              __init__.py:44
E:\stabl\models\stable-diffusion\sd-v1-4.ckpt to device: cuda:0
23:26:54.069 ERROR cuda:0 Ran out of input                                                          model_manager.py:185
Traceback (most recent call last):
  File "E:\stabl\ui\easydiffusion\model_manager.py", line 181, in reload_models_if_necessary
    action_fn(context, model_type, scan_model=False, **extra_params)  # we've scanned them already
  File "E:\stabl\installer_files\env\lib\site-packages\sdkit\models\model_loader\__init__.py", line
46, in load_model
    context.models = get_loader_module(model_type).load_model(context, **kwargs)
  File
"E:\stabl\installer_files\env\lib\site-packages\sdkit\models\model_loader\stable_diffusion\__init__
.py", line 55, in load_model
    sd = load_tensor_file(model_path)
  File "E:\stabl\installer_files\env\lib\site-packages\sdkit\utils\file_utils.py", line 15, in
load_tensor_file
    return torch.load(path, map_location="cpu")
  File "E:\stabl\installer_files\env\lib\site-packages\torch\serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "E:\stabl\installer_files\env\lib\site-packages\torch\serialization.py", line 1033, in
_legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
EOFError: Ran out of input
23:26:54.075 ERROR cuda:0 Traceback (most recent call last):                                         task_manager.py:292
  File "E:\stabl\ui\easydiffusion\task_manager.py", line 284, in thread_render
    task.run()
  File "E:\stabl\ui\easydiffusion\tasks\render_images.py", line 81, in run
    model_manager.fail_if_models_did_not_load(context)
  File "E:\stabl\ui\easydiffusion\model_manager.py", line 212, in fail_if_models_did_not_load
    raise Exception(f"Could not load the {model_type} model! Reason: " + e)
Exception: Could not load the stable-diffusion model! Reason: Ran out of input

23:26:54.199 INFO cuda:0 Session 1693427209656 task 3023918375264 failed!                            task_manager.py:302

I deleted the file - package_manager and there was no result.
![image](https://github.com/easydiffusion/easydiffusion/assets/143657333/d2bf5a40-8340-4009-a2b6-5bdda12345f2)

**Comment by cmdr2** [comment]
Hi @BogdanRos It looks like the `models/stable-diffusion/sd-v1-4.ckpt` file is corrupted. Please delete it and restart Easy Diffusion. It'll automatically download it again, and fix the problem.

> I deleted the file - package_manager and there was no result.

Please don't delete files unnecessarily. Package manager has nothing to do with this problem.

Please feel free to reopen this issue if it's still a problem.

**Comment by BogdanRos** [comment]
Thank you, everything worked
