### ISSUE TITLE
2x and 4x Upscale option the only ones? I edited the html and 16x works?!

### ISSUE THREAD

**Issue by ClockLoop** [easydiffusion/easydiffusion#1550]
**Is your feature request related to a problem? Please describe.**
I had 16x scale available in the menu at one point and a new update removed it, and left me with only 2x and 4x.

**Describe the solution you'd like**
Any reason why we can't/shouldn't have many options in the upscaler?

**Describe alternatives you've considered**

```
                        <select id="upscale_amount" name="upscale_amount">
                            <option id="upscale_amount_2x" value="2">2x</option>
                            <option id="upscale_amount_4x" value="4">4x</option>
                            <option id="upscale_amount_6x" value="6">6x</option>
                            <option id="upscale_amount_8x" value="8">8x</option>
                            <option id="upscale_amount_12x" value="12">12x</option>
                            <option id="upscale_amount_16x" value="16" selected>16x</option>
                        </select>
```

Can any desired scale work here?  Is there a max (other than ram, and the limits of the png/jpg file writing code (it thinks large files are dos/attack)
I once had 16x available and it was from a plugin, but a recent update removed that, so I looked into why, and couldn't find out why, but I found I could just add the option in the sd-ui-files/ui/index.html file, and it just worked?!?

**Comment by cmdr2** [comment]
Can you please restart ED and try again? I pushed a fix about 13 hours ago that fixed a few plugins.

**Comment by ClockLoop** [comment]
It works again, just to be sure I updated the plugin also.
https://github.com/AssassinJN/Rabbit-Hole-UI/tree/master
