### ISSUE TITLE
ModuleNotFoundError: No module named 'regex'

### ISSUE THREAD

**Issue by grandell1234** [easydiffusion/easydiffusion#1566]
**Describe the bug**

**To Reproduce**
Run ./start.sh

**Expected behavior**
Boots up easydiffusion

**Screenshots**
![Screen Shot 2023-09-04 at 6 11 51 PM](https://github.com/easydiffusion/easydiffusion/assets/78573365/1f3b571c-c050-4c3b-8a43-259ecdae77c8)

**Desktop (please complete the following information):**
 - OS: macOS (Apple M1)
 - Browser: Not Needed
 - Version: 11.6.1

**Smartphone (please complete the following information):**
 - Device: Not Needed
 - OS: Not Needed
 - Browser: Not Needed
 - Version: Not Needed

**Additional context**
I have tried a bunch of bug fixing nothing works. I think it has to be python 3.7 but I am not sure. I downloaded python 3.7 but I have no idea how to make it run on python 3.7 instead of python 3.11.

**Comment by cmdr2** [comment]
Hi, did you follow these steps to install Easy Diffusion: https://github.com/easydiffusion/easydiffusion#installation

Please try those steps exactly, and let me know if that doesn't help. Thanks

**Comment by cmdr2** [comment]
Easy Diffusion includes Python 3.8.5, which it installs inside a contained environment (so it doesn't interfere with the rest of your PC). Please try the installation steps that I linked to. Thanks!

**Comment by grandell1234** [comment]
Those were the steps that I followed. FYI I am using macOS if you know a way of making sure I run it in a specific python version please tell me I believe that is my issue. (I am currently running python 3.10.

------- Original Message -------

**Comment by JeLuF** [comment]
Please run `./start.sh` and provide the entire output (as plain text).
