### ISSUE TITLE
Bad images quality with XL model

### ISSUE THREAD

**Issue by fx1234** [easydiffusion/easydiffusion#1570]
I use easy diffusion with Windows/Firefox.

All the images I create with the old SD model look very good.

All images I create with the new XL model are only artifacts, no matter how many inference steps I set:

![kids_illustration__dolphine__cartoon_style__thick_lines__low_detail__v_S1549028208_St140_G7 5](https://github.com/easydiffusion/easydiffusion/assets/37163623/083bc821-18b4-4fe2-bb5f-150b77d5bc26)

I tried different models, e.g.:
dreamshaperXL10_alpha2Xl10.safetensors
sd_xl_base_1.0.safetensors

**Comment by Menno5** [comment]
Try to use no VAE or a VAE XL. The older VAE give these effects.

**Comment by fx1234** [comment]
That seems to be the solution - thank you very much!
