### ISSUE TITLE
WMIC is not present in Windows 11

### ISSUE THREAD

**Issue by Menno5** [easydiffusion/easydiffusion#1574]
Not really a bug, more like extra info.

At startup, Easy Diffusion is looking for WMIC. But on current Windows 11 PC's (and I believe on newer Windows 10 also), WMIC is not standard installed anymore. It has to be added as an optional app.
This is in the start of the log:

`COMSPEC=C:\WINDOWS\system32\cmd.exe
'wmic' is not recognized as an internal or external command, operable program or batch file.`

Windows Management Instrumentation is running though. In "Services" it's running, with service name _Winmgmt_
I don't know if it is an issue for running Easy Diffusion (I've had no problems so far), but advise as offered in #1569 doesn't  work then.

Easy Diffusion v3.0.5 (beta)
Windows 11 Pro 22H2 22621.2134

**Comment by JeLuF** [comment]
Thanks for the heads up. The output is only there for debugging purposes, it doesn't impact the startup of the application.

There's a python WMIC client. I'll check whether it needs `wmic` or whether it directly talks to the service. If it works without, I'll move this step to `check_modules.py`.

**Comment by Menno5** [comment]
Okay, good to hear.

And yes, that might be more practical not being depended on a Windows app that might be or not be there :)
