### ISSUE TITLE
UI customization

### ISSUE THREAD

**Issue by byteswap-rpog** [easydiffusion/easydiffusion#1579]
I would like to customize the UI, for example disable the settings tab. This would be good to have when offering my platform to some friends.

**Comment by cmdr2** [comment]
Hi @byteswap-rpog Sorry but sharing over the network is not really the focus of Easy Diffusion.

While ED works across the network, preventing users from being able to edit settings across a network requires a decent amount of work.

Just hiding the settings tab won't prevent the ability for a user to save settings (it's still possible via API calls), and will give a false impression of security.

You're always free to edit the code if you'd like. Sorry I can't be of more help! :)

Thanks
