### ISSUE TITLE
Fails on Installation - Can't find rich module [Linux]

### ISSUE THREAD

**Issue by tooManyArguments** [easydiffusion/easydiffusion#1582]
**Describe the bug**
Check script fails to find rich python module on install.

**To Reproduce**

download zip:
https://github.com/cmdr2/stable-diffusion-ui/releases/latest/download/Easy-Diffusion-Linux.zip

 unzip, do:
./start.sh as normal user

**Expected behavior**
Installation should find the rich python module

**Screenshots**
![bild](https://github.com/easydiffusion/easydiffusion/assets/32525930/76d0f581-0019-43aa-94f5-242423edfdd3)

**Desktop (please complete the following information):**
 - OS: 
 Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy

 - Browser: N/A
 - Version: N/A

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: N/A
 - Browser N/A 
 - Version N/A

**Additional context**

**Comment by JeLuF** [comment]
My fault. As an interim workaround:
1. Please start `./developer_console.sh`
2. In this shell, run `python -m pip install rich`
3. run `./start.sh` again.

**Comment by cmdr2** [comment]
Thanks, fixed this in the main branch.
