### ISSUE TITLE
The latest update broke the embeddings menu

### ISSUE THREAD

**Issue by ex479** [easydiffusion/easydiffusion#1587]
**Describe the bug**
When I click on +embedding to browse the list I get an error about the line 58 in \ui\easydiffusion\bucket_manager.py
"`NonType` object has no attribute `id`". Maybe it's somehow related to the python modules versions.

**To Reproduce**
Click on +Embedding

**Expected behavior**
Reading the embedding files from the embeddings folder and populating the list of them.

**Desktop (please complete the following information):**
 - OS: Windows 7x64
 - Browser: 109.0.5414.120 64-bit
 - Version: EasyDiffusion 3.0.6 beta

**Comment by compactmicrowave** [comment]
Same issue here also.

**Comment by cmdr2** [comment]
Hi, this has been fixed in the latest beta. Please restart Easy Diffusion and try again. Thanks for reporting!

**Comment by compactmicrowave** [comment]
Thank you.
