### ISSUE TITLE
Inputing prompt through terminal.

### ISSUE THREAD

**Issue by lysergik** [easydiffusion/easydiffusion#1599]
Hi,

I would like to use easy diffusion but only in the terminal, inputing prompts and managing settings with commands instead of the web UI. I don't know how difficult it could be to implement myself if anyone as a clue of how I could add that myself it would be great.

**Comment by cmdr2** [comment]
Hi @lysergik Sorry but that's not the focus of this project. Please feel free to implement such a script using sdkit (our internal engine) - https://github.com/easydiffusion/sdkit

An example python script that generates an image using sdkit - https://github.com/easydiffusion/sdkit/blob/main/examples/001-generate-model_file_on_disk.py

Thanks!
