### ISSUE TITLE
How do I force saving prompts?

### ISSUE THREAD

**Issue by van1027** [easydiffusion/easydiffusion#1602]
**Describe the bug**
Easy diffusion doesn't store prompts when I set the "force_save_path" variable.

**To Reproduce**
1. in the config.yaml set the variable "force_save_path"
2. in the settings use the default settings
3. restart UI
4. generate some images
5. check the folder - prompts missing!

**Expected behavior**
save prompts next to the images

**Comment by cmdr2** [comment]
Hi @van1027 You don't need to edit config.yaml for this. Please try these steps:
1. Open the Settings tab in the UI
2. Enable "Save to Disk"
3. Select "text" or "json" in the embed metadata field (under the "Save to Disk" setting)
4. Generate an image.

You'll see a text or json file next to the image in the saved folder.

Please feel free to reopen this issue, if this doesn't work for you. Thanks!

**Comment by van1027** [comment]
Hi @cmdr2 Well, I said "force" for a reason, I want prompts to be changed for everyone, not just for me. I know how to do it myself only. Why would I mentioned config.yaml if I could do it for everyone via the UI?

**Comment by van1027** [comment]
Thank you for the change, I tested it, here are the results:
1) It defaults the metadata format to json. Before I had it txt selected, after restart it showed json selected.
2) I've changed it to none, saved, generated image - no metadata was saved.
3) I restarted the app again, in the settings I saw json selected. I generated an image - json metadata was saved.

**Comment by cmdr2** [comment]
Hi @van1027 Thanks for trying it out. I've changed the implementation, to allow a new `force_save_metadata` field in `config.yaml`.

So by default, it'll not enforce a metadata on users, but if you set `force_save_metadata: json` or `force_save_metadata: txt` in `config.yaml`, then that entry will be selected automatically when a user opens Easy Diffusion.

More info at https://github.com/easydiffusion/easydiffusion/wiki/Config-settings#prevent-users-from-changing-the-folder-path-to-save-images

Please let me know if this works for you, and addresses the problem. Thanks!

**Comment by van1027** [comment]
Thank you for making changes, I tested it, it works to a degree. Only they still can modify it in the settings and set to none. In that case it doesn't save prompts. So it doesn't really force it, only sets the default value.

**Comment by cmdr2** [comment]
@van1027 Okay, pushed another change, that disables the metadata dropdown if `force_save_metadata` is set. Please let me know if this works for you. Thanks!

**Comment by van1027** [comment]
Looks great! Thank you very much! It worked as you said, disables dropdown and saves the prompts.

**Comment by cmdr2** [comment]
Great, thanks!
