### ISSUE TITLE
Merge Models button doesn't work

### ISSUE THREAD

**Issue by wingstrong** [easydiffusion/easydiffusion#1609]
**Describe the bug**
Merge Models button doesn't work, it's grey and can't be pressed.
So I can't get into the merge menu.

Tried rebooting the neural network and the computer.

**Desktop:**
 - OS: Windows 10
 - Any browser
 
![rjdsrftrs](https://github.com/easydiffusion/easydiffusion/assets/113058670/ac6d2ab7-0871-4592-82b4-df5b34344c24)

**Comment by cmdr2** [comment]
Hi, sorry about that. Pushed a fix for this in https://github.com/easydiffusion/easydiffusion/pull/1611

Please restart Easy Diffusion and try again. Please let me know if it's still an issue, thanks!
