### ISSUE TITLE
ImportError: huggingface-hub>=0.15.1,<1.0 is required for a normal functioning 

### ISSUE THREAD

**Issue by scorpiomaj27** [easydiffusion/easydiffusion#1623]
**Started ED Like normal and fails with the above error:**
I was using ED like normal, closed it down to free up some system resources (memory) and when I restarted it's failing to launch with the above error.  (I've not changed any settings, nor added any LoRa's or Models.)

**To Reproduce**
1. Launch ED.

**Expected behavior**
No error.

**Desktop (please complete the following information):**
 - OS: W10
 - Browser: Firefox
 - Version:

**Additional context**

See full log below:

=====================

Install dir: C:\EasyDiffusion\
C:\Program Files\Git\cmd\git.exe
git version 2.41.0.windows.1
C:\EasyDiffusion\installer_files\env\Library\bin\conda.bat
C:\EasyDiffusion\installer_files\env\Scripts\conda.exe
conda 22.11.1
.
COMSPEC=C:\WINDOWS\system32\cmd.exe
AdapterRAM  DriverDate                 DriverVersion    Name
            20060621000000.000000-000  10.0.19041.2075  Microsoft Remote Display Adapter
268435456   20220110000000.000000-000  30.0.13040.6001  AMD Radeon(TM) Vega 8 Graphics

"Easy Diffusion - v3"

"Easy Diffusion's git repository was already installed. Updating from main.."
No local changes to save
HEAD is now at 307b00cc Merge pull request #1622 from easydiffusion/beta
Already on 'main'
Your branch is up to date with 'origin/main'.
Already up to date.
519 File(s) copied
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
A subdirectory or file tmp already exists.
PYTHONPATH=C:\EasyDiffusion\installer_files\env\lib\site-packages
C:\EasyDiffusion\installer_files\env\python.exe
C:\Users\maj28\AppData\Local\Programs\Python\Python310\python.exe
C:\Users\maj28\AppData\Local\Microsoft\WindowsApps\python.exe
Python 3.8.5
torch: 1.13.1+cu116
torchvision: 0.14.1+cu116
 python -m pip install --upgrade sdkit==2.0.14 -q
WARNING! Tried to install sdkit==2.0.14, but the version is still 1.0.35!
sdkit: 1.0.35
python -m pip install --upgrade stable-diffusion-sdkit==2.1.5
Requirement already satisfied: stable-diffusion-sdkit==2.1.5 in c:\easydiffusion\installer_files\env\lib\site-packages (2.1.5)
Requirement already satisfied: tqdm in c:\easydiffusion\installer_files\env\lib\site-packages (from stable-diffusion-sdkit==2.1.5) (4.64.1)
Requirement already satisfied: kornia==0.6 in c:\easydiffusion\installer_files\env\lib\site-packages (from stable-diffusion-sdkit==2.1.5) (0.6.0)
Requirement already satisfied: huggingface-hub>=0.10.0 in c:\easydiffusion\installer_files\env\lib\site-packages (from stable-diffusion-sdkit==2.1.5) (0.15.1)
Requirement already satisfied: open-clip-torch==2.0.2 in c:\easydiffusion\installer_files\env\lib\site-packages (from stable-diffusion-sdkit==2.1.5) (2.0.2)
Requirement already satisfied: pytorch-lightning==1.4.2 in c:\easydiffusion\installer_files\env\lib\site-packages (from stable-diffusion-sdkit==2.1.5) (1.4.2)
Requirement already satisfied: albumentations==1.3.0 in c:\easydiffusion\installer_files\env\lib\site-packages (from stable-diffusion-sdkit==2.1.5) (1.3.0)
Requirement already satisfied: test-tube>=0.7.5 in c:\easydiffusion\installer_files\env\lib\site-packages (from stable-diffusion-sdkit==2.1.5) (0.7.5)
Requirement already satisfied: einops==0.3.0 in c:\easydiffusion\installer_files\env\lib\site-packages (from stable-diffusion-sdkit==2.1.5) (0.3.0)
Requirement already satisfied: opencv-python==4.6.0.66 in c:\easydiffusion\installer_files\env\lib\site-packages (from stable-diffusion-sdkit==2.1.5) (4.6.0.66)
Requirement already satisfied: transformers==4.33.2 in c:\easydiffusion\installer_files\env\lib\site-packages (from stable-diffusion-sdkit==2.1.5) (4.33.2)
Requirement already satisfied: omegaconf==2.1.1 in c:\easydiffusion\installer_files\env\lib\site-packages (from stable-diffusion-sdkit==2.1.5) (2.1.1)
Requirement already satisfied: torchmetrics==0.6.0 in c:\easydiffusion\installer_files\env\lib\site-packages (from stable-diffusion-sdkit==2.1.5) (0.6.0)
Requirement already satisfied: qudida>=0.0.4 in c:\easydiffusion\installer_files\env\lib\site-packages (from albumentations==1.3.0->stable-diffusion-sdkit==2.1.5) (0.0.4)
Requirement already satisfied: scikit-image>=0.16.1 in c:\easydiffusion\installer_files\env\lib\site-packages (from albumentations==1.3.0->stable-diffusion-sdkit==2.1.5) (0.19.3)
Requirement already satisfied: PyYAML in c:\easydiffusion\installer_files\env\lib\site-packages (from albumentations==1.3.0->stable-diffusion-sdkit==2.1.5) (6.0)
Requirement already satisfied: scipy in c:\easydiffusion\installer_files\env\lib\site-packages (from albumentations==1.3.0->stable-diffusion-sdkit==2.1.5) (1.10.1)
Requirement already satisfied: numpy>=1.11.1 in c:\easydiffusion\installer_files\env\lib\site-packages (from albumentations==1.3.0->stable-diffusion-sdkit==2.1.5) (1.23.5)
Requirement already satisfied: opencv-python-headless>=4.1.1 in c:\easydiffusion\installer_files\env\lib\site-packages (from albumentations==1.3.0->stable-diffusion-sdkit==2.1.5) (4.7.0.68)
Requirement already satisfied: torch>=1.8.1 in c:\easydiffusion\installer_files\env\lib\site-packages (from kornia==0.6->stable-diffusion-sdkit==2.1.5) (1.13.1+cu116)
Requirement already satisfied: packaging in c:\easydiffusion\installer_files\env\lib\site-packages (from kornia==0.6->stable-diffusion-sdkit==2.1.5) (23.0)
Requirement already satisfied: antlr4-python3-runtime==4.8 in c:\easydiffusion\installer_files\env\lib\site-packages (from omegaconf==2.1.1->stable-diffusion-sdkit==2.1.5) (4.8)
Requirement already satisfied: regex in c:\easydiffusion\installer_files\env\lib\site-packages (from open-clip-torch==2.0.2->stable-diffusion-sdkit==2.1.5) (2022.10.31)
Requirement already satisfied: ftfy in c:\easydiffusion\installer_files\env\lib\site-packages (from open-clip-torch==2.0.2->stable-diffusion-sdkit==2.1.5) (6.1.1)
Requirement already satisfied: torchvision in c:\easydiffusion\installer_files\env\lib\site-packages (from open-clip-torch==2.0.2->stable-diffusion-sdkit==2.1.5) (0.14.1+cu116)
Requirement already satisfied: typing-extensions in c:\easydiffusion\installer_files\env\lib\site-packages (from pytorch-lightning==1.4.2->stable-diffusion-sdkit==2.1.5) (4.5.0)
Requirement already satisfied: fsspec[http]!=2021.06.0,>=2021.05.0 in c:\easydiffusion\installer_files\env\lib\site-packages (from pytorch-lightning==1.4.2->stable-diffusion-sdkit==2.1.5) (2023.1.0)
Requirement already satisfied: future>=0.17.1 in c:\easydiffusion\installer_files\env\lib\site-packages (from pytorch-lightning==1.4.2->stable-diffusion-sdkit==2.1.5) (0.18.3)
Requirement already satisfied: tensorboard>=2.2.0 in c:\easydiffusion\installer_files\env\lib\site-packages (from pytorch-lightning==1.4.2->stable-diffusion-sdkit==2.1.5) (2.12.0)
Requirement already satisfied: pyDeprecate==0.3.1 in c:\easydiffusion\installer_files\env\lib\site-packages (from pytorch-lightning==1.4.2->stable-diffusion-sdkit==2.1.5) (0.3.1)
Requirement already satisfied: tokenizers!=0.11.3,<0.14,>=0.11.1 in c:\easydiffusion\installer_files\env\lib\site-packages (from transformers==4.33.2->stable-diffusion-sdkit==2.1.5) (0.12.1)
Requirement already satisfied: filelock in c:\easydiffusion\installer_files\env\lib\site-packages (from transformers==4.33.2->stable-diffusion-sdkit==2.1.5) (3.9.0)
Requirement already satisfied: safetensors>=0.3.1 in c:\easydiffusion\installer_files\env\lib\site-packages (from transformers==4.33.2->stable-diffusion-sdkit==2.1.5) (0.3.3)
Requirement already satisfied: requests in c:\easydiffusion\installer_files\env\lib\site-packages (from transformers==4.33.2->stable-diffusion-sdkit==2.1.5) (2.28.2)
Requirement already satisfied: imageio>=2.3.0 in c:\easydiffusion\installer_files\env\lib\site-packages (from test-tube>=0.7.5->stable-diffusion-sdkit==2.1.5) (2.25.1)
Requirement already satisfied: pandas>=0.20.3 in c:\easydiffusion\installer_files\env\lib\site-packages (from test-tube>=0.7.5->stable-diffusion-sdkit==2.1.5) (1.5.3)
Requirement already satisfied: colorama in c:\easydiffusion\installer_files\env\lib\site-packages (from tqdm->stable-diffusion-sdkit==2.1.5) (0.4.6)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in c:\easydiffusion\installer_files\env\lib\site-packages (from fsspec[http]!=2021.06.0,>=2021.05.0->pytorch-lightning==1.4.2->stable-diffusion-sdkit==2.1.5) (3.8.4)
Requirement already satisfied: pillow>=8.3.2 in c:\easydiffusion\installer_files\env\lib\site-packages (from imageio>=2.3.0->test-tube>=0.7.5->stable-diffusion-sdkit==2.1.5) (9.4.0)
Requirement already satisfied: pytz>=2020.1 in c:\easydiffusion\installer_files\env\lib\site-packages (from pandas>=0.20.3->test-tube>=0.7.5->stable-diffusion-sdkit==2.1.5) (2022.7.1)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\easydiffusion\installer_files\env\lib\site-packages (from pandas>=0.20.3->test-tube>=0.7.5->stable-diffusion-sdkit==2.1.5) (2.8.2)
Requirement already satisfied: scikit-learn>=0.19.1 in c:\easydiffusion\installer_files\env\lib\site-packages (from qudida>=0.0.4->albumentations==1.3.0->stable-diffusion-sdkit==2.1.5) (1.2.1)
Requirement already satisfied: tifffile>=2019.7.26 in c:\easydiffusion\installer_files\env\lib\site-packages (from scikit-image>=0.16.1->albumentations==1.3.0->stable-diffusion-sdkit==2.1.5) (2023.2.3)
Requirement already satisfied: PyWavelets>=1.1.1 in c:\easydiffusion\installer_files\env\lib\site-packages (from scikit-image>=0.16.1->albumentations==1.3.0->stable-diffusion-sdkit==2.1.5) (1.4.1)
Requirement already satisfied: networkx>=2.2 in c:\easydiffusion\installer_files\env\lib\site-packages (from scikit-image>=0.16.1->albumentations==1.3.0->stable-diffusion-sdkit==2.1.5) (3.0)
Requirement already satisfied: absl-py>=0.4 in c:\easydiffusion\installer_files\env\lib\site-packages (from tensorboard>=2.2.0->pytorch-lightning==1.4.2->stable-diffusion-sdkit==2.1.5) (1.4.0)
Requirement already satisfied: werkzeug>=1.0.1 in c:\easydiffusion\installer_files\env\lib\site-packages (from tensorboard>=2.2.0->pytorch-lightning==1.4.2->stable-diffusion-sdkit==2.1.5) (2.2.3)
Requirement already satisfied: setuptools>=41.0.0 in c:\easydiffusion\installer_files\env\lib\site-packages (from tensorboard>=2.2.0->pytorch-lightning==1.4.2->stable-diffusion-sdkit==2.1.5) (67.3.2)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in c:\easydiffusion\installer_files\env\lib\site-packages (from tensorboard>=2.2.0->pytorch-lightning==1.4.2->stable-diffusion-sdkit==2.1.5) (0.4.6)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in c:\easydiffusion\installer_files\env\lib\site-packages (from tensorboard>=2.2.0->pytorch-lightning==1.4.2->stable-diffusion-sdkit==2.1.5) (0.7.0)
Requirement already satisfied: grpcio>=1.48.2 in c:\easydiffusion\installer_files\env\lib\site-packages (from tensorboard>=2.2.0->pytorch-lightning==1.4.2->stable-diffusion-sdkit==2.1.5) (1.51.1)
Requirement already satisfied: protobuf>=3.19.6 in c:\easydiffusion\installer_files\env\lib\site-packages (from tensorboard>=2.2.0->pytorch-lightning==1.4.2->stable-diffusion-sdkit==2.1.5) (4.22.0)
Requirement already satisfied: google-auth<3,>=1.6.3 in c:\easydiffusion\installer_files\env\lib\site-packages (from tensorboard>=2.2.0->pytorch-lightning==1.4.2->stable-diffusion-sdkit==2.1.5) (2.16.1)
Requirement already satisfied: wheel>=0.26 in c:\easydiffusion\installer_files\env\lib\site-packages (from tensorboard>=2.2.0->pytorch-lightning==1.4.2->stable-diffusion-sdkit==2.1.5) (0.38.4)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in c:\easydiffusion\installer_files\env\lib\site-packages (from tensorboard>=2.2.0->pytorch-lightning==1.4.2->stable-diffusion-sdkit==2.1.5) (1.8.1)
Requirement already satisfied: markdown>=2.6.8 in c:\easydiffusion\installer_files\env\lib\site-packages (from tensorboard>=2.2.0->pytorch-lightning==1.4.2->stable-diffusion-sdkit==2.1.5) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in c:\easydiffusion\installer_files\env\lib\site-packages (from requests->transformers==4.33.2->stable-diffusion-sdkit==2.1.5) (3.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\easydiffusion\installer_files\env\lib\site-packages (from requests->transformers==4.33.2->stable-diffusion-sdkit==2.1.5) (2022.12.7)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\easydiffusion\installer_files\env\lib\site-packages (from requests->transformers==4.33.2->stable-diffusion-sdkit==2.1.5) (1.26.14)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\easydiffusion\installer_files\env\lib\site-packages (from requests->transformers==4.33.2->stable-diffusion-sdkit==2.1.5) (2.1.1)
Requirement already satisfied: wcwidth>=0.2.5 in c:\easydiffusion\installer_files\env\lib\site-packages (from ftfy->open-clip-torch==2.0.2->stable-diffusion-sdkit==2.1.5) (0.2.6)
Requirement already satisfied: yarl<2.0,>=1.0 in c:\easydiffusion\installer_files\env\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]!=2021.06.0,>=2021.05.0->pytorch-lightning==1.4.2->stable-diffusion-sdkit==2.1.5) (1.8.2)
Requirement already satisfied: attrs>=17.3.0 in c:\easydiffusion\installer_files\env\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]!=2021.06.0,>=2021.05.0->pytorch-lightning==1.4.2->stable-diffusion-sdkit==2.1.5) (22.2.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\easydiffusion\installer_files\env\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]!=2021.06.0,>=2021.05.0->pytorch-lightning==1.4.2->stable-diffusion-sdkit==2.1.5) (6.0.4)
Requirement already satisfied: frozenlist>=1.1.1 in c:\easydiffusion\installer_files\env\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]!=2021.06.0,>=2021.05.0->pytorch-lightning==1.4.2->stable-diffusion-sdkit==2.1.5) (1.3.3)
Requirement already satisfied: aiosignal>=1.1.2 in c:\easydiffusion\installer_files\env\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]!=2021.06.0,>=2021.05.0->pytorch-lightning==1.4.2->stable-diffusion-sdkit==2.1.5) (1.3.1)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in c:\easydiffusion\installer_files\env\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]!=2021.06.0,>=2021.05.0->pytorch-lightning==1.4.2->stable-diffusion-sdkit==2.1.5) (4.0.2)
Requirement already satisfied: six>=1.9.0 in c:\easydiffusion\installer_files\env\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard>=2.2.0->pytorch-lightning==1.4.2->stable-diffusion-sdkit==2.1.5) (1.16.0)
Requirement already satisfied: rsa<5,>=3.1.4 in c:\easydiffusion\installer_files\env\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard>=2.2.0->pytorch-lightning==1.4.2->stable-diffusion-sdkit==2.1.5) (4.9)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\easydiffusion\installer_files\env\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard>=2.2.0->pytorch-lightning==1.4.2->stable-diffusion-sdkit==2.1.5) (0.2.8)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in c:\easydiffusion\installer_files\env\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard>=2.2.0->pytorch-lightning==1.4.2->stable-diffusion-sdkit==2.1.5) (5.3.0)
Requirement already satisfied: requests-oauthlib>=0.7.0 in c:\easydiffusion\installer_files\env\lib\site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard>=2.2.0->pytorch-lightning==1.4.2->stable-diffusion-sdkit==2.1.5) (1.3.1)
Requirement already satisfied: importlib-metadata>=4.4 in c:\easydiffusion\installer_files\env\lib\site-packages (from markdown>=2.6.8->tensorboard>=2.2.0->pytorch-lightning==1.4.2->stable-diffusion-sdkit==2.1.5) (6.0.0)
Requirement already satisfied: joblib>=1.1.1 in c:\easydiffusion\installer_files\env\lib\site-packages (from scikit-learn>=0.19.1->qudida>=0.0.4->albumentations==1.3.0->stable-diffusion-sdkit==2.1.5) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\easydiffusion\installer_files\env\lib\site-packages (from scikit-learn>=0.19.1->qudida>=0.0.4->albumentations==1.3.0->stable-diffusion-sdkit==2.1.5) (3.1.0)
Requirement already satisfied: MarkupSafe>=2.1.1 in c:\easydiffusion\installer_files\env\lib\site-packages (from werkzeug>=1.0.1->tensorboard>=2.2.0->pytorch-lightning==1.4.2->stable-diffusion-sdkit==2.1.5) (2.1.2)
Requirement already satisfied: zipp>=0.5 in c:\easydiffusion\installer_files\env\lib\site-packages (from importlib-metadata>=4.4->markdown>=2.6.8->tensorboard>=2.2.0->pytorch-lightning==1.4.2->stable-diffusion-sdkit==2.1.5) (3.14.0)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in c:\easydiffusion\installer_files\env\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard>=2.2.0->pytorch-lightning==1.4.2->stable-diffusion-sdkit==2.1.5) (0.4.8)
Requirement already satisfied: oauthlib>=3.0.0 in c:\easydiffusion\installer_files\env\lib\site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard>=2.2.0->pytorch-lightning==1.4.2->stable-diffusion-sdkit==2.1.5) (3.2.2)
WARNING! Tried to install stable-diffusion-sdkit==2.1.5, but the version is still 2.1.1!
stable-diffusion-sdkit: 2.1.1
{'model': {'stable-diffusion': 'sd-v1-5-inpainting'},
 'models_dir': 'C:\\EasyDiffusion\\models',
 'net': {'listen_port': 9000, 'listen_to_network': False},
 'render_devices': 'auto',
 'ui': {'open_browser_on_start': True},
 'update_branch': 'main',
 'use_v3_engine': True,
 'vram_usage_level': 'high'}

Easy Diffusion installation complete, starting the server!

PYTHONPATH=C:\EasyDiffusion\installer_files\env\lib\site-packages
Python:  C:\EasyDiffusion\installer_files\env\python.EXE
Version: 3.8.5
Checking network settings
Set listen port to  9000

Launching uvicorn

Traceback (most recent call last):
  File "C:\EasyDiffusion\installer_files\env\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\EasyDiffusion\installer_files\env\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\uvicorn\__main__.py", line 4, in <module>
    uvicorn.main()
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\uvicorn\main.py", line 404, in main
    run(
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\uvicorn\main.py", line 569, in run
    server.run()
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\EasyDiffusion\installer_files\env\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "C:\EasyDiffusion\installer_files\env\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\uvicorn\server.py", line 67, in serve
    config.load()
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\uvicorn\config.py", line 477, in load
    self.loaded_app = import_from_string(self.app)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\uvicorn\importer.py", line 24, in import_from_string
    raise exc from None
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\uvicorn\importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "C:\EasyDiffusion\installer_files\env\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\EasyDiffusion\ui\main.py", line 1, in <module>
    from easydiffusion import model_manager, app, server, bucket_manager
  File "C:\EasyDiffusion\ui\easydiffusion\model_manager.py", line 7, in <module>
    from easydiffusion import app
  File "C:\EasyDiffusion\ui\easydiffusion\app.py", line 14, in <module>
    from easydiffusion import task_manager
  File "C:\EasyDiffusion\ui\easydiffusion\task_manager.py", line 20, in <module>
    from easydiffusion.tasks import Task
  File "C:\EasyDiffusion\ui\easydiffusion\tasks\__init__.py", line 2, in <module>
    from .render_images import RenderTask
  File "C:\EasyDiffusion\ui\easydiffusion\tasks\render_images.py", line 11, in <module>
    from sdkit.generate import generate_images
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\sdkit\generate\__init__.py", line 1, in <module>
    from .image_generator import generate_images
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\sdkit\generate\image_generator.py", line 4, in <module>
    from pytorch_lightning import seed_everything
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\pytorch_lightning\__init__.py", line 20, in <module>
    from pytorch_lightning import metrics  # noqa: E402
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\pytorch_lightning\metrics\__init__.py", line 15, in <module>
    from pytorch_lightning.metrics.classification import (  # noqa: F401
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\pytorch_lightning\metrics\classification\__init__.py", line 14, in <module>
    from pytorch_lightning.metrics.classification.accuracy import Accuracy  # noqa: F401
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\pytorch_lightning\metrics\classification\accuracy.py", line 16, in <module>
    from torchmetrics import Accuracy as _Accuracy
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\torchmetrics\__init__.py", line 14, in <module>
    from torchmetrics import functional  # noqa: E402
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\torchmetrics\functional\__init__.py", line 68, in <module>
    from torchmetrics.functional.text.bert import bert_score
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\torchmetrics\functional\text\bert.py", line 28, in <module>
    from transformers import AutoModel, AutoTokenizer
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\transformers\__init__.py", line 26, in <module>
    from . import dependency_versions_check
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\transformers\dependency_versions_check.py", line 57, in <module>
    require_version_core(deps[pkg])
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\transformers\utils\versions.py", line 117, in require_version_core
    return require_version(requirement, hint)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\transformers\utils\versions.py", line 111, in require_version
    _compare_versions(op, got_ver, want_ver, requirement, pkg, hint)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\transformers\utils\versions.py", line 44, in _compare_versions
    raise ImportError(
ImportError: huggingface-hub>=0.15.1,<1.0 is required for a normal functioning of this module, but found huggingface-hub==0.12.1.
Try: pip install transformers -U or pip install -e '.[dev]' if you're working with git main
Press any key to continue . . .
Press any key to continue . . .
Press any key to continue . . .`   

==============================

[Fails after the 3rd key press, simply closes.]

Let me know if you need more info.  

Thanks!
-J

**Comment by cmdr2** [comment]
Hi @scorpiomaj27 Sorry about that, please try these steps to fix this problem:
1. Double-click `Developer Console.cmd`
2. Type this and press Enter: `python -m pip uninstall safetensors huggingface-hub transformers sdkit accelerate controlnet-aux k-diffusion`
3. Type 'y' and press Enter to accept
4. Type this and press Enter: `python -m pip install sdkit transformers==4.33.2 huggingface-hub==0.16.4 safetensors==0.3.3  accelerate==0.23.0 controlnet-aux==0.0.6 k-diffusion==0.0.12`

Still investigating why this problem has started recently. Thanks

**Comment by scorpiomaj27** [comment]
Cmd2,

Thanks, that fixed the issue, sorry about the late reply.

Thanks!
-S

**Comment by scorpiomaj27** [comment]
Cmd2,

Thanks, that fixed the issue, sorry about the late reply.

Thanks!
-S
