### ISSUE TITLE
Updates / Changelog

### ISSUE THREAD

**Issue by compactmicrowave** [easydiffusion/easydiffusion#1653]
In the 'What's New' tab, I note that there has been no additions to changelog since this entry after a regular schedule of updates.

'3.0.6 - 18 Sep 2023 - Add thumbnails to embeddings from the UI, using the new Upload Thumbnail button in the Embeddings popup. Thanks @JeLuf.'

Is it a posssible problem with personal settings or have no updates been supplied since that time?

Thank you

- OS: W10
- Browser: Opera latest

**Comment by cmdrgrunt** [comment]
Nothing wrong on your end. The developer has been on break.

Hope that helps, and if so, if you wouldn't mind closing out the ticket. Thanks!
