### ISSUE TITLE
Insanely slow and constantly stuck after coming back from a break

### ISSUE THREAD

**Issue by Kasseo** [easydiffusion/easydiffusion#1672]
**Describe the bug**
I've been fine rendering out pics up to 2048x1563 a month ago, now I can't render ANYTHING above 1024x1024. The program just gets stuck and won't respond. 

**To Reproduce**
Literally trying to render anything above 1024x1024

**Expected behavior**
Actually rendering the image

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser:
 - Version:

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

**Comment by cmdr2** [comment]
Hi Kasseo, it's possible that your NVIDIA driver has updated during the break, and the recent driver versions use the system RAM as shared memory (which is very very slow). This behavior kicks in when the GPU memory is almost full (e.g. for very large images).

If you're on the latest NVIDIA driver, you can disable this behavior in the driver settings to prevent Easy Diffusion from using shared memory. That setting will be only for Easy Diffusion, it won't affect other programs.

I've added a wiki page for this: https://github.com/easydiffusion/easydiffusion/wiki/Troubleshooting#very-very-slow-rendering-on-nvidia-cards-on-windows

Please feel free to reopen (or let me know) if this is still an issue after disabling shared memory for Easy Diffusion in the driver settings. Thanks!
