### ISSUE TITLE
Vanilla install on Linux Mint, local host address not available

### ISSUE THREAD

**Issue by livinglight108** [easydiffusion/easydiffusion#1682]
**Describe the bug**

Post install upon start.sh I get error 98 error on attempting to bind on address as seen in below image. I spent 15 minutes attempting to find in text editors the file where I could change this address to no avail. Can you please help me get this up and running?

**To Reproduce**
1. Install on Linux Mint
2. Run start.sh

**Expected behavior**

I expected Stable Diffusion to open/work as it did on the Windows host I previously tried it on.

**Screenshots**

![photo_2023-11-25_18-43-18](https://github.com/easydiffusion/easydiffusion/assets/123313761/85c3cd07-fbae-4769-bf6e-6c08ba1083d9)

**Desktop (please complete the following information):**
 - OS: Linux Mint 21.1
 - Browser: Firefox
 - Version:

**Comment by JeLuF** [comment]
The error message means that port 9000 is already in use. Only one program can use a port at any given time. You can provide a port number for startup in the config file, as explained in the documentation: https://github.com/easydiffusion/easydiffusion/wiki/Config-settings#network-ports
