### ISSUE TITLE
Inpainting Error  + object has no attribute 'disable_vae_tiling'

### ISSUE THREAD

**Issue by xorrot16** [easydiffusion/easydiffusion#1701]
I get Following Error when using inpainting:

Error: 'StableDiffusionInpaintPipeline' object has no attribute 'disable_vae_tiling'
Error: 'StableDiffusionInpaintPipeline' object has no attribute 'disable_vae_tiling'

it is also Triggered when it is Enabled

I used two different models both dont work!

yesterday I could  use it without problems and generated many pictures via inpainting!

Load a image for Inpainting do some inpainting! 

use following settings:

Image Settings:
{
    "numOutputsTotal": 4,
    "seed": 2589604355,
    "reqBody": {
        "prompt": "",
        "negative_prompt": "hat, weapons, ugly, nude, old, mutation, lowres, low quality, open mouth, teeth, doll, long n eck, extra limbs, text, signature, artist name, bad anatomy, poorly drawn, malformed, deformed, blurry, out of focus, noise, dust, (deformed iris, deformed pupils, semi-realistic, cgi, 3d, render, sketch, cartoon, drawing, anime), text, cropped, out of frame, worst quality, low quality, jpeg artifacts, ugly, duplicate, morbid, mutilated, extra fingers, mutated hands, poorly drawn hands, poorly drawn face, mutation, deformed, blurry, dehydrated, bad anatomy, bad proportions, extra limbs, cloned face, disfigured, gross proportions, malformed limbs, missing arms, missing legs, extra arms, extra legs, fused fingers, too many fingers, long neck epiCPhotoGasm-colorfulPhoto-neg CyberRealistic_Negative-neg",
        "active_tags": [],
        "inactive_tags": [],
        "width": 512,
        "height": 512,
        "seed": 2589604355,
        "num_inference_steps": 20,
        "guidance_scale": 9.6,
        "preserve_init_image_color_profile": false,
        "upscale_amount": "4",
        "latent_upscaler_steps": "10",
        "sampler_name": "dpmpp_2m",
        "use_stable_diffusion_model": "cyberrealistic_v32-inpainting",
        "clip_skip": false,
        "tiling": "none",
        "use_vae_model": "CyberRealisticVae-ft-mse-840000-ema-pruned",
        "use_controlnet_model": "",
        "control_filter_to_apply": "",
        "use_lora_model": [],
        "lora_alpha": [],
        "num_outputs": 2,
        "stream_image_progress": false,
        "show_only_filtered_image": true,
        "output_format": "jpeg"
    }
}

**Expected behavior**
to start Inpainting..

**Screenshots**
![image](https://github.com/easydiffusion/easydiffusion/assets/71011570/af6a572d-92b0-43db-abfe-470b008d917f)
![image](https://github.com/easydiffusion/easydiffusion/assets/71011570/f1776e1b-1a7a-4667-bb09-f8a5a4b9553a)
![image](https://github.com/easydiffusion/easydiffusion/assets/71011570/c4659e74-d97d-45ca-ab1e-e866256acab9)
![image](https://github.com/easydiffusion/easydiffusion/assets/71011570/ab3fbc2e-7bf7-4037-87e3-6f673674fd53)
enable_vae_tiling option does not do the trick... 
![image](https://github.com/easydiffusion/easydiffusion/assets/71011570/0dce30af-b982-4e2d-807f-5df847fbc855)

I am in the beta channel... maybe I got an update yesterday? I dischecked the beta it didnt work..
I am using the v3 because I wanted to use the XL models too.. 
The models aren ot XL models also the vae is no XL model..
I tried  vae-ft-mse-840000-ema-pruned as vae also I tried to use no VAE it dint help :(

 - OS: Windows 11 64Bit
 - Browser: Chrome 
 - Version: Easy Diffusion v3.0.7 (beta)

my start bat :
@echo off

cd /d %~dp0
echo Install dir: %~dp0

set PATH=C:\Windows\System32;%PATH%

if exist "on_sd_start.bat" (
    echo ================================================================================
    echo.
    echo !!!! WARNING !!!!
    echo.
    echo It looks like you're trying to run the installation script from a source code 
    echo download. This will not work.
    echo.
    echo Recommended: Please close this window and download the installer from
    echo https://stable-diffusion-ui.github.io/docs/installation/
    echo.
    echo ================================================================================
    echo.
    pause
    exit /b
) 

@rem set legacy installer's PATH, if it exists
if exist "installer" set PATH=%cd%\installer;%cd%\installer\Library\bin;%cd%\installer\Scripts;%cd%\installer\Library\usr\bin;%PATH%

@rem set new installer's PATH, if it downloaded any packages
if exist "installer_files\env" set PATH=%cd%\installer_files\env;%cd%\installer_files\env\Library\bin;%cd%\installer_files\env\Scripts;%cd%\installer_files\Library\usr\bin;%PATH%

set PYTHONPATH=%cd%\installer;%cd%\installer_files\env

@rem Test the core requirements
call where git
call git --version

call where conda
call conda --version
echo .
echo COMSPEC=%COMSPEC%

git config pull.rebase false

@rem Download the rest of the installer and UI
call scripts\on_env_start.bat
@pause

**Comment by cmdr2** [comment]
Sorry about that. I've pushed a fix for this, can you please try again? Thanks

**Comment by xorrot16** [comment]
> Sorry about that. I've pushed a fix for this, can you please try again? Thanks

thank you for your fast reply 👍 

but it seemed not to work for me..


my cmd says and I think it was sucessfull with the updates... but still  I have the same error, do have to do some git commands?  here is my cmd:
"Easy Diffusion - v3"

"Easy Diffusion's git repository was already installed. Updating from beta.."
No local changes to save
HEAD is now at 547febaf Autosave the VAE tiling setting
Already on 'beta'
Your branch is up to date with 'origin/beta'.
Already up to date.
519 Datei(en) kopiert
        1 Datei(en) kopiert.
        1 Datei(en) kopiert.
        1 Datei(en) kopiert.
        1 Datei(en) kopiert.
        1 Datei(en) kopiert.
        1 Datei(en) kopiert.
        1 Datei(en) kopiert.
        1 Datei(en) kopiert.
        1 Datei(en) kopiert.
        1 Datei(en) kopiert.

**Comment by xorrot16** [comment]
> Sorry about that. I've pushed a fix for this, can you please try again? Thanks

THANKS IT WORKED.. my bat file did not rebase... now it worked!
