### ISSUE TITLE
QoL: Switch memory usage to Low automatically when SDXL model is used (and back).

### ISSUE THREAD

**Issue by Seedmanc** [easydiffusion/easydiffusion#1704]
I'm just a few dozen megabytes short of being able to use SDXL models on Balanced mode, while everything else works fine with High, so I have to switch it back and forth every time.

Make ED change memory usage depending on which family of models is used: Low for SDXL, Balanced or High for everything else (maybe Balanced for SD2 and High for SD1?)

If you could point me to a place in source code where this can be done, I might try to fix it locally for myself or maybe even come up with a PR (though my knowledge of Python is limited, but perhaps it can be done by manipulating the UI with a Javascript plugin?).

If switching memory usage modes based on a model seems too arbitrary, how about doing it when a generation fails due to running out of memory? Like adding a button to the error message "Retry with lower setting" or retrying automatically, going for a lower tier every time it fails and back once a model changes. 
Imagine that you created a queue of generations with different models and left it unattended, this would make it able to try and solve different memory requirements for different models on its own while not sacrificing speed for everything.

**Comment by arrowgent** [comment]
8GB Vram seems to be the limit for balanced SDXL
most of them i also have to set to low

SD1 i can always set to high.

i would agree making it "easier" to rerun the generation after clicking a prompt to try lower ram setting.  instead of having to go to the tab, set the ram, save, go back to the prompt tag, and "use these settings" back on the prompt

**Comment by Seedmanc** [comment]
Seems one of the  UI plugins adds the toggle between low and balanced, so it mostly solves the problem.
Still I wish they fixed the "2 megabytes short of VRAM" thing so I could use SDXL on Balanced. I tried everything I could to no effect.
