### ISSUE TITLE
Local network can not access problem

### ISSUE THREAD

**Issue by nickyi1990** [easydiffusion/easydiffusion#1741]
**Describe the bug**
I run the bash start.sh command and it show the picture below in my gpu server, which is an computer without screen.
![image](https://github.com/easydiffusion/easydiffusion/assets/13381684/c704e82b-18e8-4d15-8fe1-168aa15d9100)

I access the url with 30.xxx.xxx.xxx:9000 on my macbook, but it show the picture below, how to slove this problem~
![image](https://github.com/easydiffusion/easydiffusion/assets/13381684/7910cef2-e0cb-4b18-9641-506bb04a65c5)

**Expected behavior**
it need show the ui on my macbook

**Comment by wupme** [comment]
By Default it will not be accessible through the network.
Open the config.yaml and add this line

`listen_to_network: true`

**Comment by nickyi1990** [comment]
first, there's no config.yaml file only config.yaml.sample file
second, i had set listen_to_network: true but it do not work~

**Comment by nickyi1990** [comment]
> By Default it will not be accessible through the network. Open the config.yaml and add this line
> 
> `listen_to_network: true`

😭, thanks
