### ISSUE TITLE
Help me please! I wrote the book "Incredible artificial intelligence Easy Diffusion 3.0". Let me use the title "Easy Diffusion 3.0" on the cover of the book.

### ISSUE THREAD

**Issue by AlexanderChesalov** [easydiffusion/easydiffusion#1753]
Colleagues!
I wrote the book "Incredible artificial intelligence Easy Diffusion 3.0". Let me use the title "Easy Diffusion 3.0" on the cover of the book.

My publisher is asking for confirmation from the copyright holder to use the title "Easy Diffusion 3.0" on the cover of the book.
Please allow me to use the name "Easy Diffusion 3.0".
![Обложка AI черная ENG](https://github.com/easydiffusion/easydiffusion/assets/165780261/3d205f02-2eee-4a77-9b83-4c6eaacc2aab)

for example:

MY INTRODUCTION

The wonderful world of Artificial Intelligence can be fully revealed to us only when you and I can see the positive results of its work, especially those created with our direct participation. These results must be understandable and explainable to everyone, and they must also be ethical, unbiased and not violate the law.

Today, Artificial Intelligence can do a lot, for example: write the text of a new poem or even a whole story, reproduce it in different voices of famous actors or musicians, analyze a large amount of numerical data and make a forecast for the future, play computer games with us or with a thousand people at once games. Perhaps the most impressive thing, in my opinion, that Artificial Intelligence can do today is create unique and incredible images. These images can be the embodiment of a three-dimensional world of a fantastic future in a computer game or be a virtual simulation of the world around us. The images can be three-dimensional or two-dimensional, and can also be made in various painting styles by famous artists from different time periods. But the most interesting thing is that these images may contain creatures or objects that do not exist in our world.

In this book, you will acquire new knowledge about how diverse Artificial Intelligence can be, and you will become familiar with its most popular terms and definitions. You will learn what is «artificial superintelligence», «narrow Artificial Intelligence», «friendly Artificial Intelligence», «human-centered Artificial Intelligence», «distributed Artificial Intelligence», «trusted Artificial Intelligence», «composite Artificial Intelligence», «explainable» Artificial Intelligence» and much more.

I will tell you how you can transform and visualize the knowledge you have acquired using an Artificial Intelligence system, turning the text definitions of various terms from this book into fantastic drawings.

In order to bring all this to life, we will study the work of a free program — the Easy Diffusion generative Artificial Intelligence system. This program creates photorealistic images from text queries and graphic images.

Easy Diffusion is an easy-to-install assembly (distribution) of the Stable Diffusion Artificial Intelligence system. Easy Diffusion will allow us to create unique images based on the most popular neural network models today, such as Stable Diffusion, Midjourney, OpenJourney, DreamShaper, SDXL Yamer’s Realism!, ProtoVision XL, Art Universe, Realistic Vision and many others.

With the help of this book, you will learn not only how to use Easy Diffusion Artificial Intelligence as a creative tool, but you will also be able to independently install, configure and uninstall this program on your computer, connect various additional modules to it, which will significantly expand its capabilities for creating and processing images.

With the help of Artificial Intelligence, you will learn to create unique and inimitable images that you can use in your studies or for entertainment.

In order to be objective in my work and make the book as accessible as possible to a wide range of readers, I asked my son Vsevolod (5th grade student) and my daughter Diana (8th grade student) to help me work on the textbook and create various images that reflect the essence of the definitions of Artificial Intelligence presented in the book. It was interesting for me to involve them in a new activity for them, and it was also very important to understand for myself how quickly they would learn to work with the Easy Diffusion Artificial Intelligence system and be able to create their own high-quality images.

It turned out that fifteen minutes of instruction was enough to begin their first acquaintance with Easy Diffusion Artificial Intelligence and become familiar with the work of the Realistic Vision model. Their first image was a steampunk style hamster. Steampunk is a science fiction movement incorporating technology and arts and crafts inspired by technology and 19th century science fiction. Nevertheless, they gained more or less serious experience working with Easy Diffusion after some time.

It took us more than six weeks of work to fill this book with illustrations. From more than five hundred drawings, we have selected for you the most, in our opinion, impressive and interesting. The total computer time we spent working with the Easy Diffusion Artificial Intelligence is approximately three hundred and sixty hours. What can we say about the fact that writing the book itself, correcting and editing the text, as well as selecting the necessary pictures required a lot of time and effort.

Almost six months have passed since the first edition of this book was published. During this time, more than seventeen thousand readers became acquainted with the first edition of this book. Since then, the version of the Easy Diffusion program has also changed.

This book is written as a textbook for middle and high school students. It contains detailed instructions for working with the Easy Diffusion 3.0 Artificial Intelligence system, which allows you to transform the text you write or your image into a new unique image. It also contains educational information about existing types of Artificial Intelligence. The book features a beautiful set of over one hundred illustrations demonstrating the AI capabilities of Easy Diffusion 3.0.

We really hope that our positive and positive experience that we received in the process of studying the Easy Diffusion Artificial Intelligence system will be useful to you in your studies and creativity.

Enjoy your reading and productive work!

**Comment by Menno5** [comment]
Really? Spamming your stuff like this? Go away please.

**Comment by AlexanderChesalov** [comment]
> Действительно? Спамить такие вещи? Уходи пожалуйста.

This is not spam. I ask you to help me get permission.

**Comment by cmdr2** [comment]
Hi @AlexanderChesalov , yes you have permission to use Easy Diffusion 3.0 in the title of your book. Because it looks like you are writing a guide for using the Easy Diffusion software.

Good luck, and thanks!

**Comment by AlexanderChesalov** [comment]
> Привет@AlexanderChesalov, да, у вас есть разрешение использовать Easy Diffusion 3.0 в названии вашей книги. Потому что похоже, что вы пишете руководство по использованию программного обеспечения Easy Diffusion.
> 
> Удачи и спасибо!
> 
> PS: Я являюсь первоначальным создателем и ведущим разработчиком этого программного обеспечения. Кроме того, я не думаю, что вам нужно разрешение для этого в любом случае.

Thank you very much!

Yes, I wrote a book for schoolchildren based on your program.
Thanks for your program.
