### ISSUE TITLE
Error: Could not load the stable-diffusion model! Reason: 'time_embed.0.weight'

### ISSUE THREAD

**Issue by SusgUY446** [easydiffusion/easydiffusion#1754]
**Describe the bug**
when creating a image it gives this error "Error: Could not load the stable-diffusion model! Reason: 'time_embed.0.weight'"

**To Reproduce**
generate a image

**Expected behavior**
that it start generating the image requested

**Screenshots**
![image](https://github.com/easydiffusion/easydiffusion/assets/129160115/cf6f39f6-d78f-4d0c-9c56-4984c7a46977)

**Desktop (please complete the following information):**
 - OS: windows 11
 - Browser: firefox
 - Version: 124

**Additional context**
Log from console window:
20:20:29.049 INFO cpu Session 1712168406272 starting task 2133794581232 on Intel64 Family 6 Model 154 Stepping 4, GenuineIntel                                                                  task_manager.py:280
20:20:29.183 INFO cpu loading stable-diffusion model from C:\EasyDiffusion\models\stable-diffusion\custommodel10391.safetensors to device: cpu                                                   __init__.py:52
20:20:31.091 INFO cpu loading on diffusers                                                                                                                                                          __init__.py:174
20:20:31.095 INFO cpu using config: C:\EasyDiffusion\installer_files\env\lib\site-packages\sdkit\models\models_db\configs\v1-inference.yaml                                                         __init__.py:176
20:20:31.131 INFO cpu using attn_precision: fp32                                                                                                                                                    __init__.py:192
20:20:31.268 ERROR cpu 'time_embed.0.weight'                                                                                                                                                   model_manager.py:185
Traceback (most recent call last):
  File "C:\EasyDiffusion\ui\easydiffusion\model_manager.py", line 181, in reload_models_if_necessary
    action_fn(context, model_type, scan_model=False, **extra_params)  # we've scanned them already
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\sdkit\models\model_loader\__init__.py", line 54, in load_model
    context.models = get_loader_module(model_type).load_model(context, **kwargs)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\sdkit\models\model_loader\stable_diffusion\__init__.py", line 86, in load_model
    return load_diffusers_model(
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\sdkit\models\model_loader\stable_diffusion\__init__.py", line 238, in load_diffusers_model
    default_pipe = download_from_original_stable_diffusion_ckpt(state_dict, **model_load_params)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\sdkit\models\model_loader\diffusers_bugfixes.py", line 396, in download_from_original_stable_diffusion_ckpt
    converted_unet_checkpoint = convert_ldm_unet_checkpoint(checkpoint, unet_config, path=path, extract_ema=extract_ema)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\diffusers\pipelines\stable_diffusion\convert_from_ckpt.py", line 422, in convert_ldm_unet_checkpoint
    new_checkpoint["time_embedding.linear_1.weight"] = unet_state_dict["time_embed.0.weight"]
KeyError: 'time_embed.0.weight'
20:20:31.295 ERROR cpu Traceback (most recent call last):                                                                                                                                       task_manager.py:292
  File "C:\EasyDiffusion\ui\easydiffusion\task_manager.py", line 284, in thread_render
    task.run()
  File "C:\EasyDiffusion\ui\easydiffusion\tasks\render_images.py", line 89, in run
    model_manager.fail_if_models_did_not_load(context)
  File "C:\EasyDiffusion\ui\easydiffusion\model_manager.py", line 212, in fail_if_models_did_not_load
    raise Exception(f"Could not load the {model_type} model! Reason: " + e)
Exception: Could not load the stable-diffusion model! Reason: 'time_embed.0.weight'

20:20:31.462 INFO cpu Session 1712168406272 task 2133794581232 failed!

**Comment by 0000F8** [comment]
Having this issue as well

**Comment by HojatGhanad** [comment]
I just faced this issue too.
windows 10, easy diffusion 3.0, chrome

**Comment by D-Bobrikov** [comment]
OS: Ubuntu 24.04 LTS x86_64
Kernel: 6.8.0-35-generic
CPU: AMD Ryzen 5 4600H with Radeon G 
GPU: NVIDIA GeForce GTX 1650 Ti Mobi
GPU: AMD ATI Radeon RX Vega 6
Memory: 15353MiB

Same problem (

**Comment by Albee24** [comment]
Same here, M3 Max, easy diffusion 3.0 (trying to use stable diffusion 3 medium)

**Comment by Grosso2020** [comment]
win 10  Same problem

**Comment by FriedrichR** [comment]
Win 10, Easy Diffusion v3.0.9, sd3_medium

Works with sd_v1_5

**Comment by Nickup22** [comment]
win10 same problem. sd v1.5 works normally

**Comment by laurentopia** [comment]
same with Flux and MJ52
https://civitai.com/models/618692/flux
upscale also doesn't work after using these models and reverting to 1.5

**Comment by sang-shelton** [comment]
> same with Flux and MJ52 https://civitai.com/models/618692/flux upscale also doesn't work after using these models and reverting to 1.5

Same issue here with Flux. I have an NVIDIA GeForce RTX 3060 - 12GB VRAM.

![Screenshot_20240823_212942](https://github.com/user-attachments/assets/0e5f71ff-1e8e-4ed8-a9b3-0bfe83f8e8b7)

**Comment by BSchoolland** [comment]
I have the same issue on Linux.  Works fine with sd-v1-5 but fails with sd3_medium.  16 gb ram and NVIDIA GeForce GTX 1060 Mobile 6GB graphics card.  If anyone has a workaround for this it would be much appreciated!
![image](https://github.com/user-attachments/assets/fb9f0863-d4ca-4cc5-b517-f14e731842ab)

**Comment by laurentopia** [comment]
I switched to SwarmUI and now life is good, in Flux

**Comment by saumonarcenciel** [comment]
I have the same issue, tried with SwarmUI too and it didn't fixed

**Comment by JeremyHe1209** [comment]
Well, is there a temporary solution?

**Comment by meecosha** [comment]
Why is the issue closed? I also have this problem...

**Comment by Undreamed** [comment]
Same here =(

**Comment by saumonarcenciel** [comment]
Hi everyone ! 
I found what was causing the error: I was (and you probably are) using a Lora as a model.
Unlike a model, a Lora allows to improve the generation made by a model. Lora has to be placed on Lora folder and can't be used as models. It's not the same folder and not the same thing.
 The difference is not very clear on Civtai but try to find the model used in the description of the prompt of an example image. ;)
