### ISSUE TITLE
How to call the API for text-to-image generation? 

### ISSUE THREAD

**Issue by ipv6ok** [easydiffusion/easydiffusion#1786]
How to call the API for text-to-image generation? Is there any API documentation available? I see there is an API written in FastAPI in the UI directory, but I don't know how to call it.

**Comment by cmdr2** [comment]
Hi, sorry the API is undocumented, and not meant for public use. It can change at any time.

But you can look at the endpoint docs at http://localhost:9000/docs (once you have Easy Diffusion running). To understand the exact parameters sent, please look at what the UI is sending:

1. Please open Easy Diffusion, then right-click in your browser, click "Inspect", and then open the "Network" tab.
2. Then click on "Make Image" in Easy Diffusion, and look for an entry in the Network tab for "POST /render"
3. You can then look at the data sent in the /render request

Another option is to use [sdkit](https://github.com/easydiffusion/sdkit) directly, which is the python library used by Easy Diffusion to generate images. Thanks
