### ISSUE TITLE
Any SDXL model takes forever to create any images. 

### ISSUE THREAD

**Issue by Milock45** [easydiffusion/easydiffusion#1809]
**Describe the bug**
Easy Diffusion is the best out there imo, but whenever I try to create anything with the newer models (anything XL), it takes forever to create anything. Normally a 1024 x 1024 takes about 20 seconds, but with an XL model it takes about 6-8 minutes.

**Expected behavior**
Expected image to be created in no less than 20 to 40 seconds.

**Screenshots**
none.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: Version 125.0.6422.142 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
none.

**Additional context**
I hope that the speed can soon be upped. Easy Diffusion is the best out there, I find the others incredibly confusing and can never create anything good with them. Thank you.

**Comment by Milock45** [comment]
Disregard this request please. I was able to find some help in the discord. Setting the ram usage to low has sped things up considerably. Still, it could go faster. Hopefully it will someday.

**Comment by cmdr2** [comment]
Thanks!
