### ISSUE TITLE
suport ReFS partition

### ISSUE THREAD

**Issue by manotroll** [easydiffusion/easydiffusion#1816]
I went to install it on Windows 11 and it's complaining that my file system is ReFS
why doesn't it support this file system considering it is newer than ntfs

**Comment by q5sys** [comment]
It's just a glitch in the installer, it does the same for other filesystems which work fine.  The installer script just needs to be updated.  In the mean time if you can install to an NTFS formatted drive and then move the folder onto your ReFS drive it "should work". (You might have to update some shortcuts if you do that)

**Comment by manotroll** [comment]
Thank you, this tip worked for me
and there was nothing written elsewhere if it would work and in the readme there was nothing talking about the file system
