### ISSUE TITLE
Cannot use GPU (RX 7900 GRE)

### ISSUE THREAD

**Issue by xenorio** [easydiffusion/easydiffusion#1840]
**Describe the bug**
EasyDiffusion tells me that there was no compatible graphics card found. I've got a Radeon RX 7900 GRE, which should be capable of handling AI. Running on a pretty much fresh install of arch linux. I have installed rocm-core and rocminfo from arch repositories.

EasyDiffusion logs:
[log.txt](https://github.com/user-attachments/files/17002437/log.txt)

rocminfo:
[rocminfo.txt](https://github.com/user-attachments/files/17002438/rocminfo.txt)

During first run of EasyDiffusion (so the installation part), I had this error, seems related:
```
Found AMD GPU Navi 31 [Radeon RX 7900 XT/7900 XTX].
--- Applying Navi 3 settings
> python -m pip install --upgrade torch==2.1.0.dev-20230614+rocm5.5 --index-url https://download.pytorch.org/whl/nightly/rocm5.5
Looking in indexes: https://download.pytorch.org/whl/nightly/rocm5.5
ERROR: Could not find a version that satisfies the requirement torch==2.1.0.dev-20230614+rocm5.5 (from versions: 2.2.0.dev20230921+rocm5.5)
ERROR: No matching distribution found for torch==2.1.0.dev-20230614+rocm5.5
WARNING! Tried to install torch==2.0.1, but the version is still None!
Found AMD GPU Navi 31 [Radeon RX 7900 XT/7900 XTX].
```

**To Reproduce**
1. Start EasyDiffusion
2. Go to settings
3. Try to flip the "use CPU" switch off
4. No bueno

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser: Any
 - Version: Rolling Release

**Comment by arrowgent** [comment]
https://github.com/easydiffusion/easydiffusion/issues/115#issuecomment-2196400054


work around fix for ubuntu.  you'll just need to get the rocm for arch
then follow the other dev console instruction to allow it to run.

**Comment by xenorio** [comment]
yup, that did it! thank you very much :)
