### ISSUE TITLE
│                                                                              │ │ Easy Diffusion is ready to serve requests.                                   │ │                                                                              │ │ A new browser tab should have been opened by now.                            │ │ If not, please open your web browser and navigate to http://localhost:9000/  │ │                                                                              │ ╰──────────────────────────────────────────────────────────────────────────────╯ ERROR:    [Errno 48] error while attempting to bind on address ('127.0.0.1', 9000): address already in use

### ISSUE THREAD

**Issue by Trantu1102** [easydiffusion/easydiffusion#1850]
**Describe the bug**
│                                                                              │
│ Easy Diffusion is ready to serve requests.                                   │
│                                                                              │
│ A new browser tab should have been opened by now.                            │
│ If not, please open your web browser and navigate to http://localhost:9000/  │
│                                                                              │
╰──────────────────────────────────────────────────────────────────────────────╯
ERROR:    [Errno 48] error while attempting to bind on address ('127.0.0.1', 9000): address already in use

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser:
 - Version:

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

**Comment by cmdr2** [comment]
`error while attempting to bind on address ('127.0.0.1', 9000): address already in use`

That means Easy Diffusion (or another program) is already running. Please close the other instance of Easy Diffusion (or the other program listening to port 9000), to solve this. Thanks
