### ISSUE TITLE
[Doubt]  Will this model be for stable diffusion only ?

### ISSUE THREAD

**Issue by Greatz08** [easydiffusion/easydiffusion#1852]
It would be nice if we could use flux open source model for image generation so i thought to ask if it supports flux model or will it support in future or this project will be for stable diffusion models only.

**Comment by AncientMystic** [comment]
The 3.5 beta supports flux, currently just playing around with it i can only manage to make it function with the ones that have clip, etc built in, the others fail. But still, flux works.
