### ISSUE TITLE
Hash File of The Latest Release

### ISSUE THREAD

**Issue by abwildan** [easydiffusion/easydiffusion#1854]
Can I get the hash file of the latest release?

**Comment by cmdr2** [comment]
Hi, just to confirm that I understand correctly - are you looking for the hash files for each of the installers at https://github.com/easydiffusion/easydiffusion/releases/tag/v3.0.9

Probably to verify that they haven't been tampered with? Good suggestion, but I'll keep this in mind for the future when I can make the installers automatically (via GitHub actions). Right now, I won't be able to commit to doing this for every release.
