### ISSUE TITLE
Infinite "pending" issue

### ISSUE THREAD

**Issue by d1e1xyk** [easydiffusion/easydiffusion#1856]
**Describe the bug**
When I press "Make image" the programm stucks on phase "pending" forever and makes nothing. As I understand, such an issue appeared earlier on Firefox, but now I have this in any browser - Edge, Chrome, Opera. I tries even reinstall Easy Diffusion but it doesn't help.

**Screenshots**
![18427](https://github.com/user-attachments/assets/54b6122f-1d5b-45d5-80e9-875bd8ff76d8)

What is written in console of the browser:
![725](https://github.com/user-attachments/assets/4241e267-3507-4c65-8ae5-6405049549c0)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Firefox, Chrome, Opera, Edge
 - Version: 3.0.9

**Comment by Kedhran14** [comment]
Hi, 

Got same issue there, tried to reinstall, clean cache, cut off AV (using kaspersky too), use a fresh new profile, but issue presists

In addition to screens provided by @d1e1xyk, the cmd is stuck at this point (i'm pretty sure there was more steps after that before)
![image](https://github.com/user-attachments/assets/f2dc176c-6577-48f3-ae49-d267f9b8a2ac)

**Comment by Kedhran14** [comment]
@d1e1xyk finally it was kaspersky for me. Just have uninstalled it, all works fine.

Let's find another AV XD

Thank you for putting me on the good search way.
