### ISSUE TITLE
Error: Could not load the stable-diffusion model! Reason: cannot import name 'cached_download' from 'huggingface_hub'

### ISSUE THREAD

**Issue by edwrdcrpio** [easydiffusion/easydiffusion#1861]
**Describe the bug**
Error: Could not load the stable-diffusion model! Reason: cannot import name 'cached_download' from 'huggingface_hub' (/easy-diffusion/installer_files/env/lib/python3.8/site-packages/huggingface_hub/__init__.py)

**To Reproduce**
1. Generate > Make Image 

**Expected behavior**
After make image I receive an Error

**Screenshots**
<img width="796" alt="Screenshot 2024-11-13 at 6 31 23 AM" src="https://github.com/user-attachments/assets/74686dd2-9319-4fde-96f9-0525432f0d79">

**Desktop (please complete the following information):**
 - OS: Mac 5.0.1 (24A348)
 - Browser: Safari
 - Version: Version 18.0.1 (20619.1.26.31.7)

**Comment by cmdr2** [comment]
Resolved this in https://github.com/easydiffusion/easydiffusion/issues/1851#issuecomment-2478000474

Closing, please reopen if this is still a problem. Thanks!

**Comment by Wauplin** [comment]
Hey there, maintainer of `huggingface_hub` here. Sorry for all the trouble this breaking change introduced. The best 
 -and future proof- solution to fix this is to **upgrade `diffusers` version** to a more recent version (>=0.29.0).

```
pip install "diffusers>=0.29.0"
```

This fixed version dates back to June 2024. The issue with pinning `huggingface_hub` to an old version is that it might conflict with future versions of diffusers/transformers.

Hope this will prove useful :pray:

**Comment by BuddyAce** [comment]
> Hey there, maintainer of `huggingface_hub` here. Sorry for all the trouble this breaking change introduced. The best -and future proof- solution to fix this is to **upgrade `diffusers` version** to a more recent version (>=0.29.0).
> 
> ```
> pip install "diffusers>=0.29.0"
> ```
> 
> This fixed version dates back to June 2024. The issue with pinning `huggingface_hub` to an old version is that it might conflict with future versions of diffusers/transformers.
> 
> Hope this will prove useful 🙏

Brand new to this, same error, but can someone explain what that means? > pip install "diffusers>=0.29.0" and how to do that?
