### ISSUE TITLE
! If you help to solve the problem, I'm even willing to give USDT as much as I can.

### ISSUE THREAD

**Issue by Fish6664** [easydiffusion/easydiffusion#1862]
Hi, I apologize for posting about this problem here. 
I've searched the whole support section, also on GitHub, looked and read - I couldn't find it. 

So here's the question... I have a constant “lags” neuronka, for example, I do 4 art on Pony, it does fine, then goes infinite loading, and the load on video memory drops to zero (not always). I put the model Aurora SD 1.5, to relieve the memory, then again put the desired model on the Pony, only so it starts to generate art again, but then again after a while repeats the whole procedure. My friend had the same thing, but just 2-3 days ago, when he got (and me) the Windows update, he stopped “lags”, everything started working perfectly as never before (he had a very similar problem to mine).

From additional information I can provide screenshots that when it “stings”, it tries to take more load from the video card than necessary.
I have GPU core frequency 1920 - 2475, and it takes as much as 2805 (monitored the process in GPU-Z MSI, ((I have a motherboard from msi)).

We are using v3.0.9 with a friend.
I have a 32gb ddr5 ram.
and a Palit RTX 4070 JetStream.
My friend has a very similar setup.
ram ddr4 and video card from msi(12gb), the video cards are almost identical in performance, the difference is literally in the margin of error.
If you can help glad to go to private messages or continue the dialog here, all screenshots can provide. 
just in case, I'll write another note to support.

**Comment by cmdr2** [comment]
Hi, no worries about USD, there is no paid support or priority, just volunteers.

Have you tried increasing the virtual memory on your PC? I'm not sure if that'll fix the problem, but it's definitely one of the things to try first - https://www.windowscentral.com/how-change-virtual-memory-size-windows-10

**Comment by Fish6664** [comment]
give your address in usdt trc20. This solved my problem by 60%! it still stutters and loads endlessly (and the video card is 100% clogged), but this is progress, thank you I’m writing through a translator, so don’t be surprised by errors in the text :)
