### ISSUE TITLE
aur oprhaned?

### ISSUE THREAD

**Issue by kittenvr** [easydiffusion/easydiffusion#1864]
**Describe the bug**
when i try to install from the aur using yay it says that is (Orphaned) (Out-of-date: 2024-11-23) 

**To Reproduce**
1. Go to terminal
2. run yay stable-diffusion-ui 
3. see that its orphaned(?) and out of date

**Expected behavior**
fix it to not be orphaned(?) and out of date

**Screenshots**
![image](https://github.com/user-attachments/assets/86220c16-c613-4036-888c-cd107a4aeaf1)

**Desktop (please complete the following information):**
 - OS: cachyos
 - Browser:firefox
 - Version:/

**Additional context**

**Comment by cmdr2** [comment]
Sorry, I don't know who manages the stable-diffusion-ui package on the yay package manager. It's not a supported installer. For linux, the supported way is to install using the zip file - https://github.com/easydiffusion/easydiffusion/releases/tag/v3.0.9
