### ISSUE TITLE
Separate the AMD compatibility layer to be used by other programs

### ISSUE THREAD

**Issue by RenaKunisaki** [easydiffusion/easydiffusion#1865]
This app works great on AMD GPUs. Other apps that do GPU calculations seem to only work on nVidia. It's my understanding that this app is using a compatibility layer to "fake" CUDA support and translate it to ROCm for the GPU. Many other programs could benefit from such a layer, but I don't know how to "extract" it from this app and use it for them.

**Comment by cmdr2** [comment]
Hi, it uses Pytorch-ROCm, which is already a separate layer. The only thing Easy Diffusion does separately is to look at the GPU model and decide which version of Pytorch-ROCm to use, and the configuration flags required for it.

And right now, Easy Diffusion's code for that is already out-of-date, and needs to be improved.

In general, extracting that might be useful to others, but I can't commit to doing it right now. If anyone's interested in that, please look at [this file](https://github.com/easydiffusion/easydiffusion/blob/main/scripts/check_modules.py#L58) and search for "AMD" in it.
