### ISSUE TITLE
RABBIT HOLE side bar is black now?

### ISSUE THREAD

**Issue by MikeSavad** [easydiffusion/easydiffusion#1873]
v3.5.1 (beta)
I don't know if this just updated, but my sidebar is now a dark grey and I do not like that. I keep everything white. I can't read the side text  and its distracting like that. The theme is set to white, it loads white for a second then it flips to grey. I guess it could be the browser, using the latest vivaldi, but it didn't do this yesterday.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser:
 - Version:

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

**Comment by MikeSavad** [comment]
I want to update this - its not the program apparently its a pluggin called - RABBIT HOLE, it turned the screen black on the side, and then when I went create, it showed rows of images and not a list, when I looked at the pluggins  it gave me this error:

Error loading plugin Rabbit Hole UI (Cannot read properties of null (reading 'length'))

I disabled it and its all back now.   Seems I really did go down the rabbit hole

**Comment by cmdr2** [comment]
Hi, not sure why Rabbit Hole isn't working for you. You can ask on the #plugins channel on the Discord server, not sure if the plugin author pushed some changes recently
