### ISSUE TITLE
Text input box sometimes becomes right aligned

### ISSUE THREAD

**Issue by NumbersOfFuz** [easydiffusion/easydiffusion#1878]
**Describe the bug**
Some unknown key bind causes the Main Prompt input text to become right aligned, making input very difficult.
A refresh fixes it but that makes the images go away (which is not great).

**To Reproduce**
I have no idea what the key bind is, but it's one of the letter keys on the left half of the keyboard + shift and/or control.
I tried to find it and couldn't, but is has happened at least 3 times.

**Screenshots**

Broken: (notice the resize drag on the left, and messed up commas)
![SS1](https://github.com/user-attachments/assets/fad89678-1830-4a80-9c08-b9492516525e)

**Expected behavior**
Post refresh working:
![SS2](https://github.com/user-attachments/assets/bf344d49-da4b-4d4e-9677-09d1d5537b9f)

**Desktop (please complete the following information):**
 - OS: Kubuntu 24.04
 - Browser: Firefox Snap
 - Version: 133.0.3 (64-bit)

**Smartphone (please complete the following information):** Don't use for SD.

**Additional context**
Not a major problem, just an incontinence. I do have image saving enabled, so imaged anent lost on refresh, just easier to look at them on the web UI than though Dolphin.

**Comment by NumbersOfFuz** [comment]
Easy diffusion is apparently not being actively developed anymore.
Should focus on more important bugs.

**Comment by cmdr2** [comment]
Hi @NumbersOfFuz I'd check if you have any plugins (Easy diffusion plugins or browser plugins) or system settings that might be affecting this. Easy Diffusion doesn't change the right/left alignment of the textbox. Thanks

**Comment by NumbersOfFuz** [comment]
Yeah that's about what I thought, might be some weird firefox hotkey/bug,
or one of the extensions. (ClearURL, StartPage, Ublock Origin)
I have not encountered it again.
