### ISSUE TITLE
What happened to unipc?

### ISSUE THREAD

**Issue by MikeSavad** [easydiffusion/easydiffusion#1879]
I could have sworn unipc was in the old version, can you put it back?  thanks

**Comment by cmdr2** [comment]
The app hasn't changed in a few weeks, please check your settings (especially the "Engine" setting in the settings tab)

**Comment by MikeSavad** [comment]
I'm using beta right now, and I  was certain that unipc was an option, but not now.  The flux things are in its place.

Any way to get that one back?
Thanks
