### ISSUE TITLE
IndexError using some samplers with >=36 inference steps

### ISSUE THREAD

**Issue by aburgd** [easydiffusion/easydiffusion#319]
**Describe the Bug**
Index error when running euler_a sampler with >= 36 inference steps

**To Reproduce**
1. Run the `Start Stable Diffusion UI.cmd`
2. In Image Settings, ensure Sampler is euler_a
3. Set inference step count to any integer 36 or greater
4. Enter prompt
5. Click Make Image
6. Get `IndexError: index 1000 is out of bounds for dimension 0 with size 1000`

**Expected Behavior**
Return an image generated from the provided prompt

**Screenshots**
![image](https://user-images.githubusercontent.com/6305821/195218178-3f3849c8-bdde-49be-8bbe-1914c89ed018.png)
![image](https://user-images.githubusercontent.com/6305821/195218211-248b9430-dfa2-428c-a965-c266f1e8174c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Brave 1.44.108 Chromium: 106.0.5249.103 (Official Build) (64-bit) 
 - Version: 21H2

**Additional context**
No other settings adjustments were made.

**Comment by aburgd** [comment]
The same error is thrown on euler, plms, and ddim.

**Comment by ovear** [comment]
Step 27 also not works.

May related to upstream's issue basujindal/stable-diffusion#174

**Comment by Seedmanc** [comment]
What's weird is that only 36 and 37 steps don't work, 38 and above are fine.

**Comment by JeLuF** [comment]
The new "v3" engine in EasyDiffusion 3.0 doesn't have this restriction any more.
