### ISSUE TITLE
Linux:  Automatically Save To Problems (general settings) 

### ISSUE THREAD

**Issue by urbanscribe** [easydiffusion/easydiffusion#371]
**Describe the bug**
Can't get automatic save to (general settings) to work on Linux.  Works on other installs (W)

**To Reproduce**
enter local address in general settings and type local path

tried inside same folder & outside with added permissions
nothing saves locally
have to use manual download

UBUNTU 20.04

Assuming the settings are set when you type them in (no save/Apply).  they see to persist through reload page.  Applying settings unclear.  

log says SAVING IMAGES see below

dump
Global seed set to 1005
Sampling:   0%|                                           | 0/1 [00:00<?, ?it/sseeds used =  [1005]                                       | 0/1 [00:00<?, ?it/s]
Running Euler Ancestral Sampling with 35 timesteps
100%|███████████████████████████████████████████| 35/35 [00:13<00:00,  2.59it/s]
saving images
memory_final =  61.585408███████████████████████| 35/35 [00:13<00:00,  2.68it/s]
data: 100%|███████████████████████████████████████| 1/1 [00:14<00:00, 14.54s/it]
Sampling: 100%|███████████████████████████████████| 1/1 [00:14<00:00, 14.54s/it]
Task completed
Session 1666361651850 task 140528992718176 completed.

**Comment by JeLuF** [comment]
Are you using the browser on the same computer where the server is running? If these are not the same computers, the save path must exist on the server side.

**Comment by RenaKunisaki** [comment]
I've had cases where opening the web UI on two different computers (for the same server) caused some images to not be saved, and the save path to be reset. I don't know if I did something to cause that.
