### ISSUE TITLE
Loading custom Objects and Styles?

### ISSUE THREAD

**Issue by magpie514** [easydiffusion/easydiffusion#428]
Is there any way to load Objects or Styles from the huggingface's SD Concept Library? I mean these: https://huggingface.co/sd-concepts-library    as referenced in this little article  [Warning: Ugly Sonic within](https://minimaxir.com/2022/09/stable-diffusion-ugly-sonic/)

Basically microtraining. Like, for example, the standard 1.4 SD model doesn't know what the "backrooms" are, but you have them be recognized by adding this https://huggingface.co/sd-concepts-library/backrooms and adding <backrooms> into the prompt. Similarly you can train (locally or using Colab) it to recognize your own designs like, dunno, spaceships, and feed them to the machine, or train for specific styles instead. Adds a lot of flexibility to models that aren't exactly well trained on unpopular themes (like robots that aren't tin cans) or pop culture references that the models don't quite understand.

The linked Colabs have code showing how to load them. Specifically [This part](https://colab.research.google.com/github/huggingface/notebooks/blob/main/diffusers/stable_conceptualizer_inference.ipynb#scrollTo=bJx50Ta37392&line=4&uniqifier=1)

**Comment by JeLuF** [comment]
EasyDiffusion 3.0 (released yesterday) supports embeddings. To use the embeddings from the concept library, download the concept's `learned_embeds.bin`, rename it to the token to be used to activate the embedding (e.g. `backrooms.bin`) and place the file into the `models\embeddings` folder.
