### ISSUE TITLE
What am I doing wrong? 

### ISSUE THREAD

**Issue by boxabirds** [easydiffusion/easydiffusion#471]
**Describe the bug**
Can't run the Windows cmd file. Repeatedly "command not found" errors

**To Reproduce**
- Download windows installer
- Run: conda not found. git not found. This is not a 1-click installer. 
- So, Installed git and conda. 
- Then I get the errors below: help most appreciated :)
 
```
The system cannot find the path specified.
C:\Program Files\Git\cmd\git.exe
git version 2.38.1.windows.1
C:\Users\boxab\anaconda3\Library\bin\conda.bat
C:\Users\boxab\anaconda3\Scripts\conda.exe
conda 22.9.0
The system cannot find the path specified.
Press any key to continue . . .
```

**Desktop (please complete the following information):**
 - OS: Windows 11 
 - Browser: Chrome

**Comment by cmdr2** [comment]
Hi, it found git (it's printed the found path).

The `system cannot find the path specified` is probably an incorrect shell hook on your PC. It's not coming from this project. You can test by opening a new Command Prompt window (Win+R, type "cmd" and press Run) - you'll see that message again. To be honest, you can ignore that message. I think it's coming from the system-wide conda setup that you have.

The main question is, the conda being used is wrong. Our installer installs a different conda at the folder it's in, it doesn't use the system-wide conda.

Can you please confirm that you downloaded this installer using these instructions? https://github.com/cmdr2/stable-diffusion-ui#installation

Thanks

**Comment by boxabirds** [comment]
Yes. When I launched the cmd the first time it says git not found and conda
not found so I installed both.

**Comment by JeLuF** [comment]
Did you run the `Start Stable Diffusion UI.cmd` directly from the zip file, or did you first extract the contents of the zip file to e.g. `C:\stable-diffusion-ui` ?

**Comment by JeLuF** [comment]
closed due to inactivity
