### ISSUE TITLE
Error while using SD 1.5 inpainting model

### ISSUE THREAD

**Issue by Metsuryu** [easydiffusion/easydiffusion#509]
**Describe the bug**

Using the Stable Diffusion 1.5 inpainting model results in this error:
`Error: Error(s) in loading state_dict for UNet: size mismatch for model1.diffusion_model.input_blocks.0.0.weight: copying a param with shape torch.Size([320, 9, 3, 3]) from checkpoint, the shape in current model is torch.Size([320, 4, 3, 3]).`

The console shows this:

```
loading D:\stable-diffusion-ui\models\stable-diffusion\sd-v1-5-inpainting.ckpt to device cpu using precision full
Loading model from D:\stable-diffusion-ui\models\stable-diffusion\sd-v1-5-inpainting.ckpt
Global Step: 440000
UNet: Running in eps-prediction mode
Traceback (most recent call last):
  File "D:\stable-diffusion-ui\ui\sd_internal\runtime.py", line 341, in mk_img
    yield from do_mk_img(req)
  File "D:\stable-diffusion-ui\ui\sd_internal\runtime.py", line 433, in do_mk_img
    load_model_ckpt()
  File "D:\stable-diffusion-ui\ui\sd_internal\runtime.py", line 116, in load_model_ckpt
    _, _ = model.load_state_dict(sd, strict=False)
  File "D:\stable-diffusion-ui\stable-diffusion\env\Lib\site-packages\torch\nn\modules\module.py", line 1497, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for UNet:
        size mismatch for model1.diffusion_model.input_blocks.0.0.weight: copying a param with shape torch.Size([320, 9, 3, 3]) from checkpoint, the shape in current model is torch.Size([320, 4, 3, 3]).
```

**To Reproduce**
1. Open stable-diffusion-ui
2. Select the SD 1.5 inpainting model
3. Try to generate an image (either with inpainting, or not)

**Expected behavior**

The model should work without errors.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 107.0

**Additional context**
Running in CPU mode.

**Comment by kauttoj** [comment]
Please add support for this model. This error can be avoided by loading the proper yaml file "v1-inpainting-inference.yaml"  instead of the default one. However, then there is another error caused by usage of "Optimized Stable Diffusion" branch of SD, which doesn't support inpainting model that is not optimized.

**Comment by JeLuF** [comment]
EasyDiffusion 3.0, released today, introduces support for inpainting models.
