### ISSUE TITLE
Different results in some tests

### ISSUE THREAD

**Issue by bach777** [easydiffusion/easydiffusion#524]
I was testing on cmdr2/stable-diffusion-ui and AUTOMATIC1111/Webui and found that the results are significantly different, using exactly the same settings, vae, etc.
Does anyone have an idea what the problem might be?
![1](https://user-images.githubusercontent.com/115612779/202998684-69657e0d-dfb7-4fd1-b38d-67b24a569120.png)
![2](https://user-images.githubusercontent.com/115612779/202998690-ca6dcdad-982f-41f1-944c-a5e732341ac6.png)

**Comment by ChrisAcrobat** [comment]
If you copy over the sd checkpoint from AUTOMATIC1111 to cmdr2/models/stable-diffusion, and rename it so you know which is which, do you still get the same result?

**Comment by bach777** [comment]
Yes... the same result.
Maybe is the Eta noise seed delta (ENSD), but I dont know what ETA cmdr2 are using here

**Comment by JeLuF** [comment]
Does your prompt contain brackets to emphasize/deemphasize parts of the promtp? The amount of emphasis added per bracket  differs between SDUI and SDWebUI.

**Comment by JeLuF** [comment]
closed due to inactivity
