### ISSUE TITLE
Model selection for inpainting

### ISSUE THREAD

**Issue by IshanJ25** [easydiffusion/easydiffusion#539]
Just like the main model selection option, an inpainting model selection option would be really helpful and increase productivity

I tried downloading the inpainting model and placed it in the `stable-diffusion-ui\models\stable-diffusion` folder, but it shows error on running. Clearly, the said model is not for image generation but for inpainting only.

Please consider adding such feature.

It is an overall awesome project and works amazingly.
Thankyou.

**Comment by JeLuF** [comment]
This is a restriction of the Stable Diffusion distribution we're using. The developers are currently working on replacing this distribution with a more modern one, and the choice of a sampler for img2img is on the wishlist for this project.

**Comment by JeLuF** [comment]
EasyDiffusion 3.0, released today, comes with support for inpainting models.
