### ISSUE TITLE
"Localhost:9000" never will connect

### ISSUE THREAD

**Issue by mistfall1** [easydiffusion/easydiffusion#550]
I'm following the "How to use" directions after installing the software on my Windows 10 laptop.  
The first step after installation is to go to http://localhost:9000
Although my internet connection is working, every attempt to navigate to this page generates an error page that says:
"Unable to connect

Firefox can’t establish a connection to the server at localhost:9000.

    The site could be temporarily unavailable or too busy. Try again in a few moments.
    If you are unable to load any pages, check your computer’s network connection.
    If your computer or network is protected by a firewall or proxy, make sure that Firefox is permitted to access the Web."

Microsoft Edge browser also generates a "Err_Connection_refused" report when trying to navigate to that page.

Both browsers are updated to the most current version. Any suggestions as to how to proceed?

**Desktop (please complete the following information):**
 - OS: 
 - Browser:
 - Version:

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

**Comment by JeLuF** [comment]
Do you have any proxy, vpn or anti-malware protection enabled on your PC or your browsers?

Do you know your PC's local IP address? Can you try to connect to `http://your-ip:9000/`, for example `http://192.168.123.45:9000/`?

**Comment by JeLuF** [comment]
Did you close the installer window after it completed, or did you keep it running? The application server is running in that window and it is required for the application to run.

**Comment by JeLuF** [comment]
closed due to inactivity
