### ISSUE TITLE
Miss sampler selection in img2img mode

### ISSUE THREAD

**Issue by Parley1984** [easydiffusion/easydiffusion#562]
hello. it is missing the possibility to select a sampler while using img2img. There the sampler DDIM is always used and you can't change this because the dropdown menu for the samplers is hidden.

**Comment by JeLuF** [comment]
This is a restriction of the Stable Diffusion distribution we're using. The developers are currently working on replacing this distribution with a more modern one, and the choice of a sampler for img2img is on the wishlist for this project.

**Comment by JeLuF** [comment]
EasyDiffusion 3.0 (released yesterday) supports all samplers also in img2img mode
=> issue closed.
