### ISSUE TITLE
error install linux ubuntu 20.04.1 LTS

### ISSUE THREAD

**Issue by jfogin** [easydiffusion/easydiffusion#573]
error: micromamba download failed , "bzip2:  Cannot exec" - behavior as bzip2 not installed but is it installed latest version !

**Comment by d3xplo1t** [comment]
I had the same problem, fixed installing curl, do you have curl installed?
try: 
sudo apt update
sudo apt install curl
./start.sh

**Comment by JeLuF** [comment]
closed due to inactivity
