### ISSUE TITLE
Randomize seed for each prompt

### ISSUE THREAD

**Issue by olivierkes** [easydiffusion/easydiffusion#583]
Not sure this is a bug, but it does bug me ^^

**Describe the bug**
When using multiple prompts in the prompt textbox (with multiple lines) and random seed, the same random seed is used for all generated images.

**To Reproduce**
1. Create a prompt with multiple line
2. Toggle Random Seed in Image settings

**Expected behavior**
It seems to me that each generated image should have it's own random seed.

**Potential fix**
- Change the behavior when the toggle is set to random so that each image has its own random seed.
- Maybe: add a button "Randomize seed" that changes the seed value to a random number

**Desktop (please complete the following information):**
 - OS:  linux
 - Browser: chromium
 - Version: v2.4.17

**Comment by DaTedinator** [comment]
I would also like the option to use a new seed for each prompt in a batch.

**Comment by cmdr2** [comment]
If the prompt is different, it'll effectively produce different images. But this sounds like a UI plugin, since it's specific to your workflow: https://github.com/easydiffusion/easydiffusion/wiki/UI-Plugins
