### ISSUE TITLE
Support Embeddings created by Textual Inversion

### ISSUE THREAD

**Issue by WildBanjos** [easydiffusion/easydiffusion#590]
**Describe the solution you'd like**
Support the usage of embedding files created though Textual Inversion. When an embedding, which would have been trained in one of many other projects, is loaded, the user can input the keyword associated with embedding as a type of "shortcut" to influence the results towards a specific style

For example, [this embedding](https://huggingface.co/datasets/Nerfgun3/bad_prompt) can be loaded and the token "bad_prompt" is added as a negative prompt, results will be influenced to remove many common errors, reducing the number of tokens the negative prompt will often use. (ex: instead of using "deformed, bad hands, multiple limbs, blurry, etc..." as a negative prompt, "bad_prompt" would be used). Other embeddings can add a specific artstyle, subject, character, etc.

For this project, a folder could be added to the install directory called "embeddings", any embedding files would be loaded during startup.

**Describe alternatives you've considered**
Compared to model checkpoints, most embeddings are much smaller in size, usually only a few megabytes. While their influence is limited compared to a checkpoint, they do have a different usecase and are growing in usage/popularity.

**Comment by JeLuF** [comment]
EasyDiffusion 3.0, released today, comes with support for Embeddings.
