### ISSUE TITLE
Stuck during install on "using precision: full" (whole night passed)

### ISSUE THREAD

**Issue by necros2k7** [easydiffusion/easydiffusion#605]
@cmdr2 
**Describe the bug**
Is it ok?
HDD activity stuck at this message during install
"loaded model
 model file: F:\stable-diffusion-ui\stable-diffusion\sd-v1-4.ckpt
 model.device: cpu
 modelCS.device: cpu
 modelFS.device: cpu
 using precision: full"

**To Reproduce**
1. Start installing subj

**Expected behavior**
Normal run

**Desktop (please complete the following information):**
 - OS:  win11 
 - Browser: latest Chromium
 - Version: 110

**Additional context**
Can hardware be an issue? GTX 950 and dual Xeon E5-2690

**Comment by JeLuF** [comment]
That actually looks like the installation has been completed and the server is ready.
During the installation, a web page should have been opened. If not, can you please check `http://localhost:9000`?

**Comment by JeLuF** [comment]
closed due to inactivity
