### ISSUE TITLE
need some help with understanding styles

### ISSUE THREAD

**Issue by DrakenLotus** [easydiffusion/easydiffusion#629]
hey there so i have a bunch of .pt files and i have 0 idea how to use the notebook and i was wondering if there is and easy to use way to install the .pt file like is there a specific folder i can drag and drop them into or a command i can type into command prompt. if not can some one point me to a simple guide to installing these and i do mean really simple just started to learn all about this a week ago.

**Comment by JeLuF** [comment]
Easy Diffusion 3.0 adds support for embeddings (".pt files"). Place them into the `models\embeddings` files to use them.
