### ISSUE TITLE
 uvicorn server Crashes on clean install.

### ISSUE THREAD

**Issue by napstich** [easydiffusion/easydiffusion#630]
I performed a clean install on Ubuntu 22.04.1 LTS. When I try to launch the UI, the embedded web server crashes and I get interface errors that the page cannot be found. 

**To Reproduce**
1. Download Linux installer from https://github.com/cmdr2/stable-diffusion-ui
2. Run start.sh
3. Wait for install to finish and the web UI to launch
4. Within a few seconds all buttons in the interface report "localhost:9000 The Server is not Available.

**Expected behavior**
Being able to use the application. 

 - Device: Desktop PC
 - OS:  Ubuntu 22.04.1 LTS
 - Browsers: Google Chrome 108.0.5359.98 (Official Build) (64-bit) and Firefox 107.0.1 (64-bit),
 
**Additional context**
The browser often gives this error at initial load. Clicking "Try Again" takes me to the application interface, but that only runs for a few seconds.

Unable to connect

Firefox can’t establish a connection to the server at localhost:9000.

    The site could be temporarily unavailable or too busy. Try again in a few moments.
    If you are unable to load any pages, check your computer’s network connection.
    If your computer or network is protected by a firewall or proxy, make sure that Firefox is permitted to access the web.

**This is the content from the command prompt used to run start.sh**

bash start.sh 
/home/matthew/Documents/stable-diffusion-ui/installer_files/env/bin/git
git version 2.38.1
/home/matthew/Documents/stable-diffusion-ui/installer_files/env/bin/conda
conda 22.11.1

Stable Diffusion UI

Stable Diffusion UI's git repository was already installed. Updating from beta..
HEAD is now at ba2c966 First draft of multi-task in a single session. (#622)
Already on 'beta'
Your branch is up to date with 'origin/beta'.
Already up to date.

Hotfixed broken JSON file from OpenAI
Stable Diffusion's git repository was already installed. Updating..
HEAD is now at 7f32368 Use a specific version of opencv-python
You are not currently on a branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

HEAD is now at 7f32368 Use a specific version of opencv-python
Packages necessary for Stable Diffusion were already installed
Packages necessary for GFPGAN (Face Correction) were already installed
Packages necessary for ESRGAN (Resolution Upscaling) were already installed
Packages necessary for Stable Diffusion UI were already installed
Picklescan is already installed.
SafeTensors is already installed.
Data files (weights) necessary for Stable Diffusion were already downloaded
Data files (weights) necessary for GFPGAN (Face Correction) were already downloaded
Data files (weights) necessary for ESRGAN (Resolution Upscaling) x4plus were already downloaded
Data files (weights) necessary for ESRGAN (Resolution Upscaling) x4plus_anime were already downloaded
Data files (weights) necessary for the default VAE (sd-vae-ft-mse-original) were already downloaded

Stable Diffusion is ready!

PYTHONPATH=/home/matthew/Documents/stable-diffusion-ui/stable-diffusion:/home/matthew/Documents/stable-diffusion-ui/stable-diffusion/env/lib/python3.8/site-packages
/home/matthew/Documents/stable-diffusion-ui/stable-diffusion/env/bin/python
Python 3.8.5
started in  /home/matthew/Documents/stable-diffusion-ui/stable-diffusion
Scan /home/matthew/Documents/stable-diffusion-ui/models/vae/vae-ft-mse-840000-ema-pruned.ckpt: 1 scanned, 0 issue, 0 infected.
requesting for render_devices auto
WARNING: Could not find a compatible GPU. Using the CPU, but this will be very slow!
devices_to_start {'cpu'}
devices_to_stop set()
Start new Rendering Thread on device cpu
Render device CPU available as Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz
loading /home/matthew/Documents/stable-diffusion-ui/stable-diffusion/sd-v1-4.ckpt to device cpu using precision full
Loading model from /home/matthew/Documents/stable-diffusion-ui/stable-diffusion/sd-v1-4.ckpt
active devices {'cpu': {'name': 'Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz'}}
INFO:     Started server process [12775]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:9000 (Press CTRL+C to quit)
Global Step: 470000
UNet: Running in eps-prediction mode
./scripts/on_sd_start.sh: line 330: 12775 Killed                  uvicorn server:app --app-dir "$SD_UI_PATH" --port ${SD_UI_BIND_PORT:-9000} --host ${SD_UI_BIND_IP:-0.0.0.0}
Press any key to continue

**Comment by JeLuF** [comment]
Your PC probably ran out of memory and the Linux kernel killed uvicorn. SDUI needs at least 8 GB physical memory and on top of that at least 16 GB real swap space. zswap might not be sufficient, since it consumes physical RAM.

**Comment by napstich** [comment]
I've got 8GB of RAM, but nowhere near that much swap space. I'll look into increasing my swap space and trying again. Thank you.

**Comment by realenuf** [comment]
I have 16GB RAM, and I have the exact same problem on Ubuntu 22.04.1LTS.

**Comment by JeLuF** [comment]
Check your `dmesg` output. Very likely, `./scripts/on_sd_start.sh: line 330: 12775 Killed uvicorn server:app` means that your PC ran out of virtual memory. You need to have enough swap space configured, and it's recommended not to use zswap. The total amount of physical RAM + Swap space should be at least 24 GB.

**Comment by KrissiBT** [comment]
![image](https://user-images.githubusercontent.com/6164394/215181657-27f670fa-ed25-4134-b523-06aefcbc61d5.png)
same happens here eats up 16gigs of ram and 4 gigs of swap and crashes

**Comment by KrissiBT** [comment]
> ![image](https://user-images.githubusercontent.com/6164394/215181657-27f670fa-ed25-4134-b523-06aefcbc61d5.png) same happens here eats up 16gigs of ram and 4 gigs of swap and crashes

this is not an issue with automatic 1111. What is happening differently here
