### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by Vadim1387** [easydiffusion/easydiffusion#633]
I'm sorry, I don't know at all. I get an error during installation, what could be the problem?
![Screenshot_2](https://user-images.githubusercontent.com/120197182/206736726-40fb31dc-5150-4da2-8275-899a6c7832b0.jpg)

**Comment by JeLuF** [comment]
You need to follow the instructions of the error message and delete the corrupted file. The installer will then try to download a working copy when you run `Start Stable Diffusion UI.cmd` again.

**Comment by kfsone** [comment]
Doesn't look like the site has the bandwidth for the downloads:

```
PS> curl -L -k https://me.cmdr2.org/stable-diffusion-ui/sd-v1-4.ckpt --output sd-v1-4.ckpt
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  3 4067M    3  132M    0     0  3400k      0  0:20:25  0:00:39  0:19:46     0
curl: (56) Failure when receiving data from the peer
```

(repeatedly, whether I do it thru the script or manually, from windows, wsl, macbook or linux)

**Comment by JeLuF** [comment]
Closing issue, since EasyDiffusion 3.0 doesn't use this download server any more.
