### ISSUE TITLE
What about tiling feature?

### ISSUE THREAD

**Issue by ProgrammingLife** [easydiffusion/easydiffusion#640]
**Is your feature request related to a problem? Please describe.**
What about tiling feature for genereating seamless textures?

**Describe the solution you'd like**
Tiling checkbox to generate seamless textures

**Describe alternatives you've considered**
AUTOMATIC1111's stable diffusion webui can do so

**Additional context**
n/a

**Comment by JeLuF** [comment]
EasyDiffusion 3.0, released today, comes with seamless texture support
