### ISSUE TITLE
The server is not available.

### ISSUE THREAD

**Issue by jassim-madan** [easydiffusion/easydiffusion#656]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser:
 - Version:

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

**Comment by JeLuF** [comment]
Please provide a description of your problem.
Did you start the server using `Start Stable Diffusion UI.cmd`?
Are there any error messages in the console window started by `Start Stable Diffusion UI.cmd`?
On the browser page, type `Ctrl-Shift-R`, does this fix your problem?

**Comment by Sam-Varghese** [comment]
Greeting of the day @JeLuF 

This is the first time I'm using stable-diffusion-ui. After I click on `Start Stable Diffusion UI.cmd`, it opens a new tab on my Brave browser. But when I click on `Make Image` button, I keep getting the error `Connection with the server lost`

Here are the screen shots for evidence

![image](https://user-images.githubusercontent.com/79152648/208356267-96af1150-e2c8-43c6-b534-b2634f9cb4c5.png)

![image](https://user-images.githubusercontent.com/79152648/208356296-2c45a394-8b1c-4383-b8ea-f210dfcb910d.png)

![image](https://user-images.githubusercontent.com/79152648/208356338-0cfe8b05-8176-4a1f-85f3-36f4a8a39ea7.png)

And here is the screenshot of my cmd

![image](https://user-images.githubusercontent.com/79152648/208356460-026c0e1b-7758-45dd-ac13-9bc903eac79d.png)

I request you to help me out so I may explore this amazing technology

Regards
Sam Varghese

**Comment by lukekendall** [comment]
Same problem, under Linux, started via "./start.sh"
Notable errors that appeared before the final one:
scripts/on_env_start.sh: line 3: ./scripts/functions.sh: No such file or directory
(Correct: the script directory contains only bootstrap.sh  install_status.txt  on_sd_start.sh
config.json    on_env_start.sh)
and
INFO:     Started server process [1388096]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
ERROR:    [Errno 98] error while attempting to bind on address ('0.0.0.0', 9000): address already in use
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
./scripts/on_sd_start.sh: line 330: 1388096 Aborted                 (core dumped) uvicorn server:app --app-dir "$SD_UI_PATH" --port ${SD_UI_BIND_PORT:-9000} --host ${SD_UI_BIND_IP:-0.0.0.0}

It's possible I have a tab open in some browser window; finding it among the 500 or so I have open will be challenging (assuming that IS the real problem)

**Comment by lukekendall** [comment]
I also tried a fresh install from https://stable-diffusion-ui.github.io/
Same result. The UI appears but it won't render.
Also tried on a 2nd Linux computer.
(Both have only a CPU, no GPU.)

**Comment by Rashudorufu** [comment]
I have the problem now in Windows in a similar way, but in my case it gets stuck at opening Stable Diffusion UI by "Start Stable Diffusion UI.cmd". There ain't any error messages, but it leads to the problem that I'm not able to generate an image. It worked quite well when I opened it the first time after installation. Now, these are the points where it stops loading, for everytime I did a new attempt:

![Screenshot 2023-01-06 211048](https://user-images.githubusercontent.com/105920506/211094313-7ba64c6b-52ce-473a-a287-d858a5c3bc27.png)

Another attempt:

![Screenshot 2023-01-06 212255](https://user-images.githubusercontent.com/105920506/211094309-5a93addb-b1ec-4028-899d-d41f1b578b0e.png)

When I try to generate a new image, this happens:

![Screenshot 2023-01-06 211231](https://user-images.githubusercontent.com/105920506/211094316-ae74d301-9cb1-49ca-9ca8-31d28e017bf5.png)

**Comment by JeLuF** [comment]
>`ERROR: [Errno 98] error while attempting to bind on address ('0.0.0.0', 9000): address already in use`

The server can't start because port 9000 is used by another program.

https://github.com/cmdr2/stable-diffusion-ui/wiki/Config-settings#network-ports describes how to change the port

**Comment by dlakelan** [comment]
Similar symptoms here... I run start.sh on Linux... it pulls up the UI but says "stable diffusion is starting" in the upper right corner and never starts up... tens of minutes later I still can't generate an image.

There is no process using port 9000 before running, and one process listening on port 9000 after running, obviously it connects to get the UI... but generate image doesn't work.



![image](https://user-images.githubusercontent.com/4332910/212758145-afebb983-d3cf-4771-b286-68efd3a1e4ef.png)
![image](https://user-images.githubusercontent.com/4332910/212758195-58babe94-e68c-4763-9723-6d11f126dcb9.png)

**Comment by dlakelan** [comment]
Sorry for the noise. This was apparently fixed by a reboot of my machine, it had some issues with a hung network share.

**Comment by JeLuF** [comment]
closed due to inactivity
