### ISSUE TITLE
Endless progress bar.

### ISSUE THREAD

**Issue by Archon332** [easydiffusion/easydiffusion#658]
**Describe the bug**
It started yesterday. When I use the consistent generation of few images, UI started to show me only one of generated images. And during generation progress bar started to stuck on one point (29 minutes in example) even if .cmd file says that generation is completed and all images are saved.

I didn't pushed any buttons in settings last few days.

**Screenshots**
![Session1](https://user-images.githubusercontent.com/119755850/207422619-72f7b28c-343a-4597-b1c0-48b3fc181e20.png)
![Session2](https://user-images.githubusercontent.com/119755850/207422633-1c9fc7e9-e90a-4c90-b929-8f1e47662fd9.png)

**As you can see, generation is completed, but progress bar still exists.**

![Session3](https://user-images.githubusercontent.com/119755850/207423823-c2344a54-cabd-477b-88f5-2e58d72cd102.png)

AI use so much time for generation because I use CPU instead of GPU in term of having weak video card (Nvidia geforce gtx 1050).

Sorry for my English.

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Browser: Open UI with Microsoft Edge
 - Version: 108.0.1462.46

**Comment by cmdr2** [comment]
Closing, please feel free to reopen if this is still relevant, and continues to be an issue in the latest version: https://github.com/easydiffusion/easydiffusion/releases/tag/v3.0.2
