### ISSUE TITLE
Is there an ability to use ready-to-use embedding .pt files?

### ISSUE THREAD

**Issue by ProgrammingLife** [easydiffusion/easydiffusion#665]
How to use embeddings with this repo? Which folder should I use to store ready-to-use embedding (.pt) files?

**Comment by PrudentPotato** [comment]
Been looking around for a place to put them. I don't think there is a place to put the **PT files**. Other software refers to them (by folder name) as "**embeddings**."

**Comment by cmdr2** [comment]
This is now available with the latest version: https://github.com/easydiffusion/easydiffusion/releases/tag/v3.0.2

You can put them in the `models/embeddings` folder, and add them to your prompt by clicking the `+ Embeddings` button, or just typing the name of the embedding (without the extension) in the prompt.
