### ISSUE TITLE
Download error

### ISSUE THREAD

**Issue by JeLuF** [easydiffusion/easydiffusion#678]
Greeting of the day @JeLuF 

This is the first time I'm using stable-diffusion-ui. After I click on `Start Stable Diffusion UI.cmd`, it opens a new tab on my Brave browser. But when I click on `Make Image` button, I keep getting the error `Connection with the server lost`

Here are the screen shots as evidence

![image](https://user-images.githubusercontent.com/79152648/208356267-96af1150-e2c8-43c6-b534-b2634f9cb4c5.png)

![image](https://user-images.githubusercontent.com/79152648/208356296-2c45a394-8b1c-4383-b8ea-f210dfcb910d.png)

![image](https://user-images.githubusercontent.com/79152648/208356338-0cfe8b05-8176-4a1f-85f3-36f4a8a39ea7.png)

And here is the screenshot of my cmd

![image](https://user-images.githubusercontent.com/79152648/208356460-026c0e1b-7758-45dd-ac13-9bc903eac79d.png)

- And reloading the page with the shortcut key `Ctrl` + `Shift` + `R` didn't work out.
- I used Google instead of Brave, after executing `Start Stable Diffusion UI.cmd` program again, but no change.

System details

![image](https://user-images.githubusercontent.com/79152648/208357882-0b6a49ae-bfc4-4746-a410-8b876b2c93b9.png)

I request you to help me out so I may explore this amazing technology

Regards
Sam Varghese

_Originally posted by @Sam-Varghese in https://github.com/cmdr2/stable-diffusion-ui/issues/656#issuecomment-1357130612_

**Comment by JeLuF** [comment]
Hello @Sam-Varghese,

Please don't post requests in unrelated bug reports, open your own issues instead. This way you can avoid confusion.

Please post the full log of the `Start Stable Diffusion UI.cmd` window. You can select and copy the text by typing `Ctrl-A` followed by `Enter` into the window. Then, please paste it into a notepad window, save it and upload the text here.

From the small part that I could see, the SDUI server failed to download model data from the internet due to connectivity issues. Please ensure that no anti-malware, anti-virus, VPN or proxy software is preventing downloads.

**Comment by Sam-Varghese** [comment]
Sorry for the inconvenience. I'll take care of this next time.

> Please ensure that no anti-malware, anti-virus, VPN or proxy software is preventing downloads.

No I've my laptop doesn't have any anti-malware, anti-virus, VPN or proxy software which can prevent downloads.

Here's the full log

[StableDiffusionErrorLog.txt](https://github.com/cmdr2/stable-diffusion-ui/files/10265595/StableDiffusionErrorLog.txt)

**Comment by cmdr2** [comment]
Closing, please reopen if this is still an issue, and doesn't work with the latest version: https://github.com/easydiffusion/easydiffusion/releases/tag/v3.0.2
