### ISSUE TITLE
dark popups 

### ISSUE THREAD

**Issue by Ryder17z** [easydiffusion/easydiffusion#683]
**Is your feature request related to a problem? Please describe.**
it feels weird that the popup is using the light theme exclusively, regardless of what theme is selected

**Describe the solution you'd like**
Have the popups follow the selected theme (this could be a checkbox to enable or disable)

**Describe alternatives you've considered**
Light theme and overriding it with Dark Reader, but this looks really bad.

**Additional context**
"Dangerous Actions"

**Comment by cmdr2** [comment]
This was resolved several version ago. Thanks for the suggestion!
