### ISSUE TITLE
suggestion for video AI

### ISSUE THREAD

**Issue by uswin** [easydiffusion/easydiffusion#697]
Hi cmdr2 team, your project has been insanely good. and im forever grateful for this project.
anyway, i really wish after this project is mature enough, you might consider to make Video AI project with UI exactly like this project.

this is by far the easiest and most complete stable diffusion project i have ever seen, it would be amazing if you can do this too for video ai

best regards

**Comment by sandiMexicola** [comment]
"this is by far the easiest and most complete stable diffusion project i have ever seen"... I really must agree.

**Comment by cmdr2** [comment]
Thanks! Unfortunately video is not planned for the future, it's a completely different product with a lot of features that I won't be able to get to.

**Comment by ke1ne** [comment]
@cmdr2 Maybe, this one? https://github.com/guoyww/AnimateDiff
Cheers!
