### ISSUE TITLE
Listing available samplers in an API response

### ISSUE THREAD

**Issue by andrey-helldar** [easydiffusion/easydiffusion#713]
**Is your feature request related to a problem? Please describe.**

I'm developing a PHP script that interacts with the Stable Diffusion UI to generate a sampler table (for example, [this one](https://github.com/andrey-helldar/stable-diffusion-ui-samplers-generator#sampler)).

I started writing an application for version 2.4.22, and today I turned on a subscription to the Beta channel and, having received version 2.5.3 beta, I saw new samplers.

Thus, if I run the generation of my application on a new SD version, then the new samplers will not get into the final image. And if you add them, then when you try to run the application on version 2.4, we will get a file existence error.

**Describe the solution you'd like**

The API has a `GET /get/models` method that returns a list of available models and vae. I suggest considering also adding a list of available samplers to it.

For example, current state:

```json
{
  "active": {
    "stable-diffusion": "sd-v1-4",
    "vae": "",
    "hypernetwork": ""
  },
  "options": {
    "stable-diffusion": [
      "sd-v1-4",
      "synthwavePunk_v2"
    ],
    "vae": [
      "vae-ft-ema-560000-ema-pruned",
      "vae-ft-mse-840000-ema-pruned"
    ],
    "hypernetwork": []
  }
}
```

Proposed state:

```jsonc
{
    "active": {
    "stable-diffusion": "sd-v1-4",
    "vae": "",
    "hypernetwork": ""
  },
  "options": {
    "stable-diffusion": [
        "sd-v1-4",
        "synthwavePunk_v2"
    ],
    "vae": [
        "vae-ft-ema-560000-ema-pruned",
        "vae-ft-mse-840000-ema-pruned"
    ],
    "hypernetwork": [],
    "samplers": {
        "plms": "PLMS",
        "ddim": "DDIM",
        // ...
        "dpm_solver_stability": "DPM Solver (Stability AI)",
        "dpmpp_2s_a": "DPM++ 2s Ancestral"
    }
  }
}
```

Stable:

https://github.com/cmdr2/stable-diffusion-ui/blob/8cedeb349d3440bb120d761800485f9c3e848790/ui/index.html#L139-L148

Beta:

https://github.com/cmdr2/stable-diffusion-ui/blob/280f0be690ee6ca7c4cbad2e1769ebbfa5f60401/ui/index.html#L145-L160

**Describe alternatives you've considered**

Right now I'm keeping the sampler names explicit in the config file, but I plan to change that to the following logic:

When requesting `GET /get/system_info`, I will read the `default_output_dir` parameter from which I will get the path to the `sd-ui-files/ui/index.html` file.

Further, I will parse this file as xml, getting an array of samplers from it.

**Comment by cmdr2** [comment]
Hi, sorry but the API is not meant for external use. You can use sdkit via Python which is our main engine and supports all the features that you're asking for. https://github.com/easydiffusion/sdkit
