### ISSUE TITLE
It is recommended to add the existing functions of auto 1111

### ISSUE THREAD

**Issue by labelhigh** [easydiffusion/easydiffusion#716]
It is recommended to add these functions:
1. Updated to support Stable Diffusion 2.1
2. Textual Inversion embeddings
3. inpainting & outpainting

**Comment by spiralofhope** [comment]
outpainting is available with a plugin:  https://github.com/cmdr2/stable-diffusion-ui/issues/32#issuecomment-1503253629

**Comment by JeLuF** [comment]
SDXL, inpainting and embedding support have been added with EasyDiffusion 3.0, released today.
