### ISSUE TITLE
Support for Apple Silicone (M1/M2 and so on) platform (.dmg to .app drag n drop install) and Flatpak installation for Linux.

### ISSUE THREAD

**Issue by sarcastic-tofu** [easydiffusion/easydiffusion#723]
#1. This project can greatly be financially be benefited from possible revenue coming from potential contributors amongst Apple users.. there are some good FOSS programs available on Apple App Store that collects money by providing easy, reliable access to their products with very nominal onetime fees for both novices and professionals users of OS X. Plus it will also benefit from contributions from FOSS developers that work on OS X.

#2. Even if you guys decide that MacOS is not a platform worth considering at all and just sticking to X64 (Windows & Linux) is just fine having a common, easy & portable universal solution (Flatpak) can give a good breathing space for further improvements & problem solving on a diverse & diluted Linux space with it's Arch, Fedora, Debian & other branches.. right?

In any case these are just my takes, I will highly be appreciative even if you guys not wanna think about these at this moment... just keep up your excellent work!!!

**Comment by cmdr2** [comment]
Thanks for the suggestions. Since this post, we've added full support for Mac (intel, M1 and M2).

We're still interested in making .dmg and .flatpack and .snap files, and are looking for code contributors to help with that.

Once .dmg is ready, yeah listing on the app stores would be a good idea.
