### ISSUE TITLE
Preview is not working after the first image

### ISSUE THREAD

**Issue by iegoshin** [easydiffusion/easydiffusion#728]
**Describe the bug**
The new release stops updating preview images. When I am generating large images with img2img, e.g. 1024 x 1536 it displays first image and then it doesn't add new ones. The batch displays 3 of 10, but in the preview - only 1 image. It auto-saves images into the specified folder though. I am using CPU mode.

**To Reproduce**
1. select large image e.g. 1024 x 1536
2. enter prompt
3. number of images: 10
4. Inference Steps: 30
5. w: 1024 h: 1536
6. click Enqueue next 10 images
7. wait

**Behavior**
It displays 1st image and then nothing changes any more

**Expected behavior**
It should display 2st, 3rd, ... and 10th image as well

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser: Firefox
 - Version: 108.0.1 (64-bit)

**Comment by cmdr2** [comment]
Hi this has been working for a long time, please feel free to reopen if you still face this issue.
