### ISSUE TITLE
Sugession: integrate stable difusión infinity 

### ISSUE THREAD

**Issue by modma** [easydiffusion/easydiffusion#780]
Please, A interesting tool that can be add is stable diffusion infinity for outpaiting https://huggingface.co/spaces/lnyan/stablediffusion-infinity

**Comment by cmdr2** [comment]
Sorry, but this is a large amount of work that I won't be able to get to right now. You can try the Outpaint plugin here for now: https://github.com/easydiffusion/easydiffusion/wiki/UI-Plugins
