### ISSUE TITLE
Prompt compilation preview

### ISSUE THREAD

**Issue by ChrisAcrobat** [easydiffusion/easydiffusion#782]
**Is your feature request related to a problem? Please describe.**
**Describe the solution you'd like**
A thing I'm missing is a compact tooltip or hint window to displays the pending prompt batches before they are generated.
This could be solved by optionally calling `getPrompts` on prompt changes and display a compact list below the prompt input, if more then one response is returned.
https://github.com/cmdr2/stable-diffusion-ui/blob/1da4b3d94aa3f0d545f0fa1089409334b3acd381/ui/media/js/main.js#L964

**Describe alternatives you've considered**
`None`

**Additional context**
I have been thinking of adding this my self, but I haven't got the time and will probably not for some time either. So in the meanwhile I'll just share the idea.

Also, a separata issue is that could be solved in the same time is that the `Enqueue Next 3 Images` does not take number of prompts into consideration. An update to the button could be `Enqueue Next 3 Images x 4 prompts`.

**Comment by cmdr2** [comment]
Sorry, I won't be able to get to this. Plus this sounds like a good idea for a UI plugin: https://github.com/easydiffusion/easydiffusion/wiki/UI-Plugins

**Comment by ChrisAcrobat** [comment]
Thanks for the idea! I will probably put some time into this later.
