### ISSUE TITLE
Add ability to remove images in local storage when [Remove] button is clicked in client.

### ISSUE THREAD

**Issue by dim1902** [easydiffusion/easydiffusion#788]
Currently, if [Auto-Save images] enabled, images are saved to provided location - and that is great! But when I click [Remove] button on client - generated image is removed on client only, but it stays in auto-save folder. Because generation and deletion is iterative process and is done periodically - very soon ton of garbage can be found in auto-save folder and I have to remove it once more manually.

Feature request:
- Add to Settings new flag: Remove generated images in auto-save folder on [Remove] pressed in client. By default set it to FALSE and everything works like it is implemented right now.
- When flag set to TRUE - on [Remove] button press on generated image in client - this image should be removed in auto-save folder as well (both jpg/pgn file and txt file with metadata)

Alternative:
- If [Settings:Auto-Save Images] is FALSE - to show among other options on image
![image](https://user-images.githubusercontent.com/6151064/213435006-3baf7379-4031-49bb-ade9-946ecbc7e35b.png)
new option: Save to local storage. If this option is clicked - save to auto-save folder this image (both jpg/pgn file and txt file with metadata)

**Comment by cmdr2** [comment]
Sorry, I won't be able to get to this because of the security risks of deleting files on the computer based on browser inputs. Lots of users use Easy Diffusion on the network, and this would cause a security risk.
