### ISSUE TITLE
Stable Diffusion doesn't start: port 9000 is not accessible

### ISSUE THREAD

**Issue by Xiaofang362** [easydiffusion/easydiffusion#792]
Stable Diffusion doesn't start. A message in console:
ERROR:    [Errno 10013] error while attempting to bind on address ('0.0.0.0', 9000): An attempt was made to access a socket in a way forbidden by its access permissions
Please answer me, what is the probable cause of the error, and what can be done about it.

**Comment by JeLuF** [comment]
This can have three causes that I'm aware of:
* _Stable Diffusion UI_ is already running. You can't start it twice.
* Another program is running that is using port 9000. To check, open a `cmd` window and run the command `netstat -an | findstr :9000`. If the output contains a line like `  TCP   0.0.0.0:9000     0.0.0.0:0    LISTENING`, the port is already in use.
* Windows Firewall might block your access. This [Microsoft knowledge base article](https://support.microsoft.com/en-us/windows/risks-of-allowing-apps-through-windows-defender-firewall-654559af-3f54-3dcf-349f-71ccd90bcc5c) describes how to allow a program to open access. In the list of apps, search for `python`. If you need to add it, the path is `C:\stable-diffusion-ui\stable-diffusion\env\python.exe` (replace `C:` if you installed to a different drive)

**Comment by filipecunhabrasil** [comment]
tri to change: https to http
