### ISSUE TITLE
Image Style:  Landscape

### ISSUE THREAD

**Issue by The-QCC** [easydiffusion/easydiffusion#795]
Easy Diffusion v2.5.10 (beta)
The setting for Image Style:  Landscape is saved and restored with the next session.
Except the thumbnails are always Faces.
The Landscape thumbnails may be restored by toggling the Image Style from Faces
 to Landscape.
A very minor issue.
Browser: FireFox 109.0 (64-bit)
Windows 10 Pro
Hp Z640

![Landscape](https://user-images.githubusercontent.com/122744905/214473473-6ea3c3a9-ec6a-42dc-99a4-e2dda1e60f03.jpg)
![Faces](https://user-images.githubusercontent.com/122744905/214473474-cc67da8c-7aa0-4d49-9f00-80fab827e6af.jpg)

**Comment by The-QCC** [comment]
The "Image Style" is still not being restored.

**Comment by JeLuF** [comment]
This has been fixed in EasyDiffusion 3.0
