### ISSUE TITLE
"Error: The downloaded model file was invalid! Bytes downloaded: 478158408" any help guys

### ISSUE THREAD

**Issue by Protovax** [easydiffusion/easydiffusion#798]
i was doing everything correctly beside's the minor error's and stuff then this came after downloading the (weights) or data files and it stayed it right their saying that i should contact this or simpley reinstall which i did but then again this came up

**Comment by paolodalprato** [comment]
Same message here, then reinstalled and was ok (it started from the model download step)

**Comment by Protovax** [comment]
what model download step ?

**Comment by paolodalprato** [comment]
the default model proposed in the installation

**Comment by Protovax** [comment]
okay my guy so how do you reinstall this i don't know much about this or i could have forget about a all lot about python and other stuff . so how do you reinstall

**Comment by paolodalprato** [comment]
I'am on windows, I clicked again the "Start Stable Diffusion UI.cmd" file

**Comment by Protovax** [comment]
my bro it happened again and this time i reinstalled it .  will you give me a in depth understanding of "this"

**Comment by cmdr2** [comment]
If this is still relevant, please download the file manually from https://github.com/easydiffusion/sdkit-test-data/releases/download/assets/sd-v1-5.safetensors and save it to the `models/stable-diffusion` folder.
