### ISSUE TITLE
Show current jobs in jobs list on fresh page load

### ISSUE THREAD

**Issue by brandonsturgeon** [easydiffusion/easydiffusion#801]
I like to check the progress of jobs from my phone, but when I load the page from another device it doesn't show the current jobs. This could also potentially be used to share the result images if they're saved to disk.

**Comment by RenaKunisaki** [comment]
This would also be nice for not losing all queued jobs when your browser crashes.

**Comment by JeLuF** [comment]
This is a non-trivial change. Currently, the queue exists only in the browser. The backend only knows about the current jobs.

**Comment by cmdr2** [comment]
Sorry, this won't be possible to implement at this time. Please feel free to contribute a pull request if interested.
