### ISSUE TITLE
CondaHTTPError: HTTP 000 CONNECTION FAILED for url

### ISSUE THREAD

**Issue by Swbrad** [easydiffusion/easydiffusion#802]
https://conda.anaconda.org/pytorch/win-64/pytorch-1.11.0-py3.8_cuda11.3_cudnn8_0.tar.bz2>

I searched for this url and found:

Code: NoSuchKey
Message: The specified key does not exist.
Key: pytorch/win-64/pytorch-1.11.0-py3.8_cuda11.3_cudnn8_0.tar.bz2>
RequestId: 12E447B4HSTY6JFY
HostId: EK0HW5R5tj46VRtfWNXgIZUpc7KJCSsKsbpPZr3A2lMhoBLv9oBHTwE3at4J1dkKySLfI0Y31p8=

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: EDGE
 - Version: 109

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**
Just trying to download stable-diffusion-ui.  Tried this twice. Could my browser be the problem?

**Comment by twerpyfie** [comment]
The ">" at the end of the link is the problem I think.

**Comment by Swbrad** [comment]
Thank you for your idea.  I changed my browser from edge to firefox and got the program loaded.  I haven't found any operating glitches, but really need to spend a few concentrated hours building some idea.  My photoshop training really helps with the finesse, but the ideas are hard.
 Best,
Steven Bradley Bradley's Cabinet ShopGreen Building Associates2029 Calle LejanoSanta Fe, NM 87501505-983-5125In a message dated 2/4/2023 7:03:57 AM Mountain Standard Time, ***@***.*** writes: 

 

The ">" at the end of the link is the problem I think.

**Comment by SouthLink** [comment]
I have the same problem with my system

**Comment by JeLuF** [comment]
> I have the same problem with my system

Which message exactly do you get? Please copy the full output of the command window.

**Comment by SouthLink** [comment]
> > 我的系统有同样的问题
> 
> 你到底得到了哪条信息？请复制命令窗口的完整输出。
windows 10 system
"Downloading micromamba from https://github.com/cmdr2/stable-diffusion-ui/releases/download/v1.1/micromamba.exe to D:\stable-diffusion-ui\installer_files\mamba\micromamba.exe"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 8028k  100 8028k    0     0   364k      0  0:00:22  0:00:22 --:--:--  580k
Micromamba version:
0.26.0

                                           __
          __  ______ ___  ____ _____ ___  / /_  ____ _
         / / / / __ `__ \/ __ `/ __ `__ \/ __ \/ __ `/
        / /_/ / / / / / / /_/ / / / / / / /_/ / /_/ /
       / .___/_/ /_/ /_/\__,_/_/ /_/ /_/_.___/\__,_/
      /_/

Empty environment created at prefix: D:\stable-diffusion-ui\installer_files\env
"Packages to install: conda"

                                           __
          __  ______ ___  ____ _____ ___  / /_  ____ _
         / / / / __ `__ \/ __ `/ __ `__ \/ __ \/ __ `/
        / /_/ / / / / / / /_/ / / / / / / /_/ / /_/ /
       / .___/_/ /_/ /_/\__,_/_/ /_/ /_/_.___/\__,_/
      /_/

conda-forge/noarch                                  11.1MB @ 509.3kB/s 22.4s
conda-forge/win-64                                  19.1MB @ 276.0kB/s 1m:10.2s

Transaction

  Prefix: D:\stable-diffusion-ui\installer_files\env

  Updating specs:

   - conda


  Package                         Version  Build               Channel                 Size
---------------------------------------------------------------------------------------------
  Install:
---------------------------------------------------------------------------------------------

  + brotlipy                        0.7.0  py311ha68e1ae_1005  conda-forge/win-64     343kB
  + bzip2                           1.0.8  h8ffe710_4          conda-forge/win-64     152kB
  + ca-certificates             2022.12.7  h5b45459_0          conda-forge/win-64     147kB
  + certifi                     2022.12.7  pyhd8ed1ab_0        conda-forge/noarch     151kB
  + cffi                           1.15.1  py311h7d9ee11_3     conda-forge/win-64     293kB
  + charset-normalizer              2.1.1  pyhd8ed1ab_0        conda-forge/noarch      36kB
  + colorama                        0.4.6  pyhd8ed1ab_0        conda-forge/noarch      25kB
  + conda                         22.11.1  py311h1ea47a8_1     conda-forge/win-64       1MB
  + conda-package-handling          2.0.2  pyh38be061_0        conda-forge/noarch     253kB
  + conda-package-streaming         0.7.0  pyhd8ed1ab_1        conda-forge/noarch      17kB
  + cryptography                   39.0.0  py311h28e9c30_0     conda-forge/win-64       1MB
  + idna                              3.4  pyhd8ed1ab_0        conda-forge/noarch      57kB
  + libffi                          3.4.2  h8ffe710_5          conda-forge/win-64      42kB
  + libsqlite                      3.40.0  hcfcfb64_0          conda-forge/win-64     670kB
  + libzlib                        1.2.13  hcfcfb64_4          conda-forge/win-64      71kB
  + menuinst                       1.4.19  py311h1ea47a8_1     conda-forge/win-64     110kB
  + openssl                         3.0.7  hcfcfb64_2          conda-forge/win-64       7MB
  + pip                              23.0  pyhd8ed1ab_0        conda-forge/noarch       1MB
  + pluggy                          1.0.0  pyhd8ed1ab_5        conda-forge/noarch      16kB
  + pycosat                         0.6.4  py311ha68e1ae_1     conda-forge/win-64     105kB
  + pycparser                        2.21  pyhd8ed1ab_0        conda-forge/noarch     103kB
  + pyopenssl                      23.0.0  pyhd8ed1ab_0        conda-forge/noarch     127kB
  + pysocks                         1.7.1  pyh0701188_6        conda-forge/noarch      19kB
  + python                         3.11.0  hcf16a7b_0_cpython  conda-forge/win-64      20MB
  + python_abi                       3.11  3_cp311             conda-forge/win-64       6kB
  + requests                       2.28.2  pyhd8ed1ab_0        conda-forge/noarch      57kB
  + ruamel.yaml                   0.17.21  py311ha68e1ae_2     conda-forge/win-64     250kB
  + ruamel.yaml.clib                0.2.7  py311ha68e1ae_1     conda-forge/win-64      96kB
  + setuptools                     67.1.0  pyhd8ed1ab_0        conda-forge/noarch     576kB
  + tk                             8.6.12  h8ffe710_0          conda-forge/win-64       4MB
  + toolz                          0.12.0  pyhd8ed1ab_0        conda-forge/noarch      49kB
  + tqdm                           4.64.1  pyhd8ed1ab_0        conda-forge/noarch      83kB
  + tzdata                          2022g  h191b570_0          conda-forge/noarch     108kB
  + ucrt                     10.0.22621.0  h57928b3_0          conda-forge/win-64       1MB
  + urllib3                       1.26.14  pyhd8ed1ab_0        conda-forge/noarch     113kB
  + vc                               14.3  hb6edc58_10         conda-forge/win-64      16kB
  + vs2015_runtime            14.34.31931  h4c5c07a_10         conda-forge/win-64     725kB
  + wheel                          0.38.4  pyhd8ed1ab_0        conda-forge/noarch      33kB
  + win_inet_pton                   1.1.0  pyhd8ed1ab_6        conda-forge/noarch       8kB
  + xz                              5.2.6  h8d14728_0          conda-forge/win-64     218kB
  + zstandard                      0.19.0  py311he5d195f_1     conda-forge/win-64     306kB
  + zstd                            1.5.2  h12be248_6          conda-forge/win-64     288kB

  Summary:

  Install: 42 packages

  Total download: 41MB

---------------------------------------------------------------------------------------------


Transaction starting
python_abi                                           6.1kB @  36.5kB/s  0.2s
vc                                                  15.7kB @  93.3kB/s  0.2s
tzdata                                             108.1kB @  12.6kB/s  8.4s
ca-certificates                                    146.6kB @  16.1kB/s  9.1s
win_inet_pton                                        8.2kB @ 898.0 B/s  0.0s
ucrt                                                 1.3MB @ 140.8kB/s  9.1s
pluggy                                              16.4kB @   1.8kB/s  0.0s
idna                                                56.7kB @   6.2kB/s  0.0s
ruamel.yaml.clib                                    96.1kB @   9.1kB/s  1.4s
zstandard                                          306.3kB @  27.0kB/s  0.8s
conda-package-streaming                             17.5kB @   1.5kB/s  0.0s
requests                                            56.7kB @   5.0kB/s  0.1s
libsqlite                                          669.9kB @  52.3kB/s  1.4s
xz                                                 217.8kB @  16.1kB/s  0.7s
setuptools                                         575.7kB @  29.0kB/s 11.2s
pycparser                                          102.7kB @   5.1kB/s  0.1s
certifi                                            150.8kB @   7.3kB/s  0.6s
tqdm                                                83.5kB @   4.0kB/s  0.4s
cffi                                               293.0kB @  13.7kB/s 12.2s
ruamel.yaml                                        250.4kB @  11.7kB/s  0.5s
pyopenssl                                          127.1kB @   5.8kB/s  0.3s
bzip2                                              152.2kB @   6.3kB/s  2.4s
wheel                                               32.5kB @   1.3kB/s  0.1s
charset-normalizer                                  36.5kB @   1.5kB/s  0.1s
pycosat                                            105.2kB @   4.2kB/s  0.7s
brotlipy                                           342.7kB @  13.1kB/s  1.1s
vs2015_runtime                                     725.0kB @  24.0kB/s 30.2s
zstd                                               288.4kB @   6.6kB/s 13.6s
toolz                                               49.1kB @   1.1kB/s  0.1s
cryptography                                         1.1MB @  23.6kB/s  2.0s
libffi                                              42.1kB @ 916.0 B/s  0.0s
colorama                                            25.2kB @ 548.0 B/s  0.0s
urllib3                                            112.5kB @   2.4kB/s  0.4s
openssl                                              7.1MB @ 142.3kB/s 23.4s
pip                                                  1.4MB @  27.5kB/s  3.3s
conda-package-handling                             253.2kB @   5.1kB/s  0.1s
libzlib                                             71.2kB @   1.4kB/s  0.0s
pysocks                                             19.3kB @ 388.0 B/s  0.0s
menuinst                                           110.3kB @   2.2kB/s  0.2s
conda                                                1.2MB @  22.6kB/s 33.5s
tk                                                   3.7MB @  52.0kB/s 1m:10.6s
python                                              19.8MB @ 240.8kB/s 1m:8.8s
Linking python_abi-3.11-3_cp311
Linking ucrt-10.0.22621.0-h57928b3_0
Linking ca-certificates-2022.12.7-h5b45459_0
Linking vs2015_runtime-14.34.31931-h4c5c07a_10
Linking vc-14.3-hb6edc58_10
Linking openssl-3.0.7-hcfcfb64_2
Linking libsqlite-3.40.0-hcfcfb64_0
Linking libffi-3.4.2-h8ffe710_5
Linking bzip2-1.0.8-h8ffe710_4
Linking xz-5.2.6-h8d14728_0
Linking tk-8.6.12-h8ffe710_0
Linking libzlib-1.2.13-hcfcfb64_4
Linking zstd-1.5.2-h12be248_6
Linking tzdata-2022g-h191b570_0
Linking python-3.11.0-hcf16a7b_0_cpython
Linking wheel-0.38.4-pyhd8ed1ab_0
Linking setuptools-67.1.0-pyhd8ed1ab_0
Linking pip-23.0-pyhd8ed1ab_0
Linking pycparser-2.21-pyhd8ed1ab_0
Linking win_inet_pton-1.1.0-pyhd8ed1ab_6
Linking colorama-0.4.6-pyhd8ed1ab_0
Linking charset-normalizer-2.1.1-pyhd8ed1ab_0
Linking idna-3.4-pyhd8ed1ab_0
Linking certifi-2022.12.7-pyhd8ed1ab_0
Linking toolz-0.12.0-pyhd8ed1ab_0
Linking pluggy-1.0.0-pyhd8ed1ab_5
Linking pysocks-1.7.1-pyh0701188_6
Linking tqdm-4.64.1-pyhd8ed1ab_0
Linking ruamel.yaml.clib-0.2.7-py311ha68e1ae_1
Linking pycosat-0.6.4-py311ha68e1ae_1
Linking menuinst-1.4.19-py311h1ea47a8_1
Linking cffi-1.15.1-py311h7d9ee11_3
Linking ruamel.yaml-0.17.21-py311ha68e1ae_2
Linking cryptography-39.0.0-py311h28e9c30_0
Linking zstandard-0.19.0-py311he5d195f_1
Linking brotlipy-0.7.0-py311ha68e1ae_1005
Linking pyopenssl-23.0.0-pyhd8ed1ab_0
Linking conda-package-streaming-0.7.0-pyhd8ed1ab_1
Linking urllib3-1.26.14-pyhd8ed1ab_0
Linking conda-package-handling-2.0.2-pyh38be061_0
Linking requests-2.28.2-pyhd8ed1ab_0
Linking conda-22.11.1-py311h1ea47a8_1
Transaction finished
C:\Program Files\Git\cmd\git.exe
git version 2.27.0.windows.1
D:\stable-diffusion-ui\installer_files\env\Library\bin\conda.bat
D:\stable-diffusion-ui\installer_files\env\Scripts\conda.exe
conda 22.11.1

"Stable Diffusion UI - v2"


"Downloading Stable Diffusion UI.."

"Using the main channel"

Cloning into 'sd-ui-files'...
remote: Enumerating objects: 12981, done.
remote: Counting objects: 100% (223/223), done.
remote: Compressing objects: 100% (93/93), done.
remote: Total 12981 (delta 146), reused 190 (delta 126), pack-reused 12758 eceiving objects: 100% (12981/12981), 55.07 MiB | 565.00 KiB/s
Receiving objects: 100% (12981/12981), 55.33 MiB | 528.00 KiB/s, done.
Resolving deltas: 100% (8465/8465), done.
491 File(s) copied
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.

Hotfixed broken JSON file from OpenAI
module torch not found
"Installing torch and torchvision.."
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu116
ERROR: Could not find a version that satisfies the requirement torch (from versions: none)
ERROR: No matching distribution found for torch
"Error installing torch. Sorry about that, please try to:"
"  1. Run this installer again."
"  2. If that doesn't fix it, please try the common troubleshooting steps at https://github.com/cmdr2/stable-diffusion-ui/wiki/Troubleshooting"
"  3. If those steps don't help, please copy *all* the error messages in this window, and ask the community at https://discord.com/invite/u9yhsFmEkB"
"  4. If that doesn't solve the problem, please file an issue at https://github.com/cmdr2/stable-diffusion-ui/issues"
"Thanks!"
Press any key to continue . . .

**Comment by JeLuF** [comment]
> ERROR: Could not find a version that satisfies the requirement torch (from versions: none)
> ERROR: No matching distribution found for torch

You have a completely different error message to the original poster. There was a problem with our installer that caused this problem. Please delete the previous installation and download the new installer from https://github.com/cmdr2/stable-diffusion-ui/releases/download/v2.5.15/stable-diffusion-ui-windows.zip
