### ISSUE TITLE
Negative prompts possibly being ignored?

### ISSUE THREAD

**Issue by apollolux** [easydiffusion/easydiffusion#809]
**Describe the bug**
Attempting to reproduce similar results to a particular negative prompts tutorial seems to give results similar to those as if the negative prompts were ignored or reduced in weight. The checkpoint in use is the Anything-3.0 set, but I'm worried that it's not limited to just that.

**To Reproduce**
1. Visit the Aitrepreneur video at https://www.youtube.com/watch?v=W4tzFI3e_xo for the info about the Anything-3.0 model and background on the comparisons done.
2. Visit the linked Miro board at https://miro.com/app/board/uXjVPChrzFo=/ to obtain the prompts used for testing. You may need to zoom out to see more. The prompts and negative prompts in particular were the "Christina Hendricks" prompts later in the board and video, as well as their associated settings.
3. Obtain the Anything-3.0 model and VAE for the particular prompts
4. Run SD with the given prompts and settings. I understand that the interface of this Stable Diffusion UI is different from the Stable Diffusion web UI used in the video I linked, but I did my best to match the fields given that this is my first attempt at SD-UI.
5. Get images that, while very good looking, look much closer to the set in the video without negative prompts than the set in the video with negative prompts.

**Expected behavior**
I expected the negative prompts to be applied as given and the images generated to be closer to the set with the negative prompts than the set without them.

**Screenshots**
Screenshots attached.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro v21H2, Intel64 Family 6 Model 142 Stepping 9, GenuineIntel (cpu rendering)
 - Browser: Edge 109
 - Version: SD-UI 2.4.13
Surface Pro 5th gen, 8GB RAM, i5-7300U @ 2.60GHz

**Additional context**
The version of Anything-3.0 in use was obtained 2023-01-28 and is the "fp16-pruned" version of the set for resource conserving purposes. Using CPU rendering because the tablet does not have a qualifying GPU. Not sure if the given negative prompt string is too long or something.

Seed: 1198044006
![Seed-1198044006_Steps-28_Guidance-10](https://user-images.githubusercontent.com/493607/215374020-58e62a51-d578-4bcf-9c8a-935eb7aa3fd2.jpeg)

Seed: 200526402
![Seed-200526402_Steps-28_Guidance-10-r3](https://user-images.githubusercontent.com/493607/215374023-a359b0dc-cba6-400e-aa9a-b61785f4745d.jpeg)

**Comment by JeLuF** [comment]
Please provide the prompt and negative prompt that were causing problems.

**Comment by apollolux** [comment]
Prompt: Ultra realistic photo portrait of Christina Hendricks cosmic energy, colorful painting burst, beautiful face, symmetrical face, tone mapped, intricate, elegant, highly detailed, digital painting, artstation, concept art, smooth, sharp focus, illustration, beautiful face, intricate, highly detailed, smooth, sharp focus,art by artgerm and greg rutkowski and alphonse mucha

Negative prompt: lowres, (bad anatomy, bad hands:1.1), text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry, artist name, b&w, weird colors, (cartoon, 3d, bad art, poorly drawn, close up, blurry:1.5), (disfigured, deformed, extra limbs:1.5)

Steps (inference step in SD-UI?) = 28, Sampler = euler_a, CFG scale (guidance scale in SD-UI?) = 10, edited the original comment to point out what seed each image is.

I'm not sure if having some terms duplicated in either affect their weight as I'm new to using Stable Diffusion txt2img in general.

**Comment by JeLuF** [comment]
The negative prompt is a hint for the AI, it's not an absolute requirement that the AI can't violate. Especially if the AI encounters contradicting requirements in the prompt and negative prompt it will ignore parts of it.

The AI has no idea what good or bad anatomy is. It is trained on image descriptions of millions of pictures, but I doubt that a single one is tagged with "bad anatomy". Terms like "missing fingers" or "extra digit" have the same problem. These are terms that the AI hasn't been trained with. 

The use of brackets in combination with weights isn't supported in Easy Diffusion's current parser. `(disfigured, deformed, extra limbs:1.5)` does cause error messages and parts of it get ignored, as described in the [wiki](https://github.com/cmdr2/stable-diffusion-ui/wiki/Writing-prompts#emphasizing-parts-of-the-prompt)

**Comment by sandiMexicola** [comment]
I think maybe that negative prompt might be too long?

**Comment by JeLuF** [comment]
> IF YOU THINK IM UPSET ITS BECAUSE I HAD TO WASTE THREE HOURS OF MY LIFE TO FIGURE THIS OUT

What do you think how I feel, writing lots of documentation, linking to it from the `Help & Community` tab, just to find out that no one puts in the effort into reading before posting lengthy rants on github?

And btw, a new parser is available in the "[Diffusers Tech Preview](https://discord.com/channels/1014774730907209781/1014774732018683924/1094858222353010768)" 

It uses the [compel](https://github.com/damian0815/compel/blob/main/Reference.md) standard for prompts.

**Comment by sandiMexicola** [comment]
We

> > The use of brackets in combination with weights isn't supported in Easy Diffusion's current parser. `(disfigured, deformed, extra limbs:1.5)` does cause error messages and parts of it get ignored, as described in the [wiki](https://github.com/cmdr2/stable-diffusion-ui/wiki/Writing-prompts#emphasizing-parts-of-the-prompt)
> 
> my brother in christ, i love you, but you guys suck ass at explaining things
> 
> here's what you do, you rewrite that whole garbage, and you use a normal format like this
> 
> * you start with the positive prompt, and you teach people, THIS IS THE EXACT FORMAT you gotta use, then you tell them, how the weights work, you explain all the weird ass details about them, so that there wont be any confusion about them ever, you put a nice visual example like the one i made and, it will help out a lot, you also write down a section of common errors and how to fix them, because people will mess up, this is not intuitive at all
> * next, you go to the negative prompt and you say, THIS IS THE EXACT FORMAT DUMBASS, and you explain the parentheses, and how to do the math, also add an extra section on, potential errors you could make and how to fix them
> 
> then you explain the extra bullshit
> 
> blah
> 
> either that or, make the parser more consistent, why do the text boxes use two different systems??? whyy???
> 
> for all i know the negative prompts work perfectly fine but, their documentation is just, abysmal and its embarassing to look at, im sorry but its just badly made, i know you guys are programmers but, this needs to be rewritten and it needs to be more complete
> 
> IF YOU THINK IM UPSET ITS BECAUSE I HAD TO WASTE THREE HOURS OF MY LIFE TO FIGURE THIS OUT BLAH

Maybe you would like to become a contributor?
Anyways, the programmers don't owe you anything.

**Comment by JeLuF** [comment]
Closed ticket due to inactivity.
