### ISSUE TITLE
ERROR: The downloaded model file was invalid! Bytes downloaded: 201612854

### ISSUE THREAD

**Issue by zharinovkv** [easydiffusion/easydiffusion#814]
**Describe the bug**
Downloading data files (weights) for Stable Diffusion..                         
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  4 4067M    4  192M    0     0   603k      0  1:55:07  0:05:26  1:49:41     0
curl: (18) transfer closed with 4063767658 bytes remaining to read

EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE

ERROR: The downloaded model file was invalid! Bytes downloaded: 201612854

Error downloading Stable Diffusion UI. Sorry about that, please try to:
 1. Run this installer again.
 2. If that doesn't fix it, please try the common troubleshooting steps at https://github.com/cmdr2/stable-diffusion-ui/wiki/Troubleshooting
 3. If those steps don't help, please copy *all* the error messages in this window, and ask the community at https://discord.com/invite/u9yhsFmEkB
 4. If that doesn't solve the problem, please file an issue at https://github.com/cmdr2/stable-diffusion-ui/issues

Thanks!

**Comment by alphadaddy-stacked** [comment]
same here

**Comment by cmdr2** [comment]
Closing a stale bug. This is no longer relevant, since the new installer installs the model using a different technique: https://github.com/easydiffusion/easydiffusion/releases/tag/v3.0.2
