### ISSUE TITLE
how to use loRA

### ISSUE THREAD

**Issue by RandomPollas** [easydiffusion/easydiffusion#816]
iv'e been seeing these loRA archives, at [civit.ai](https://civitai.com/models/5014/my-hero-academia-horikoshi-kouhei-style-lora) and i don't know if we can use them with this version

**Comment by lztz0022** [comment]
Have you found out how to use loRA in stable-diffusion-ui?

**Comment by JeLuF** [comment]
Closed as duplicate of #1170
