### ISSUE TITLE
[img2img] Non square input images give distorted output

### ISSUE THREAD

**Issue by Deltrego** [easydiffusion/easydiffusion#819]
img2img generation does not preserve h/w ratio of image. This sometimes affects the network's interpretation of the scene so fixing it afterwards may not work. A workaround is to initially resize the canvas of the input image to a square and center in a photo editor but this is tedious and the border affects the result a bit.  Could it be done automatically?
Edit: using Stable Diffusion UI - v2.4.24 on Windows 10 x64

**Comment by Trithilon** [comment]
A two pass rendering solution as I have proposed will fix these issues. (basically hires fix similar to Auto1111)

**Comment by Deltrego** [comment]
Conceptually images should not require a fixed ratio, of course SD is tuned on 512px but infinite canvas proves it can be abstracted away. My thought would be to pad the image's lesser dimension to a square without wasting memory (virtually extend/mirror/wrap input image by reading it using modulo maths or maybe as a sparse matrix - I don't know how numpy works - and then crop the result before viewing).
Padding with noise uses up VRAM but also causes spurious items to appear, so not sure about that one.

**Comment by JeLuF** [comment]
The output image's size depends on the width and heigt options in the image settings. The input image gets the same aspect ratio as the output image. If your input image is non-square, and you want to keep this aspect ratio, you need to use the width and height settings to create a similar aspect ratio.
