### ISSUE TITLE
Auto Download upon Upscale (and other events)

### ISSUE THREAD

**Issue by Trithilon** [easydiffusion/easydiffusion#822]
**Is your feature request related to a problem? Please describe.**
My process involves "saving" images which I like to manually shortlist them for further iteration. 

When I really like an image, I like to:
1. Make Similar Images
2. Upscale
3. Draw another 25 steps
4. Download

When reviewing batches of 100s of images, this time can add up and sometimes I download the same image twice.

**Describe the solution you'd like**
It would be great if there was a "Auto Download upon Upscale" or "Auto Download upon Make similar Images" etc option in settings.
Obviously, auto-download would only happen once (unless you force download).

**Describe alternatives you've considered**
Just mentally keeping track of each image and wasting more time clicking.

**Comment by cmdr2** [comment]
Sorry, this sounds like it's best done as a UI plugin, since it's specific to your workflow. https://github.com/easydiffusion/easydiffusion/wiki/UI-Plugins
