### ISSUE TITLE
Severely fluctuating memory usage on CPU rendering

### ISSUE THREAD

**Issue by Deltact** [easydiffusion/easydiffusion#826]
Just started using the beta version of Easy Diffusion [v2.5.14 (beta)] and I must say I'm impressed that most bugs present in 2.4 have been ironed out, good job guys, unfortunately I can't really contribute with code yet as I'm not skilled enough and reporting issues is my only way of bringing light to this problem. You're all working overtime to provide a service for free and we appreciate your effort.

## Onto the bug part;
Since using v2.5.14 memory usage has been fluctuating insanely as shown below. (1 image generated at a time _**or**_ 1 in parallel)
![image](https://user-images.githubusercontent.com/92210959/216938496-9e5bb5c9-6ac4-449a-a77c-c3990c2b686b.png)
It's around the range of about 2 GB from baseline until peak memory usage and it gets amplified the more images that are rendered in parallel.

Back in v2.4.13 it didn't matter what you were rendering and how many in parallel, as long as the model was locked in and loaded, RAM usage would plateau and remain stable. Be it a single image being rendered or many in parallel, memory usage did not change only processing time did. 

Rendering multiple images with only 1 in parallel would not be visible in the UI after the first image was done. 
If you were to render 4 images but only 1 in parallel, only 1 would be visible in the UI and you'd have to Auto-Save Images to see the rest from the file explorer (this is still an issue by the way, even in 2.5!) so it was preferred to render everything at once (4 images, 4 in parallel) and wait it out. But you can't do this anymore in 2.5.

---
Running this on Windows 10 Pro x64 22H2 (19045.2486)
CPU: Ryzen 5 1600 AF (OC 3600 MHz)
RAM: 16GB DDR4 2400MHz

**Comment by cmdr2** [comment]
I'm not sure how the RAM wasn't changing in the previous versions. RAM usage will always fluctuate a lot during processing, since models will be loaded/unloaded (temporarily to the system RAM as well), and a lot of data will be created during processing (which will be unloaded after use).

In any case, if this is still relevant, please try the latest version: https://github.com/easydiffusion/easydiffusion/releases/tag/v3.0.2
