### ISSUE TITLE
'Error: CUDA out of memory' after recent update

### ISSUE THREAD

**Issue by erikpaasonen** [easydiffusion/easydiffusion#851]
**Describe the bug**
started getting `Error: CUDA out of memory` on startup. cannot even load the webUI at all now. this is in an installation which was previously working fine for 30+ days.

**To Reproduce**
1. reboot, just to clear up any possible latent VRAM consumption
2. `rm -fr ~/.cache/huggingface` (just as an overly paranoid precaution)
3. immediately open terminal and run `./start.sh`
4. start refreshing bookmark to webUI
5. wait until `model_manager.py` starts to log the error
6. never able to load webUI

**Expected behavior**
Expected webUI to load and able to run prompts as usual.

**Screenshots**
> /usr/bin/git
git version 2.34.1
/home/user1/stable-diffusion-ui/installer_files/env/bin/conda
conda 22.11.1
> 
> 
> Stable Diffusion UI
> 
> Stable Diffusion UI's git repository was already installed. Updating from main..
> HEAD is now at 026a4b6 Merge pull request #842 from cmdr2/beta
> Already on 'main'
> Your branch is up to date with 'origin/main'.
> remote: Enumerating objects: 77, done.
> remote: Counting objects: 100% (77/77), done.
> remote: Compressing objects: 100% (44/44), done.
> remote: Total 77 (delta 43), reused 54 (delta 31), pack-reused 0
> Unpacking objects: 100% (77/77), 46.28 KiB | 1.93 MiB/s, done.
> From https://github.com/cmdr2/stable-diffusion-ui
>    026a4b6..c35a731  main       -> origin/main
>    7bc95b6..4f3d2bd  beta       -> origin/beta
>  * [new tag]         v2.5.15    -> v2.5.15
> Updating 026a4b6..c35a731
> Fast-forward
>  CHANGES.md                         | 3 ++-
>  README.md                          | 4 ++--
>  scripts/bootstrap.sh               | 1 +
>  ui/easydiffusion/device_manager.py | 2 +-
>  ui/index.html                      | 4 ++--
>  5 files changed, 8 insertions(+), 6 deletions(-)
> 
> Hotfixed broken JSON file from OpenAI
torch and torchvision have already been installed.
sdkit is already installed.
sdkit version: 1.0.35
stable-diffusion version: 2.1.1
rich has already been installed.
Packages necessary for Stable Diffusion UI were already installed
Data files (weights) necessary for Stable Diffusion were already downloaded
Data files (weights) necessary for GFPGAN (Face Correction) were already downloaded
Data files (weights) necessary for ESRGAN (Resolution Upscaling) x4plus were already downloaded
Data files (weights) necessary for ESRGAN (Resolution Upscaling) x4plus_anime were already downloaded
Data files (weights) necessary for the default VAE (sd-vae-ft-mse-original) were already downloaded
> 
> 
> Stable Diffusion is ready!
> 
> PYTHONPATH=/home/user1/stable-diffusion-ui/stable-diffusion/env/lib/python3.8/site-packages
/home/user1/stable-diffusion-ui/stable-diffusion/env/bin/python
Python 3.8.5
No module 'xformers'. Proceeding without it.
20:51:12.540 INFO MainThread started in /home/user1/stable-diffusion-ui/stable-diffusion                                          server.py:19
20:51:12.545 INFO MainThread started at 02/09/23 20:51:12                                                                       server.py:20
20:51:13.342 INFO MainThread Scanned 13 models. Nothing infected                                                        model_manager.py:215
20:51:15.380 INFO MainThread Start new Rendering Thread on device: cuda:0                                                task_manager.py:393
20:51:16.829 WARNING cuda:0 forcing full precision on this GPU, to avoid green images. GPU detected: NVIDIA GeForce    device_manager.py:114
GTX 1650                                                                                                                                    
20:51:16.832 INFO cuda:0 Setting cuda:0 as active, with precision: full                                                device_manager.py:118
20:51:16.834 INFO cuda:0 loading stable-diffusion model from                                                                  __init__.py:22
/home/user1/stable-diffusion-ui/models/stable-diffusion/sd-v1-4.ckpt to device: cuda:0                                                        
20:51:22.078 INFO cuda:0 using config:                                                                                        __init__.py:45
/home/user1/stable-diffusion-ui/stable-diffusion/env/lib/python3.8/site-packages/sdkit/models/models_db/configs/v1-inference.ya               
ml                                                                                                                                          
20:51:22.096 INFO cuda:0 using attn_precision: fp32                                                                           __init__.py:51
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
20:51:28.743 INFO cuda:0 Created a temporary directory at /tmp/tmpurlnjw0k                                                instantiator.py:21
20:51:28.745 INFO cuda:0 Writing /tmp/tmpurlnjw0k/_remote_module_non_sriptable.py                                         instantiator.py:76
20:51:34.574 INFO cuda:0 VRAM Optimizations: {'KEEP_FS_AND_CS_IN_CPU', 'SET_ATTENTION_STEP_TO_16'}                       optimizations.py:24
20:51:35.113 ERROR cuda:0 Error while loading stable-diffusion model:                                                    model_manager.py:44
/home/user1/stable-diffusion-ui/models/stable-diffusion/sd-v1-4.ckpt                                                                          
20:51:35.116 ERROR cuda:0 Error: CUDA out of memory. Tried to allocate 50.00 MiB (GPU 0; 3.82 GiB total capacity; 2.72   model_manager.py:45
GiB already allocated; 61.19 MiB free; 2.81 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory                     
try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and                                          
PYTORCH_CUDA_ALLOC_CONF                                                                                                                     
20:51:35.128 ERROR cuda:0 Consider removing the model from the model folder.                                             model_manager.py:46

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.01 LTS
 - Browser: Firefox 109.0.1
 - Version: (version of what? `stable-diffusion-ui`? I think that's `2.5.15` but the browser won't load to tell for sure)

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: 
 - Browser 
 - Version 

**Additional context**
I know that my 1650 has only 4GB of VRAM. it normally runs just fine as long as I stay within certain params, like only txt2img (unable to do any img2img), no upscaling, no fixing faces, etc.

I have tried multiple models, all of which were previously downloaded and working fine. I even let it re-download the default SD 1.4 model and this issue still occurs with that freshly downloaded one.

I have a second computer with a 1070 which has 8GB of VRAM, and this repo operates successfully on that one at the current version.

side note: for anyone finding this issue in the future but you're having trouble installing for the first time on Linux: check not just your system RAM but specifically _your swap file._ I found that when I installed SD on a system with 8GB of system RAM, the OS install had allocated a swapfile of only 1GB (cue the old famous quote, that ought to be enough for everyone eh?). something loads into system RAM and then swaps to the swap file, and that was causing my particular "out of memory" errors. as soon as I replaced the Linux swap file with an 8GB swap file (hey if you have the disk space, and who doesn't these days, why not?), everything started working.

**Comment by Lostsite** [comment]
I have similar issues:
I have RTX3050 for laptop (4G VRAM). The good news is I am able to run the stable diffusion with balanced VRAM usage requirement. (It's at least 3 times faster then the Low VRAM usage opposition). 

However it just lack around 250 MB to apply realesrgan model. Which makes me have to stay in the slow mode.

I means I successfully use 4G VRAM to run all 50 Inference Steps, applied gfpgan, but just lack the last several MB to load realesrgan.... That's frustrating. 

I am not professional on it, but is there any possibilities to unload some finished models away from VRAM to give realesrgan last 100s MB to load?

**Comment by JeLuF** [comment]
> Error: CUDA out of memory. Tried to allocate 50.00 MiB 
> (GPU 0; 3.82 GiB total capacity; 2.72 GiB already allocated; 61.19 MiB free; 2.81 GiB reserved in total by PyTorch)

EasyDiffusion is only using 2.8GB at this point. So something else must be using the remaining 1GB. Can you please check the memory usage using the command `nvidia-smi`?

**Comment by erikpaasonen** [comment]
thank you for the hint on how to check VRAM usage! I didn't know what tool could show this info. here's what `nvidia-smi` captured just after generating the error:
```
Sat Feb 11 17:41:36 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.161.03   Driver Version: 470.161.03   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0  On |                  N/A |
| 50%   26C    P0    16W /  75W |   3851MiB /  3911MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      2172      G   /usr/lib/xorg/Xorg                219MiB |
|    0   N/A  N/A      2336      G   /usr/bin/gnome-shell               89MiB |
|    0   N/A  N/A     28193      G   ...1/usr/lib/firefox/firefox        3MiB |
|    0   N/A  N/A     36560      G   ...499119131643473463,131072       35MiB |
|    0   N/A  N/A     40363      G   ...oud-3.7.1-x86_64.AppImage       10MiB |
|    0   N/A  N/A     58919      C   ...-diffusion/env/bin/python     3487MiB |
+-----------------------------------------------------------------------------+
```
again, I have been able to load and use `stable-diffusion-ui` for over a month now with this same hardware and OS. something is causing it to load more than it used to before.

**Comment by erikpaasonen** [comment]
in further testing I found that while loading, when it first allocates VRAM it shows this:
```
Sat Feb 11 18:01:07 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.161.03   Driver Version: 470.161.03   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0  On |                  N/A |
| 50%   25C    P8     8W /  75W |   1155MiB /  3911MiB |      5%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      2172      G   /usr/lib/xorg/Xorg                236MiB |
|    0   N/A  N/A      2336      G   /usr/bin/gnome-shell               49MiB |
|    0   N/A  N/A     28193      G   ...1/usr/lib/firefox/firefox        3MiB |
|    0   N/A  N/A     36560      G   ...499119131643473463,131072       26MiB |
|    0   N/A  N/A     40363      G   ...oud-3.7.1-x86_64.AppImage       16MiB |
|    0   N/A  N/A     59388      C   ...-diffusion/env/bin/python      817MiB |
+-----------------------------------------------------------------------------+
```
i.e. 817MB. it reports this static amount for some time during loading (I'm speaking as an end user of `./start.sh`). then as soon as it starts to load the model (the point where the error occurs), it jumps (obviously trying to load the model):
```
Sat Feb 11 18:01:08 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.161.03   Driver Version: 470.161.03   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0  On |                  N/A |
| 50%   27C    P0    19W /  75W |   3709MiB /  3911MiB |      4%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      2172      G   /usr/lib/xorg/Xorg                236MiB |
|    0   N/A  N/A      2336      G   /usr/bin/gnome-shell               49MiB |
|    0   N/A  N/A     28193      G   ...1/usr/lib/firefox/firefox        3MiB |
|    0   N/A  N/A     36560      G   ...499119131643473463,131072       26MiB |
|    0   N/A  N/A     40363      G   ...oud-3.7.1-x86_64.AppImage       16MiB |
|    0   N/A  N/A     59388      C   ...-diffusion/env/bin/python     3371MiB |
+-----------------------------------------------------------------------------+
```
and as soon as it reaches 3487MB it throws the error.

curious whether that 817MB threshold is what increased...? would have loved to know about `nvidia-smi` a month ago, then I'd have a baseline. hoping this timing info gives the right folks the just-right hint.

**Comment by S0ulMeister** [comment]
Can I see your webui-user.bat file?

**Comment by sakralbar** [comment]
I have exactly the same problem. GT-1660 super graphics card, 6 gigabytes. Linux mint 21.1

In GPU mode "balanced", the message "Error: CUDA out of memory. Tried to allocate 64.00 MiB (GPU 0; 5.79 GiB total capacity; 4.34 GiB already allocated; 26.06 MiB free; 4.44 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF". 

If you disable the "Fix incorrect faces and eyes" option, the error will disappear.

There were no such errors about a month ago. I also checked the SD work in Windows 11 - there are also no memory errors, even when using the "Fix incorrect faces and eyes" option.

**Comment by erikpaasonen** [comment]
apologies, I am not able to find `webui-user.bat` anywhere in my `stable-diffusion-ui` directory. the OS is Linux (Ubuntu 22.04.02 LTS).

**Comment by saberbholt** [comment]
Some problem here, every model load was the same isue of memory, gtx1650 super in windows 11, low, 512* 512, no fix faces, and when open the stable difussion was used 138mb of the 4gb of the card.

Is some the Pytorch reservates 3.5 gb of memory and never liberate they.
![Sin título](https://user-images.githubusercontent.com/4301767/235105793-388d716d-5504-4272-bef4-b859b9b2f3a6.jpg)
![Sin título1](https://user-images.githubusercontent.com/4301767/235105799-63a8bd82-8893-4bf9-926c-6072edd01074.jpg)
![Sin título2](https://user-images.githubusercontent.com/4301767/235105801-c7f54b58-3ade-46d4-9914-96a57ea163a6.jpg)

**Comment by cmdr2** [comment]
Hi @saberbholt In your case the error is not due to GPU, but due to your system running out of RAM.

The error `DefaultCPUAllocator: not enough memory` means your system RAM is full.

I see a lot of tabs in the screenshot, closing those and other unnecessary programs would help. Also adding some more virtual memory would help - https://www.ibm.com/docs/en/opw/8.2.0?topic=tuning-optional-increasing-paging-file-size-windows-computers

**Comment by saberbholt** [comment]
mmmm is imposiblethat thats the actual usage of ram and as you see is all the options in the generic .
![Sin título](https://user-images.githubusercontent.com/4301767/235108412-5f03b1f0-db86-4cf2-b581-a99e0028f175.jpg)

I don't belive that oconfiguration need more than 6gb of ram

**Comment by cmdr2** [comment]
@saberbholt 8 GB of total system RAM is quite low for Stable Diffusion. The screenshot you're showing is the current usage, when Stable Diffusion isn't running. Please try running stable diffusion again, and watch the memory graph as it peaks.

The model often consumes more than 10 GB of system RAM during loading, since it performs a lot of processing during loading.

8 GB is the minimum requirement, and that means you'll have to close every other application and browser tab in order for Stable Diffusion to work.

**Comment by cmdr2** [comment]
@saberbholt  Many users have 8 GB of system RAM, and are able to use Stable Diffusion by adding virtual memory. Please try the suggestion I linked to previously to add virtual memory. This is a common user question, and I've seen that error many times in support questions - https://www.ibm.com/docs/en/opw/8.2.0?topic=tuning-optional-increasing-paging-file-size-windows-computers

**Comment by saberbholt** [comment]
more than 20gb of virtual memory and don't use none of all. In the month ago release don't have isues of any type, well can't make nothing.
