### ISSUE TITLE
Sorting order of custom models in drop-down list

### ISSUE THREAD

**Issue by murrrf** [easydiffusion/easydiffusion#855]
In version 2.4.13, the drop-down list of custom models has been sorted alphabetically. In version 2.5.15 there is no sorting. Because of this, choosing a model when there are several options in the list becomes more complicated.

If possible, please return the alphabetical sorting to the drop-down list of custom models.

Steps to reproduce the issue:

- start and then stop Easy Diffusion in a separate folder;
- add additional models (for demonstration purposes, you can create symbolic links to the base model)
- re-launch Easy Diffusion and open the drop-down list.

Current view of the list:

![crop](https://user-images.githubusercontent.com/4840415/218198618-0eb1fb8e-eae9-42f4-ae63-57c3320aec55.png)

**Comment by JeLuF** [comment]
I can't reproduce this problem. Everything is sorted on my side:
![image](https://user-images.githubusercontent.com/5852422/218262425-14dbed5d-4f9b-4964-967c-29bd211f8b35.png)

Can you please provide details about your environment? Which OS, which browser are you using?

**Comment by murrrf** [comment]
OS: Linux Mint 20.3 Una
Browser: Firefox 109.0.1
What other information might be helpful?

**Comment by cmdr2** [comment]
Please reopen if this is still an issue.
