### ISSUE TITLE
Error: CUDA error: CUBLAS_STATUS_ALLOC_FAILED when calling `cublasCreate(handle)`

### ISSUE THREAD

**Issue by rikorokir** [easydiffusion/easydiffusion#857]
**Describe the bug**
after installation, I click create image and this is the result of how to solve it

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - Browser: chrome
 - VGA: nvdia gt 740 4gb ddr5

![Screenshot 2023-02-11 234607](https://user-images.githubusercontent.com/125145848/218270359-fcee9901-d75c-4fed-b3ba-27b07a6177e6.png)

**Comment by killo3** [comment]
Same as I

**Comment by alaninnovates** [comment]
I have the same issue.

Processor: Intel64 Family 6 Model 63 Stepping 2, GenuineIntel
Graphics Card: Quadro K4200 (cuda:0)

Browser: Edge
OS: Win 10
