### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement torch (from versions: none) ERROR: No matching distribution found to torch

### ISSUE THREAD

**Issue by urianlinck** [easydiffusion/easydiffusion#875]
I have a bug on installation. Sorry I'm a noob. Can someone help me?

ERROR: Could not find a version that satisfies the requirement torch (from versions: none)
ERROR: No matching distribution found to torch

![error stable](https://user-images.githubusercontent.com/125294858/218516860-4803d6dd-1943-464c-8d25-ecbc235a8711.PNG)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: win 10
 - Browser: chrome
 - Version:

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

**Comment by JeLuF** [comment]
This happens when using an old version of the installer to install Easy Diffusion. Please use the current version of our installer from https://github.com/cmdr2/stable-diffusion-ui/releases/download/v2.5.15/stable-diffusion-ui-windows.zip
