### ISSUE TITLE
A way to disable automatic updates as it keeps crashing and chugging

### ISSUE THREAD

**Issue by YOLOnlineYT** [easydiffusion/easydiffusion#876]
Hi, 

Recently I started messing around with ai tools and having this make use of your own hardware running locally has been such a huge help. However i noticed a few days ago the ui and command lines changed somewhat and since that change things really don't work as smoothly if at all anymore. I would like to know if it is possible to alter some files in the startup to not ping for updates every time at startup but keep running the "older" version until i decide to manually update?

I would love to revert back a little and have it all run smoothly again.

**Comment by YOLOnlineYT** [comment]
Hello,

The issue is even worse now, even before generating something or even doing anything with the ui, having the bat file open really slows down my machine. I can't imagine its my pc as its fairly powerful so something the program is doing is causing this issue. it's come to the point its somewhat unusable which is a shame but having to wait up to 15 mins to have the whole system unfrozen and fully responsive again is not fun

**Comment by YOLOnlineYT** [comment]
UPDATE

Usability has been somewhat restored after deleting the 1.5 model i had in the models folder. I dont know how or why this helped really but at least i can go about doing more stuff with this haha

**Comment by cluster-bn** [comment]
also on Pgenom945, renders 3 images, and stops
![image](https://github.com/easydiffusion/easydiffusion/assets/98166262/9d432431-4fe1-4491-a74f-6c097ac9450a)
render process v5.4.22 upgrades to 5.4.8 and freeze because state on client PC (Easy Diffusion - rendering) cannot add process task

**Comment by cmdr2** [comment]
@cluster-bn This is a separate issue, please download the latest installer from https://github.com/easydiffusion/easydiffusion/releases/tag/v3.0.2 and create a new issue if this continues to be a problem.
