### ISSUE TITLE
Integrated Graphics

### ISSUE THREAD

**Issue by PandaUprising** [easydiffusion/easydiffusion#877]
This stable diffusion is great and works exceptionally well. I am using my CPU (Intel core i5-1235U) to render images, it doesn't take too long, but I am unable to use my integrated graphics (Intel Iris Xe Graphics) Which I'm sure would be much faster than CPU rendering.

If there is a way to use my integrated graphics please let me know.

**Comment by JeLuF** [comment]
Currently, only NVidia GPUs are supported

**Comment by sawaday7** [comment]
I would also like support for this

**Comment by cmdr2** [comment]
Sorry, we've tried comparing the performance of an integrated GPU and it wasn't faster than the CPU. I suspect that the main bottleneck is memory access speed, i.e. using system RAM instead of dedicated GPU RAM (that's optimized for large bandwidth).
