### ISSUE TITLE
Error: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:0!

### ISSUE THREAD

**Issue by barretpj** [easydiffusion/easydiffusion#887]
**Describe the bug**
Since latest update, my Linux box with 2 GPUs fails consistently with the error "Error: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:0!."

**To Reproduce**
On a Linux box with 2 GPUs, try to generate images. Many times the error is given. Seems to be more often when GFPGAN is enabled. I'd only ever seen this error before when using the Beta channel, it was always stable on the release channel.

**Expected behavior**
Render without error, as happened last week.

**Desktop (please complete the following information):**
 - OS: CentOS 8.5.2111
 - GPUs: 2x RTX A4000

**Comment by cmdr2** [comment]
This has been fixed in the recent versions: https://github.com/easydiffusion/easydiffusion/releases/tag/v3.0.2

Please feel free to reopen if this is still relevant and continues to be an issue. Thanks
