### ISSUE TITLE
Problem installing Stable Diffusion

### ISSUE THREAD

**Issue by E-AhrixOne** [easydiffusion/easydiffusion#892]
**Describe the bug**
It does not install the torch, a lot of errors appear
From what I looked, it seems to be a memory problem but I'm not sure.

**To Reproduce**

1 - Run "Start Stable Diffusion UI"
2 - Starts downloading/installing a bunch of stuff
3 - appears " Installing torch and torchvision.."
4 - the message "Downloading https://download.pytorch.org/whl/cu116/torch-1.13.1%2Bcu116-cp38-cp38-win_amd64.whl" appears
5 - When I try to install, I get a bunch of errors

**Expected behavior**
Install and run stable diffusion

**Screenshots**
Some screenshots of the issue
![Captura de tela 2023-02-16 140629](https://user-images.githubusercontent.com/124693949/219437257-4a31164b-7c87-47bb-8feb-9259d1e57888.png)
![Captura de tela 2023-02-16 140705](https://user-images.githubusercontent.com/124693949/219437504-fc4d2e61-03b9-402d-be90-e1c668b94a89.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 Home - 22H2 - 22621.1105
 - Browser: Brave 
 - Version: 1.48.164 (Official Version) 64-bit

**Additional context**
I've tried installing stable diffusion several times, different versions and this error always appears.

________________________________________________________________________________________________________

Sorry if you don't understand some things, my native language is Portuguese so I had to translate ^-^

**Comment by PlatinumSphere** [comment]
I have the same issue too, I posted on here as well [https://github.com/cmdr2/stable-diffusion-ui/issues/841](url). I believe this other person is experiencing the same problem when downloading the torch file.

**Comment by PlatinumSphere** [comment]
> I have the same issue too, I posted on here as well #841. I believe this other person is experiencing the same problem when downloading the torch file.

**Comment by E-AhrixOne** [comment]
The problem is, the torch downloads but does not install. I can download the file from the link "https://download.pytorch.org/whl/cu116/torch-1.13.1%2Bcu116-cp38-cp38-win_amd64.whl", but I don't know which folder to put the file in .
I don't know much about technology but I was reading some forums and, probably for me it could also be the ram memory issue, I only have 4gb and it probably won't install because of that.
__________________________________________________________________________________________

Sorry if you don't understand some things, my native language is Portuguese so I had to translate ^-^

**Comment by JeLuF** [comment]
A minimum of 8GB is needed for Easy Diffusion. 4GB is unfortunately not enough.

**Comment by E-AhrixOne** [comment]
complicated, so unfortunately I won't be able to install it...
