### ISSUE TITLE
Some models don't work

### ISSUE THREAD

**Issue by SuppaKillaComics** [easydiffusion/easydiffusion#897]
**Describe the bug**
In the V2.5 News there was written: "Full support for Stable Diffusion 2.1 (including CPU) - supports loading v1.4 or v2.0 or v2.1 models seamlessly. No need to enable "Test SD2", and no need to add sd2_ to your SD 2.0 model file names. Works on CPU as well." 
I've downloaded some 2.0 and 2.1 models from Civitai with the Checkpoint filter on and they don't work.

**To Reproduce**
1. Dowload Vector-Art on https://civitai.com/models/4618/vector-art
2. Add to the Easy/Stable Diffusion UI models folder
3. Generate an image

**Expected behavior**
Nothing happens. There's only error messages

**Screenshots**
MESSAGES:
Error: Unexpected Read Error:
Error:undefined
EventInfo: {
    "reader": {}
}

Error: Unknown model! No config file path specified in context.model_configs for the "stable-diffusion" model!
Error: Unexpected Read Error:
Error:undefined
EventInfo: {
    "reader": {}
}

Error: The model for Stable Diffusion has not been loaded yet! If you've tried to load it, please check the logs above this message for errors (while loading the model).

MESSAGE ON PROMPT:
17:42:51.897 INFO cuda:0 Global seed set to 9567769                                                          seed.py:65
17:42:51.900 ERROR cuda:0 Traceback (most recent call last):                                        task_manager.py:346
  File "C:\stable-diffusion-ui\ui\easydiffusion\task_manager.py", line 336, in thread_render
    task.response = renderer.make_images(
  File "C:\stable-diffusion-ui\ui\easydiffusion\renderer.py", line 38, in make_images
    images, seeds = make_images_internal(req, task_data, data_queue, task_temp_images,
step_callback)
  File "C:\stable-diffusion-ui\ui\easydiffusion\renderer.py", line 58, in make_images_internal
    images, user_stopped = generate_images_internal(
  File "C:\stable-diffusion-ui\ui\easydiffusion\renderer.py", line 89, in generate_images_internal
    images = generate_images(context, callback=callback, **req.dict())
  File
"C:\stable-diffusion-ui\stable-diffusion\env\lib\site-packages\sdkit\generate\image_generator.py",
line 50, in generate_images
    raise RuntimeError(
RuntimeError: The model for Stable Diffusion has not been loaded yet! If you've tried to load it,
please check the logs above this message for errors (while loading the model).

17:42:51.977 INFO cuda:0 Session 1676666516421 task 2644309441936 failed!                           task_manager.py:355

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser: Chrome
 - Version: 110.0.5481.104 64-btis

**Additional context**
It doesn't happen with other models, mainly with those trained with 1.5 V

Thanks for your great work!

**Comment by Wordjoy** [comment]
Title should be "SOME models no not work". I can repro with THIS model, which has "beta" in its name.
I have 8+ other Civitai models that work perfectly.

**Comment by SuppaKillaComics** [comment]
> **Additional context**
> It doesn't happen with other models, mainly with those trained with 1.5 V

Yup, I wrote: 
"Additional context
It doesn't happen with other models, mainly with those trained with 1.5 V"

but thanks. I edited the title.

**Comment by JeLuF** [comment]
```
Error: Unknown model! No config file path specified in context.model_configs for the "stable-diffusion" model!
```
Stable Diffusion 2.1 and 2.0 models come with config files, often called yaml files. On civitai, use the "arrow down" button next to the download button to access it.
![image](https://user-images.githubusercontent.com/5852422/220324634-50a1f12a-3927-403b-b519-af52d2245df9.png)
Place it next to your model file in the `models\stable-diffusion` folder. Its name needs to match the model files name, except for the suffix.
![image](https://user-images.githubusercontent.com/5852422/220325124-b59b99a5-a703-4cf7-abe6-c5f4bbaf51ac.png)
This works for both `ckpt` and `safetensors` files

**Comment by SuppaKillaComics** [comment]
> Place it next to your model file in the `models\stable-diffusion` folder. Its name needs to match the model files name, except for the suffix.

Oh! I'll download them and check if it works. Thanks!

**Comment by JeLuF** [comment]
EasyDiffusion 3.0, released today, comes with automatic config detection, so that it doesn't need  model config files any more.

**Comment by SuppaKillaComics** [comment]
Thanks!
