### ISSUE TITLE
Question about functionality

### ISSUE THREAD

**Issue by Pash3384** [easydiffusion/easydiffusion#898]
Is it possible to use Easy Diffusion only as a local: https://huggingface.co/spaces/akhaliq/GFPGAN  
If "YES" what exclusion commands and settings should be used?
What exceptions (Negative Prompt) does Easy Diffusion understand? Is there a guide somewhere?

**Comment by cmdr2** [comment]
Hi, Easy Diffusion is designed to be installed and run on your PC.
