### ISSUE TITLE
help needed: errors on  installing "Stable Diffusion UI - v2"

### ISSUE THREAD

**Issue by pingPlato** [easydiffusion/easydiffusion#901]
this was the error message: "Hotfixed broken JSON file from OpenAI module torch not found
"Installing torch and torchvision.."
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu116 "
P.S. I used the latest installer Easy Diffusion 2.5, the date is Feb 6.
![屏幕截图(21)](https://user-images.githubusercontent.com/125718343/219845506-32635f6c-b2a8-4eba-a213-98bfcc5635b0.png)
thanks for helping with the issue!

**Comment by pingPlato** [comment]
P.S. windows 10, also placed the folder on the top level drive C:

**Comment by JeLuF** [comment]
pip has found some proxy configuration it tries to use. Please open a `cmd` window and check the output of these commands:
```
echo %HTTP_PROXY%
echo %HTTPS_PROXY%
```
If they return anything _else_ than
```
%HTTP_PROXY%
%HTTPS_PROXY%
```
you need to unset these environment variables.

**Comment by pingPlato** [comment]
they return: 
%HTTP_PROXY%
%HTTPS_PROXY%
what else can I try？ thanks

**Comment by JeLuF** [comment]
Another reason for it could be a config file. In a `cmd` window, can you please run:
```
dir C:\ProgramData\pip\pip.ini
dir %APPDATA%\pip\pip.ini
dir %HOME%\pip\pip.ini
```
Does any one of them not return "File not found"? If it finds any of the three files, do they contain proxy settings?

**Comment by pingPlato** [comment]
thanks; the first two returned "file not found";the last one returned: 
"cannot find the specified path" , what should I do next? are we making progress?

**Comment by JamesJeremyHall** [comment]
Same issue. Here's a log snip.

Hotfixed broken JSON file from OpenAI
module torch not found
"Installing torch and torchvision.."
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu116
ERROR: Could not find a version that satisfies the requirement torch (from versions: none)
ERROR: No matching distribution found for torch
