### ISSUE TITLE
Ошибка при загрузке файлов данных (весов) для GFPGAN

### ISSUE THREAD

**Issue by tomiks1963** [easydiffusion/easydiffusion#905]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser:
 - Version:

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

**Comment by JeLuF** [comment]
Try rerunning the installer, the issue you've been reporting has been fixed.

**Comment by JeLuF** [comment]
closed due to inactivity
