### ISSUE TITLE
Error running stable diffusion ui installer

### ISSUE THREAD

**Issue by MaximeID** [easydiffusion/easydiffusion#911]
**Describe the bug**
"Error: The downloaded ESRGAN x4plus_anime model file was invalid! Bytes downloaded: "
"Error downloading the data files (weights) for ESRGAN (Resolution Upscaling) x4plus_anime. Sorry about that, please try to:"
"  1. Run this installer again."
"  2. If that doesn't fix it, please try the common troubleshooting steps at https://github.com/cmdr2/stable-diffusion-ui/wiki/Troubleshooting"
"  3. If those steps don't help, please copy *all* the error messages in this window, and ask the community at https://discord.com/invite/u9yhsFmEkB"
"  4. If that doesn't solve the problem, please file an issue at https://github.com/cmdr2/stable-diffusion-ui/issues"
"Thanks!"

**To Reproduce**
1. Go to 'stable-diffusion-ui'
2. Click on 'Start Stable Diffusion UI'
3. Install and wait

**Expected behavior**
I should just install and be done, but it fails each time.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 Famille
 - Browser: Chrome
 - Version: 22H2

**Smartphone (please complete the following information):**
 - Device: NA
 - OS: NA
 - Browser NA
 - Version NA

**Additional context**

**Comment by Anyvie** [comment]
@MaximeID Seems similar to https://github.com/cmdr2/stable-diffusion-ui/issues/861

**Comment by JeLuF** [comment]
Please re-run the installer, it should get fixed on second try.

**Comment by JeLuF** [comment]
closed due to inactivity
