### ISSUE TITLE
Can we use lora in stable-diffusion-ui?

### ISSUE THREAD

**Issue by lztz0022** [easydiffusion/easydiffusion#914]
It doesn't work neither I put the lora.safetensors file in **models/lora** nor **models/stable-diffusion/lora**.
Can we use lora in stable-diffusion-ui?

**Comment by JeLuF** [comment]
No, there's currently no LORA support

**Comment by lztz0022** [comment]
Thank you for your reply.
And thank you for your wonderful work. It's really the easiest way to install and use Stable Diffusion, especially version 2.5.

**Comment by devingfx** [comment]
This issue have the answer...
https://github.com/cmdr2/stable-diffusion-ui/issues/1170

**Comment by JeLuF** [comment]
Closed as duplicate of #1170
