### ISSUE TITLE
Installer: could not open '/dev/null'

### ISSUE THREAD

**Issue by jabcreations** [easydiffusion/easydiffusion#934]
could not open '/dev/null'

My understanding is the installer is supposed to automate all of this. I'm a developer though I don't program with anything remotely related here. All I can do is dump the installer output:

The last page of the install log:
-------------------------------------------------------------
Linking zstd-1.5.2-h12be248_6
Linking sqlite-3.40.0-hcfcfb64_0
Linking python-3.8.5-h60c2a47_9_cpython
Linking wheel-0.38.4-pyhd8ed1ab_0
Linking setuptools-67.4.0-pyhd8ed1ab_0
Linking pip-23.0.1-pyhd8ed1ab_0
Linking win_inet_pton-1.1.0-pyhd8ed1ab_6
Linking pycparser-2.21-pyhd8ed1ab_0
Linking colorama-0.4.6-pyhd8ed1ab_0
Linking charset-normalizer-2.1.1-pyhd8ed1ab_0
Linking idna-3.4-pyhd8ed1ab_0
Linking certifi-2022.12.7-pyhd8ed1ab_0
Linking toolz-0.12.0-pyhd8ed1ab_0
Linking pluggy-1.0.0-pyhd8ed1ab_5
Linking pysocks-1.7.1-pyh0701188_6
Linking tqdm-4.64.1-pyhd8ed1ab_0
Linking ruamel.yaml.clib-0.2.7-py38h91455d4_1
Linking pycosat-0.6.4-py38h91455d4_1
Linking menuinst-1.4.19-py38haa244fe_1
Linking cffi-1.15.1-py38h57701bc_3
Linking ruamel.yaml-0.17.21-py38h91455d4_2
Linking zstandard-0.19.0-py38hea8d35e_1
Linking brotlipy-0.7.0-py38h91455d4_1005
Linking cryptography-39.0.0-py38h086c683_0
Linking conda-package-streaming-0.7.0-pyhd8ed1ab_1
Linking pyopenssl-23.0.0-pyhd8ed1ab_0
Linking conda-package-handling-2.0.2-pyh38be061_0
Linking urllib3-1.26.14-pyhd8ed1ab_0
Linking requests-2.28.2-pyhd8ed1ab_0
Linking conda-23.1.0-py38haa244fe_0
Transaction finished
D:\My Documents\Desktop\AI Generated Art\stable-diffusion-ui\installer_files\env\Library\bin\git.exe
fatal: could not open '/dev/null' for reading and writing: No such file or directory
D:\My Documents\Desktop\AI Generated Art\stable-diffusion-ui\installer_files\env\Library\bin\conda.bat
D:\My Documents\Desktop\AI Generated Art\stable-diffusion-ui\installer_files\env\Scripts\conda.exe
conda 23.1.0

"Stable Diffusion UI - v2"

The system cannot find the file specified.
The system cannot find the file specified.
"Stable Diffusion UI's git repository was already installed. Updating from main.."
The system cannot find the path specified.
fatal: could not open '/dev/null' for reading and writing: No such file or directory
fatal: could not open '/dev/null' for reading and writing: No such file or directory
fatal: could not open '/dev/null' for reading and writing: No such file or directory
File not found - ui
0 File(s) copied
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
Press any key to continue . . .

**Comment by JeLuF** [comment]
You apparently deleted or disabled your Windows NUL device. You need to re-enable it to finish the installation.

**Comment by JeLuF** [comment]
closed due to inactivity
