### ISSUE TITLE
Annoying auto scroll back up when removing an image toggle switch in settings request. (or removal of the auto scroll)

### ISSUE THREAD

**Issue by TheBalanceKeeper** [easydiffusion/easydiffusion#943]
**Is your feature request related to a problem? Please describe.**

For some reason every time I remove an image from the UI (clicking the X to remove it) it forces me to the top of the page so I have to scroll back down.

**Describe the solution you'd like**

removing the bug or adding a toggle for it in settings.

**Describe alternatives you've considered**

**Additional context**

**Comment by cmdr2** [comment]
Hi, this isn't part of the normal UI, so please check if you're using any plugins, or have enabled the "scroll to latest image" enabled in the top-right corner.

**Comment by TheBalanceKeeper** [comment]
I don't use plugins or have that enabled.
