### ISSUE TITLE
Error [WinError 225] 

### ISSUE THREAD

**Issue by JackHammer01** [easydiffusion/easydiffusion#944]
Collecting pyyaml
  Using cached PyYAML-6.0-cp38-cp38-win_amd64.whl (155 kB)
Requirement already satisfied: torch>=1.7 in d:\stable-diffusion-ui\installer_files\env\lib\site-packages (from gfpgan->sdkit==1.0.35) (1.13.1+cu116)
Collecting basicsr>=1.4.2
  Using cached basicsr-1.4.2.tar.gz (172 kB)
  **__ERROR: Error [WinError 225] Operation did not complete successfully because the file contains a virus or potentially unwanted software while executing command python setup.py egg_info
  Preparing metadata (setup.py) ... error_
**ERROR: Could not install packages due to an OSError: [WinError 225] Operation did not complete successfully because the file contains a virus or potentially unwanted software**_**

**Comment by TheDarkLord333** [comment]
I have the problem too. I have no antivirus software, but Windows Defender. I have disabled Firewall Protection and Virus & Threat Protection and have still this error message. What can a vendor of a antivirus software do that fix that problem?
