### ISSUE TITLE
Support for LoRA and textual inversion embeddings

### ISSUE THREAD

**Issue by Blueblizard** [easydiffusion/easydiffusion#946]
They are very popular now in model webs like Civitai, especially for styles and characters using small size, but i don´t see support in Easy Difussion. I would be a very interesting enhancement.

**Comment by marcolardera** [comment]
I think that would be one of the greatest addition to stable-diffusion-ui. It would be great if there is the possibility of both training and using textual inversion embeddings.

**Comment by cmdr2** [comment]
Hi @marcolardera and @Blueblizard You can now test LoRA in the latest beta. Please note that this change is very early, and doesn't work with all the samplers, and consumes a lot of VRAM. We're working on improving those aspects.

Please enable the "Beta channel" setting in the Settings tab, save and restart the UI. Then please enable the "Test Diffusers" setting in the Settings tab, save and restart the UI.

You'll see a "LoRA" dropdown in the Image Settings, and can put your LoRA models in the `models/lora` folder. Please select the desired LoRA, and don't forget to use the tokens in the prompt, if the LoRA author mentions that in the model description.

**Comment by Blueblizard** [comment]
Hello. Yes, i always have the beta activated and tonight received a pleasant surprise when restarted the gui and read the changes in the v2.5.27 version. I was testing some LoRA models and although as you say, still doesn´t work with some of the samplers (by example with UniPC SNR 2 that i am using lately) i was checking it with others like UniPC TU and DMP Solver and it worked. 

 Thanks for the upgrade and keep on the good work. :)

**Comment by mikesimone** [comment]
Are we going to be able to start using <lora:WhateverLoraName:1.4> in the actual prompt, or will we remain limited to using the dropdown? When I try putting it in the prompt, I get 
`22:22:53.347 WARNING cuda:0 Warning: 'WhateverLoraName:1.4>,' is not a value, are you missing a space?`

**Comment by devingfx** [comment]
Hi all!

I'm new to LoRa, can you tell me some details explaination?

- Can I use any LoRa on any model? If not what are the condition to check?
- On civitai, promps sometimes does have a `<lora:name:weight>` syntax, is it usefull to put that into the prompt? (cause, their prompts also have the trigger word without syntax)
    - Is it a global syntax? Or it depends on each UI implementation?
- It is possible to use several LoRa on the same generation? Especially in EasyDiffusion, there is only 1 select box, is it a limitation to constrain to 1 unique LoRa, or is it planned to create an UI for multiple LoRas (I can understand the early nature of support in beta)

Thx!

**Comment by JeLuF** [comment]
> Can I use any LoRa on any model? If not what are the condition to check?

No. Please check the documentation of the specific LoRa. In general: Many do work with many models, some only work well with a specific model.

> On civitai, promps sometimes does have a `<lora:name:weight>` syntax, is it usefull to put that into the prompt? (cause, their prompts also have the trigger word without syntax)
> Is it a global syntax? Or it depends on each UI implementation?

This is a automatic1111's Stable Diffusion WebUI specific syntax. Easy Diffusion has a dropdown dialog for LORAs, there's no need to use cryptic prompts.

> * It is possible to use several LoRa on the same generation? Especially in EasyDiffusion, there is only 1 select box, is it a limitation to constrain to 1 unique LoRa, or is it planned to create an UI for multiple LoRas (I can understand the early nature of support in beta)

Multi-LORA support is on the todo list.

**Comment by JeLuF** [comment]
Embedding support has been introduced with Easy Diffusion 3.0, released today.

**Comment by Blueblizard** [comment]
Yes, i have been using it since appeared in the beta versions. Also controlnet and Stable Diffusion XL are supported. Great job. :)
