### ISSUE TITLE
duplicate double rez 512 and more

### ISSUE THREAD

**Issue by DJLachance** [easydiffusion/easydiffusion#957]
if 512 and more picture is duplicated and not correct plz fix
![1](https://user-images.githubusercontent.com/16768502/222672009-b9f8462f-24fd-4029-9880-130c34cf56a4.jpg)
![2](https://user-images.githubusercontent.com/16768502/222672013-0b4ec808-0565-4820-b80c-c5a3d78fb231.jpeg)
![a_photograph_of_an_astronaut_riding_a_horse_Seed-6390491_Steps-25_Guidance-7 5 (1)](https://user-images.githubusercontent.com/16768502/222672358-5e2c5cac-b117-45ee-910a-a5c6c93d87a9.jpeg)
![a_photograph_of_an_astronaut_riding_a_horse_Seed-6390491_Steps-25_Guidance-7 5](https://user-images.githubusercontent.com/16768502/222672460-420c72b2-06ff-45ae-aa10-186992d216ea.png)

**Comment by DJLachance** [comment]
![a_photograph_of_an_astronaut_riding_a_horse_Seed-3413512_Steps-25_Guidance-7 5 (1)](https://user-images.githubusercontent.com/16768502/222672715-6ffbc111-9c09-4c08-8d1d-887b871fed07.jpeg)
![Just_one_cat_in_a_black_void_Seed-3917732_Steps-50_Guidance-7 5](https://user-images.githubusercontent.com/16768502/222672762-e2e6a0fa-ea05-48f8-b060-6773a00d0848.jpeg)

**Comment by JeLuF** [comment]
The AI is trained on images of the size 512x512 (or 768x768 for some special models). If there's more space available, it will fill it with "more of the same". To get better results, start with a resolution 'close' to 512x512 and then, when you've found an interesting image, click on "use as input" and select a larger size with the same aspect ratio.

**Comment by JeLuF** [comment]
closed due to inactivity
