### ISSUE TITLE
I made some edit on the index.html file but its not reflecting the same on the browser. What can i do so that the changes will reflect on the server as well

### ISSUE THREAD

**Issue by leonnmathew** [easydiffusion/easydiffusion#958]
I made some edit on the index.html file but its not reflecting the same on the browser. What can i do so that the changes will reflect on the server as well

**Comment by JeLuF** [comment]
If you want to make local changes, you need to set up a development environment as described in https://github.com/cmdr2/stable-diffusion-ui/blob/main/CONTRIBUTING.md

**Comment by JeLuF** [comment]
closed due to inactivity
