### ISSUE TITLE
After update, I can't run. 

### ISSUE THREAD

**Issue by chensinit** [easydiffusion/easydiffusion#960]
**Describe the bug**
After update, I can't run.

error message.
Unable to create process using 'C:\_program\stable-diffusion-ui\installer_files\env\python.exe C:\_program\stable-diffusion-ui\installer_files\env\Scripts\conda-script.py --version'

There is no python.exe in there.
I try to run many time, but it work same.
I try to copy python.exe, but i can't. 

**To Reproduce**
1. Go to just execute.
4. See error  there are error message in console

**Expected behavior**
It should be run.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser:
 - Version: 2.33.0

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

**Comment by chensinit** [comment]
I try to re-install. and i get new error.
'"C:\stable-diffusion-ui\installer_files\env\condabin\..\Scripts\conda.exe"' is not recognized as an internal or external command,

**Comment by JeLuF** [comment]
This usually happens when an anti-malware program quarantines the `conda.exe` or `python.exe` programs.

**Comment by JeLuF** [comment]
closed due to inactivity
