### ISSUE TITLE
Error installing Stable-Diffusion

### ISSUE THREAD

**Issue by AleksGolder** [easydiffusion/easydiffusion#964]
Error description:
When installing stable-diffusion at the installation stage after loading 8gb, an error pops up. Turned off all antivirus, tried uninstalling and reinstalling, nothing works. I keep getting the same error.

Error text:
  ERROR: Error [WinError 5] Отказано в доступе while executing command python setup.py egg_info
  Preparing metadata (setup.py) ... error
ERROR: Could not install packages due to an OSError: [WinError 5] Отказано в доступе
Consider using the `--user` option or check the permissions.

PC Information:
 - ОС: Windows 11
 - Браузер: Yandex Browser
 - Версия: 23.1.1

![SD1](https://user-images.githubusercontent.com/126984754/222980638-345d428d-b90c-4c38-9616-c60b8ebae8c2.png)

**Comment by JeLuF** [comment]
Did you make a previous attempt to install this as Administrator? This might mess up the permissions and further installation attempts will fail.

**Comment by JeLuF** [comment]
closed due to inactivity
