### ISSUE TITLE
Warn if generating multiple of the same image

### ISSUE THREAD

**Issue by RenaKunisaki** [easydiffusion/easydiffusion#968]
**Is your feature request related to a problem? Please describe.**
Sometimes I generate a few images, then go to make adjustments with inpainting, so I click "use these settings", and end up generating multiple identical images because I forgot to change the seed to random.

**Describe the solution you'd like**
A warning if generating multiple images with the exact same settings in one batch.

**Describe alternatives you've considered**
Trying to pay closer attention.

**Additional context**
N/A

**Comment by JeLuF** [comment]
If you create multiple images in the same batch, they will use different seeds, even if "random" is set to off. You can check by inspecting the `Seed:` field in the image's overlay menu. 
![image](https://user-images.githubusercontent.com/5852422/224473541-272e465a-f463-4276-8b9b-7f771ddd7620.png)

If your images look the same, you're probably using a very small prompt strength.

**Comment by JeLuF** [comment]
closed due to inactivity
