### ISSUE TITLE
Bug report / feature request: mobile browser keeps reloading the page

### ISSUE THREAD

**Issue by iegoshin** [easydiffusion/easydiffusion#971]
**Describe the bug**
On mobile, each time you switch the tab or go to different app, when you return the page is reloading and you are losing everything that was there.
I understand that you don't want to display outdated app, but when the page always reloads, the app become unusable on mobile.
Is there a way to return longer max-age when working from mobile?

**To Reproduce**
1. Open easy diffusion UI on mobile
2. Start some prompt
3. Open some other tab
4. Return to easy diffusion tab
5. Page reloads and you lost all the progress

**Expected behavior**
Stay on the page without reloading it

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy 11e
 - OS: Android
 - Browser: Samsung Internet, Chrome
 - Version: current

**Additional context**

**Comment by cmdr2** [comment]
Hi, this isn't done by Easy Diffusion, but rather by the browser. I don't think/know if we can control this.
