### ISSUE TITLE
Doggettx Prompting with Lora

### ISSUE THREAD

**Issue by S0ulMeister** [easydiffusion/easydiffusion#980]
**Edit**
I got bamboozled. In the documentation it shows what I was trying to do is incompatible.
![image](https://user-images.githubusercontent.com/72477332/224120827-6496918f-bc3c-4b57-9401-4dc99c61e4aa.jpeg)

**Describe the bug**

When prompting with brackets, Automatic1111 is incorrectly using textual inversion/lora embedding tokens.

**To Reproduce**

Prompt with the following and any additions of choice:
[<lora:yaeMikoRealistic_yaemikoFull:0.3>:15]
Training Steps: 20

Available from civitai.com
https://civitai.com/models/8484/yae-miko-or-realistic-genshin-lora

**Expected behavior**
Generation from the first 15 steps to not look like trained Lora Model (Yae Miko)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Auto1111 (chrome)
 - Version: Commit Hash: 0cc0ee1bc4bc24a8c9715f66cede06601bfc00c8

**Additional context**
It also will not stop adding the embedding after 15 steps when doing the following:  [<lora:yaeMikoRealistic_yaemikoFull:0.3>::15]
This can be done on any model and any lora embedding.

Information on Prompt editing with brackets available here:
https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Features

![image](https://user-images.githubusercontent.com/72477332/223995398-742b9167-aaf4-4fd6-81a4-744b24821363.png)

**Comment by JeLuF** [comment]
This is not the automatic1111 bug tracker.
