### ISSUE TITLE
ERROR: Error [WinError 225] Операция не была успешно завершена, так как файл содержит вирус или потенциально нежелательную программу while executing command python setup.py egg_info

### ISSUE THREAD

**Issue by Singlface45** [easydiffusion/easydiffusion#990]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser:
 - Version:

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

**Comment by JeLuF** [comment]
Please contact the supplier of your anti-virus software. This is an issue on their side.

**Comment by JeLuF** [comment]
closed due to inactivity
